### ISSUE TITLE
Quality in Settings dialog assuming Mbps incorrectly

### ISSUE THREAD

**Issue by Gerk** [plexinc/plex-media-player#1]
It looks like it's assuming Mbps instead of calculating.  This channel based video was sending Kbps for sure.

![screen shot 2015-10-20 at 1 47 03 pm](https://cloud.githubusercontent.com/assets/172505/10616094/6ef8f8ba-7731-11e5-87df-19446f1e8e09.png)

**Comment by mseeley** [comment]
Interesting. I'm not certain we're provided a unit for the quality and instead assume Mbps.

Which channel / can you post the XML metadata?

**Comment by Gerk** [comment]
I've seen in a couple of channels so far.  This one was with HGTV Canada (probably not much help to you), I will try and dig up some XML.

**Comment by Gerk** [comment]
```
<MediaContainer size="1" identifier="com.plexapp.system" mediaTagPrefix="/system/bundle/media/flags/">
<Video url="http://www.hgtv.ca/video/video.html?v=547758147556" deferred="0" sourceIcon="http://resources-cdn.plexapp.com/image/source/com.plexapp.plugins.hgtvcanada.jpg?h=645e744" key="/system/services/url/lookup?url=http%3A%2F%2Fwww.hgtv.ca%2Fvideo%2Fvideo.html%3Fv%3D547758147556" type="episode" originallyAvailableAt="2015-10-19" summary="Jason, Eleiza and their young daughter Lily have moved all over the world for his career as a physics professor, but they're ready to set down roots and buy their first home near his current job in the Hartford, Connecticut area." title="A Connecticut Family Hopes To Create A Home With All Natural Elements" index="8" art="http://resources-cdn.plexapp.com/image/art/com.plexapp.plugins.hgtvcanada.jpg?h=f02f240" thumb="http://media.hgtv.ca/videothumbnails/143/898/HGTV_HouseHunters_S5E508_230x129_547774531744.jpg" grandparentTitle="House Hunters: Renovation" parentIndex="5" duration="2594325" sourceTitle="HGTV Canada" ratingKey="http://www.hgtv.ca/video/video.html?v=547758147556">
<Media audioChannels="2" protocol="hls" videoFrameRate="29" height="544" width="968" container="mpegts" audioCodec="aac" duration="2594325" videoCodec="h264" videoResolution="544" bitrate="827363">
<Part duration="2594325" container="mpegts" key="/:/plugins/com.plexapp.system/serviceFunction/url/com.plexapp.plugins.hgtvcanada/HGTV%20Canada/PlayVideo.m3u8?args=Y2VyZWFsMQoxCnR1cGxlCjAKcjAK&kwargs=Y2VyZWFsMQoxCmRpY3QKMQpzMjU5Cmh0dHBzOi8vaGd0di12aC5ha2FtYWloZC5uZXQvaS8sMTQzLzg5OC9IR1RWX0hvdXNlSHVudGVyc19TNUU1MDgubXA0LC5jc21pbC9tYXN0ZXIubTN1OD9oZG5lYT1pcD0yNC4xNDAuMjQ2LjEzNn5zdD0xNDQ1MzYzNDA3fmV4cD0xNDQ1MzY0MDA3fmFjbD0vaS8qfmlkPWI5NzhhMzg0LWNiMTQtNDBkMy04OTAwLWE0NmFmMzVjMjliN35obWFjPTg1OTM5YmMxZmY4NDc5MGE5YTU0MzU5N2Y3NzczZjhhMjg1NjkzYjJhNzQ0NmE4OTJiMzQ0Y2I0Mzg2MWE4OWFzMwp1cmxyMAo_" file="">
<Stream index="0" selected="1" streamType="1" height="544" width="968" codec="h264" duration="2594325" bitrate="827107" id="1"/>
<Stream index="1" selected="1" streamType="2" channels="2" codec="aac" duration="2594325" bitrate="256" id="2"/>
</Part>
</Media>
</Video>
</MediaContainer>
```

**Comment by Gerk** [comment]
When viewing media info in Web it shows correctly

![screen shot 2015-10-20 at 1 47 03 pm](https://cloud.githubusercontent.com/assets/172505/10616305/725632f6-7732-11e5-82f7-846906206812.png)

**Comment by Gerk** [comment]
And here is XML for a library item, which also seems to present bitrate in Kbps.

<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="17" librarySectionTitle="TV" librarySectionUUID="98f28503f824950f12b493fd49b89d9f6eae337e" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1444876548">
<Video ratingKey="608543" key="/library/metadata/608543" parentRatingKey="608539" grandparentRatingKey="608341" guid="com.plexapp.agents.thetvdb://77666/22/4?lang=en" type="episode" title="I Love Monkeys!" grandparentKey="/library/metadata/608341" parentKey="/library/metadata/608539" grandparentTitle="The Amazing Race" contentRating="TV-PG" summary="Stress makes one contestant cry; a team makes history while trying to stay in the game." index="4" parentIndex="22" rating="7.3" year="2013" thumb="/library/metadata/608543/thumb/1441560467" art="/library/metadata/608341/art/1441560475" parentThumb="/library/metadata/608539/thumb/1441560474" grandparentThumb="/library/metadata/608341/thumb/1441560475" grandparentArt="/library/metadata/608341/art/1441560475" grandparentTheme="/library/metadata/608341/theme/1441560475" duration="2606335" originallyAvailableAt="2013-03-10" addedAt="1441286711" updatedAt="1441560467" chapterSource="">
<Media videoResolution="sd" id="981198" duration="2606335" bitrate="1551" width="720" height="406" aspectRatio="1.78" audioChannels="2" audioCodec="aac" videoCodec="h264" container="mp4" videoFrameRate="60p" optimizedForStreaming="1" has64bitOffsets="0">
<Part accessible="1" exists="1" id="1076394" key="/library/parts/1076394/file.mp4" duration="2606335" file="/Volumes/nRAID1/Media/TV/The Amazing Race/Season 22/The Amazing Race.S22E04.I Love Monkeys!.mp4" size="505308570" container="mp4" has64bitOffsets="0" indexes="sd" optimizedForStreaming="1">
<Stream id="1891449" streamType="1" codec="h264" index="0" bitrate="1414" bitDepth="8" cabac="1" chromaSubsampling="4:2:0" codecID="avc1" colorSpace="yuv" duration="2606303" frameRate="59.940" frameRateMode="cfr" hasScalingMatrix="0" height="406" level="31" profile="high" refFrames="5" scanType="progressive" streamIdentifier="1" width="720"/>
<Stream id="1891450" streamType="2" selected="1" codec="aac" index="1" channels="2" bitrate="130" audioChannelLayout="stereo" bitrateMode="vbr" codecID="40" duration="2606335" profile="lc" samplingRate="48000" streamIdentifier="2"/>
</Part>
</Media>
<Extras size="0"></Extras>
</Video>
</MediaContainer>

**Comment by rcombs** [comment]
The channel is sending an absurd value and PMP is displaying it correctly. Please report this with the channel developers.
