### ISSUE TITLE
Have Options to Shutdown / StandBy / etc, not just Quit

### ISSUE THREAD

**Issue by JonathanFowlke** [plexinc/plex-media-player#100]
It would be nice for PMP to be able to Shutdown / Restart / StandBy my HTPC from the same menu as the Quit.

**Comment by NedtheNerd** [comment]
Feature requests should be posted in the Forum, there is already such a Feature Request.

**Comment by atrus05** [comment]
Yes, use the forum for FR. Closing this one out.
