### ISSUE TITLE
Plex Player for macOS still does not retain its window position and size

### ISSUE THREAD

**Issue by mpmchugh** [plexinc/plex-media-player#1002]
### Test environment

**PMS Version: 1.21.1.3753**
**PMP Version: 1.24.0**
**Platform macOS :**

### Steps to reproduce
Launch Plex, Resize window to desired size and position. Quit and relaunch Plex, and window returns to default size.

### Current behavior
Plex Player for macOS still does not retain its window position and size

### Expected behavior
Plex Player for macOS should retain its window position and size after quitting and relaunching. This is basic app behavior—one should not have to resize the window every time it launches.

**Comment by mseeley** [comment]
We save the current window size and position approximately 1s after the last size or position change. At the next startup we do restore each to their previous settings. I've confirmed this behavior works correctly for me on `1.24.0.1436-fa670700` and macOS 10.15.7. Are you on Big Sur?

Please review the `[ui]` portion of `~/Library/Application\ Support/Plex.ini`. Here's mine for example:

```
[ui]
screen=LG HDR 4K
visibility=2
windowHeight=494
windowWidth=1048
windowX=326
windowY=418
```

Do you have any unusual numbers in there?

Position/size updates will be saved to disk shortly after the changes stop. Will you confirm this behavior?

Are you removing screens between application sessions? As you can see, there is a single previous shape to restore.

**Comment by mseeley** [comment]
Please reply with additional information if this is still not working for you.
