### ISSUE TITLE
Request: Build for Apple Silicon

### ISSUE THREAD

**Issue by flying-sausages** [plexinc/plex-media-player#1003]
The usual template does not really fit this so I took the liberty to remove it.

Please add support for the Apple Silicon arm systems. The Plex app is one of the last few things that I use that still need to make the migration. The iOS app _works_, but UX wise it is quite sub-optimal, and it suffers from a lot of weird time stretching (an issue I suppose I'll be making elsewhere).

**Comment by alexalder** [comment]
Kinda weird we had no update in the last two months

**Comment by flying-sausages** [comment]
Are you insinuating I'm barking at the wrong tree here? 😄

**Comment by mseeley** [comment]
We've got a dependency on Qt (with WebEngine) building on Apple Silicon first: https://bugreports.qt.io/browse/QTBUG-85279. We'll be unblocked once QT 6.2 is released. Although it's worth a bit of patience in case QT 6.2  brings blockers of its own or other build system updates need to occur in parallel.

Thanks for the request. We'll keep an eye out.

**Comment by flying-sausages** [comment]
Should this bug be closed here or are you guys tracking it elsewhere? Just want to make sure this will get updates and have progress tracked as other sites are pointing to this issue to keep track of what does and does not support Apple Silicon. e.g. https://isapplesiliconready.com/app/Plex%20Media%20Player (see "More Info" button)

**Comment by flying-sausages** [comment]
[Qt's 6.2 Roadmap is here](https://wiki.qt.io/Qt_6.2_Release) and the first beta is out. The full release should be in September.

**Comment by anonyme123** [comment]
Any update on this?

**Comment by ICULikeMac** [comment]
+1 any updates?

**Comment by almottier** [comment]
+1
iPad app on MacOS is not adapted and missing features

**Comment by flying-sausages** [comment]
@mseeley are there any updates by any chance?

**Comment by almottier** [comment]
@mseeley could you re-open this issue as QT has now Silicon support 🙏

**Comment by PathToLife** [comment]
I'm mainly wanting to minimise battery drain (Rosetta2 emulation is not as optimal as native arm)

Is the App Store version of Plex (iPad) a good compromise for now? As it's built for apple silicon. - Giving it a go

<img width="501" alt="image" src="https://user-images.githubusercontent.com/12622625/163726489-1243d6af-75b6-4cf2-be4d-320a2b821079.png">
