### ISSUE TITLE
Add Hardware transcoder support for RPI4

### ISSUE THREAD

**Issue by MrD2** [plexinc/plex-media-player#1006]
The header is self explanatory.

i can make the hw interface exposed in the container (/dev/dri/) but the transcoder option on the server configurations are not shown . I did buy the plex pass on purpose for this and also the server has group permissions has i added it to the video group.

Apparently the code its hardcoded to use the IntelQ transcoder hw accelerator, it seems that this is tied to the Qt package tho, (not sure, i did a quick read through the code.)

I could help with this, if i have some pointers, but i will not be able to test this after.

**Comment by OttoKerner** [comment]
This repository is for the player, not the server.

**Comment by MrD2** [comment]
Do you know where the original repo for the server is?

I can't find a original one.

**Comment by MrD2** [comment]
Do you know the original URL of the plex-server?

I can't find anything relevant in the original repo.

https://github.com/plexinc/pms-docker OR
https://github.com/plexinc/PlexMediaServer-Ubuntu

**Comment by OttoKerner** [comment]
There is no publicly accessible repo for the server.
