### ISSUE TITLE
Tidal songs stop after 19 seconds

### ISSUE THREAD

**Issue by hirnschmalz** [plexinc/plex-media-player#1007]
### Test environment

**PMS Version:** 1.21.1.3876
**PMP Version:** 4.29.2
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Arch Linux

### Steps to reproduce
1. Have a valid Tidal account
2. Play a song on Tidal

### Current behavior
1. The song stops after 19 seconds and the next song get startet (this repeats forever)

### Expected behavior
1. The song should be played until the end

**Comment by hirnschmalz** [comment]
After some investigation it looks like this only happens in the desktop view. If I use the TV view songs are played as expected.

**Comment by mseeley** [comment]
Thanks for the additional context @hirnschmalz. We're unsure what it's operating that way. We're focusing on other apps and won't be circling back into the PMP desktop layout to investigate further.

Hosted Plex Web or Plexamp for Linux will be your best workarounds until we have an official Plex for Linux version of the Plex for Mac/Windows app.
