### ISSUE TITLE
No Fast Forward or Rewind Controls for Music or Podcasts while in TV Mode for PMP on PC

### ISSUE THREAD

**Issue by justing1216** [plexinc/plex-media-player#1009]
The are no controls for Fast Forward/RW in the TV Mode UI of Plex Media Player for Windows 10 in addition to this there aren't any key binds to Fast Forward/RW AND you can't even you the mouse/touchpad(or in our case air mouse) to click the progress bar or move the slider. Because of this you are forced to either start the entire track over or move on to the next track. Upon exiting TV Layout you are able to use the mouse to click different sections of the progress bar and there are FF/RW binds to the Left and Right Arrow Keys however there are still no FF/RW buttons in the UI. 

Pretty please update ASAP so we can use our HTPC to listen to Music and Podcasts without having to breakout the Ol' Keyboard and Mouse or Exit TV Mode every time.

First time poster! Thanks A TON in advance!! :-)

-Justin

**Comment by justing1216** [comment]
Awesome thank you for the information! I had almost fourteen about my post.
To solve my problem so I just switched back the the web client instead. Can
you send me a link to the HTPC app? And maybe I will give that a try!

Thanks again,
         Justin

**Comment by mseeley** [comment]
@justing1216 sure thing: https://forums.plex.tv/t/plex-htpc/703783
