### ISSUE TITLE
Windows intaller looks ugly DPI of 150% 

### ISSUE THREAD

**Issue by sjorge** [plexinc/plex-media-player#101]
The installer looks horrible on Windows 10 with a DPI of 150%.

**Comment by tru** [comment]
Screenshot?

**Comment by sjorge** [comment]
I will try to capture one but l swapped DPI to install and got locked out due to it being stuck on the login screen (VNC + Autologin)

**Comment by wm4** [comment]
With Windows 8.1 on a MBP I can confirm that the installer looks ugly, but it's not unusable.

**Comment by sjorge** [comment]
![Installer](http://i.imgur.com/QKzMPs0.png)

**Comment by tru** [comment]
I think that proper DPI support for windows was added in Qt5.5 so this might just be fixed when I update the installer (which is on my list of things to do).

#80 #43

**Comment by tru** [comment]
Can you give this one a go: https://nightlies.plex.tv/directdl/plexmediaplayer/dist-ninja/1.0.2.50-17f51ba4/PlexMediaPlayer-1.0.2.50-17f51ba4-windows-x86_64.exe

Does it look better and does it work as expected?

**Comment by sjorge** [comment]
Still looks the same at first glance.

[1.0.2.50-17f51ba4/PlexMediaPlayer-1.0.2.50-17f51ba4-windows-x86_64.exe](http://i.imgur.com/4hLU1hh.png)

**Comment by tru** [comment]
Thanks. We might improve it even more later.
