### ISSUE TITLE
Plex win10 client apps (pmp) dropping connection to server on different pc’s

### ISSUE THREAD

**Issue by mykljh** [plexinc/plex-media-player#1013]
### Test environment

**PMS Version:**1.21.3.4021
**PMP Version:**1.27.2.1599-7689068b
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**Win 10

### Steps to reproduce
1.
The issue occurs on the PMS machine client app as well as other client apps on other pc’s on my network. It works for awhile and then dashboard freezes. I have to kill the app and restart it. The web UI and other devices work fine. It worked fine for years up to about a week ago.
### Current behavior
1.
Same.
### Expected behavior
1.
Same.

**Comment by mseeley** [comment]
There's quite literally nothing practical we can do with the provided steps to reproduce.

If you catch this issue again please provide logs.
