### ISSUE TITLE
Win10 PMP can't play downloads without internet connection. 

### ISSUE THREAD

**Issue by Jako4460** [plexinc/plex-media-player#1017]
### Test environment

PMS Version:  4.54.4
PMP Version: 1.29.1.1974-a65b3ef3
Platform (Windows/macOS/Embedded RPi/Embedded Intel): Win10 / Win10

### Steps to reproduce
1.) I have some videos downloaded and they work just fine when playing them from the 'download' tap with internet connection.
2.) When internet is disabled on PMP, while in the app, i can stille play every video downloaded just fine. 
3.) When app is restartet, without the internet connection, i can still see everything downloaded but nothing happens when i press play. 
4.) I know every file has been downloaded, because i can play them directly from the windows folder: \AppData\Local\Plex\Plex Media Server\Sync\1\2.

### Current behavior
1. When the PMP app has been started without internet connection, i can see but not play any of the download videos through the PMP. 

### Expected behavior
1. Offline files should be playable without an internet connection. 
[Plex_logs.zip](https://github.com/plexinc/plex-media-player/files/6217196/Plex_logs.zip)

-I have tried reinstalling PMP several times and also on another windows pc, same resulat 
// Best Regards / Jakob

**Comment by mseeley** [comment]
Hi @Jako4460, thank you very much concisely reporting the issue. The 1.30.0 update released just a few moments ago addresses this issue.

**Comment by Jako4460** [comment]
Wow that was very fast, thanks alot! It works great now. You guys are awesome! <3
