### ISSUE TITLE
Plex/Web missing some info when PMP is playing something.

### ISSUE THREAD

**Issue by sjorge** [plexinc/plex-media-player#102]
![Plex/Web Now Playing](http://i.imgur.com/63hGFzV.png)

No player info is shown, just the hostname

**Comment by sjorge** [comment]
May be related to #98

**Comment by tru** [comment]
I don't think this is related to #98, this seems like something wrong with the timeline updates. Ping @mseeley and @ericmatthys

**Comment by mseeley** [comment]
The displayed dimension is odd but this appears to be working as correct against 1.0.1 and UI `master@HEAD`. Although, the dimension displayed looks a little odd.

![screen shot 2015-11-02 at 2 18 37 pm](https://cloud.githubusercontent.com/assets/30019/10898235/9ccda82c-816c-11e5-9c39-d42d59be3668.png)

![screen shot 2015-11-02 at 2 14 03 pm](https://cloud.githubusercontent.com/assets/30019/10898242/a640e0b8-816c-11e5-9a0e-beaed59fa146.png)

![screen shot 2015-11-02 at 2 13 55 pm](https://cloud.githubusercontent.com/assets/30019/10898243/a647c234-816c-11e5-83b1-52ead60c5793.png)

What specifically is expected to display which is not?

**Comment by atrus05** [comment]
I am fairly certain that at least once upon a time we were able to see which app was playing the media. Right?

**Comment by sjorge** [comment]
I just compared again, PHT and PMP looks the same now. But as @atrus05 I seem to remember at somepoint we could see which app was playing.

And background images are working now with PMP, before everything had a gray bug like in my first screenshot.

**Comment by mseeley** [comment]
We still can, that's the `Plex for PlayStation...` bit above. It appears PMP is identifying itself as the host machine's name instead of `Plex Media Player`. This seems relevant to previous feedback where multiple PMP on the same network all identified identically.

I want to say the resource information we get from the host could use additional information, or, Web needs to special case PMP. One of these fellas must be providing the machine name.

```
dimensions['X-Plex-Product'] = resource.product;
dimensions['X-Plex-Platform-Version'] = resource.version;
dimensions['X-Plex-Device-Name'] = resource.title;
```

**Comment by ericmatthys** [comment]
```xml
<Player address="192.168.1.99" machineIdentifier="aj3dztq20xjemi" platform="Konvergo" product="Plex Media Player" state="playing" title="machine" />
```

![screen shot 2015-11-12 at 9 28 44 am](https://cloud.githubusercontent.com/assets/1154586/11123979/c8ead15e-891f-11e5-895a-b1f100b58759.png)

This appears to be working correctly for me. We've always shown the device name with the device icon. The device icon you see above will show up in the next web update.
