### ISSUE TITLE
PMP is failing to play manually added videos in the 'special' season folder and plays S01E01 instead

### ISSUE THREAD

**Issue by Dingmatt** [plexinc/plex-media-player#1027]
As mentioned in the title if you add a video in the 'special' season folder and have it detected via a scanner, when you go to play the video it'll play S01E01 instead. 

This only seems to occur for media files that don't exist in TVDB and it's worth noting that my scanner numbers manually added episodes #101+ (aka Episode 101, Episode 102, etc). 

This is a new issue as the media has played fine in the past, it also only effect PMP (desktop and web), the android app still plays the media correctly.

### Test environment
**PMS Version: 1.23.0.4497**
**PMP Version: 1.31.1.2262-74fdc6b7**
**Platform: Windows**

### Steps to reproduce
1. Add a media file into an existing series 'special' folder (the specials season)
2. Wait for Plex to detect the media
3. Click Play

### Current behavior
1. The episode S01E01 will play instead

### Expected behavior
1. The correct episode will play

[Logs.zip](https://github.com/plexinc/plex-media-player/files/6468956/Logs.zip)
[MetaData.txt](https://github.com/plexinc/plex-media-player/files/6469021/MetaData.txt)

**Comment by gbooker** [comment]
Note: Specials need to have their airdate set correctly to be placed in the proper order in the play queue.  Additionally the server has an issue when the airdate is the same as another special or a normal episode which will be fixed in 1.23.2.

**Comment by Dingmatt** [comment]
The program isn't having to determine which order to play the special in, this is happening went the episode is selected directly; the metadata shows all the correct file location, it's just not playing it and falling back to something else instead.

This is also a new issue, previous versions and the app work fine.

**Comment by gbooker** [comment]
It's always creating a playqueue when you play a particular episode.

**Comment by Dingmatt** [comment]
That does make sense but surely that should only affect its own place in said queue, the idea that it would override what you've selected and just play something random instead is definitely not expected or previous behaviour.

Is a fix coming in 1.23.2 or has something fundamentally changed that will require changes to an media agent?
