### ISSUE TITLE
PMP v4.29.2 switches off when trying to change manually "Home Screen"

### ISSUE THREAD

**Issue by balacsoft** [plexinc/plex-media-player#1028]
When trying to change the organization of the HOME screen manually (not automatic change), the Plex Media Player window closes without any message or warning.

### Test environment

PMS Version: 4.54.4 
PMP Version: 4.29.2
Platform (Windows/macOS/Embedded RPi/Embedded Intel): Windows 10

### Steps to reproduce
1. In "home" screen, click the "pen" icon at top right
2. select "disable (manually change)"
3. Plex crashes

### Current behavior
1. crash - window closes without any message

### Expected behavior
1. no crash and possibility to change the home screen

**Comment by OttoKerner** [comment]
Manual Home screen is no longer supported by the server. So don't try to do it now.
