### ISSUE TITLE
Cut a release to resolve OpenGL issue

### ISSUE THREAD

**Issue by JamieMagee** [plexinc/plex-media-player#1029]
### Test environment

**PMS Version:** 1.23.1.4602
**PMP Version:** 2.58.0.1076
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Linux (NixOS)

### Steps to reproduce
1. Install plex-media-player
2. Attempt to open PMP

### Current behavior
1. PMP crashes with "Could not initialize OpenGL"

### Expected behavior
1. PMP opens

I initially created this bug over at NixOS here: NixOS/nixpkgs#123173 (There is more detailed debug information there). @ecoughlan helped to identify the issue, and that it had been resolved in a recent commit here: https://github.com/plexinc/plex-media-player/commit/5430cd807250a8f7329baad76b15a363f35b53fa.

Is it possible to cut a release that contains this fix, so we can package the updated version for NixOS? Thanks!

**Comment by mseeley** [comment]
Was going to ask to pin the package to a commit but there's minimal activity between the last release and HEAD. We'll look into tagging a 2.58.1 early next week.

**Comment by JamieMagee** [comment]
Thank you!
