### ISSUE TITLE
Release v2.58.1-ae73e074 breaks with naming scheme

### ISSUE THREAD

**Issue by ombre8** [plexinc/plex-media-player#1030]
Hi there,

With the latest release, there is a break in the naming scheme, which breaks the pipeline used to update the [AUR Package](https://aur.archlinux.org/packages/plex-media-player/). Is this a new scheme we can relay on or not?

Thanks for your work

**Comment by mseeley** [comment]
Hi @ombre8, thanks for reaching out.

Yes, this this naming scheme will be stable.

**Comment by ombre8** [comment]
Hi @mseeley 
thanks for your answer, I will then adapt our Pipeline
