### ISSUE TITLE
Still experincing micro-stuttering every time i use PMP

### ISSUE THREAD

**Issue by Jako4460** [plexinc/plex-media-player#1031]
Hi again 

A while back i reported micro-stuttering when using PMP and unfortunaly the problem still persist. Every time is watch a 20 min epsiode, atleast once the frame will freeze for a split second, which is pretty anoying. I switched to the web player for a while, but i like the app better, so i though i would give it another go. 

I have been going through all settings I though might casuse this: Enable/disable hardware decoding, direct strem/transcoding (different qualities), keep plex on top of windows. And different combinations of those settings.

[PLexLogs.zip](https://github.com/plexinc/plex-media-player/files/6651480/PLexLogs.zip)

 All files have been h.264 encoded and played on local network. My laptop is new with the Intel i7 1065g7, which should be more than sufficient. 

In the latest log i switched off direct stream when the first stuttering occured, and playback was fine throughout the rest of the eppisode. 

I know this is probably a pretty shitty task, but thanks for the effort :)

### Test environment

PMS Version: 1.23.2.4656
PMP Version: 1.31.1.2262-74fdc6b7
Platform (Windows/macOS/Embedded RPi/Embedded Intel): WIN10 / WIN10

### Steps to reproduce
1. Watch something. 

### Current behavior
1. Micro-stuttering occuring at least once for every 20 min playback. 

### Expected behavior
1. Smooth playback like

**Comment by tartley** [comment]
@Jako4460 Do new releases still have this issue for you?

**Comment by tartley** [comment]
Dupe of #1022

**Comment by Jako4460** [comment]
The problem still persists, but i'm closing this since another case is open.
