### ISSUE TITLE
TV Layout is missing... TV

### ISSUE THREAD

**Issue by hellomiakoda** [plexinc/plex-media-player#1034]
The TV Layout has no way to view the guide in TV and DVR, and thus, no ability to watch OTA TV live. 

### Test environment

**PMS Version:**
**PMP Version: 1.23.5.4862 **
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): Manjaro**

### Steps to reproduce
1.Open PMP
2. Select TV layout
3. Select "TV and DVR"

### Current behavior
1. No guide
2. no ability to tune in live

### Expected behavior
1.Guide
2. Ability to watch live

**Comment by OttoKerner** [comment]
PMP as such will not get any new features.
Use "Plex HTPC" or "Plex for Windows/Mac"

**Comment by hellomiakoda** [comment]
"Use Plex for Windows/Mac" - No, I don't think I will, as I don't have
Windows or Mac. That is probably why I went for a Linux program, but
that's just a guess.
