### ISSUE TITLE
Transcoding problem

### ISSUE THREAD

**Issue by yoanndelattre** [plexinc/plex-media-player#1035]
### Test environment

**PMS Version:** 1.23.6.4881 
**PMP Version:** 8.20.1.26670
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Android Google Pixel 4a

I have a problem, sometimes when I read a movie, plex starts to transcode the movie. 
It transcodes it from H264 to H264. 
The film is in .mkv. 
Direct reading and direct broadcasting are well authorized.
I would like to avoid absolutely transcoding. 
I get this in the logs file.

![image](https://user-images.githubusercontent.com/32218722/127748452-2d6df103-e2f9-4a33-b9e8-55d6a5bd726f.png)

**Comment by OttoKerner** [comment]
The Plex app on Android is not "Plex Media Player".
Please use the forums. https://forums.plex.tv/tags/c/plex-players/mobile-devices/28/android-mobile
