### ISSUE TITLE
Thin bars flickering on right and bottom sides while playing videos (after updating to newest version on MacOSX)

### ISSUE THREAD

**Issue by joshmweinstein** [plexinc/plex-media-player#1037]
### Test environment

**PMS Version:**
**PMP Version: 1.34.1.2590-74ea7099**
**Platform:macOS**

### Steps to reproduce
1. Open plex and select media file to play
2. Play file

### Current behavior
1. When playing a file, thin semi-opaque lines flicker on and off on the right side and bottom of the screen (see screenshot for comparison of on/off

### Expected behavior
1. No lines
[plex-logs.zip](https://github.com/plexinc/plex-media-player/files/7071296/plex-logs.zip)

![Screen Shot 2021-08-28 at 21 33 39](https://user-images.githubusercontent.com/3496053/131228148-35fe6ef4-6037-478d-9e38-c4839138fba9.png)
![Screen Shot 2021-08-28 at 21 33 26](https://user-images.githubusercontent.com/3496053/131228154-ef2655b0-c74d-4bec-b7e4-c34780a0ce9a.png)

**Comment by gbooker** [comment]
This repository is for the old Plex Media Player, not "Plex for Mac".
