### ISSUE TITLE
PMP no input response from preconnected gamepad

### ISSUE THREAD

**Issue by emrysblack** [plexinc/plex-media-player#1038]
**PMS Version:1.24.2.5000**
**PMP Version:2.58.0.1076-38e019da**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): Windows 10**

### Steps to reproduce
1. Exit PMP
2. Power on wireless gamepad (Xbox 1 windows controller in my case) and connect to PC
3. Launch PMP

### Current behavior
1. No gamepad input is detected in PMP from controller with pre-existing connection
2. If PMP is launched and gamepad powered on in focused PMP window, gamepad navigation works as expected

### Expected behavior
1. Gamepad should interact with PMP regardless of gamepad and PMP launch order

**Comment by gbooker** [comment]
PMP is no longer seeing any development.  If you use the desktop UI (mouse-driven) you should use Plex for Windows (https://www.plex.tv/media-server-downloads/#plex-app) and if you are using the 10ft UI, you should try out Plex HTPC which is currently in forum preview: https://forums.plex.tv/t/introducing-plex-htpc/703075

**Comment by gbooker** [comment]
> **PMP Version:2.58.0.1076-38e019da**

> This is for the Plex HTPC application, that's what I use.

This isn't an HTPC version; it's a PMP version.  Additionally you repeatedly referenced PMP and not HTPC.

> Is this not the place to submit bugs reports for Plex HTPC

It's not.  The forums would be the best place to discuss this.  There is a general feedback thread (https://forums.plex.tv/t/plex-htpc-feedback/703205) linked from the link I previously gave you.

**Comment by emrysblack** [comment]
> 
> 
> > **PMP Version:2.58.0.1076-38e019da**
> 
> > This is for the Plex HTPC application, that's what I use.
> 
> This isn't an HTPC version; it's a PMP version. Additionally you repeatedly referenced PMP and not HTPC.
I meant my bug report was meant for HTPC, not this repo space. I just thought the HTPC was called PMP in the context of this repo, I didn't realize it was for a deprecated code base.
> 
> > Is this not the place to submit bugs reports for Plex HTPC
> 
> It's not. The forums would be the best place to discuss this. There is a general feedback thread (https://forums.plex.tv/t/plex-htpc-feedback/703205) linked from the link I previously gave you.
Thanks. I will repost there then. You've been most helpful.
