### ISSUE TITLE
Progress bar issues

### ISSUE THREAD

**Issue by miketweaver** [plexinc/plex-media-player#104]
I'm having strange progress bar drawing issues:
![PMP Issues](http://i.imgur.com/xGWbPXL.png)
_Side note: that's a nasty color of yellow._

When I show the same clip in chrome it looks OK.
![Works fine in Chrome](http://i.imgur.com/6Gnf9b5.png)

When I view the width in chrome it lists it as 177%
![177%](http://i.imgur.com/kkWul3C.png)

That may have something to do with it.

This is how far I actually am into the episode:
![Actual Length](http://i.imgur.com/64ZH8ze.png)

**Comment by elan** [comment]
You must really be watching the %#$% out of that episode!

(My suspicion is that media analysis found the wrong duration--too short--and the UI code doesn't bound the % at 100)

**Comment by miketweaver** [comment]
elan:
You're probably right. Plex seems to think the clip is only 10min long.
![10min](http://i.imgur.com/L0JKtDa.png)

**Comment by mseeley** [comment]
Good call on the analysis duration vs actual duration.

Instead of clamping at 100% I'd like to ignore the `viewOffset` when it exceeds the `duration` -- show nothing when we can't show something accurate. Any objections?

**Comment by elan** [comment]
It's impossible to say _where_ exactly the progress should be, but it seems equally disingenuous but perhaps less misleading to show the video as 50% played, rather than not at all?

**Comment by elan** [comment]
cc: @mmccurdy

**Comment by mmccurdy** [comment]
I could get behind the 50% fallback (at least it implies partial watchedness, even though it may be somewhat surprising upon resume to find that you're not exactly at the 50% mark). It's a fairly pathological case after all, so maybe a small amount of lying is not terrible here.

**Comment by mseeley** [comment]
Yeah no good answer really. Going 50%, split the difference. :)
