### ISSUE TITLE
An unknown error occurred (4294967283)

### ISSUE THREAD

**Issue by Foowy** [plexinc/plex-media-player#1043]
### Test environment

PMS Version: *1.24.4.5081*
PMP Version: *1.35.1.2632-c6783c78*
Platform (Windows/macOS/Embedded RPi/Embedded Intel): *Windows*

### Steps to reproduce
1. Currently playing any movie/show

### Current behavior
1. Playback Error
An unknown error occurred (4294967283)
Error code: 4294967283

### Expected behavior
1. No error on playback

[Plex.log](https://github.com/plexinc/plex-media-player/files/7255062/Plex.log)

**Comment by Foowy** [comment]
Tested:

Uninstall and Re-install
Disabled/stopping of all unnecessary applications in case of GPU hold
Previous videos that were play prior to error, these are no longer able to be played.

Recent Changes:

Updated PMS to 1.24.4.5081, issue appeared several hours after update.

Can upload PMS logs if required.

**Comment by gbooker** [comment]
In your logs is:
```
Sep 29, 2021 13:55:26.682 [38296] ERROR - [MPVEngine/mpv] ffmpeg: tls: Peer certificate failed verification
Sep 29, 2021 13:55:26.682 [38296] ERROR - [MPVEngine/mpv] stream: Failed to open https://192-168-1-40.150713001e77416fb00a032568e8cc85.plex.direct:32400/library/parts/148789/1614657941/file.mkv?<snip>
```
Check if the cert is valid at the provided URL.

The app you are referencing is not `Plex Media Player` but rather `Plex For Windows`.  This repo is for the former so I'm closing as a result of that.

**Comment by Foowy** [comment]
Yes, Attaching screenshot
![Plex Secure](https://user-images.githubusercontent.com/49217685/135357233-5e041d6c-963b-4469-8107-589d89b92f3e.png)
