### ISSUE TITLE
Windows Web Player displaying multiple "Recently Added"

### ISSUE THREAD

**Issue by OnyxXP** [plexinc/plex-media-player#1044]
PMS Version: 1.24.4.5081
PMP Version: 4.66.1
Platform (Windows/macOS/Embedded RPi/Embedded Intel): Windows 10 10 Pro 19042.1237 running inside of a Generation 2 Hyper-V VM that's running on a Dell R720XD (Dual Intel E5-2695 V2 and 128GB RAM) updated to all current firmware and Windows Server 2016 Standard.

Issue: Plex Web player shows several "Recently Added" rows for both Movies and TV libraries on the Home page. 

### Steps to reproduce
1. Pin Libraries to Home screen. 

### Current behavior
1. Recently Added TV Shows has 3 rows on the home page (where it used to only show one) and does not combine any other libraries. It seems that if I unpin the TV Shows library, all three Recently Added TV Shows rows will disappear and if I pin that single Library, all three rows return. They all contain the exact same content.
2. Recently Added Movies combines the following Libraries, Movies, Family Movies, Comedy, and Documentaries and displays 2 rows that display the same content. If I unpin Family Movies, Comedy, and Documentaries, both rows remain and just remove newly added media from the "Recently Added Movies" row. If I unpin ONLY Movies, 1 row will disappear and another remains with all of the content from the other libraries. If I repin Movies, the remaining row will add the recent content from Movies to that Recently Added Movies row and a new row will not be added. If I unpin all and then repin all of them, I will get the two Recently Added Movies rows again.

### Expected behavior
1. I expected only 1 row of Recently Added TV Shows and 1 row of Recently Added Movies. 

EDIT: I did not include logs because I get no errors when performing any tasks. If these are needed still, I will perform the tasks to repeat the displayed inconsistencies and post the logs.

**Comment by gbooker** [comment]
This repository isn't for the web app.

**Comment by OnyxXP** [comment]
The forum stated to post here. Would you mind directing me to the correct place to post this please?

**Comment by OttoKerner** [comment]
https://forums.plex.tv/tags/c/plex-players/computers/34/plex-web
