### ISSUE TITLE
Plex window does not open (with solution)

### ISSUE THREAD

**Issue by rkirman** [plexinc/plex-media-player#1050]
Windows 11 x64, 3 monitors, latest version windows player
i found on running the app it would not open a window, but would flash some white windows as it was opening and closing but nothing stayed on screen.

to reproduce and correct.....
i found if i had oppened plex on the right hand screen from my "main screen", and then closed plex
changed "main screen" to be the right most monitor
reopened plex it attempted to render the window to the right of the main monitor (which of course there is not one)

restored main monitor to centre screen and plex happily opened up to it's right again...

**edit after a trial i found i could also push plex off the left side, also rendering it unusable

sorry for the poor explination

**Comment by gbooker** [comment]
The template is there for a reason as it provides us with necessary information.
