### ISSUE TITLE
Player crashes on podcasts

### ISSUE THREAD

**Issue by egon010** [plexinc/plex-media-player#1051]
### Test environment

**PMS Version:** 1.24.5.5173
**PMP Version:** 1.34.1.2590-74ea7099
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS Catalina 10.15.7

### Steps to reproduce
1. Start playing an episode of a podcast.

### Current behavior
1. Episode starts to play, but crashes after less than a minute. Plex then continues to crash even when not playing, or highlighting a podcast

### Expected behavior
1. Client does not crash.

Entry from Apple crash reporter:

Application Specific Information:
terminating with uncaught exception of type std::runtime_error: Log: Error handling format string 'Download %s of %s progress %s of %s bytes (%d%%)': invalid type specifier
abort() called

**Comment by OttoKerner** [comment]
Update to the latest version of Plex for Windows/Mac manually.

FYI, this repository is for "Plex Media Player", not Plex for Windows/Mac.
