### ISSUE TITLE
Win 10 App window scaling totally borked!

### ISSUE THREAD

**Issue by mmalliaparfitt** [plexinc/plex-media-player#1052]
Hi Plex Team,

I recently upgraded my Win10 Desktop app after a server upgrade, to version 1.35.1.2632-c6783c78, and the display in the widow is so far scaled the interface is unusable and there is now an unknown playback error that I cannot find reference for online: 
![image](https://user-images.githubusercontent.com/42617569/139869107-b25c2650-cd17-4d54-a899-6ebf93d2e612.png)
[Plex Display Scaling Issues.pdf](https://github.com/plexinc/plex-media-player/files/7461486/Plex.Display.Scaling.Issues.pdf)

I expect it has something to do with the following lines in the logs:
Nov 02, 2021 14:27:33.656 [14044] INFO - [Controllers/WebController] Expected restored appearance: w:0 h:0 x:0 y:0 windowStates:WindowMaximized screen:\\.\DISPLAY1
Nov 02, 2021 14:27:33.656 [14044] INFO - [Controllers/WebController] Actual restored appearance: w:614 h:321 x:0 y:9 windowStates:WindowMaximized screen:\\.\DISPLAY1
[PlexLogs 02-11-2021.zip](https://github.com/plexinc/plex-media-player/files/7461485/PlexLogs.02-11-2021.zip)
This display from this log is 1920x1080@60Hz, and the other two displays are 4k - broken scaling on all of the screens.

Please help as cannot use Plex despite performing a full uninstall, a clean install, and I even deleted all registry keys and files in ‘AppData’ before installing again with the same results.
Windows Display scaling has not changed and have tried forcing PC to other resolutions and screen scales to resolve. Images of the windows below

### Test environment

**PMS Version:** PlexMediaServer-1.24.5.5173-8dcc73a59-x86_64.qpkg
**PMP Version:** Plex-1.35.1.2632-c6783c78-x86_64.exe
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows 10 Pro 64-bit

### Steps to reproduce
1. Installing Plex

### Current behavior
1. As described above

### Expected behavior
1. Plex app should open at the correct display scaling to be useable like it did before the update!

**Comment by gbooker** [comment]
This repository is for PMP, not the app you are reporting.

**Comment by mmalliaparfitt** [comment]
Dear @gbooker ,

Correct me if I am wrong, PMP is Plex Media Player???
I installed Plex for Windows from here: https://www.plex.tv/en-gb/media-server-downloads/#plex-app
Please advise which forum I should be using if the PMP forum is not right.

Regards
Max

**Comment by gbooker** [comment]
PMP != Plex For Windows.

**Comment by mmalliaparfitt** [comment]
Fair enough, will try to find another forum to post in.
