### ISSUE TITLE
Plex for MacOs do not respect ScreenTime

### ISSUE THREAD

**Issue by Lonli-Lokli** [plexinc/plex-media-player#1053]
### Test environment

**PMS Version:** 1.24.2.4973
**PMP Version:** 1.35.1.2632-c6783c78
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** MacOS

### Steps to reproduce
1. Open Plex on MacOS with Screen time enabled, allowed time is 10min

### Current behavior
1. After 10 mins play do not stop (as it is done with YouTube on Safari), sound is on, just no video

### Expected behavior
1. Playing should be stopped when allowed ScreenTime ended

**Comment by gbooker** [comment]
This repository is for PMP, not the app you are reporting.
