### ISSUE TITLE
HDR Playback Broken on PMP Version 1.37.0.2706-5b2cfe50

### ISSUE THREAD

**Issue by ACastanza** [plexinc/plex-media-player#1055]
### Test environment

**PMS Version:**
Version 1.24.5.5173-8dcc73a59

**PMP Version:**
Version 1.37.0.2706-5b2cfe50

**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**
Windows 11 Pro (AMD Ryzen 9)
GPU: Nvidia RTX 3090
Monitor: LG 27GN950-B (HDR supported and enabled on both the monitor and in Windows, functional HDR playback confirmed in MPC-BE)

### Steps to reproduce
1. Playback HDR10 Content

### Current behavior
1. HDR is not properly displayed

### Expected behavior
1. HDR should be properly displayed as it worked on previous versions

See also forum post by a different user with the same player version and the same issue: https://forums.plex.tv/t/colors-are-washed-up-even-on-non-hdr-content-version-problem/757467

**Comment by gbooker** [comment]
> **PMP Version:**
> Version 1.37.0.2706-5b2cfe50

That's not PMP.
