### ISSUE TITLE
Playing Movie From Collection

### ISSUE THREAD

**Issue by cornbean** [plexinc/plex-media-player#106]
Whenever I play a movie after selecting a collection, whenever I stop the movie and hit back to go back to the collection, it instead goes back to the All Movies selection, not back to the collection I selected. I hope that makes sense haha. I select a collection. Click a movie. Press play. Stop movie. Press back to return to collection. Instead it takes me to All Movies. Just thought that was a bit strange, and don't know if you have come across it yet or not. Just thought I'd let you know anyway. Thanks!

**Comment by dogonwheels** [comment]
Thanks - filters getting forgotten is a known issue. Will hopefully address this soon - https://github.com/plexinc/plex-web-client/issues/3394
