### ISSUE TITLE
Broken link during Linux Install (Debian 11)

### ISSUE THREAD

**Issue by dolhastelian** [plexinc/plex-media-player#1062]
**PMP Version:**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**
Debian 11 - bulseye
### Steps to reproduce
1. follow Linux build instructions , 

### Current behavior
1. broken download link - the file does not exist
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/hash.txt:
  "HTTP response code said error"

more info here
cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.9.5/5.9/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:49 (set_policy)

-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Success
-- set(TV_VERSION 4.29.6-045db5b)
-- Directory /home/dsi/pmp/plex-media-player/build/dependencies/universal-web-client-desktop/183-045db5be50e175/web-client-desktop-4.29.2-e50e175 already exists, remove it to redownload
-- Directory /home/dsi/pmp/plex-media-player/build/dependencies/universal-web-client-tv/183-045db5be50e175/web-client-tv-4.29.6-045db5b already exists, remove it to redownload
-- Not using bundled deps
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/hash.txt to plexmediaplayer-qt-206-hash.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:59 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/hash.txt:
  "HTTP response code said error"

    Trying 104.18.13.47:443...

  Connected to nightlies.plex.tv (104.18.13.47) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

.....

### Expected behavior
1. cmake completes successfully

**Comment by gbooker** [comment]
This only occurs if you didn't follow the instructions stating that you must download Qt on Linux.  See https://github.com/plexinc/plex-media-player#downloading-and-installing-qt
