### ISSUE TITLE
Debug info clipping and ontop

### ISSUE THREAD

**Issue by sjorge** [plexinc/plex-media-player#107]
![debug info](http://i.imgur.com/ve4IxiC.png)

On Mac OS X it seems if there are a few nics the list becomes huge because of all the intermediat stuff mac adds losing part of the list. Perhaps filtering out  Software Network Interface (gif),  6to4 tunnel interface (stf), Apple Wireless Direct Links (awdl), Bridges (birdge), and Tunnel devies (utun).

Also some of the filenames are long they go over/under the output more to the right.

**Comment by wm4** [comment]
Well yes, there's simply not enough space for everything. Personally I think it's ok that the playback URL is clipped off - you can see which endpoint it is (transcode or direct play), which is good enough information.

I admit we should maybe try not to let the config file cover the right part of the debug overlay.

**Comment by sjorge** [comment]
Perhaps only show the links that are active, the whole lot (inactive, bridges,...) can still be logged in the log for big problems that need some tough love.
