### ISSUE TITLE
Display mode switching not working

### ISSUE THREAD

**Issue by KaySeeOne** [plexinc/plex-media-player#111]
PMP fails to playback video files of different resolution/refresh rate to the desktop when in full screen mode.

Hardware/Software
Plex Media Player version: 1.0.1.42-56cc6ef9
Running on: Windows 8.1 [6.3.9600] arch x86_64
Display #0: AMD Radeon HD 8280
Display Mode on Display #0: 1920 x 1080 x 32bpp @60Hz

To recreate:
Set desktop display mode to 1920x1080 32bpp @60hz.
Check 'Allow Display Mode Switching' in settings video.
Play back a movie/TV show file containing video at a different resolution or refresh rate, e.g. 1920x1080 @24hz.
Screen will go black but audio will be heard via speakers. (The TV reports the correct mode for the video, e.g. 1920x1080 @24hz.
Switch out of full screen mode, 'ctrl-f', and switch back, 'ctrl-f' again.
Video will play back in correct mode.
When video finishes screen will go blank again.
Repeat the 'ctrl-f' switch to get the UI to display, the TV reports correct mode for the UI, e.g. 1920x1080 @60hz.

P.S. As a workaround run the player in windowed mode once the video is playing hot keying into full screen mode; hot key into windowed mode when video has finished; this is fine for me but not for others.

**Comment by wm4** [comment]
Sounds like the OpenGL driver is going on strike when this happens. The fact that going to windowed mode and then back to fullscreen mode fixes this makes me think it is. (We don't do anything special when toggling fullscreen.)

**Comment by KaySeeOne** [comment]
I thought I would try to recreate the issue on my workstation, which runs Windows 10, but the same PMP version and settings.
Strangely the refresh rate does not change, i.e. it stays at 60hz, and obviously the screen doesn't go blank.
I also forgot to mention in the previous comment that I tested the mode switching in PHT and it works as expected, on both machines.

**Comment by scdemanett** [comment]
This looks even closer to my issue so I moved my follow up here. Anyway I updated to 1.0.1.42 I have display mode switching on and attempted to play the same file with both PMP and PHT again PMP didn't put the TV into 24p but PHT did.

Here is the log from PMP from that test: http://pastebin.com/m3hYLL31

**Comment by wm4** [comment]
> 2015-11-02 19:26:37 [ WARN  ] DisplayComponent.cpp @ 234 - Unable to locate current display. 

This again.

**Comment by tru** [comment]
Do we have any idea what causes that?

**Comment by wm4** [comment]
Likely qt window position having nothing to do with how the monitors cover the virtual desktop. Have to take a closer look.

**Comment by tru** [comment]
Yeah that seems worth to put some time into. And maybe at the same time look at the problem where it doesn't open on the same display it was closed on.

**Comment by sjorge** [comment]
Not sure you are still collecting logs for when display mode switching is not working... but I have the issue too.

I'm running an APU system but I added a nvideo GPU to it because it offers better performance. The iGP from the APU is disabled in bios.

Log: http://sjorge.sinners.be/PlexMediaPlayer.log

**Comment by KaySeeOne** [comment]
The new version, 1.0.2.70-15a01542, try's to fix the problem by not actually switching the display mode.

Log: http://www.claydons.net/plex/PlexMediaPlayer.log

**Comment by wm4** [comment]
There's some talk about this on the forums: https://forums.plex.tv/discussion/192443/frametrate-switching-still-broken-in-latest-1-02-release-for-windows

The latest state is that we need a developer with an adequate test setup to look at this.

**Comment by KaySeeOne** [comment]
I'd love to help, but my c++ is extremely weak to non existent.

**Comment by daneel3001** [comment]
Is this bug still unresolved ?
I still experience it with my NUC running latest Intel drivers and Windows 10 build.

**Comment by wm4** [comment]
The general windows mode switching problems have been fixed a long time ago, but that doesn't mean _all_ mode switching bugs have been resolved.

Maybe you're hitting another issue that results in the same misbehavior.

**Comment by sjorge** [comment]
@wm4 must have been hitting an edge still then, works 1/2 the time using ANGLE, never works with OpenGL still.

**Comment by GhostM121** [comment]
I am having the same issue for me, opengl does not switch my tv's refresh rate angle does it fine. Windows 7, rx 460 gpu.

I made a post here, someone on avsforum told me simply opengl refresh rate switching has not worked for awhile, is this actually the case?

Thread is here, doesnt look like the logs will help say anything.

https://forums.plex.tv/discussion/240357/display-mode-switching-not-working-with-opengl#latest
