### ISSUE TITLE
OSD selection box can remain on screen when casting from iOS

### ISSUE THREAD

**Issue by mikedm139** [plexinc/plex-media-player#113]
![selection box onscreen during playback](https://cloud.githubusercontent.com/assets/277223/10866362/cbc5d118-7ff0-11e5-8568-10f9cee43bb1.jpg)

Steps to Reproduce:
1. Connect Plex iOS to PMP as remote.
2. Hit the `back` button on iOS remote while on the PMP homescreen causing the `reboot/relaunch` dialog to open.
3. Cast a video or (in this case) a playlist of videos to PMP from the iOS app.

Further interaction with playback controls do not seem to get the selection box to disappear although, it can move the position of the selection box across the invisible OSD.

Stopping playback and restarting it (without the `reboot/realunch` dialog open, seemed to fix the issue.

**Comment by LongChair** [comment]
this seems to be fixed now, closing.
