### ISSUE TITLE
Consider using ANGLE by default instead of OpenGL on Windows.

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#114]
Since we get so many crashes in OpenGL drivers we should consider to make ANGLE the default and give the option to upgrade to OpenGL. If nothing else I think we should enable it by default for at least a version or two and see if the strange OpenGL related crashes goes away from sentry.

To really do this well I think we should try to make it a GUI option instead of different shortcuts. I wonder if we can do a small wrapper binary that just reads our config file and then invokes the "real" binary with the correct environment, or change the batch script that invokes it.

This way we can even enable OpenGL by default if you enable filters that requires OpenGL.

@wm4 thoughts?

**Comment by wm4** [comment]
Yes, looks like we seriously need to consider this. It doesn't solve all problems either, though.

I really think there's something else wrong. Normally Windows OpenGL drivers shouldn't be that crashy. I doubt Chrome always enables ANGLE by default either (although I haven't checked - would be interesting to know). The thing I distrust most here is QtWebEngine/Chromium's OpenGL context sharing code, and it's also possible that the disable-chromium-gpu .bat script I added does nothing.

>To really do this well I think we should try to make it a GUI option instead of different shortcuts. I wonder if we can do a small wrapper binary that just reads our config file and then invokes the "real" binary with the correct environment, or change the batch script that invokes it.

This could be done within the PMP process too, as long as we influence the Qt setting before it creates the first OpenGL context, or so.

**Comment by tru** [comment]
From googles page on angle https://code.google.com/p/angleproject/

```
ANGLE is used as the default WebGL backend for both Google Chrome and Mozilla Firefox on Windows platforms. Chrome uses ANGLE for all graphics rendering on Windows, including the accelerated Canvas2D implementation and the Native Client sandbox environment
```

I agree it's fishy for sure that we crash that much. Which is why I propose that we flip it and see if the crash reports go down. Just as a test.

**Comment by wm4** [comment]
Well, we can try it. Users who want to use the high quality video rendering features will have to explicitly start the native OpenGL version then.

**Comment by TheFireKahuna** [comment]
https://github.com/mpv-player/mpv/issues/443

Note that one of the comments notes that ANGLE currently only provides ES 2.0. Its not a replacement for desktop OpenGL calls.
