### ISSUE TITLE
Multichannel tracks are not preferred when on a multichannel system

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#115]
The web client doesn't use the X-Plex-Capabilities header that is needed for the media server to autoselect a multichannel track over a stereo one. This was discussed in slack but I don't think I filed an issue.

**Comment by mseeley** [comment]
Any reference on the expected values? I only spotted:

* https://github.com/plexinc/plex-clients/issues/8
* and, https://github.com/plexinc/specs/search?q=X-Plex-Capabilities&type=Code&utf8=%E2%9C%93

Thanks :)

**Comment by tru** [comment]
https://github.com/plexinc/plex-home-theater/blob/master/plex/FileSystem/PlexFile.cpp

Scroll down a bit in that file and it create the header based on the settings.

**Comment by mseeley** [comment]
@tru, I need help me with the correct value for `X-Plex-Capabilities`. Pseudo code:

```
var protocols;
switch (platform) {
  case (rpi2):
    protocols = 'protocols=shoutcast,http-video;videoDecoders=h264{profile:high&resolution:1080&level:42};audioDecoders=mp3,aac';
    break;
  case (osx):
  case (windows):
    protocols = 'protocols=shoutcast,http-video;videoDecoders=h264{profile:high&resolution:3840&level:51};audioDecoders=mp3,aac';
    break;
  default:
    protocols = 'protocols=shoutcast,http-video;videoDecoders=h264{profile:high&resolution:1080&level:42};audioDecoders=mp3,aac';
    break;
}

// There's no `passthrough[CODEC]` settings in the UI (but there are in the conf), so I _guess_ we'd send both AC3 and DTS when the UI settings selected channels is over 2.

if (audio.channels > 2) {
  protocols += ',dts{bitrate:800000&channels:8}';
  protocols += ',ac3{bitrate:800000&channels:8}';
}
```

Questions:
* What do we send for `audioDecoder` capabilities when channels is set to Auto?
* With MPV, do we support many more `videoCodec` and `audioCodec` values than present in the PMP code sample?
* Do NUC devices identify themselves as running OpenELEC or Windows/Linux? builds? I need help understanding how we'd differentiate a Window's desktop from a NUC running Windows in order to provide the 4K resolution to `videoDecoders`.

**Comment by wm4** [comment]
I didn't know web-client reads the channels setting... could give some interesting interactions. Normally pmp/mpv tries to handle these things on its own, including ac3 transcoding.

> What do we send for audioDecoder capabilities when channels is set to Auto?

It might use multichannel audio then (behavior is only known at runtime).

> With MPV, do we support many more videoCodec and audioCodec values than present in the PMP code sample?

Definitely.

> Do NUC devices identify themselves as running OpenELEC or Windows/Linux builds? I need help understanding how we'd differentiate a Windows desktop from a NUC running Windows in order to provide the 4K resolution to videoDecoders for desktops.

A user can install Windows and the normal desktop version of pmp on a NUC. so there's currently no way of knowing this.

**Comment by wm4** [comment]
@mseeley any progress on this? We're getting frequent complaints about this on the forums.

**Comment by tru** [comment]
@Moussa this is a pretty highly requested feature so we should add these headers, it should be pretty easy.

**Comment by mseeley** [comment]
@tru / @Moussa the UI PR landed.
