### ISSUE TITLE
Audio mute for first second or two on a Raspberry Pi

### ISSUE THREAD

**Issue by palfrey** [plexinc/plex-media-player#117]
So, for some reason on my Pi, when I play a video file, for the first second or so it doesn't play the audio. When it kicks in, it's perfectly in sync, but there's just no audio for the first second or so. Tried with a variety of files, and I'm sure they've got audio, it's just not being played back for that first second or so...

**Comment by wm4** [comment]
This usually depends on the receiver. Most receivers ignore the first seconds of audio you send to them.

**Comment by tru** [comment]
PHT had a hack for this, where it would send silence at all times when it was not output audio.

**Comment by derik0709** [comment]
I am having the same issue. Has this been addressed?

**Comment by tru** [comment]
Not yet.

**Comment by wm4** [comment]
It's not that simple. There are some messy design decisions that have to be made.

For example, we could add a hack that "primes" audio for a few seconds with silence, but this would delay playback start.

Another possibility is opening the audio device in the pre-play screen (or keeping it always open in the background), but if you play something, it could turn out that the current audio format is not ideal for the file. Then we'd either have to convert audio, or reopen the audio device. I suspect reopening the device would also trigger this mute issue.
