### ISSUE TITLE
consider 21:9 ultra-wide screen video playback support

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#12]
I don't think we need to make the UI scale to 21:9 in a first iteration, but at least get the videos to play back normally on there.

But I need to understand why this doesn't work today, is it because the aspect forcing we do in QML or does it has something to do with the video player? @dogonwheels and @wm4 might have additional insights.

I know that @LongChair have a 21:9 display so he can probably test things for us.

**Comment by wm4** [comment]
I don't see a reason why this wouldn't work? The video player simply uses the available window size.

**Comment by dogonwheels** [comment]
I would expect this to have ugly clipping to the left and right of the controls, since the OSD is rendered in the contained 16:9 box. If we increase the size of the view during playback, it will _probably_ work - but needs to be considered in general as we add controls/layout to the OSD in the rest of the TV apps.

**Comment by tru** [comment]
I will look into making the view bigger later. But this will most likely come after 1.0.1

**Comment by alypseak** [comment]
21:9 files do play correctly for me, it's only the menu which isn't.

**Comment by marctwo** [comment]
I'd like to see 21:9 support on all platforms. I run a Pi 2 to my 21:9 TV and have always wished the interface would run full screen. Letterboxed UI in a  16:9 screen is fine as the TV will scale up to fit.

**Comment by tru** [comment]
We have video playback already working afaik, adapting the UI is a completely different thing, so I will close this for now.
