### ISSUE TITLE
Fullscreen Windowed/Stay in Focus

### ISSUE THREAD

**Issue by ShadyCrab** [plexinc/plex-media-player#120]
I am not sure of whether this is in use, but there is a fundamental issue with multi-monitor at the moment. If you alt-tab from Plex Media Player when Fullscreen is enabled, the player will minimise no matter what you try, This means that you cannot watch a video on the side while say, playing a game, reading online, doing work, etc etc.

Is there a way for PMP to stay in focus while on a different monitor?

Is it also possible to have PMP by default launch on a different monitor or switch to a different monitor without using the WIN-SHIFT-LEFT shortcut that Windows 10 offers.

**Comment by wm4** [comment]
We're aware, but unsure how to solve it.

We minimize on lost focus to avoid other problems with fullscreen mode and the widows compositor.

**Comment by tru** [comment]
I wonder if this is less of a problem when using ANGLE?

**Comment by wm4** [comment]
Made some tests. It looks like ANGLE doesn't even allow entering exclusive mode (i.e. the thing that's apparently causing problems for us). So this would solve our problem. But non-exclusive mode is probably also worse for video playback.

(It's actually a bit more complicated when exclusive mode is used and when not, but this can be ignored for now.)

The latest ninja build has a ``minimizeOnDefocus`` option, which simply disables the defocus behavior. It'll be in the next release build too.

**Comment by Trahloc** [comment]
wm4 commented 11 days ago:
The latest ninja build has a minimizeOnDefocus option, which simply disables the defocus behavior. It'll be in the next release build too.

Just downloaded latest version off website which now works in my multi monitor environment but when clicking on this window to type this out it loses focus and minimizes.  Tried executing it with -minimizeOnDefocus but that didn't work.  The .exe doesn't respond to /? /help /h -? --help -h so I might be  doing the option incorrectly.

**Comment by wm4** [comment]
``minimizeOnDefocus`` isn't a command line switch, but an option in the ``main`` section of the config file. (For editing the config file, follow: https://support.plex.tv/hc/en-us/articles/207338798-Advanced-Configuration But mind that the ``minimizeOnDefocus`` option is not documented there yet.)

**Comment by twpol** [comment]
I'm glad `minimizeOnDefocus` has been added (albeit undocumented and not in the UI) but it's still not up to PHT quality, as it visibly flickers when focus switches. Given PHT defaulted to non-exclusive full screen I really hope this can be sorted out in PMP. :)

**Comment by twpol** [comment]
P.S. This use of exclusive full screen also has consequences for volume and other overlays in Windows, i.e. you don't get them. Since there doesn't seem to be volume shortcut keys yet, showing the system volume changes within PMP is crucial.

**Comment by wm4** [comment]
If you use ANGLE/DirectX mode, it should be using non-exclusive fullscreen. If it still flickers on focus switches (even if the window doesn't resize), it's probably out of our control.

**Comment by twpol** [comment]
@wm4 How do I enable that? I can't see anything obvious in the conf or support webpages.
