### ISSUE TITLE
3D support

### ISSUE THREAD

**Issue by sjorge** [plexinc/plex-media-player#123]
Preferabbly autodetecting Side-By-Side and Horizontal Split video files and make the UI match that. 

This should make the interface usable when in 3D mode. (Biggest headache causing issues on PHT)

Probably something for a 2.0 or further away though.

**Comment by mseeley** [comment]
Oh interesting. So, for example, if the video was SBS the UI would render twice, once on each side?

**Comment by sjorge** [comment]
That's the idea, render the UI twice with the correct distortion/offset. It should appear 'normal' when the TV is in the correct 3D mode.

e.g. my Sony TV will detect a SBS video playing and offer to switch. Which is great. But then the PMP (or PHT) UI then gets cut in half, distorted and projected in the same way as the movie. (Can't really capture a screenshot or picture as I do not have a sterioscopic camera ;))

**Comment by atrus05** [comment]
Thank you for the comment @sjorge, but in case you have missed it; feature requests are made in the forum. The bug tracker is meant for bugs only. Sorry if you feel that is harsh but that is the stance at the moment.

Closing this one.

**Comment by sjorge** [comment]
Personally having the interface not be usable unless forcing the tv out of 3D mode for changing audio track etc... is more a bug than a feature. But I will leave this up to your discretion. Took a bit of efford but here is a screenshot of the unusableness. Included for completion and archival purposes.

Picture of playback: 
![SBS interface](http://i.imgur.com/yT20SFY.jpg)

Also subs are rendered like usualy so they don't work, if rendered at twice at the correct offset/distortion they would appear fine. I do have to say the playback controls are less flashy than with PHT which is good but still unusable.

I couldn't capture one of the main menu because the TV drops back to non 3D mode too withing 3-5 seconds and I couldn't get it to focus fast enough. (Still nightmare vision from hellish ;))
