### ISSUE TITLE
Allow upgrade installation in Windows

### ISSUE THREAD

**Issue by kayone** [plexinc/plex-media-player#124]
Trying to install a newer version of PMP in windows causes this error
![image](https://cloud.githubusercontent.com/assets/412280/10895475/4cda9daa-8169-11e5-839f-4c49fbcac2dc.png)

It would be great if the installer would give the user an upgrade option.

**Comment by ghenry22** [comment]
Yep just tried to update to the new 1.0.2 release.

It never showed as an update in app so I just downloaded it and ran the installer and got the same error until I manually uninstalled the older version.
