### ISSUE TITLE
`.` key press isn't passed to the UI

### ISSUE THREAD

**Issue by kayone** [plexinc/plex-media-player#125]
`.` _(dot, period)_ isn't past to the UI, we need this to allow IP entry using physical keyboard.

**Comment by kayone** [comment]
this breaks `.,>` being `seek_forward` not sure how we can handle this.

**Comment by tru** [comment]
is this when I bring up the idea of context keymappings again?

**Comment by kayone** [comment]
IMHO we are gonna need context aware keymappings, I'm a bit surprised people haven't complained about it more (or maybe I've missed them), the main question would be how could we communicate context back to konvergo, or would it be completely managed on JS side, either way I think it's the direction we need to head.

**Comment by tru** [comment]
I think that the cleanest solution is just for the web client to report context to the host via setContext() call since we already translate keys->actions in the host, so this would be pretty low impact in the web-client (except for adding the context reporting).

**Comment by mseeley** [comment]
I hear the context concern loud and clear. Looking at a `setContext()` call and another alternative for handling context aware keys. We're designing towards supporting context aware keys on all platforms.

**Comment by LongChair** [comment]
Should be fixed now, closing.
