### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by jpsutton** [plexinc/plex-media-player#126]
I've built PMP from source on Linux, but upon starting the application, I'm required to go through the PIN process to link with a plex account.  Is there an option to bypass and use only a local plex server?

**Comment by tru** [comment]
No not yet. It's coming later.

**Comment by tru** [comment]
Oops I closed it even if that was not my intention. But I guess it could be closed anyway since it's more of a feature request and not a technical bug.

**Comment by jpsutton** [comment]
So (currently) a plex pass is required even if compiling from source?

**Comment by tru** [comment]
Yes.
