### ISSUE TITLE
InputCEC can block while scanning for devices

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#129]
Currently InputCEC sets up a timer to scan for devices. There are several problems with the current approach:

1) FindDevices() blocks while scanning the USB bus. This is pretty bad since this happens on the main thread and creates frame drops for video
2) The scan is executed EVERY second. So if you don't have a CEC device connected when you start PMP it will scan the full USB bus every second to see if you have connected something. We definitely should not do this.

Looking at Kodi's code they have abstracted the scanning to their USB finding code. When they see a USB device connected (with various system APIs) they then just straight open the device with the right port address without needing to do another scan.

We have some options here:
1) Move device scanning to another thread than the main thread and maybe not do it every second.
2) Implement USB auto-detection and use that for both InputCEC and InputSDL. This most likely means writing OS specific code or use something like QDeviceWatcher (but that seems to be buggy for OS X according to the docs).

I see benefits from doing method 2 since it will improve not only CEC but also SDL. But more work for sure.

Opinions?

**Comment by wm4** [comment]
Option 2 sounds awfully complicated, so moving to a thread seems preferable.

**Comment by tru** [comment]
Agreed, let's go with a thread and lower the retry value to 10 seconds or something for now. We can always complicate stuff later if we really feel a need.

**Comment by LongChair** [comment]
That is interesting because there used to be a thread there which we changed to a timer for a reason I can't remember...

**Comment by wm4** [comment]
Is this fixed now?

**Comment by tru** [comment]
Yes this should be closed as fixed.
