### ISSUE TITLE
PMP does not disable screensaver

### ISSUE THREAD

**Issue by clee** [plexinc/plex-media-player#130]
I'm running PMP on a GNOME3 desktop and it does not disable the screensaver (like mpv does) when playing videos, so I have to remember to move my mouse or hit a keyboard key at least once every ten minutes.

**Comment by TheYetiWakes** [comment]
Any update on this? Happens for me on both fedora gnome desktop and Ubuntu unity.

**Comment by wm4** [comment]
install xdg-screensaver, or try to compile with `-DLINUX_DBUS=on`. Other than that these problems have been long solved.
