### ISSUE TITLE
Long delay when starting video if Display Mode Switching is enabled

### ISSUE THREAD

**Issue by stadarn** [plexinc/plex-media-player#131]
If I have Display Mode Switching active, PMP takes approx.15 seconds (timed with stopwatch) to start a video. Without it the video starts more or less immediately (under 2 seconds). There is also a delay with white noise after the video finished playing until the Home screen is displayed again.

See also https://forums.plex.tv/discussion/192068/long-delay-when-starting-video-if-display-mode-switching-is-enabled

Log files from a short test with and without Display Mode Switch Enabled. Please let me know if further testing is needed.
(I can't attach logs due to no write permission on this tracker. But they can be found on the forums linked above)

System: 
PMS & PMP both run on:
Late 2012 Mac Mini w. 2.3GHz quad-core Intel Core i7
OSX El Capitan (10.11.1)
Intel HD Graphics 4000
4GB RAM

Fileserver:
AMD A10-6700T with RAID5-setup running Debian Wheezy. 
Files shared via NFS to PMS.

**Comment by tru** [comment]
Is that different than with PHT? We wait for the screen to reinit so it would be mostly up to your TV in that case.

**Comment by stadarn** [comment]
Yes. I haven't seen that in PHT, but I can verify with the same file played in PHT tonight.

**Comment by wm4** [comment]
I can't make sense of the log either. It looks like it's freezing for 10 seconds for no reason. After that, the video appears to load swiftly (the log doesn't tell us how long it actually takes). I'll add some more logging.

**Comment by stadarn** [comment]
Did some further testing:
* Tested same video with PHT: Video starts playing within 3 seconds. According to debug info on screen the framerate was 24 fps. No white noise on screen when exiting.

* Tested with PMP and video stored locally on the PMS/PMP-machine. Still the 15 seconds delay.

* Changed HDMI input on TV:
Improved start time for most of the times. Still white noise on screen when exiting.

* Switched back without restarting PMP: Improved start time for most of the times. Still white noise on screen when exiting.

* Restarted PMP. Back to 15 seconds start time. On screen it looks like the player freezes with the 3-dot screen for about 10 seconds. Then a new view with art from the video and a new pause for 2-3 seconds, display switches and video starts.

The difference between the HDMI ports are that my normal port I use for computer is the ARC-port, but I don't have any HDMI inputs on my receiver so the HDMI cable runs from the Mac Mini to the TV and I use optical (set in Audio settings).

Let me know if more logs are wanted.
