### ISSUE TITLE
web-client should tell C++ host when to restore display mode after playback

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#132]
Currently, transcode seeks are unfortunately handled like this:
- terminate playback
- load a new URL (which includes the new time offset)

This works well, except for one thing: when playback is terminated, the C++ host will restore the display mode. It will immediately switch back to the video display mode when playback resumes. It shouldn't do this, because it's annoying and introduces a huge delay. But it can't know whether the playback termination is a normal user action, or only due to a transcode seek.

The easiest way to fix this is to have web-client tell the C++ host when playback is _really_ terminated. E.g. when returning to the pre-play screen.

**Comment by firasdib** [comment]
Seems like a dup of https://github.com/plexinc/plex-media-player/issues/121 which is fixed, no?

**Comment by wm4** [comment]
Yep.
