### ISSUE TITLE
MCE USB Remote not working in Plex Media Player

### ISSUE THREAD

**Issue by truckershitch** [plexinc/plex-media-player#139]
In Plex Home Theater, I was able to use my remote without configuration.  I use the remote with mythfrontend and mythtv.  I am unable to get a response from the remote control when running Plex Media Player by itself or when called from mythfrontend.

I use lirc and I tried to add a profile for Plex Media Player in my .lircrc but I was unsuccessful.  My attempt is listed below:

begin
prog = plexmediaplayer
button = Left
config = left
end

begin
prog = plexmediaplayer
button = Right
config = right
end`

Note to others: This did not work.

Please document how this can be done.

Thanks!

**Comment by nitrobass24** [comment]
This is working for me using the latest version 1.05.

**Comment by truckershitch** [comment]
I got this to work by copying `LIRC.json` in `/home/myuser/.local/share/plexmediaplayer/inputmaps/examples` to `/home/myuser/.local/share/plexmediaplayer/inputmaps/LIRC.json` and editing the file as needed.  I used `irw` and pressed various buttons on my remote to determine what strings to change in this file.  The remote works fine now.
