### ISSUE TITLE
Map volume up/down to +/- buttons to mimic PHT.

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#14]

**Comment by firasdib** [comment]
Figured this needs mainly web work at this point, so I'll take it over. Ok?

**Comment by firasdib** [comment]
@wm4 Could you update this issue with how the volume buttons should work? I have the following assumptions, please clarify any misconceptions:

1. `setVolume` accepts an absolute value and `volume` returns an absolute value between 0-100
2. Each volume click should increase or reduce the volume by 1.
3. Volume should not be allowed to be increased beyond 100

**Comment by wm4** [comment]
That sounds pretty good to me, but I'm not an UX person.

(Sorry for the late reply.)

**Comment by swarmier** [comment]
I noticed that the Embedded and MAC clients the - (dash) key is now mapped to lower the volume (AWESOME, thank you)  but the + or = is not mapped to raise it back.  Can anyone comment on if this was accidental or is there a different key mapping?
