### ISSUE TITLE
Mouse cursor not visible

### ISSUE THREAD

**Issue by danisusb** [plexinc/plex-media-player#140]
I have installed Plex Media Player for Embedded Platforms (Intel 64-bit) (Version 1.0.1.42-56cc6ef9 
Oct 28, 2015) on an Intel NUC but I can't see my mouse cursor. I can only see the highlighted areas when I cross them with the cursor but not the cursor itself.

**Comment by LongChair** [comment]
Soube be fixed now, closing.

**Comment by LongChair** [comment]
Soube be fixed now, closing.
