### ISSUE TITLE
Allow manual server by domain name

### ISSUE THREAD

**Issue by ghenry22** [plexinc/plex-media-player#142]
The current release of PMP allows manual server address but only by IP.  It would be good to allow the user to enter an IP or a hostname so that of us that run our own DNS can use the domain name.

**Comment by elan** [comment]
Did you know you can use custom server access URLs to the same effect, without needing to configure every client?

![2015-11-10 at 6 30 pm](https://cloud.githubusercontent.com/assets/10298/11083946/23b83f24-87d9-11e5-850b-d8bfdd7dda39.jpg)

**Comment by ghenry22** [comment]
That's on the server side right?  I have that already I think.

it's more that if there is an argument for entering server address manually by IP then it is surely equally valid to enter it manually by domain name as lots of people use dynamic DNS providers already.

I was also thinking that having it configured on the server side then relies upon plex's servers to login and then tell the new client where to look, what if plex's servers are not accessible (for whatever reason), it would still be good to be able to access my media through PMP both locally in my house or externally say from my office which are both common use cases for me.

It would seem like a reasonably trivial thing to do, I asked for it for PHT as well but I don't think it ever eventuated.

**Comment by elan** [comment]
> That's on the server side right? I have that already I think.

Yup, on the sever side.

In general, the clients are specced to behave well in the offline case and keep their list of connections, FWIW, but I do see your point.

**Comment by ghenry22** [comment]
yeh don't get me wrong it's not a criticism, I just think it's a good enhancement which should be quite straight forward as you already have the ability to input a manual address.

If there is a use case for a manual IP there is probably an equally valid one for manual domain name.

**Comment by LongChair** [comment]
closing for cleanup.
