### ISSUE TITLE
Resized (scaled down) PMP window causes menu items to skip

### ISSUE THREAD

**Issue by danemacmillan** [plexinc/plex-media-player#144]
I noticed a bizarre issue with the latest version of PMP. I resized the window to be smaller than the default non-fullscreen size. After doing that, half the `Settings` in menu items could not all be accessed; what I mean to say is that every second menu item (conjecture: every `odd` item?) would just be skipped over. The strangeness of the issue demanded I create a gif and let the behaviour illustrate the problem for itself; the first part of the gif is with PMP in a maximized window, while the second part of the gif is with PMP in a scaled down, resized window. Note that the issue happens in the second part.

**Example of menu items skipping:**
![pmp-menu-skip](https://cloud.githubusercontent.com/assets/4390491/11120738/e252126a-891f-11e5-852d-dc802968baf4.gif)

**Version of PMP:**

```
Mavericks 10.9 or later (64-bit only).
Version 1.0.2.70-15a01542
Nov 10, 2015
```

**Computer specs:**
- Late 2013 MBP
- 15" retina screen

```
Software:

    System Software Overview:

      System Version: OS X 10.11.1 (15B42)
      Kernel Version: Darwin 15.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: dane
      User Name: Dane MacMillan (danemacmillan)
      Secure Virtual Memory: Enabled
      Time since boot: 21 minutes

Kernel & Architecture:

    15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 i386
```

**Comment by dogonwheels** [comment]
On the forums, with logs, here: https://forums.plex.tv/discussion/193476/settings-menu-bug

**Comment by LongChair** [comment]
@danemacmillan : is this still relevant in recent builds ? or can we close this ?

**Comment by LongChair** [comment]
that should be fixed now that tv2 is out, closing.
