### ISSUE TITLE
Inconsistent preroll and trailer count handling

### ISSUE THREAD

**Issue by dogonwheels** [plexinc/plex-media-player#145]
It sounds like PMP differs from PHT in the way it counts preroll/trailers. "In PHT it behaved the same except that if you didn't tell it to play any trailers it still would play the pre-roll automatically if it was set in PMS." - this is not the way I remember handling it in web base code, since the play media command has no concept of preroll vs trailer. We only provide an integer for items to prepend the main item in the PQ with. We should dig into if PHT does something different, or if PMP/TV/web have just gone wrong with this setting and we're missing something to detect preroll.

https://forums.plex.tv/discussion/193296/play-pre-roll-without-cinema-trailer-first

**Comment by Cimplex** [comment]
It would be cooler if you could bake this into the transcoder instead of each client. Plex Admins could force this option on without it being a per client setting. That said, I can see why this hasn't been touched for 2 years.

**Comment by LongChair** [comment]
Should be fixed now, closing.
