### ISSUE TITLE
Don't display player UI when using stream shortcuts

### ISSUE THREAD

**Issue by dogonwheels** [plexinc/plex-media-player#147]
We apparently currently show the whole player UI when toggling subtitles - this feels heavy and unintentional.

**Comment by atrus05** [comment]
Isn't my GHI good enough for you?!?
https://github.com/plexinc/plex-web-client/issues/3624

**Comment by dogonwheels** [comment]
Hehe. Sorry dude, had missed that one! Thanks :laughing:
