### ISSUE TITLE
[RPI] Update default system name

### ISSUE THREAD

**Issue by mbnn** [plexinc/plex-media-player#15]
Right now the hostname is displayed as `PlexMediaPlayer` by default. It would be nice if this could be changed to `Plex Media Player` to match how it is labeled for HDMI-CEC devices. Even better, would be if the user could set the hostname in the Settings menu.

Mostly because if there are multiple RPI's active running PMP on the same network, the user has no idea which one is what.

**Comment by tru** [comment]
You want us to change the default name to a name with spaces? This is not really possible considering how Linux hostnames work. We could expose names with spaces to GDM and such, but I don't think that's the priority. We need to get the setting for hostname into the UI settings, but that will require a On Screen Keyboard first.

Not sure if there is anything actionable in this issue, let me know if we can close it.

**Comment by mbnn** [comment]
Waiting for On Screen Keyboard :)
