### ISSUE TITLE
PMP install to allow for multiple windows user accounts using it 

### ISSUE THREAD

**Issue by sa2000a** [plexinc/plex-media-player#150]
Not sure if this is a known issue but could not find it on the issues register.
Forum topic: 
https://forums.plex.tv/discussion/193799/pmp-only-installs-for-current-user-in-windows

Multiple windows user installs of PMP are not permitted (error - already installed)
The installed application though is not available for all users and no such option given at install time

**Comment by LongChair** [comment]
old stuff, we had no other complaints on this, closing it for clarity :)
