### ISSUE TITLE
Display FPS 0.000 (0)

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#152]
No idea how I did not make the connection before, but I have found the reason for the Display FPS issue, and a reliable way to reproduce it on my setup.

STR:
1. Start PMP, and start a video. Notice that Display FPS is correct in debug overlay.
2. Leave PMP running and switch input on receiver to for example the TV input.
3. Switch back to PMP computer where you still have PMP running.
4. Start a video and check the debug overlay. It now does not show correct Display FPS.

Hardware: Mac Mini 2012 (Quad i7), Pioneer VSX-2021(receiver), Panasonic VT50 Plasma (TV)
Software: OSX Yosemite, PMP 1.0.2.75 (bc0443eb)
Connection schedule: Mac Mini -> HDMI -> Receiver -> HDMI -> TV

Log: https://gist.github.com/atrus05/648f4034f551dfeecfce
Log explanation: Started PMP. Started a Mythbusters episode and enabled the debug overlay to make sure everything was ok. It was. Then I pressed stop so I ended up in the menu again. I then switched input while leaving PMP running. Then switched back to the computer input and I was in PMP again. I then started up the same episode and saw that display FPS was 0.000 (0).
Everything is in the same log.

**Comment by atrus05** [comment]
This was solved for a couple of weeks, but it just started happening again for me. It is not happening the same way I believe (harder to reproduce), so I will have to figure out some way to do this again.

**Comment by LongChair** [comment]
@atrus05 : i suppose this was fixed right ? can we close this ?

**Comment by atrus05** [comment]
I can't reproduce it reliably anymore, so I will close it until I can figure out a way.
