### ISSUE TITLE
web-client dies when refresh rate switching on RPI

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#155]
We're still trying to track down why refresh rate switching suddenly stopped working on RPI.

The latest result is: when switching modes during playback, the web-client apparently stops playback, and goes back to the pre-play screen. So maybe the older theory of Qt completely reloading web-client is wrong. (We also need to exclude that mpv stops playback on mode switching in this specific case.)

**Comment by dogonwheels** [comment]
Web investigations so far show the page refreshing after we `player.load` and before we get the callback on success. Who is doing the refresh though is still unknown. It may be relevant that during playback we use a `noop` state/URL and if you were to refresh the route in a regular browser you'd end up at the preplay. This may be a red :fish: though.

**Comment by atrus05** [comment]
When I try to switch refresh rate while still in the home menu the app relies as well (well I get to see the splash at least).

**Comment by wm4** [comment]
Seems like C++ (Qt) actually reloads web when the GUI renderer state is recreated after a mode switch. Sometimes, web will end up in the same place as before the reload because the URL remains the same.

It's still unclear what caused this change in Qt behavior.

**Comment by LongChair** [comment]
should be fixed now
