### ISSUE TITLE
Cannot upgrade PMP Embedded on UEFI system

### ISSUE THREAD

**Issue by ivanrayner** [plexinc/plex-media-player#159]
On a Nuc with UEFI on /dev/sda1, the installer will fail when attempting to upgrade.

At line 399 of /usr/bin/install, the script makes a call to tune2fs looking for the label of the partition while it is searching for the System disk. On a UEFI system, /dev/sda1 is vfat and not ext4 and tune2fs will fail.

There needs to be a check for the fstype and to use dosfslabel rather than tune2fs when appropriate.

(I also posted this bug to the pmp forum.  Sorry for the duplication.)

**Comment by ziggimon** [comment]
Fixed in: https://github.com/plexinc/OpenELEC.tv/commit/a95cc3d10f403104fd87db5083a29e37d51460c7
