### ISSUE TITLE
Catastrophic failure error screen unresponsive to key input

### ISSUE THREAD

**Issue by mseeley** [plexinc/plex-media-player#161]
We found an issue handling keys in catastrophic startup failure cases. In these times the application was unable to start and has no access to the PMP channel. There are two rather unsavory UI workarounds:
- The application makes assumptions regarding default key codes and hopes for the best. We'd break with mapping provided by some users.
- We refactor PMP and Anvergo channels and startup to establish the communication channel before the application starts. This gets messy and complex to support across platforms.

There's an elegant host workaround if you all are willing/able to play. Some [browsers, including Opera SDK,](http://caniuse.com/#feat=keyboardevent-key) are implementing a [`.key` property on event objects](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key). The property allows the host to handle key code to key name mapping and keep the UI blissfully mapping unaware. Sounds a lot like channel key events. :)

Great right? We get the best of channel key events and browser key events. Here's what got to happen:
- [ ] PMP starts sending `keydown` again
- [ ] UI changes PMP key event handler to use `keydown`, passes `.key` property to callers

@kayone / @Flamefork 

@IanDBird copying for heads up for the same concern in Android land.

**Comment by kayone** [comment]
just a note, this would also allow us to bring back Plex Launcher to these devices, as well as chrome debugging (not that big of a deal)

**Comment by LongChair** [comment]
This should be fixed now, closing.
