### ISSUE TITLE
Dragging PMP across monitors causes app reload in Windows

### ISSUE THREAD

**Issue by kayone** [plexinc/plex-media-player#163]
STR:
- Start plex in a multi-monitor system in windows
- disable fullscreen so the app is in windowed mode
- move the app from one screen to another
- the app is reloaded, media playback is stopped

**Comment by wm4** [comment]
Sounds suspiciously like the problem we have on RPI.

**Comment by bkim** [comment]
This happens on OS X, also.

**Comment by Ruvetuve** [comment]
Seems like it happens when your mouse holds the PMP screen and drags it AND the mouse *hits* the side of the screen you wanna pass through. Maybe this helps in exploring the issue.

**Comment by kayone** [comment]
I can't seem to repro this anymore in `PlexMediaPlayer-1.0.3.123-ea0c563c-windows-x86_64.exe`

**Comment by LongChair** [comment]
This should be fixed now, closing.
