### ISSUE TITLE
Stereoscopic 3D does not work at all

### ISSUE THREAD

**Issue by HLFH** [plexinc/plex-media-player#164]
Hi,

@atrus05 @tru @wm4 

I have Plex Pass, only to discover if Stereoscopic 3D is really supported with Plex Media Player: it is not at all supported. 

This is a huge bug. Stereoscopic 3D is not supported with Plex Media Player and it should be.
![capture](https://cloud.githubusercontent.com/assets/2359059/11267369/46507a50-8eab-11e5-96c8-d96af2b09a93.PNG)

The best media player for 3D on Windows is [Daum PotPlayer](https://potplayer.daum.net/) and you should clearly be inspired by this media player.
![weneed3d](https://cloud.githubusercontent.com/assets/2359059/11267372/4bf6a7f4-8eab-11e5-9a95-468321783ab7.PNG)
As you can see, compared to Daum PotPlayer, there are not any 3D settings in PMP. How could you really support 3D with Plex Media Player? 

 If you have H-SBS or H-TAB movie in input, you should have Stereoscopic 3D in output, automatically if you can, or manually with at least some 3D settings to manual select between Side-by-Side, Top-and-Bottom. Please make 3D work on Plex Media Player.

**Comment by atrus05** [comment]
Feature request are done in the forum. This bug tracker are for bugs only (at least currently).
And this is a feature request and not a bug, as PMP is only supporting 3D video, and not a 3D interface.
And the 3D video is only supported in a way that you have to manually switch to 3D mode on your TV remote (or use a Harmony of course).

Closed.

**Comment by HLFH** [comment]
@atrus05 I don't have a TV, I have a DLP 3D Ready videoprojector, named Vivitek Qumi Q7. Even if it's switched to 3D in the videoprojector, it does nothing. It seems I need a 3D interface support.

**Comment by HLFH** [comment]
Related to https://forums.plex.tv/discussion/194668/feature-request-we-need-3d-interface-support

**Comment by atrus05** [comment]
Sorry but if your projector does not switch to 3D when you press the 3D button, then something is likely wrong on the projector side. I say this because a video from the source is not transmitted differently because your TV/projector has 3D support. It is just a side-by-side video image that is being stiched together by the end-device. In your case the projector.

**Comment by HLFH** [comment]
Plex Media Player and Plex Theater never worked in 3D. There is no 3D button on Vivitek Qumi Q7 but in the videoprojector settings, I can enable DLP-Link 3D or IR 3D, and I have to set my resolution to 1280x720 (3D) with 120 Hz refresh rate on Windows 10 to make it work on Daum PotPlayer.

**Comment by HLFH** [comment]
@atrus05 In fact, there is a workaround if you develop this feature. If I could share HTTP links, I'll be then able to use directly Daum PotPlayer for 3D content of my Plex Media Server. https://forums.plex.tv/discussion/126076/feature-request-share-links-for-media

**Comment by ziggimon** [comment]
Please keep feature requests to the forums. We are reserving github for bugs for now.

**Comment by HLFH** [comment]
@ziggimon GitHub is for bugs and feature requests. I prefer to say it openly when important features of the Plex Media Server and/or Plex Media Player are not implemented. Nevermind, @atrus05 already told me that feature requests need to be posted on the forums and this is what I did.
