### ISSUE TITLE
PMP 1.0.2 full screen prevents display sleep on OS X

### ISSUE THREAD

**Issue by bkim** [plexinc/plex-media-player#166]
PMP prevents displays from sleeping when it is in full screen mode. The displays will sleep if it is in windowed mode. I have multiple displays using OS X 10.11.1.

**Comment by tru** [comment]
This is by design if it runs in full screen mode we "take over" the screensaver and the screensaver is what controls display sleep in OS X.

**Comment by bkim** [comment]
Are there any plans to add an option to put displays to sleep when in full screen mode (similar to the option in PHT)? Although, unlike the PHT implementation, it would be nice if it only put displays to sleep when it is in full screen mode.
