### ISSUE TITLE
Beeing able to unmatch movies series

### ISSUE THREAD

**Issue by Snorlock** [plexinc/plex-media-player#169]
It would be nice to be able to unmatch a specific file, leaving it haning in an umatched state, so I can specific that its a tv show or movie. Iv experienced that its tried to place a whole season into movies, an episode each. This is not perfect. Therefor I would like to unmatch all of them, and say all these are season 1 tv show.

**Comment by Snorlock** [comment]
I cant place labels myself it seems like.

**Comment by OttoKerner** [comment]
This sounds more like a Plex server issue.
If you are new to Plex in general, please learn about the platform first.

**Comment by Snorlock** [comment]
Im sorry for that, I havent looked over the repos for plex, just search during the conferenca and posted here. Im an active user of plex, just not contribution yet. Do you have a link to the repo? I cant seem to find any in the repolist.

**Comment by atrus05** [comment]
support.plex.tv gives you a ton of info on how to name and manage your files and metadata.
Basically: Do not put tv shows in a folder which you have designated as a Movie folder in Plex a Media Server. If you need help after reading through that; please create a thread in the forum asking specific questions there.

Closing this, let me know if you still think this should be open.

**Comment by Snorlock** [comment]
Thx for the info @atrus05. But I just think that its not always in my controll what ifles I get and the work of renaming files should be handled somewhat easier. Either by beeing able to dematch and match again. But I see that there might be some other solution here I can do, because it originates from having movies and tv shows in the same folder. And that originates from i want automatic detection when I have received the file. Which might be able to split up.  But thx anyway.
