### ISSUE TITLE
Correctly display 10bit video on RPi

### ISSUE THREAD

**Issue by dogonwheels** [plexinc/plex-media-player#17]
We ask to transcode this type of content since RPi has maximum bit depth of 8, but we don't inform the transcoder of this limitation.

**Comment by wm4** [comment]
It looks like this should also check the maximum dimensions (maxWidth/maxHeight), as it is declared by the web-client profile. I suspect ignoring these restrictions makes the RPI show very funny things.

**Comment by dogonwheels** [comment]
Fixed in https://github.com/plexinc/plex-web-client/pull/3692 - but @rcombs - do you think we should also pass over the dimensions/bitrate as well as extras?

**Comment by dogonwheels** [comment]
...and if we do add these then my arbitrary threshold of 3 items copy/pasted will be breached. We should then use the `konvergoPlayerProfile.raspberry` to get the values when building up the limitations in the player controller.

**Comment by dogonwheels** [comment]
I'll follow this up with a width/height/bandwidth issue if we end up caring about those.

**Comment by wm4** [comment]
>but @rcombs - do you think we should also pass over the dimensions/bitrate as well as extras?

I'm not rcombs, but I think we definitely should. This device does not claim to handle larger video.
