### ISSUE TITLE
unecessary transcoding of WTV recording (1080p mpeg2video)

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#171]
forum post https://forums.plex.tv/discussion/196917/pmp-wont-direct-play-wtv-files-but-pht-does

tested on Windows 8.1
PMS 0.9.14.4
PMP 1.0.3.101

mediainfo XML and PMP log https://gist.github.com/OttoKerner/0d4b19cb55dce03a7740

This file should be played back at least per Direct Streaming (Mpeg2video, ac3). But both Video and Audio get transcoded unnecessarily to h.264 and aac.
If the same file is muxed into an MKV, Direct Play is suddenly possible.

**Comment by wm4** [comment]
Yes, we just need to white-list it. I hope.

**Comment by mseeley** [comment]
I've whitelisted `wtv` video containers for direct playback in PMP.
