### ISSUE TITLE
Cannot Download Dependencies

### ISSUE THREAD

**Issue by toniotelli** [plexinc/plex-media-player#175]
Hi I have this message from the cmake call:

`CMake Error at CMakeModules/FetchDependencies.cmake:92 (message):`
`Failed to download konvergo-qt-linux-x86_64-release-c7461ff.tbz2.sha.txt`
`error: "HTTP response code said error"`
`Call Stack (most recent call first):`
`CMakeModules/QtConfiguration.cmake:3 (download_deps)`
`CMakeLists.txt:35 (include)`

I tried :
`wget https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt-linux-x86_64-release-c7461ff.tbz2.sha.txt`

and 

`wget https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt-linux-x86_64-release-c7461ff.tbz2`

I got the 404 answer from the server so I suppose that this file does not exist

**Comment by tru** [comment]
Linux doesn't have pre-built dependencies yet.. Most likely you need to make some if statements there.

**Comment by toniotelli** [comment]
Ok Could you detailled your answer a bit. I did manage to build pmp version 1.0.3 without any trouble.

**Comment by tru** [comment]
in `cmake/QtConfiguration.cmake` try to change the `download_deps()` to:

```
if(APPLE AND NOT WIN32)
  download_deps()
endif(APPLE AND NOT WIN32)
```

**Comment by toniotelli** [comment]
OK Thanks a lot. This issues is fixed for me I guess.

Here is a small patch containing the fix you have proposed:
[FixingIssue#157Linux.patch.txt](https://github.com/plexinc/plex-media-player/files/54336/FixingIssue.157Linux.patch.txt)

**Comment by svenstaro** [comment]
This patch should be applied.

**Comment by wm4** [comment]
Strangely I don't need to do anything special when I build on Linux, and it doesn't try to download any deps.

**Comment by tru** [comment]
I think this was applied in some form. I think we just didn't close the issue.

**Comment by wm4** [comment]
I think it doesn't download deps for me because I always use `-DQTROOT=` (followed by the path of the root binary dir of my Qt build).
