### ISSUE TITLE
Mac Mini HiDPI mode 960x540 resolution

### ISSUE THREAD

**Issue by stueeey666** [plexinc/plex-media-player#176]
...when launched PMP only displays the top left hand quarter of the UI.

current solution: issue is resolved by exiting fullscreen mode and re-entering fullscreen mode... the UI is then displayed correctly.

it would be great if HiDPI mode users didn't have to exit and re-enter fullscreen to achieve the correct aspect/view.

**Comment by jptaranto** [comment]
This seems to be true for 960x540 HiDPI mode on mac os x in general.

**Comment by stueeey666** [comment]
this issue appears to be fixed with latest build 1.0.6-RC2(ish)

thanks PMP team, PMP is coming along great!
