### ISSUE TITLE
Pi Analog Volume Control

### ISSUE THREAD

**Issue by swarmier** [plexinc/plex-media-player#178]
I am not if you would consider this a feature request but, there is a large group of users on the PI still using the analog port (dealt with a lot on Rasplex).  I could not find a way to change volume levels outside 'volume normalization' and the +/- keys do not seem mapped.

Cheers, 
JG

**Comment by tru** [comment]
Yeah we are planning to add that, see #14 #75

**Comment by swarmier** [comment]
Apologize for the redundancy, I looked and missed those.
Thanks for the excellent work,
JG
