### ISSUE TITLE
Windows installer simplification

### ISSUE THREAD

**Issue by kayone** [plexinc/plex-media-player#179]
# Installation

There are steps in installation and uninstallation that seem redundent/unnessary: 
![image](https://cloud.githubusercontent.com/assets/412280/11823728/8264bd2e-a32a-11e5-96ec-4f3ddd7e1241.png)

What's Runtime? do we really need it? It doesn't have a description, can I uncheck it? what happens if I don't install it?
# Uninstall

you get a cryptic error about repository when selecting the "Add or remove components" or "Update components" during uninstall.

![image](https://cloud.githubusercontent.com/assets/412280/11823782/e0419c78-a32a-11e5-8a8c-a9e955e587e9.png)

so the only valid option for users is the last option.

clicking the "Settings" button on the lower left opens this window which I have no idea what is for

![image](https://cloud.githubusercontent.com/assets/412280/11823851/3735e3c2-a32b-11e5-8d52-f8398acd0f37.png)

I'm guessing something related to why the first two options don't work.

Also in Add/Remove programs Plex Media Player claims to have an "Uninstall" and "Change" options. we should drop the "Change" options since we only allow uninstallation.

**Comment by tru** [comment]
These stuff comes with the installer framework we use. I am not sure it's worth time investment to learn how to script it deeper. Maybe, maybe not.

**Comment by kayone** [comment]
can you point to where the scripts are which framework we use, I've wrestled with a bunch of these and can probably clean up some of it pretty easily.

**Comment by LongChair** [comment]
not in the current plans, closing this for now.
