### ISSUE TITLE
1.0.3RC added many dropped and mistimed frames on Mac

### ISSUE THREAD

**Issue by tiberian83** [plexinc/plex-media-player#181]
1.0.3RC added many dropped and mistimed frames on my Mac, no matter if hardware decoding is enabled or disabled. Does anybody else experience this? 1.0.2 also had more dropped frames than PHT but ran much better than 1.0.3RC.

I use two Mac Mini (late 2012) and both have this issue. One is connected to a Denon receiver and the other one directly to the TV. Both use the drop/dupe audio option.
In PMP 1.0.2 I always had some dropped frames but never as many as in 1.0.3RC. The same files play without any dropped frames in PHT.

Here you can find the log files:
http://forums.plex.tv/discussion/198342/1-0-3rc-added-many-dropped-and-mistimed-frames-on-mac

**Comment by firasdib** [comment]
I wonder if [this](https://forums.plex.tv/discussion/193527/dropped-frames-when-using-hardware-acceleration-ok-when-switched-off) is the same issue.

**Comment by LongChair** [comment]
supposedly fixed since then ;)
