### ISSUE TITLE
RPi2: Pause button during music playback broken

### ISSUE THREAD

**Issue by randhawk** [plexinc/plex-media-player#182]
**Device**
- RPi2
- Plex: 2.4.37
- PMP: 1.0.3
- OpenELEC: 6.0

**STR**
1. Playback any music track
2. Pause track on playback screen

**Current Behavior**
When a track is paused, the play icon displays for a second then reverts back to a paused button which indicates the song is still playing, but no audio plays and the offsets are stopped. The view will stay for about 20 seconds then revert back to displaying a play button and display an error message before moving onto the next track.

**Expected Behavior**
User can pause track from the playback screen.

Image 1: Error message displayed after about 20 seconds when pausing a track before moving onto the next song
![img_1857](https://cloud.githubusercontent.com/assets/12534497/11882676/b12c89c2-a4c2-11e5-9112-7c81982812ac.JPG)

**Comment by LongChair** [comment]
Closing this, should be fixed now.
