### ISSUE TITLE
RPi2: Casted local camera roll photos don't display

### ISSUE THREAD

**Issue by randhawk** [plexinc/plex-media-player#183]
**Devices**
- Controller
  - Device: Samsung Galaxy Tab (OS: 5.1.1)
  - Plex Build: 4.17.2.488
  - User Type: Plex Pass
- Receiver
  - Device: RPi2
  - Plex: 2.4.37
  - PMP: 1.0.3
  - OpenELEC: 6.0

**STR**
1. (Controller) Select local device as server
2. (Controller) Fling any local camera roll photo to the RPi2

**Current Behavior**
The RPi2 will display a blurred out screen as it does for photo backgrounds, but no photo will display. Instead the blurred out image behind appears to be whatever media was lasted played.

**Expected Behavior**
User can fling local photos

**Comment by LongChair** [comment]
Closing this, should be fixed now.
