### ISSUE TITLE
OSD doesn't always automatically hide when watching videos

### ISSUE THREAD

**Issue by DrMacinyasha** [plexinc/plex-media-player#185]
When watching TV Shows in Plex Media Player, I have run into the OSD not automatically hiding after several seconds, as if it's still detecting some kind of input even with the keyboard and mouse disconnected from the computer along with all other HID devices.

The issue persists between episodes of the same or different shows, as well as completely separate libraries and media types. The only way to force PMP to hide the OSD like it should is to completely quit the program and relaunch it.

Note that this behavior does not always happen. Typically when it does, it is after watching several episodes of a show. I have yet to experience it on other devices, or with movies.

Environment: Windows 10.0.10586 N/A Build 10586, PMP 2.4.36

**Comment by cdlans** [comment]
I have the same problem. PMP 2.4.37 (1.0.3) on Raspberry Pi.

**Comment by sjorge** [comment]
This may actually be fixed by 8be6d9bc9ca9d85130d577ac6393b8d9921b48e0

**Comment by wm4** [comment]
@DrMacinyasha: can you post a screenshot?

**Comment by ajslater** [comment]
I have this issue as well with OS X 10.11.5, PMP 1.1.2

Often when this happens, the stuck OSD Play/Pause button is also stuck displaying a yellow/selected |> 'play' but is unresponsive and does not Pause the playback.

**Comment by lukeab** [comment]
Experiencing this issue on 1.1.3 and 1.1.4 on linux 
i've found focusing the player window and hitting the up key and clicking off the window again hides the OSD. I'm guessing the OSD is responding to a button focus on the play/pause button, so pushing up moves focus off it and allows OSD to hide.

**Comment by LongChair** [comment]
@DrMacinyasha : is this still relevant in recent builds ? or can we close this ?

**Comment by DrMacinyasha** [comment]
@LongChair I think we can close this, I haven't seen this in quite some time.

**Comment by LongChair** [comment]
Thanks !
