### ISSUE TITLE
Always on top

### ISSUE THREAD

**Issue by tofagerl** [plexinc/plex-media-player#189]
I know this is really meant for center stage use, but I like to watch things while I surf, and I would love an always-on-top mode. I'm on a mac, and I would usually use afloat, but even that doesn't work. A dedicated toggle for always-on-top would be the best, but compatibility with afloat is a very close second choice for me :)

**Comment by lukele** [comment]
Hi,

you might be interested in this pull request:
https://github.com/plexinc/plex-media-player/pull/344

**Comment by tofagerl** [comment]
I am interested in that pull request :)

**Comment by lukele** [comment]
Also happy about any suggestions how to improve that. At the moment there's no visual indicator if "Always on top" has been toggled when you activate it via keyboard shortcut. That's something I might add. (Similar to Afloat)

**Comment by tofagerl** [comment]
Can't think of a good one except the obvious text notification.

**Comment by xanderiel** [comment]
Was this added to the main build which users download themselves? I think Always on Top is crucial to have.

**Comment by wm4** [comment]
Yes it was. It should be available in the TV settings UI.
