### ISSUE TITLE
Cannot switch back to home server from shared server

### ISSUE THREAD

**Issue by pooploser** [plexinc/plex-media-player#190]
This happens on latest PMP builds, tested on a OSX.
STR:
1. Open a fresh PMP session.
2. Go to a shared server at the top using the server dropdown.
3. Wait for everything to load, then go back to the home server (=top of the dropdown list).
Nothing will happen.
The only way to get back to the home menu is via an app restart.

**Comment by LongChair** [comment]
@pooploser : this is getting old, i guess we can close this now right ?

**Comment by LongChair** [comment]
Closing this as it's most likely outdated.
