### ISSUE TITLE
Generic messaging interface between host and client

### ISSUE THREAD

**Issue by firasdib** [plexinc/plex-media-player#192]
A generic messaging interface that can be used in the host to display arbitrary messages in the client in an overlay/dialog could come in handy. The implementation should be quite straight forward. The client can listen to a `system.hostMessage` signal (or something similar) and simply display the text on screen.

**Comment by firasdib** [comment]
I have pushed the code for the client, waiting for the host to catch up before we can start testing it. Perhaps @wm4 can help with the host part?

**Comment by wm4** [comment]
Sorry, saw this only now. Sure I can help.

**Comment by firasdib** [comment]
Closing this as done
