### ISSUE TITLE
RPi2: Portrait videos play in landscape orientation

### ISSUE THREAD

**Issue by randhawk** [plexinc/plex-media-player#193]
**Devices**
- Controller
    - NOKIA Lumia 1520 (OS: 8.1)
    - Plex Build: 2.1.2.22
- Player
    - RPi2 (OpenELEC: 6.0)
    - Plex Build: 2.4.37
    - PMP Build: 1.0.3

**STR**
1. (Controller) Select local device as server
2. (Controller) Connect to player
3. (Controller) Begin playback of any local, portrait video

**Current Behavior**
Videos shot in portrait orientation play turned sideways in landscape.

Note: Also tried with an iPhone 6 on Plex 4.0.9 and got the same result.

**Expected Behavior**
Portrait videos will not be turned sideways.

Image: Portrait video playing back in landscape orientation on its side.
![img_1914](https://cloud.githubusercontent.com/assets/12534497/12103678/27306cee-b2f9-11e5-851d-a75f9f40d949.JPG)

Linking https://github.com/plexinc/qa-automation/issues/7

**Comment by wm4** [comment]
Does this work with PMP on other platforms?

I implemented video rotation on OpenELEC (it didn't work because it wasn't implemented in the RPI-specific video output). If it works on other platforms, it will almost certainly work in the next build which happens to include the fix.

**Comment by randhawk** [comment]
@wm4 confirmed working correctly on PMP (1.0.3.132-16fa0ecc) on Mac
![screen shot 2016-01-05 at 8 59 42 am](https://cloud.githubusercontent.com/assets/12534497/12121566/ca7ea5b4-b38a-11e5-9911-4adf6b5b045f.png)

**Comment by wm4** [comment]
Then it should work with the newest OE ninja build (144).

**Comment by randhawk** [comment]
@wm4 working on 1.0.4 for the RPi2. Closing out the issue
