### ISSUE TITLE
Update tool breaks uninstall in Windows

### ISSUE THREAD

**Issue by kayone** [plexinc/plex-media-player#194]
Automatic update tool breaks the windows uninstaller,
### after an update the plex icon is gone from the programs list in windows.

![image](https://cloud.githubusercontent.com/assets/412280/12152349/f012b2be-b468-11e5-9b19-f35c1583fa9e.png)
### trying to uninstall the app causes an error,

![image](https://cloud.githubusercontent.com/assets/412280/12152363/0e90fa48-b469-11e5-8704-93a1f3d18b1e.png)

**Comment by kayone** [comment]
Ideally once https://github.com/plexinc/plex-media-player/issues/124 is fixed we might not even need the updater tool anymore and could just trigger an unattended install/upgrade. but we would lose partial/delta updates.

**Comment by LongChair** [comment]
Should be fixed by now. closing
