### ISSUE TITLE
First track flung to PMP will display error message then move onto next track

### ISSUE THREAD

**Issue by randhawk** [plexinc/plex-media-player#195]
**Devices**
- Controller
    - NOKIA Lumia 1520 (OS: 8.1)
    - Plex Build: 2.1.2.22
- Player
    - RPi2 (OpenELEC: 6.0)
    - Plex Build: 2.4.37
    - PMP Build: 1.0.3

**STR**
1. (Controller) Select any music album while connected to the player
2. (Controller) Press play on any track

**Current Behavior**
The first track selected will not play on the device. Plex Web (Image 1), the player (Image 2), and the WP (Image 3) will show the track is playing even though it actually isn't. Eventually, an error message will display on Plex Web (Image 4) and the player (Image 5), and the next track will successfully begin playback.

Note: A Samsung Galaxy Tab and Galaxy S4 both ran into the same problem.

**Expected Behavior**
A user can successfully play the first track they select.

Image 1: Playing state shown on Plex Web even though no audio is playing
![screen shot 2016-01-04 at 11 10 51 am](https://cloud.githubusercontent.com/assets/12534497/12098611/1ff611e8-b2d8-11e5-9e8c-f5b4ba7f7a08.png)

Image 2: Playing state shown on the player even though no audio is playing
![img_1913](https://cloud.githubusercontent.com/assets/12534497/12098625/35a8e916-b2d8-11e5-9314-a1d730213d82.JPG)

Image 3: Playing state shown on the WP even though no audio is playing
![wp_ss_20160104_0008](https://cloud.githubusercontent.com/assets/12534497/12098823/5fff1f40-b2d9-11e5-94b0-6a52aab5ea87.png)

Image 4: Error message on Plex Web
![screen shot 2016-01-04 at 11 22 17 am](https://cloud.githubusercontent.com/assets/12534497/12098800/29e7286c-b2d9-11e5-939a-260cb0414237.png)

Image 5: Error message on the player
![img_1912](https://cloud.githubusercontent.com/assets/12534497/12098784/1ea68ae2-b2d9-11e5-816c-1b23d24dff97.JPG)

Linking https://github.com/plexinc/qa-automation/issues/7

**Comment by simonair** [comment]
I observe the exact same behavior with latest Plex on iPhone 6 controlling the latest Plex Media Player (1.0.3) on Raspberry Pi2. The issue has been present from the very first version of Plex Media Player on RPi2.

**Comment by tru** [comment]
@kayone ?

**Comment by kayone** [comment]
I can't repro this with either android or windows phone,

**Comment by randhawk** [comment]
I just got the same bug on PMP 1.0.4 when trying on the windows phone again (OS: 8.1, Plex: 2.1.2.26) and an iPhone 6 (OS: 9.2, Plex: 4.0.10)

**Comment by dfgsaerh** [comment]
I can reproduce / having the same issue
Android phone with Plex 4.19.2.514
PMP Version 1.0.3.132-16fa0ecc

Select the cast icon to connect Android phone to PMP, select play and track 1 never plays (Doesn't display any error message on PMP) 
When you skip forward to track two, thats when music starts playing. You can then skip back to track 1

**Comment by mseeley** [comment]
(I believe) we addressed all the state issues causing this https://github.com/plexinc/plex-web-client/issues/4041 and https://github.com/plexinc/plex-web-client/issues/4040. PMP latest dist pull of the web-client includes the fixes.

@randhawk will you please try to reproduce on our latest internal PMP build?

**Comment by randhawk** [comment]
@mseeley @kayone No longer seeing this issue on the Android, iOS, or Windows device with the following setup

**Configuration**
- RPi2
   - PMP: 1.0.4.179
   - Plex: 2.53
   - OS: openELEC 6.0
- PMS
   - 0.9.15.2
- iPhone 6
   - OS: 9.2.1
   - Plex: 4.0.11
- Nexus 7
   - OS: 6.0.1
   - Plex: 4.19.2.514
- Nokia Lumia 1520
   - OS: 8.1
   - Plex: 2.1.2.28

Closing out the issue, nice work!
