### ISSUE TITLE
Plex is not reachable on RaspberryPi 2

### ISSUE THREAD

**Issue by lynndixon** [plexinc/plex-media-player#196]
I am getting "Plex is not reachable" on the latest release (Version 1.0.3.140-16fa0ecc) when using the ethernet on my RaspberryPi 2.  I am using the build downloaded from Plex.tv for the RPi2.  

I am not even seeing the RPi2 try to get an address from the DHCP server, as I am not seeing any requests come in from it at all in the DHCP server logs.  I am using a known good ethernet cable (its the same one I use for my Roku) so I know the physical layer is good.

I can't get the screen to do anything, as connecting a keyboard or mouse essentially doesnt do anything.  It will eventually go to the screensaver with the Plex logo floating around.

**Comment by mmccollum2** [comment]
Are you using the plexpass embedded 1.0.3? Boot up with no network cable and a usb keyboard with the newly formatted and reimaged micro sd. if you're still having issues with no keyboard response then that would be your first thing to figure out. try a different sd card? how are you getting the image onto the card?

**Comment by lynndixon** [comment]
I am using the embedded download for Raspberry Pi2 available on the Plex.tv downloads section:

https://downloads.plex.tv/plexmediaplayer-openelec/1.0.3.140-16fa0ecc/PlexMediaPlayer-1.0.3.140-16fa0ecc.RPi2-arm.img.gz

I then extract the .gz on my Mac, and have tried using several methods to write the image to the card. Pi Filler application, using dd, etc.  All these methods work for other Raspberry Pi distro's.

As a test, I re-downloaded the image...unzipped..used Pi Filler and ejected the card.
Stuck it in the Pi, and booted the pi with ONLY the HDMI and a USB keyboard attached.  I get the same message "Plex is not reachable"
I know the keyboard is working because a ctrl-alt-del will reboot the Pi.  The caps lock and num lock keys also work and light up their respective LEDs...however, no other key presses will do anything.

**Comment by mmccollum2** [comment]
And if you leave the plex is not reachable on the screen for a few minutes, the 3 options will show up at the bottom of Retry, Go Home, Sign in, try the keyboard then and move over to go home

**Comment by lynndixon** [comment]
I waited about 15 or 20 minutes, never saw the 3 options you mentioned.  It eventually went to the screen saver of the plex logo floating about.  Pressing a key on the keyboard caused it to flip back to the "Plex is not reachable" screen, but it never gives me the 3 options.  

Is there any way to get those up with a keyboard command?  Or get it to do anything with the keyboard other than reboot?
