### ISSUE TITLE
Volume issue

### ISSUE THREAD

**Issue by tomtom54** [plexinc/plex-media-player#197]
Hi there,

I've not found open issue about this topic but maybe I'm wrong so don't hesitate to tell me. 
I used PMP on a macbook pro (Yosemite) and I'm not able to change volume output on PMP. 
I've tried to find a way but could not find how to change it. 

Thanks,
Thomas.

**Comment by atrus05** [comment]
Hi Thomas!
The commands are not in the inputmap yet. You can add them yourself to whatever button combination you want on your keyboard or remote. Here is an example that should work if you add it to keyboard.json (which you can find in the inputmaps folder, let me know if you can't find it):

```
"Alt\\+V": "host:player add volume 1",
"Alt\\+Shift\\+V": "host:player add volume -1",
```
You can of course choose whichever keyboard input command you want. In the example above alt+V will increase volume, and alt+shift+V will decrease the volume.

**Comment by wm4** [comment]
Also, disable "exclusive" mode in the audio settings.

**Comment by tomtom54** [comment]
Hi,

Thanks for your answer. 
I've found the folder inputmaps and the example for keyboard.json. 
But before use this file I've apply the advice of @wm4 and it works. 
So thanks that's perfect ! 

For those who don't know where change this settings : 
Open the Settings on PMP, search audio, Show advance settings and Exclusive appear. 

Thanks again.

**Comment by sprig** [comment]
Sorry to bring up this old issue, but I don't have "Audio" under Settings in PMP. Where should it be?

<img width="1264" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2652983/25356553/3d4a627a-2943-11e7-85e0-db31e852fa39.png">

This is with the latest PMP available on plex.tv

**Comment by wm4** [comment]
Enter fullscreen/TV mode. The setting can only be changed in TV mode.

**Comment by sprig** [comment]
1. Thanks!

**Comment by sprig** [comment]
Sorry about the double post - I couldn't edit the previous from the mobile interface.

2. When I am not in fullscreen/TV mode, plex is just a window - and as such the expected behavior (for me at least) is that is should act as a window and not steal sound focus from the entire system. This is especially true now that I know that the audio settings are actually hidden. What do you think?

**Comment by wm4** [comment]
You need to disable exclusive mode. We don't enable exclusive mode in new installations, but if you've run/installed certain old PMP versions before, exclusive will be the default (and remain the default unless the config file is deleted).

**Comment by sprig** [comment]
Thanks for the clarification!
