### ISSUE TITLE
USB audio sometimes doesn't work on OSX

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#2]
E.g.: https://forums.plex.tv/discussion/comment/1038546

I suspect it comes from the change-physical-format hack, which we added for better multichannel PCM support.

**Comment by wm4** [comment]
Also: https://forums.plex.tv/discussion/188312/osx-usb-audio-output-not-working#latest

**Comment by mmccurdy** [comment]
(I can readily repro this here with an Audioengine D1 USB DAC and my MBP if that's helpful...)

**Comment by wm4** [comment]
(It should be fixed with the latest dist-ninja build. Reset your config, e.g. by deleting plexmediaplayer.conf, to test this.)

**Comment by mmccurdy** [comment]
:+1: looks good (sorry I missed the closed/fixed notes there)

**Comment by wm4** [comment]
They were closed as duplicates. I guess we haven't closed this yet, because we haven't put out a public build with the fix yet. So we have no real confirmation from users that it works fine.

**Comment by tru** [comment]
I think we can called this closed until we see people with continued problems.
