### ISSUE TITLE
Subpixel graphics issue

### ISSUE THREAD

**Issue by Endemoniada** [plexinc/plex-media-player#20]
When starting a movie, the loading animation's three dots are displayed incorrectly. See attached screenshot. The issue occurs both in Windows on a 1920x1200 HP monitor and in OS X on a 1920x1080 Sony TV.
![plex](https://cloud.githubusercontent.com/assets/575022/10638521/a47e3a92-780b-11e5-9330-9318c5d735c3.PNG)

**Comment by atrus05** [comment]
To clarify; the three dots are very jagged. This might very well be a subpixel issue.

**Comment by tru** [comment]
Is this still a problem?

**Comment by LongChair** [comment]
This should be fixed now, closing.
