### ISSUE TITLE
RPi: switching receiver input to PMP causes receiver to turn off

### ISSUE THREAD

**Issue by rcombs** [plexinc/plex-media-player#203]
https://gist.github.com/rcombs/87fc1401c28d520552de <-- Log showing me switching to a different input, then switching back ~43 minutes later. The receiver turned off (presumably due to some CEC command) and switched to video passthrough only.

**Comment by LongChair** [comment]
@rcombs : is this still relevant in recent builds ? or can we close this ?

**Comment by mseeley** [comment]
Hey @rcombs if you can repro please feel free to reopen. I'm just trying to clear out older idle issues.
