### ISSUE TITLE
PMP @ChromeBox - Audio config incorrect

### ISSUE THREAD

**Issue by Massaguana** [plexinc/plex-media-player#209]
Hello PMP Team,

here are some problems with my Audio Setup with my Asus ChromeBox connected to an AVR (ChromeBox >> AVR >> TV).
- The "Auto select Audio Device" don´t work. No Audio with my AVR. I must Set HDMI 1 manual.
- The Audio Mode at my AVR don´t goes back to "Standart" after Playback. Standart is "Stereo", when i start an Movie with  DTS-HD Sound the AVR jumps to DTS-HD mode. so far so good... but when i Stop the Playback the AVR don´t jump back to Stereo...
  All other Plex Devices do this. PMP at Rapi2, PHT, PHT at OE, OpenPHT... is only important if it sounds navigation are comes Available...

**Comment by wm4** [comment]
The default probably goes to some other audio output on that device, possibly an analogue audio jack. So it's nothing unusual that you have to explicitly select HDMI.

Your second problem must be something weird about your receiver. We do direct the audio device to play PCM if we switch back to PCM, of course. Just to be sure, a playback log of your reproduction steps would be nice.

**Comment by Massaguana** [comment]
I made an log on Weekend, in moment there are no PMP on my ChromeBox... 

But is this may by because PMP play´s no navigation sound´s? No Sound = No Playback/ don´t need to change audio mode?

**Comment by wm4** [comment]
Yeah, there are no navigation sounds yet. (And personally I don't see the need to, but not my decision.)

**Comment by Massaguana** [comment]
Here are an log for you. Just Startup PMP Starting Playback and Stop playback after 3 seconds...
http://pastebin.com/UJQ5LuZu

I think we need Navigation Sound´s, for me this is an feedback for press an key. Like on your Mobil, dial an number you can hear that when you are pressing an key...
And i like the Soundtrack with TV shows

**Comment by wm4** [comment]
Nothing conclusive in the log. There isn't a second playback attempt. Because you complained that it broke _after_ playing with DTS passthrough, this would be interesting. But I can't promise that I'll know more from such a log.

**Comment by Massaguana** [comment]
Okay, when i Play another Movie with Stereo or something like that the AVR jumps to... You can close this Tread. Thanks.
