### ISSUE TITLE
Pausing video makes Dock pop up over PMP if dragging mouse there

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#212]
I will start off by saying that I do not know if this is intended behavior or not. But I am guessing it is not.

STR:
1. Start a video
2. Pause the video (I used the space bar on the keyboard to do that)
3. Move the invisible mouse down to where you have the hidden Dock.
4. The Dock appears over PMP

**Comment by wm4** [comment]
Is pausing actually needed for reproduction?

**Comment by atrus05** [comment]
Yes. Same thing happens on both my Mac Mini and my MBP.

**Comment by wm4** [comment]
Just looked, the dock appears even if I don't pause. (Yosemite.)

**Comment by LongChair** [comment]
@atrus05 : is this still relevant in recent builds ? or can we close this ?

**Comment by atrus05** [comment]
Does not seem to happen anymore. Closing this for now.
