### ISSUE TITLE
Companion: Seeking in track never gets out of buffering state

### ISSUE THREAD

**Issue by randhawk** [plexinc/plex-media-player#213]
**Devices**
- Controller
  - NOKIA Lumia 1520 (OS: 8.1)
  - Plex Build: 2.1.2.26
- Player
  - RPi2 (OpenELEC: 6.0)
  - Plex Build: 2.5.3
  - PMP Build: 1.0.4

**STR**
1. (Controller) Begin playback of any track while connected to player
2. (Controller) Once audio begins playing, seek to any position in the track

**Current Behavior**
Seeking will pause the track as it buffers (Image 1). Unfortunately, the track never plays as it sits in a continuous buffering state.
Note: An iPhone 6 (OS: 9.2, Plex Build: 4.0.10) under the same conditions also had the same issue.

**Expected Behavior**
A user can successfully seek to any point in the track.

Image 1: Plex Web showing the track is buffering
![screen shot 2016-01-04 at 11 05 45 am](https://cloud.githubusercontent.com/assets/12534497/12099322/6fd8c7c4-b2dc-11e5-952b-f64ee5eafe68.png)

Linking https://github.com/plexinc/qa-automation/issues/7
https://github.com/plexinc/qa-automation/issues/217

**Comment by wm4** [comment]
I've heard of seeking problems on RPI before; maybe it's not specific to companion.

**Comment by kayone** [comment]
doesn't sound like something companion has control over, all we do is tell the player to skip to a new time.

**Comment by randhawk** [comment]
I'm not sure where the issue lies if that's the case because seeking works on both controlling devices when flinging to other players. Let me know if you want me to try anything. It could be an RPi issue.

**Comment by mseeley** [comment]
Will check if this is fixed on master. We used to get confused by buffering notifications triggering a buffering state.

**Comment by mseeley** [comment]
Moved to the web-client repo for triage.
