### ISSUE TITLE
Key input messages should carry multiple keys

### ISSUE THREAD

**Issue by Flamefork** [plexinc/plex-media-player#214]
Currently, only the first match in input mapping file triggers the event for a key press.
For keyboard input to work in search (and other possible text inputs) we need to change this so there would be multiple key names in the payload: one with a letter and one (if exists) with matching logical key.

Implementation proposal is to add a line like `"(?:Shift\\+)?([A-Z])": "%1",` to `keyboard.json` and change triggering code to not stop after first match but to collect every matched keys.
Desired API change: use existing endpoint, just change the argument from string to array of strings.

Testing: currently this model is supported in `tv-key-handling-refactoring-9001` branch of web repo. It's intended to be merged really soon.

**Comment by Flamefork** [comment]
Closing the issue until the spec for this would be really finalized.

**Comment by Flamefork** [comment]
Updated the description and reopened.

**Comment by tru** [comment]
How do I test this?

**Comment by tru** [comment]
Oh now I see, you want me to send both `"jump+%1"` and `"%1"` when pressing `Shift+[Letter]`?

**Comment by Flamefork** [comment]
Yes, and `['H', 'home']` when pressing `H`.

**Comment by Flamefork** [comment]
That branch supports both string and array of string arguments for the signal, so it _should just work_ :)

**Comment by tru** [comment]
I'll give it a try.
