### ISSUE TITLE
No lyrics display

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#217]
PMP OE 1.0.4.173 on RasPi2
PMP 1.0.4.164 on Win 8.1

I see no lyrics. It apparently recognises that there are lyrics available, because there is a switch available to change between my sidecar txt file and the automatic LyricsFind lyrics. 
But the actual text is not displayed.
![pmp_nolyrics](https://cloud.githubusercontent.com/assets/10280992/12569359/7d0c69d4-c3ce-11e5-9122-50855eadecb4.png)

Both sidecar and online lyrics work fine in Plex Web.

**Comment by mseeley** [comment]
Hiya @OttoKerner. I'm closing this out in favor of a web-client issue: https://github.com/plexinc/plex-web-client/issues/4092. Thanks!
