### ISSUE TITLE
Subtitle utf-8 restrictions

### ISSUE THREAD

**Issue by athanas08** [plexinc/plex-media-player#218]
I use greek external srt subtitles. 

All the downloaded subtitles that use local charcode (windows-1253 for greek) are shown incorrectly with bad characters.

I had to save them as utf-8 in order to playback correctly. 

Plex media theater or plex media server do not have same issues.

**Comment by matansh** [comment]
I have a similar problem, I use hebrew subtitles (that plex itself downloads for me) and on the media player they are shown as gibberish.
No other plex app has this problem

**Comment by ExtraKiller** [comment]
So nothing new? I have this problem as well...

**Comment by wm4** [comment]
We'll enable another charset detector on the OSX and maybe the Embedded builds. Not for Windows yet.
