### ISSUE TITLE
Can start paused playback from user select screen

### ISSUE THREAD

**Issue by chrissearle** [plexinc/plex-media-player#223]
This happened to me on OSX.

Paused playback - went and made a coffee.

Returned - switched back to PMP - user select screen was presented.

Hit spacebar and playback resumed - I couldn't see it since the user select screen was on top - but I could hear the audio.

Then cleared the user select by selecting/entering pin of the user that was being used to play and returned to the video

Shouldn't keypresses to the video layer be suspended when user select is on top?

**Comment by mseeley** [comment]
Thanks Chris. Yeah there were some weird problems leaving the previous screen constructed when the user select screen is shown. Very, very, shortly we'll be closing the previous screen when the user select screen is displayed.

We won't show the user select screen when the screensaver is activated if the user isn't in a Plex Home or has auto sign in enabled.
