### ISSUE TITLE
ToggleDebug command does not work during playback on RPi2 anymore

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#224]
It was first raised in this topic, and I was able to reproduce it on my RPi2 (on my Mac it however works just fine): https://forums.plex.tv/discussion/205718/input-mapping-host-toggledebug

The log shows the same command and the same wording if you press toggledebug during playback or when I am in the home screen. But it only shows the debug overlay if press it while in the home screen.

```
2016-02-05 12:16:12 [ DEBUG ] InputComponent.cpp @ 86 - Input received: source: "Keyboard" keycode: "Volume Mute" 
2016-02-05 12:16:12 [ DEBUG ] InputComponent.cpp @ 103 - Got host command: "toggleDebug" arguments: "" 
2016-02-05 12:16:12 [ DEBUG ] InputComponent.cpp @ 109 - Invoking slot toggleDebug 
```

I tried with the standard command for toggledebug on my RPi2, and it behaves the same. So it has nothing to do with the fact that the above user is using a weird keyboard command for it. The entire log is in the thread linked to at the beginning of this GHI.

**Comment by atrus05** [comment]
The debug overlay command does work if I trigger it on my CEC remote during playback. So it is only during playback AND if I use the keyboard.

**Comment by atrus05** [comment]
Hitting ```i``` on the keyboard does not work either during playback. KEY_RED (which triggers the debug overlay as well) on my CEC remote however works every try. Tried 5 times now, 100% reproducible.

**Comment by farkel** [comment]
It seems to be tied to the "Allow Display Mode Switching" flag.  When I set it to off, I can get the debug overlay both in a menu or a playing video.  When I try it with the flag set to on, I no longer get the debug overlay while playing a video.  Looks like that might have something to do with it.

**Comment by atrus05** [comment]
cbjerg in this thread also confirms it working if he turns off "Allow Display Mode Switching". Here is the thread he made: https://forums.plex.tv/discussion/comment/1125466#Comment_1125466

**Comment by wm4** [comment]
And all this is while the OSD still works, right?

Something in the QtQuick state must be getting messed up.

**Comment by farkel** [comment]
Yes.  I'm able to bring up the OSD to pause, stop, etc.  Thanks!

**Comment by wm4** [comment]
Sounds like we already know this bug. But we could never track it down properly. It seems to happen randomly, and only on RPI.

**Comment by farkel** [comment]
In my case, it doesn't happen randomly.  As long as I've got "Allow Display Mode Switching" set to on, I can't get the debug overlay to show up during videos.  If I turn it off, I can see the overlay.

**Comment by farkel** [comment]
Still occurring in 1.05.  Thanks!

**Comment by farkel** [comment]
And in 1.06 RC.

**Comment by tru** [comment]
@jturcotte - I think we need your help here. The debug layer is a QML layer that is placed on top of the webview when the user invokes it. After we switch refresh rate (and do the horrible dance to tear down the graphics context on the PI) it doesn't appear again. Could you have a look if 1) our RRS could be handled better or 2) figure out why the QML layer doesn't render after that happens. Thanks!

**Comment by jturcotte** [comment]
@tru Sure, I'll have a look this week, I have an RPi2 lying around. It might be that the video display mode isn't allowing QtQuick or GL to initialize somehow while the OSD display mode would.

Is there some info on how to build mpv and everything for the RPi?

**Comment by farkel** [comment]
If you need me to try something, let me know and I'll give it a shot.  Thanks!

**Comment by jturcotte** [comment]
The problem is that reinitializing the QPlatformIntegration in DisplayManagerRPI::resetRendering is leaking a QEvdevKeyboardManager each time, meaning that keyboard events are sent multiple times. toggleDebug would then have no effect when the number of alive QEvdevKeyboardManager object is pair since it would be toggled on-off-on-off a pair number of time, and an unpair number of time when not playing video.
