### ISSUE TITLE
Filter is not preserved in video library when navigating back from video playback

### ISSUE THREAD

**Issue by PombeirP** [plexinc/plex-media-player#228]
When I filter home videos by a given year, watch a video and then go back to the videos page after playback, the filter is lost (goes back to `All`), which makes it quite useless to watch videos from a given year.

**Comment by dogonwheels** [comment]
Also raised here - https://github.com/plexinc/plex-web-client/issues/3394 (general issue on TV apps)

**Comment by mseeley** [comment]
Closing this out as a dupe and scheduling the existing issue. We may not address this milestone yet it'll be out of the backlog and ready for pickup. Thank you Pedro for the file and you too Dom for the reminder. :+1:
