### ISSUE TITLE
V-Sync not working with Intel Embedded edition and Nvidia video card

### ISSUE THREAD

**Issue by youngm** [plexinc/plex-media-player#23]
Version: 1.0.0.4
OS: Embedded
Hardware Intel 64-Bit Nvidia graphics

I see significant refresh tearing.  V-Sync appears to not be working and I don't see a way to turn it on.  I can see it at 60hz but is gets significantly worse when matching refresh rate at 24hz.

It is not clear to me if the embedded image is supposed to work with generic PCs or only with machines using Intel graphics.

OpenELEC PHT works just fine with this same hardware.

**Comment by youngm** [comment]
I see the tearing both when watching movies and when navigating the UI.

**Comment by scdemanett** [comment]
I have also noticed this issue, Plex Media Player doesn't seem to sync the display like Plex Home Theater does. I tested and noticed this with a 24Hz TV show, my TV reports what native rate it's running and Plex Home Theater puts the TV in 24Hz but the same content on Plex Media Player does not. I tested with display sync set to audio and display.

Version: 1.0.0.5
OS: Windows 7
Hardware: i7-4770k, Radeon HD 7870
TV: XBR-52HX909

**Comment by wm4** [comment]
These sound like different problems.

>I see significant refresh tearing. V-Sync appears to not be working and I don't see a way to turn it on. I can see it at 60hz but is gets significantly worse when matching refresh rate at 24hz.

It's not easy to tell what's wrong here. In the best case we just need to update the drivers.

>I tested and noticed this with a 24Hz TV show, my TV reports what native rate it's running and Plex Home Theater puts the TV in 24Hz but the same content on Plex Media Player does not.

this sounds like a refresh rate switching issue. Make sure "Allow display mode switching" is enabled in the setting. Post a log after trying playback. (Preferably using the new update, 1.0.1.42.)

**Comment by youngm** [comment]
Tried nvidia-legacy version of 1.0.2 and things seem much better.  Well close for now.
