### ISSUE TITLE
Raspberry Pi 2 - Hangs after playing

### ISSUE THREAD

**Issue by farkel** [plexinc/plex-media-player#232]
Original Topic:  [https://forums.plex.tv/discussion/205878/1-04-raspberry-pi-2-hangs-after-playing#latest](url)

Intermittent issue where after playing a video on 1.04, it does not return back to the episode's information screen. Trying to hit the stop or back button on my keyboard remote does not seem to do anything. Nor does bringing up the onscreen stop button and using it. I have to hit the home button on my remote to get out of it. Since I can't regularly reproduce, I'm not able to produce fresh logs, but hopefully the attached will help. 

[plexmediaplayer.txt](https://github.com/plexinc/plex-media-player/files/122321/plexmediaplayer.txt)

**Comment by wm4** [comment]
>2016-02-05 12:15:59 [ WARN  ] PlayerComponent.cpp @ 430 - ffmpeg/video: h264_mmal: Could not set input buffering limit. 

Seems we're still building with older firmware. (Whether it's related to this freeze or not.)

**Comment by cbjerg** [comment]
I have the same problem. Seems like it will exit normally if show was started from the home screen, but as soon as you start it from anywhere else, it will fail after playback, forcing you to press home button

**Comment by ac4lt** [comment]
I see this happening also in 1.0.5 though I haven't seen a pattern to making it happen reliably.

**Comment by LongChair** [comment]
supposedly fixed now as firmware was updated several times.
