### ISSUE TITLE
Music not playing in PMP 1.0.4 embedded

### ISSUE THREAD

**Issue by scfigg** [plexinc/plex-media-player#234]
I have an Intel NUC BOXDCCP847DYE with 1.0.4 stable embedded installed on it. Generally pretty stable release, doesn't really crash much. However, I can play music, but I can't ever hear it. I have it hooked up to my receiver and audio output via HDMI. TV shows and Movies play audio just fine, but I can't get my music to play. Same issue was on 1.0.3 before as well.

**Comment by wm4** [comment]
Playback log, please.

**Comment by ziggimon** [comment]
Is your receiver perhaps a Pioneer?

**Comment by tocheeba** [comment]
I'll have to grab logs later tonight when I get home from work. My pioneer is an Onkyo 5.1

**Comment by ziggimon** [comment]
Does this temporary make it work? https://github.com/plexinc/plex-media-player/issues/36#issue-112802173

**Comment by LongChair** [comment]
Closing due to the lack of feedback.
