### ISSUE TITLE
Missing qt5positioning.dll - Windows 10

### ISSUE THREAD

**Issue by lehmanjo** [plexinc/plex-media-player#235]
Hi.

PlexMediaPlayer-1.0.2.70-15a01542-windows-x86_64.exe installs and runs successfully on a new Windows 10 installation.

PlexMediaPlayer-1.0.4.169-da1dda84-windows-x86_64.exe installs but fails to start with a "qt5positioning.dll" missing error on  a new  Windows 10 installation.

J

**Comment by LongChair** [comment]
@lehmanjo : i suppose this is not an issue anymore ? can we close this ?
