### ISSUE TITLE
Bad GUI rendering, iMac 5k, second display

### ISSUE THREAD

**Issue by RumpelstilzchenV** [plexinc/plex-media-player#237]
Hello,

PMP gui is rendered wrong when using it full screen on second display (please see screen shot attached + log).
![screen shot 2016-02-13 at 02 40 22 2](https://cloud.githubusercontent.com/assets/17261858/13064066/e06be63c-d457-11e5-82a7-4f11a1cf1ad4.png)

**Platform** - iMac 5k late 2014,3.5 GHz Intel Core i5, AMD Radeon R9 M295X 4096 MB  (PMP runs fine on iMac main display in full screen, problem only with second display)
**OS** - OS X El Capitan 10.11.3 (15D21)
**second display** - Pioneer KURO PDP LX5090, Full HD 1080p, connected with Thunderbolt to HDMI adapter.

CMD+Shift+R or Alt+Enter (exit/enter fullscreen) does not resolve the issue
[Plex Media Player.txt](https://github.com/plexinc/plex-media-player/files/131689/Plex.Media.Player.txt)

**Comment by vladashram** [comment]
It seems I have the same issue as you.
https://github.com/plexinc/plex-media-player/issues/231

**Comment by LongChair** [comment]
@RumpelstilzchenV : is that issue still relevant with latest builds ?

**Comment by LongChair** [comment]
Closing due to the lack of feedback.
Feel free to reopen with more details if needed.
