### ISSUE TITLE
Loading screen won't disappear after buffering

### ISSUE THREAD

**Issue by famAlex** [plexinc/plex-media-player#239]
Environment:
PMP 1.0.4
osx 10.11
Plex 2.5.3

If a buffer appears during a remote stream, a loading icon is displayed on top of the screen but it never goes away. Then the Play/pause button stops working. 

Hope to help!

**Comment by AlainBijl** [comment]
Same problem here on both:
PMP 1.0.4 latest nightly on PI2
PMP 1.0.4. latest nightly on Win10 64bits

**Comment by tru** [comment]
I can definitely reproduce this here. We will investigate.
