### ISSUE TITLE
DisplayManager::isRateMultipleOf should never return true for 24.975 and 24 as input

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#241]
Some video files which have a variable frame rate as part of a video might get som weird frame rate reported in the container. I have such a video file on my server that you can use to test this. "The IT Crowd" S01E01 is a mp4 video file that really is 25fps, except for the intro (I believe). The container reports the frame rate as 24.975 fps, and when I try to play the episode in PMP it switches to 24 hz instead of 50hz. PHT does correctly switch to 50hz.
The PMP code it tries to check whether a rate is a multiple of another rate. Vincent said "and I guess casting to integer and/or explicit rounding is a way to make it somewhat fuzzy. But it shouldn't trigger for same or similar rates. The prize question is, does the matching logic implicitly rely on this wrong behavior now?".

Here is the snippet from my log: https://gist.github.com/atrus05/dc765dfd2547d702bd38

**Comment by LongChair** [comment]
@atrus05 : is that still an issue ?

**Comment by atrus05** [comment]
This has since been fixed. Closing this.
