### ISSUE TITLE
Rearranging tracks in an album via companion fails in strange ways

### ISSUE THREAD

**Issue by rcombs** [plexinc/plex-media-player#245]
STR:
- Play a track from an album in PMP
- Connect to PMP from iOS for remote control
- Attempt to rearrange the later tracks in the PQ, or remove a track from it

iOS reports it gets a "Bad Request" response, but it still shows the item as moved. Disconnecting, killing the app, and reconnecting still shows it as moved. PMP doesn't show any change in the queue. If you moved a track to immediately after the current track, PMP advances to the next track on the album anyway, but later returns to the _current_ track and _then_ plays the track you moved. What‽

**Comment by mseeley** [comment]
Same issue affects other TV clients too. The PQ doesn't react appropriately to modifications on the controller.

@tru can @firasdib help out on this one?

**Comment by tru** [comment]
Yeah, as soon as he is done with the check for update I think he can tackle this.

**Comment by firasdib** [comment]
Looked into this, seems that `transientServer` is never set on the appModel which causes this to fail the way it does. I have not been able to look into why that value is never set, but writing down my progress here so I don't forget it :smile:
