### ISSUE TITLE
Not pausing after refresh rate change

### ISSUE THREAD

**Issue by gbooker** [plexinc/plex-media-player#247]
PMP 1.0.5 embedded, Intel 64-bit.

Starting with 1.0.3 (or perhaps 1.0.4), PMP stopped pausing on refresh rate changes in my setup.  The display does change it's refresh rate correctly, but PMP is no longer pausing on this change.  Since my TV doesn't display any content for 2-3 seconds after a change, this means I miss the first 2-3 seconds of everything I play.

Example log snippet:
```
2016-02-24 12:37:08 [ INFO  ] DisplayManager.cpp @ 174 - DisplayManager RefreshMatch : found a suitable mode :  " 1920 x 1080 x  0bpp @29.9701Hz" 
2016-02-24 12:37:08 [ DEBUG ] DisplayComponent.cpp @ 132 - Best video matching mode is  " 1920 x 1080 x  0bpp @29.9701Hz" on display 0 
2016-02-24 12:37:08 [ DEBUG ] PlayerComponent.cpp @ 297 - Switching refresh-rate failed or unnecessary. 
2016-02-24 12:37:08 [ INFO  ] PlayerComponent.cpp @ 445 - resuming loading 
```

P.S.  The 29.970Hz display rate is appropriate as the content is interlaced MPEG 2 from a DVD.

**Comment by atrus05** [comment]
Doesn't that log snippet just say that it did not switch refresh rate? Most likely because it was already a 60hx output from your computer?

**Comment by atrus05** [comment]
hx = hz

**Comment by gbooker** [comment]
When I started playback, it was at 60Hz.  It switched to 30Hz (approximate numbers).  These are confirmed by the TV's display as well as the Receiver's info page on the video signal.

Perhaps a longer log snippet would be more helpful as I noticed it detected a refresh rate change later, but never said it successfully did a change:
[Refresh Rate Change Snippet.txt](https://github.com/plexinc/plex-media-player/files/145157/Refresh.Rate.Change.Snippet.txt)

**Comment by atrus05** [comment]
I am willing to bet good money on that "Unable to retrieve main display" is the big issue here. :)
And what the hell kind of TV do you have that have 30hz?

**Comment by gbooker** [comment]
I saw that line too, and wondered about it, but I can't recall if it was in a version that switched refresh rates correctly too.
The TV is a Sharp LC-70UQ17U.  It seems to have a very large set of modes.

**Comment by wm4** [comment]
Does OE build #215 improve it?

**Comment by gbooker** [comment]
OE build 215 (1.1.0.215-dc1e9378) does seem to fix it.  I tried against both 30Hz and 24Hz content and in each case, it paused about 3 seconds before starting playback on the refresh rate switch.

**Comment by wm4** [comment]
Then I'll consider it fixed. A bit nervous that there's still something unexplained, but it's too hard to reproduce and confirm, and even if I came so far, there'd likely still be no proper solution.
