### ISSUE TITLE
Pi 3 support

### ISSUE THREAD

**Issue by jabbera** [plexinc/plex-media-player#253]
OpenElec 6.0.2 is already out with Pi 3 support. New video core supports 60fps 1080p and hardware h265 at 30 fps!

**Comment by atrus05** [comment]
Where did you find info on hardware h265 at 30 fps? The only info I can find is that there is no h265 hardware support. The faster CPU will however help in software decoding h265. So your comment is interesting and I would like to read more on that.

**Comment by wm4** [comment]
If there's no hw support, I doubt h265 is generally going to be fast enough.

**Comment by jabbera** [comment]
The source I had found seems to have retraced that statement. Sad panda.

**Comment by elan** [comment]
:cry: :panda_face:

**Comment by tru** [comment]
We now have Pi3 support in the latest images. I will close this. We can open a new ticket if they add h265 support in the firmware.
