### ISSUE TITLE
Mac HiDPI Support

### ISSUE THREAD

**Issue by obsess** [plexinc/plex-media-player#254]
I use HiDPI on the mac to make using it from the couch much easier. PMP Doesn't seem to like it. I am unable to read the code to pair the PMP with my account. See Screenshot
<img width="960" alt="screen shot 2016-03-04 at 8 33 17 pm" src="https://cloud.githubusercontent.com/assets/252365/13545180/f8fe4bb4-e248-11e5-88ab-9a5630f73eb6.png">

**Comment by stueeey666** [comment]
I believe this is linked to this issue I raised here several months ago... was informed by @atrus05 at the time it would not be a high priority for the PMP team...  but I really wish they would resolve it as it is very annoying to launch fullscreen and then have to toggle fullscreen on/off to get PMP to fit the screen properly.  I can't imagine it is a difficult one for them to resolve.

link to other HiDPI issues I raised https://github.com/plexinc/plex-media-player/issues/176

**Comment by tru** [comment]
Let's continue tracking in #176.
