### ISSUE TITLE
FEATURE Add the ability to modify/edit Movie Posters

### ISSUE THREAD

**Issue by n8io** [plexinc/plex-media-player#255]
This may or may not be on your radar to add, but it might be a nice feature.

http://blog.n8io.com/adding-a-screener-ribbon-to-plex-movie-posters/

![68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3435323935392f686f737465642f73637265656e65722d63686f6f7365722e676966](https://cloud.githubusercontent.com/assets/2074517/13579619/74e88efe-e46c-11e5-9ea9-78120870ea8b.gif)

<img width="928" alt="68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f3435323935392f686f737465642f73637265656e65725f6578616d706c65732e706e67" src="https://cloud.githubusercontent.com/assets/2074517/13579623/7ed1e10e-e46c-11e5-91b5-980807e2e3a3.png">

**Comment by tru** [comment]
This would belong to the management client instead. I suggest you post in the Plex for Web forum instead. Thanks!

**Comment by n8io** [comment]
Posted it there. Thanks for the redirect @tru !
