### ISSUE TITLE
QT5_CFLAGS missing -fPIC on Ubuntu Linux

### ISSUE THREAD

**Issue by mdesdin** [plexinc/plex-media-player#256]
The errors displayed are like this one:
`In file included from /opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qsharedpointer.h:37:0,
                 from /opt/Qt5.6.0/5.6/gcc_64/include/QtCore/QSharedPointer:1,
                 from ../external/qslog/QsLogDest.h:30,
                 from ../external/qslog/QsLogDestFunctor.h:30,
                 from ../external/qslog/QsLogDestFunctor.cpp:27:
/opt/Qt5.6.0/5.6/gcc_64/include/QtCore/qglobal.h:1090:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
`

Happening with master on Ubuntu 14.04 Server and Ubuntu 15.10 Desktop when using final qt-opensource-linux-x64-5.6.0_360.run installer.

As a temporary solution I am appending -fPIC to QT5_CFLAGS manually inside the COMP ${components} foreach loop for it to compile.

**Comment by tru** [comment]
It's called something else now. I haven't looked yet since we don't build on Ubuntu automatically. But it should be changed to what's listed in Qt5Core.conf

**Comment by mdesdin** [comment]
Sorry, I am looking around for this file, but cannot find it, I am also looking for similar ones. It does not seem to be included in this official installer. Any tips?

**Comment by tru** [comment]
There should be cmake files in QTROOT/lib/cmake/Qt5Core

**Comment by mdesdin** [comment]
yup, those I found, heading there now... thanks!

**Comment by mdesdin** [comment]
I see conditions inside Qt5CoreConfigExtras.cmake that should append -fPIC, but it is also supposed to be handled by the cmake version we are using: 3.2.2. This will take me longer, never dealt with this environment in the past, and I might be out of the league already ;-)

**Comment by nicjo814** [comment]
I've submitted a PR #275 which potentially could fix this. I've not used cmake before so I'm not sure if there are any side effects based on my solution.

**Comment by tru** [comment]
@mdesdin have you tried this after #275 was merged? It should fix your problem.

**Comment by mdesdin** [comment]
@tru hi, yes, done, tested and working!

**Comment by tru** [comment]
Ah perfect. Thanks for confirming.
