### ISSUE TITLE
Raspberry Pi 3: Support for BT/Wifi via Broadcom BCM43438

### ISSUE THREAD

**Issue by nooryani84** [plexinc/plex-media-player#259]
Can you add the necessary driver/firmware to support the Broadcom BCM43438 on the Raspberry Pi 3?  The chip provides 2.4GHz 802.11n wireless LAN, Bluetooth Low Energy, and Bluetooth 4.1 Classic radio support.

http://lists.infradead.org/pipermail/linux-arm-kernel/2016-February/412098.html

From what I can tell it's the firmware for the bcm2835-sdhost
https://github.com/raspberrypi/linux/tree/dc59e187b00ce0d4386b4468fe06ab644e8a7d91/drivers/mmc/host

I'm not very familiar with Github , so I may be linking to an entirely incorrect directory.

Is this something you guys will need to add or will we receive this via an updated Linux ARM kernel?

**Comment by ziggimon** [comment]
Were already working on a 6.0.3 rebase of OE that includes all that. And for the record, if its missing for OpenELEC 6.0.3 then it will be missing on our upcoming build also.

**Comment by nooryani84** [comment]
Sorry about that.  Should I just close this ticket then?  I don't want to add additional clutter here

**Comment by ziggimon** [comment]
I'll close it, we are already on it :D
