### ISSUE TITLE
PMP not honoring forced subtitle flag

### ISSUE THREAD

**Issue by ac4lt** [plexinc/plex-media-player#261]
While PHT does, PMP does not honor the forced subtitle flag in mkv files. This can be verified by playing any mkv with a track marked forced. Once the video is playing you can choose the forced subtitle track (and PMP does show that is is a forced track) but it isn't enabled automatically.

**Comment by ac4lt** [comment]
Oh, I'm seeing this in 1.0.6 rc2-ish.

**Comment by OttoKerner** [comment]
The 'forced' flag is for automatic selection.
If you select the subtitle track manually and it doesn't show - it has nothing to do with 'forced' or not.

A PMP log file is at least required for this.
End PMP
start PMP
go straight to the movie and play it with activated subtitle for ~ 1-2 minutes
then end PMP and fetch the `PlexMediaPlayer.log` and put it into a [Gist](https://gist.github.com/)
then post the link to the Gist in here

**Comment by atrus05** [comment]
And do this on a media file which you previously has a force track flag, but you have not manually switched subtitles on. Because as soon as you have switched to a subtitle on a media, then Plex knows you have made a manual choice and saves that.

**Comment by ac4lt** [comment]
The windows system is no longer here (it was just passing through) but I will try to repro this on the Pi2 this evening. I did try 1.0.6rc2-ish Mac on the same file this morning and that worked properly. I'll get a log for you later today.

**Comment by ac4lt** [comment]
atrus05, what you described was exactly what I was doing. Unfortunately, I can' reproduce this on my mac with 1.0.6rc2-ish or the Pi2 with 1.0.5. The system I was seeing it on was an Intel Skylak NUC running Windows 10 but it wasn't mine. I don't know if I can get access to it again but if I do, I'll try to reproduce it again. For now, consider this unreproducible. For now, go ahead and close this out.
