### ISSUE TITLE
Selected subtitles does not always work

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#262]
I am using PMP 1.1.0.217-866be538 and sometimes (often) when I start up an episode which does have a **selected** external subtitle (might be applicable for embedded subs as well, but as I almost always use external this is the only thing I have seen so far) the subtitle does not show up when it should. I have to hit `L` on the keyboard to switch to "None" and then hit `L` again for the sub to start showing up again.
Here is the log: https://gist.github.com/atrus05/43109fd52f6daf1b22af

**Comment by wm4** [comment]
Do you have a more complete log? I suspect it happens if you select or deselect a subtitle at runtime, then stopping playback, then starting something else with a subtitle.

**Comment by atrus05** [comment]
Here are a compilation of 4 log files that show the entire duration of me running PMP
https://gist.github.com/atrus05/48a99019fdea7d14812c

**Comment by LongChair** [comment]
@atrus05 : is this still relevant or can we close ?

**Comment by atrus05** [comment]
I am closing this, as it no longer is valid. A different issue happens now when I start a video which has a selected external SRT (it shows a random line from the SRT from the start and it is shown until the first actual dialogue is spoken, then it works as normal. The same thing seems to happen if I switch to another subtitle file, and then later switches back... a random line is shown and it does not go away until the next timecode hits in the SRT).
