### ISSUE TITLE
Filters cleared with every load of Browse All page

### ISSUE THREAD

**Issue by toddrob99** [plexinc/plex-media-player#264]
Windows 10, PMP 1.0.5

1. Navigate to a TV section > Browse All (which is redundant but that's another issue altogether)
2. Select a filter using the controls above the show posters (Collection is the one I use most)
3. Select a show
4. Press Back
5. Observe filter is no longer selected. 

The Unwatched filter persists, but the others are cleared each time the Browse All page loads. Impacted filters are Year, Genre, Content Rating, Network, and Collection.

**Comment by mseeley** [comment]
Hi @toddrob99. I've linked our internal issue to this one and will close this issue. We have the fix scheduled for this month so long as fate is willing.

That other issue altogether is getting a lot of attention at the moment. We're gearing up some really nice changes to address it. More on this later! ;)
