### ISSUE TITLE
show 'more' movie extras results in empty screen

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#266]
PMP 1.0.6 and 1.1.0
Windows 8.1

PMS 0.9.16.0 - 0.9.16.3
Windows 8.1

When on the preplay screen of a movie with extras (whether local or online doesn't matter), if you click on 'More' extras you get a screnn without content, except for the upper default icons 'Plex Logo', 'Search' and 'Home'
![norextras](https://cloud.githubusercontent.com/assets/10280992/13822759/3ea72bf6-eba7-11e5-838a-dbec2900bc73.jpg)

player log
https://gist.github.com/OttoKerner/cf9c138edf491b057800

**Comment by mseeley** [comment]
Same here on a different movie. Thanks @OttoKerner.

**Comment by mseeley** [comment]
UI @https://github.com/plexinc/plex-web-client/commit/c777513dfbf696c6d29f3af64ba5317efed48325

![image](https://cloud.githubusercontent.com/assets/30019/13859963/2f4020ea-ec2a-11e5-85ac-5994f64897ff.png)

![image](https://cloud.githubusercontent.com/assets/30019/13860006/62489f08-ec2a-11e5-8040-f56780ad759d.png)

![image](https://cloud.githubusercontent.com/assets/30019/13860066/902bbbb2-ec2a-11e5-84fa-6c19a71c8a9f.png)

Running against production UI

* Clicks to the `More` correctly display list of content
* Still seeing empty hub.

**Comment by LongChair** [comment]
@OttoKerner : we can close this right ?

**Comment by LongChair** [comment]
Web associated issue seems closed, so will close ours.
Feel free to reopen if needed.
