### ISSUE TITLE
Lower portion of video is choppy during most playback

### ISSUE THREAD

**Issue by phrend** [plexinc/plex-media-player#268]
Platform and OS Version: Windows 7 Home Premium, SP 1
Plex Version: 2.5.8
Plex Media Player Version: 1.0.6

When I play most videos, the lower third, or quarter of the screen is a little choppy - is't as if there's a horizontal line across the screen, and the video above and below is not quite in sync all the time. (I can upload a video of the TV recorded on my phone, if that helps.)

I can reproduce it by playing a video. It happens with most (maybe all) of the videos in my collection. I'm even seeing it when watching streaming movie trailers, so I don't think it's related to my media.

It's also odd that when I bring up the debug overlay, that seems to stop happening...?

I'm attaching my logs, and a screen-shot of the debug overlay - hope it helps you track the issue down. I'm happy to collect additional info, or try fiddling with stuff if that will help!

[Plex Media Server.zip](https://github.com/plexinc/plex-media-player/files/180643/Plex.Media.Server.zip)
[PlexMediaPlayer.zip](https://github.com/plexinc/plex-media-player/files/180644/PlexMediaPlayer.zip)
![plex](https://cloud.githubusercontent.com/assets/1667900/13896708/898ea632-ed53-11e5-803a-085954904b1f.jpg)

EDIT: I should also mention that when using Plex for Home Theater on the same computer, this is not a problem.

**Comment by wm4** [comment]
Sounds like tearing. This is mostly a driver issue, and we don't have much control over it. It may depend on timing coincidences, which would explain why it doesn't happen with debug overlay.

Try one of the following things: driver update, enable or disable Aero, enable native OpenGL mode (in the PMP settings).

**Comment by phrend** [comment]
Thanks, enabling native OpenGL seems to have fixed it, or at least dramatically improved it.
