### ISSUE TITLE
"Plex is not Reachable" PMP 1.0.6

### ISSUE THREAD

**Issue by ChacalCH** [plexinc/plex-media-player#269]
PMP 1.0.6 is running on a Intel NUC. It seems Plex is starting faster than the ethernet connection initializing. I always get "Plex is not reachable" and I have to hit "try again" at least two times. Then suddenly it works.
Same thing happens sometimes when switching between movies or the menu (but only for some miliseconds), might be related.

Hardware/Software:
NUC D34010WYKH running PMP (embedded version).
SSD: Samsung 950 Evo

**Comment by tru** [comment]
@mseeley I was thinking about this, would it be hard to get the web-client to retry automatically if we add a signal when the network configuration changes? The host knows about this already and we can easily expose a signal that triggers when it should retry.

**Comment by mseeley** [comment]
No wouldn't be hard to add a signal for us to retry automatically. We already have app handling for responding to network connectivity changes. We would need to wire up the PMP signal and update our error views to retry on connectivity changes.

**Comment by LongChair** [comment]
@ChacalCH : it's getting rather old, and i'm not sure which platform this was related to.
If that is embedded then a wait on network script was added before starting PMP which should fix that issue.

Can you confirm we can close this ?

**Comment by ChacalCH** [comment]
@LongChair 

I can't tell you, because I don't use an embedded PMP anymore.

**Comment by LongChair** [comment]
Ok, thanks, will close then :)
