### ISSUE TITLE
Screensaver not launching after a playback

### ISSUE THREAD

**Issue by Ismelda** [plexinc/plex-media-player#270]
The Screensaver just doesn't work anymore after you play a file. Seems there is a 10mn minimum to make it so. After that even if you switch among your users in a PlexHome, it doesn't come back. The only way to see the screensaver working again is to pause a video.

I believe this was introduced when the screensaver fix for the photos slideshow was fixed. Back then the screensaver was appearing in the middle of a slideshow which wasn't good. But since, it only works if you never played anything or if you pause what you are viewing.

**Comment by tru** [comment]
@Flamefork @mseeley @firasdib - can you guys have a look?

**Comment by tru** [comment]
More screensaver problems in 1.0.6 https://forums.plex.tv/discussion/212382/1-06-screen-saver-on-pi2#latest

**Comment by wm4** [comment]
Was fixed in dist-ninja from last Friday. Probably.
