### ISSUE TITLE
Timelines are sent with https protocol and IPv4 host

### ISSUE THREAD

**Issue by PombeirP** [plexinc/plex-media-player#274]
I noticed that timelines are arriving with `https://192.168.16.250` instead of the `*.plex.direct` host names. I'm using `1.0.6.236-1ce41570`. Haven't seen this before.

**Comment by kayone** [comment]
just so I can manage the priority, is it breaking anything or just doing the correct?

**Comment by PombeirP** [comment]
I'm having problems controlling PMP with the Windows app, and this is what caught my attention in the log files.

**Comment by LongChair** [comment]
this should be fixed by now. closing.
