### ISSUE TITLE
Write qt.conf in non-priviliged folder

### ISSUE THREAD

**Issue by nicjo814** [plexinc/plex-media-player#276]
I'm working on getting PMP to build on Launchpad to get a deb package ready for installation. Launchpad builds the project as a non-root user and does not allow external connections to download files as part of the build process. I've created a PR that would solve the external downloads issue, but there is still the aspect of building as non-root.

In the CMakeModules/QtConfiguration.cmake file the script tries to write a "qt.conf" file in the ${QTROOT}/bin folder, which for me translates to /opt/qt56/bin where I'm not allowed to write stuff. Would it be possible to use something like ${CMAKE_SOURCE_DIR}/qt.conf instead here? I've only found one reference to where the file is read/copied and that is in the src/CMakeLists.txt. What do you think, would it work?

**Comment by TingPing** [comment]
To add onto that, if the QTROOT is `/usr` and a custom Prefix doesn't need to be set just don't write the file at all.

**Comment by nicjo814** [comment]
If it's not possible to put the qt.conf file in another folder (for building on OSX) would you consider adding another cmake option that could be used to prevent writing the file at all?

**Comment by tru** [comment]
I think that the file should only be written when using our deps. This was a specific problem we worked around on Windows. It could be skipped if the user supplies a QTROOT variable.

**Comment by nicjo814** [comment]
Ok, then the code for writing the file just needs to be moved inside the if-clause that checks for the QTROOT variable I guess.
