### ISSUE TITLE
Issue connecting to nightlies when running cmake

### ISSUE THREAD

**Issue by ProfessorKaos64** [plexinc/plex-media-player#277]
If I go to the root site, it notes I need a plex ID. Is this URL right that it is referencing?

```
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-616e301.tbz2.sha.txt to konvergo-qt--release-616e301.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:44 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-616e301.tbz2.sha.txt:
  "HTTP response code said error"

  Hostname was NOT found in DNS cache
```

https://gist.github.com/ProfessorKaos64/86be8d955a181223491a

**Comment by LongChair** [comment]
this is not related to the webclient. looks to be downloading the deps, your QTROOT is probably undefined.

**Comment by ProfessorKaos64** [comment]
ok. Guess I also have to rethink my dh_autoconfigure and dh_configure for buldingt qt. I use pbuilder for clean builds, so leaving a whopper install in /usr/local isn't what I prefer.
