### ISSUE TITLE
playback issues in 1.1.0.257-67b978e3

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#285]
PMS v0.9.17.0.1865-cdb9d98 on Win 8.1

PMP on Windows 8.1 x64 (separate machine from server)
video output on normal computer monitor
sound to external soundinterface with 8ch and 96kHz sample rate, fixed
audio preferences are set to Basic / 5.1 / normalize: no
Direct Play and Direct Stream = yes

with the big changes in this build there are numerous issues which I am trying to list below

# complaint about missing zlib.dll 
repeats on every app start 2 - 5 times

# typical matroska file with AVC video in 720p, with AC3 audio - nothing special

then playback starts with no picture and choppy audio
upon 2nd playback, the complaint about zlib1.dll is gone, but the rest of the issues is still there
mediainfo and Player log
https://gist.github.com/OttoKerner/90d795fa672d00a770173074eb8530e4

# FLAC audio file with 44.1kHz 16 bit 2.0ch - playback success

# FLAC audio file with 88.2kHz 24 bit 2.0ch - playback success

# FLAC audio file with 192kHz 24 bit 5.1ch - playback success

# FLAC audio file with 96kHz 24 bit 7.1ch - playback success

# MP3 audio file with 44.1kHz 16 bit 2.0ch 
1x complaint about a missing zlib1.dll - then playback commences normally

# MKV with DTS audio (AVC L4.1 ~12mbps 23.976 fps 1808x1080px, audio AC3 + **DTS**, subtitles in SRT)
there is just a complaint that audio output initialization failed
medainfo and player log
https://gist.github.com/OttoKerner/8f227937379ae2462673c06a54a0ca27

# MKV with AVC 1080p ~11mbps, and **TrueHD** + AC3 audio
there is just a complaint that audio output initialization failed
medainfo and player log
https://gist.github.com/OttoKerner/c4b8ac5c661e6e0bbb1b309527604c72

**Comment by Mediaconoclast** [comment]
I see the same behavior on Win7 ... with the only thing to add is that even while successfully playing back FLAC audio, the log was reported this persistently & repeatedly during playback:

`[ ERROR ] PlayerComponent.cpp @ 467 - ffmpeg: spdif: Wrong AAC file format`

**Comment by OttoKerner** [comment]
# mkv with DVD video anamorphic and AC3 + **Flac** audio
playback starts with black picture and choppy audio

mediainfo and player log
https://gist.github.com/OttoKerner/038c229a88a4f7fa4a93bd345a21ebed

**Comment by OttoKerner** [comment]
# music with a "naked" DTS 96/24 file
no playback, just a red message 'unrecognized file format'

mediainfo and player log
https://gist.github.com/OttoKerner/6b18c53cd52648668fd3a5612d3c2d6a

**Comment by wm4** [comment]
Resolved in build 258.
