### ISSUE TITLE
Build Fails 

### ISSUE THREAD

**Issue by soelu** [plexinc/plex-media-player#289]
ninja and XCode build fails...

commands as described in Readme

`[6/11] Linking CXX executable "src/Plex Media Player.app/Contents/MacOS/Plex Media Player"
FAILED: : && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -mmacosx-version-min=10.9 -fno-omit-frame-pointer -Wall -g -Wl,-search_paths_first -Wl,-headerpad_max_install_names  src/CMakeFiles/PlexMediaPlayer.dir/ComponentManager.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/main.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/SignalManager.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/display/osx/DisplayManagerOSX.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/display/dummy/DisplayManagerDummy.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayManager.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/player/PlayerComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/player/PlayerQuickItem.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/CachedRegexMatcher.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/PlatformUtils.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/HelperLauncher.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/Utils.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/Log.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/HelperLaunchd.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/utils/osx/OSXUtils.mm.o src/CMakeFiles/PlexMediaPlayer.dir/server/HTTPServer.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/ui/ErrorMessage.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/ui/EventFilter.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/ui/KonvergoWindow.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/input/apple/InputAppleRemote.mm.o src/CMakeFiles/PlexMediaPlayer.dir/input/apple/AppleRemoteDelegate.mm.o src/CMakeFiles/PlexMediaPlayer.dir/input/apple/InputAppleMediaKeys.mm.o src/CMakeFiles/PlexMediaPlayer.dir/input/InputComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/input/InputMapping.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/input/InputSocket.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/input/InputRoku.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/input/InputSDL.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/input/InputCEC.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/system/OEUpdateManager.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/system/SystemComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/system/UpdateManager.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/system/UpdateManagerWin32.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/system/UpdaterComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/breakpad/BreakPadOSX.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/settings/AudioSettingsController.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/settings/SettingsComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/settings/SettingsSection.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/power/PowerComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/power/PowerComponentMac.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/remote/GDMManager.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/remote/RemoteComponent.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/remote/RemoteSubscriber.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/qrc_resources.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/plex-web-client-konvergo-a7f4a47.cpp.o src/CMakeFiles/PlexMediaPlayer.dir/PlexMediaPlayer_automoc.cpp.o  -o "src/Plex Media Player.app/Contents/MacOS/Plex Media Player"  src/shared/libshared.a external/qhttp/libqhttp.a external/qslog/libqslog.a external/plistparser/libplistparser.a dependencies/darwin-x86_64-plexmediaplayer-dependencies/latest/konvergo-depends-darwin-x86_64-release-1266e30/lib/libmpv.dylib -framework OpenGL dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtXml.framework/QtXml dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtWebEngine.framework/QtWebEngine dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtWidgets.framework/QtWidgets -framework Foundation -framework AppKit -framework IOKit -framework Cocoa -framework Security -framework Carbon external/SPMediaKeyTap/libspmediakeytap.a external/HIDRemote/libhidremote.a dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/libSDL2.a -framework ForceFeedback -framework Carbon -framework CoreAudio -framework AudioUnit -framework CoreVideo /opt/local/lib/libiconv.dylib dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/libcec.dylib dependencies/darwin-x86_64-plexmediaplayer-dependencies/latest/konvergo-depends-darwin-x86_64-release-1266e30/lib/libbreakpad_client.a -lpthread dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/libSDL2.a -framework ForceFeedback -framework CoreAudio -framework AudioUnit -framework CoreVideo /opt/local/lib/libiconv.dylib dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/libcec.dylib dependencies/darwin-x86_64-plexmediaplayer-dependencies/latest/konvergo-depends-darwin-x86_64-release-1266e30/lib/libbreakpad_client.a -lpthread dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtWebEngineCore.framework/QtWebEngineCore dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtWebChannel.framework/QtWebChannel dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtQuick.framework/QtQuick dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtQml.framework/QtQml dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtNetwork.framework/QtNetwork dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtPositioning.framework/QtPositioning dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtGui.framework/QtGui dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/lib/QtCore.framework/QtCore && cd /Users/soelu/projects/github/plex-media-player/build/src && /opt/local/bin/cmake -E copy /Users/soelu/projects/github/plex-media-player/build/dependencies/darwin-x86_64-plexmediaplayer-qt/latest/konvergo-qt-darwin-x86_64-release-616e301/bin/qt.conf /Users/soelu/projects/github/plex-media-player/build/src/Plex\ Media\ Player.app/Contents/MacOS/../Resources
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _SDL_iconv_REAL in libSDL2.a(SDL_iconv.c.o)
      _SDL_iconv_string_REAL in libSDL2.a(SDL_iconv.c.o)
     (maybe you meant: _SDL_iconv_REAL, _SDL_iconv_string , _SDL_iconv_open , _SDL_iconv_open_REAL , _SDL_iconv_close_REAL , _SDL_iconv_close , _SDL_iconv , _SDL_iconv_string_REAL )
  "_iconv_close", referenced from:
      _SDL_iconv_close_REAL in libSDL2.a(SDL_iconv.c.o)
      _SDL_iconv_string_REAL in libSDL2.a(SDL_iconv.c.o)
     (maybe you meant: _SDL_iconv_close_REAL, _SDL_iconv_close )
  "_iconv_open", referenced from:
      _SDL_iconv_open_REAL in libSDL2.a(SDL_iconv.c.o)
      _SDL_iconv_string_REAL in libSDL2.a(SDL_iconv.c.o)
     (maybe you meant: _SDL_iconv_open, _SDL_iconv_open_REAL )
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.`

**Comment by tru** [comment]
Which version of OSX and Xcode are you using there?

**Comment by soelu** [comment]
OSX 10.11.4 (15E65)
XCode Version 7.3 (7D175)

**Comment by soelu** [comment]
Ninja still fails with commit `48700fe586ef650d653b908fd80f99a147faae9c `

**Comment by allcode** [comment]
I got the same error and was able to trace the problem back to the MacPorts version of libiconv. MacPorts uses `_libiconv` instead of `_iconv`, resulting in errors.
This can be solved by using the native libiconv in `/usr/lib`.

**Comment by soelu** [comment]
thank you. this resolved my issue.
