### ISSUE TITLE
Plex for Android as remote only detects one of two computers with PMP on the same network.

### ISSUE THREAD

**Issue by ghettorat** [plexinc/plex-media-player#29]
Plex Media player 1.0.0.5.
Windows 10 x64 on both computers.

Previously with PHT on two computers on the same network (and same plex account) it was possible to choose which one to control with the Plex app on android (it would show computer name in the list of which one to connect to). Does not work now.
I installed PMP to 1 machine first. Used Plex android as a remote no problem. Installed PMP on second pc with same Plex account on same network. Not visible on network. Turned off 1st computer restarted PMP on 2nd computer. Still not visible. Turned on 1st computer again and i can connect with Plex android. 2nd computer will not show up in Plex android whatsoever.

**Comment by ghettorat** [comment]
Tested with a third pc with PMP on the same network and not able to use Android as remote on it either. Not detected. Only the 1st PC i installed PMP on will appear in the list of computers I can control. Any additional after that not working. I have not tried different accounts yet but that might be the issue since i am only using the same plex account on all the devices. This was nto a problem with PHT.

**Comment by tru** [comment]
Yeah, we have found a issue that should be corrected in the next version. I will push the changes to the repository during today

**Comment by ghettorat** [comment]
Thank you! Love the new PMP. Good luck with the development :)

**Comment by tru** [comment]
Please reopen if this is still a problem in newer versions.
