### ISSUE TITLE
PMP in a Docker container

### ISSUE THREAD

**Issue by nicjo814** [plexinc/plex-media-player#293]
Hi,

I'm setting up PMP to run inside a Docker container and have stumbled across an issue that I fail to resolve. With all builds of PMP after the 11:th of Mars the UI crashes randomly (either with a completely black screen where a "restart" of PMP is possible, or a complete crash with "Bus error" being displayed in the terminal). This happens as soon as the window is larger than the "default" 1440 height or when I'm trying to run in fullscreen mode. Running PMP in windowed mode at default size works perfect and no crashes occur. For the record I have a "working" version from the 11:th where the UI is only displayed in the top left part of the screen, but still works without crashes when in fullscreen mode. I've attached the debug screen dumps from both the version compiled on the 11:th and a version from yesterday.

I know that Linux is not supported and Docker most probably even less so, but is there any way to enable more verbose logging, get some crash dump or do proper debugging that could help find the issue?  The standard log does not contain any info at all regarding the reason for the crash...

![build 2016-03-11](https://cloud.githubusercontent.com/assets/3428300/14187629/3f359218-f784-11e5-9f42-edce168f54e6.png)
Above is the version form the 11:th with the UI in the top left of the screen.

![build 2016-03-31](https://cloud.githubusercontent.com/assets/3428300/14187634/45666cd4-f784-11e5-880c-054adaef2bc1.png)
Above the version from yesterday.

**Comment by wm4** [comment]
Run in gdb, post "bt" backtrace on a crash.

**Comment by nicjo814** [comment]
I have no debugging symbols for qtwebengine in my current build, which I assume would be needed for the gdb/bt log. Recompiling QT hopefully with debug info now.

**Comment by wm4** [comment]
Depends where it's crashing.

**Comment by nicjo814** [comment]
I had to recompile QT to get any sensible output from gdb, and that took some time on my machine... Here is finally a backtrace from when PMP crashes completely: http://pastebin.com/mNryvDhY All help with this is extremely appreciated. 

Would it make sense to get another backtrace from when PMP "goes black" and not crashes completely?

**Comment by nicjo814** [comment]
Here is how to reproduce my setup.

Requirements:
Linux machine with X window manager and Nvidia proprietary drivers installed (important). I have only tested with Debian 7 and Ubuntu 14.04, but it "should" work on other distros as well.

Setup:

1. Install Docker according to your distro with info available here: [https://docs.docker.com/engine/installation/](https://docs.docker.com/engine/installation/) 
2. Run `xhost +` as the user running the X session
3. Run `touch /tmp/.docker.xauth` as the user running the X session
4. Start the Docker container with `docker run -d --privileged -v /tmp/.X11-unix:/tmp/.X11-unix:rw -v /tmp/.docker.xauth:/tmp/.docker.xauth:rw --name=pmp nicjo814/docker-plexmediaplayer:ppa`  
This will download the Docker Image and start up a new container.Please note that the size of the image is > 1GB and it will be by default be placed in /var
5. Tail the Docker logs with `docker logs -f pmp` and wait for the Nvidia driver to be installed
6. Enter the running container with `docker exec -it pmp bash`
7. For debugging symbols: Inside the container run `apt-get install plexmediaplayer-dbg qt56webengine-dbg`

Start PMP with `plexmediaplayer`. Note that the container will update PMP to the latest available build in my PPA on every restart.

**Comment by nicjo814** [comment]
Finally found the issue as to why the display went black. The Qt WebEngine/Chromium crashed due to insufficient space available in /dev/shm. A remount with more space allocated fixed the problem.
