### ISSUE TITLE
External subtitle codepage setting

### ISSUE THREAD

**Issue by trustin** [plexinc/plex-media-player#295]
It seems like PMP does not detect the codepage/charset of an external subtitle file (e.g. .SMI) correctly, resulting in corrupted subtitles.

It would be great if there's a way to specify the list of preferred charsets of external subtitle files. I worked around by applying this simple patch that sets `sub-codepage` option for MPV:

``` diff
diff --git a/src/player/PlayerComponent.cpp b/src/player/PlayerComponent.cpp
index 4d26eb1..7ee5b8f 100644
--- a/src/player/PlayerComponent.cpp
+++ b/src/player/PlayerComponent.cpp
@@ -803,6 +803,8 @@ void PlayerComponent::updateSubtitleSettings()
     mpv::qt::set_option_variant(m_mpv, "sub-text-align-x", subpos[0]);
     mpv::qt::set_option_variant(m_mpv, "sub-text-align-y", subpos[1]);
   }
+
+  mpv::qt::set_option_variant(m_mpv, "sub-codepage", "utf8:cp949");
 }

 ///////////////////////////////////////////////////////////////////////////////////////////////////
```

**Comment by trustin** [comment]
Note that some of my external subtitle files are encoded in UTF-8 while the others are in CP949 (or EUC-KR), which is a pretty common case for CJK .smi files when you have a large collection.

**Comment by wm4** [comment]
Does creating a `mpv.conf` in the PMP config dir (same as `plexmediaplayer.conf`) and adding ``sub-codepage=utf8:cp949`` not work?

If you're compiling libmpv yourself, you can also try compiling it with libuchardet (https://github.com/BYVoid/uchardet) which should be relatively ok at detection the codepage.

**Comment by trustin** [comment]
@wm4 Ah, I didn't know that trick. Is it documented somewhere? Will try and let you know!

**Comment by atrus05** [comment]
@trustin https://mpv.io/manual/master/
Search for "codepage" and you will be taken to the correct part.
