### ISSUE TITLE
Incorrect build instruction for Linux in README.md

### ISSUE THREAD

**Issue by trustin** [plexinc/plex-media-player#296]
The current build instruction says:

```
-DMPV_LIBRARY=/usr/local/lib/libmpv.so.1
```

but I couldn't get it work with that option. I had to use:

```
-DMPV_LIBRARY_mpv=/usr/local/lib/libmpv.so.1
```

Also, in my distribution (Debian), the name of the ninja executable is not `ninja-build` but just `ninja`.

**Comment by trustin** [comment]
CMake version: 3.5.1

ninja-build version:
```
$ dpkg -l | grep ninja
ii  ninja-build                          1.3.4-1.2                         amd64        small build system closest in spirit to Make
```

**Comment by wm4** [comment]
On a side note: normally, you shouldn't even need to set this explicitly, and it should be autodetected. (In theory - cmake's pkg-config support is bad, so in some situation it's needed anyway.)

**Comment by LongChair** [comment]
this should be fixed afaik.
