### ISSUE TITLE
Server removed from user's list, still appears as unavailable server

### ISSUE THREAD

**Issue by pooploser** [plexinc/plex-media-player#297]
I have a server that I removed from my account, while adding a new one.
The new one appears fine. I was expecting the old one to disappear since it's been deleted, but it's still around in the drop-down server list.

**Comment by pooploser** [comment]
This still occurs and looks like this:

<img width="409" alt="screen shot 2016-04-26 at 10 51 14" src="https://cloud.githubusercontent.com/assets/471026/14812280/d074eb58-0b9c-11e6-904f-3761e743a40e.png">

**Comment by dakth** [comment]
I'm also experiencing this problem. Nobody knows what's going on?

**Comment by LongChair** [comment]
this should be fixed by now closing.
