### ISSUE TITLE
Improve scrolling performance when using remote controllers.

### ISSUE THREAD

**Issue by BobWatson** [plexinc/plex-media-player#30]
As per title - using Candelair, pressing and holding, say, 'left' selects the item immediately to the left and stops. I'd expect the same behaviour as PHT - press and hold scrolls through all items.

**Comment by tru** [comment]
Yes agreed that we should improve scrolling performance with remote input. I will rename this so it more explains the problem.

**Comment by LongChair** [comment]
i think this is good enough now, closing.
