### ISSUE TITLE
Clicking "More" underneath "Extras" lead to empty screen

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#300]
Clicking "More" underneath "Extras" lead to empty screen. Meaning that the top part of the interface is there, but no results. Even though there should be results there as I can see 3 extras on the previous page (where I clicked "More").

PMP log: https://gist.github.com/atrus05/b204f091b72fb1d0344ffc68b958523e
PMP version: https://gist.github.com/atrus05/b204f091b72fb1d0344ffc68b958523e
OS: OSX 10.11
PMS: Latest nightly (0.9.16.4.something)
PMS OS: Ubuntu

PS: The latest iOS beta app that I use shows all the extras, so this is likely a PMP issue.

**Comment by dogonwheels** [comment]
Fixed in latest UI code - should land in next release, I'd hope. - https://github.com/plexinc/plex-web-client/issues/4372.
