### ISSUE TITLE
Plex is not reachable, not getting IP from DHCP on RaspberryPi 2

### ISSUE THREAD

**Issue by CubedRoot** [plexinc/plex-media-player#308]
I am running the latest download from plex.tv for embedded, downloaded via the Plex.tv website.

Versions:
Plex: 2.5.8
Plex Media Player: 1.0.6
OpenELEC: 6.0

I copied the imaged downloaded from plex.tv to a 2gig card and it boots up. I see the plex logo, and then get the pop-up about "Plex Not Reachable".

I can use my mouse to get to the setting, but the only options are for setting my Plex server IP. I can't configure any network at all. This machine is behind a pfSense firewall that is running my DHCP. I am using ethernet for my networking and I have verified this setup works by running any of the other RPi2 distros without any problems.

When I go through my pfSense logs, I do not even see where the Plex Media Player is trying to reach out to get an IP address. Since I can't get an IP, natrually I cant sign in, and I can't even SSH in to troubleshoot.

Oddly enough, if I grab the exact version of OpenELEC and put it on the same card, the machine will boot, and get an IP address without any issues.  So it would appear that this is only happening on PMP.

**Comment by LongChair** [comment]
Are you using Wired ethernet or Wifi USB key ?

**Comment by CubedRoot** [comment]
I am using wired ethernet.  I have verified the port, cable and entire path from the switch gear to pfSense are good with several other devices using the same cable and port.  I can drop OpenELEC on the Pi2 and boot it and it gets IP.  I have tried writing the Plex MP image to the card several times, redownloading it, and still have same results.

**Comment by LongChair** [comment]
Could you try bringing down the firewall for a test, just to make sure it's not involved ?

**Comment by CubedRoot** [comment]
Well, its a pfSense machine so I can't do that.  To be fair, the firewall rules I am using are only applicable to my WAN connection, and not anything LAN facing.   This same pfSense machine serves as my DHCP server.

When I tail the DHCP daemon logs on the server, I never seen the MAC from the RaspberryPi even try to request an IP address.  I can look at the switch (Cisco 3560) that the Pi2 is plugged into, and I can see the MAC has activated the interface on the switch, so PMP is enabling the NIC. 

Any suggestions on how I could monitor the packets flowing to/from the Pi2 to inspect it for DHCPDISCOVER packets?

Or, is there anyway I can set the IP to be static on Plex Media Player so I can rule out issues with DHCP?

**Comment by LongChair** [comment]
I have no idea for the DHCP discover packets. Static Ip configuration would have to be made with connman commandline.
