### ISSUE TITLE
Pick surround track if 5.1 / 7.1 is configured in settings.

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-media-player#309]
A lot of my media is .mp4 H.264 with a AAC track as track 1 (for mobile devices), DTS / AC3 5.1 as track 2. When playing these files, the AAC track is always played first. Can get logs but not sure they are necessary here? Plex Media Player should pick the 5.1 track for default based on the settings configuration. 

OpenPHT seems to do this correctly.

**Comment by danjames92** [comment]
Any edit I can make to force this behaviour?

**Comment by danjames92** [comment]
Or a way to enable the # command to change audio tracks in PMP that mpv provides?

**Comment by wm4** [comment]
Well, in theory you could invoke the mpv command (`cycle audio`) and bypass the web UI.

But implementing "proper" control of this would require further UI work.

**Comment by danjames92** [comment]
Are you saying it should work already with the # key or I would somehow have to pass the command to mpv correctly? # does not currently work.

Think it's a bit beyond me as I'm not a programmer / power user.

**Comment by wm4** [comment]
No, mpv's keyboard input handling is completely locked out.

Actually, I just realized we've implemented changing audio tracks via key binding a while ago. IT's mapped to the `A` key by default.

**Comment by danjames92** [comment]
Ah ok that's great. I never noticed that, I will test it out later. 

Still, the default behaviour should change and provide the surround track first or have a GUI to toggle it off / on. Would be super useful and save an extra step.

**Comment by LongChair** [comment]
@danjames92 : can we close this one or do you consider this still relevant ?

**Comment by LongChair** [comment]
@danjames92 : closing this due to the lack of feedback, free free to reopen if needed.
