### ISSUE TITLE
main.cpp Unhandled FatalException: Failed to parse application engine script. 

### ISSUE THREAD

**Issue by ProfessorKaos64** [plexinc/plex-media-player#311]
PlexMediaPlayer builds successfully, seen in the build log, but there are a load of errors in the PMP log. Perhaps building the pre-requisite build deps was not enough, or there are missing links on the binary.

* [Build Log](http://sprunge.us/eTJY)
* [PlexMediaPlayer log](http://sprunge.us/gWaY)
* [output of ldd on binary](http://sprunge.us/GWgd)

**Comment by tru** [comment]
The log says that your qt install misses QtWebEngine

**Comment by ProfessorKaos64** [comment]
I have [built](http://packages.libregeek.org/SteamOS-Tools/package_lists/brewmaster_testing_main.txt) qtwebeinge, mimicking the exact install set Fedora/OpenSUSE used. Not sure why it's  not being picked up, as I thought it was required to build PlexMediaPlayer in the first place? I'll have to recheck then the install setup I have I guess.

**Comment by ProfessorKaos64** [comment]
These are the qml* modules, not just webengine/webchannel/qtquick. I'll check out building those and see how I make out.

**Comment by ProfessorKaos64** [comment]
Closer:http://sprunge.us/ZWAT

Current [control file](https://github.com/ProfessorKaos64/LibreGeek-Packaging/blob/brewmaster/plexmediaplayer/debian/control) for runtime deps.

**Comment by LongChair** [comment]
Looks to me that your qt5 install is not complete according to the last lines of your log

**Comment by ProfessorKaos64** [comment]
I don't know about that, [this](https://codereview.qt-project.org/#/c/149874/) is the associated Qt bug. Still checking out why icudtl.dat is not installed or why I need that. Seems qtwebengine related, if that is what you meant.

**Comment by LongChair** [comment]
Once webengine is built you should have a qt/ressources dir in your installation dir since qt 5.6 in which the icu files are deployed.

You would need first to fix this :)

**Comment by ProfessorKaos64** [comment]
Rebuilt libqtwebengine with --system-ice=0, so that /usr/share/qt5/resources/icuedtl.dat is present, ut now a [segfault](http://sprunge.us/PIeR) grr..

**Comment by ProfessorKaos64** [comment]
Moved to #406
