### ISSUE TITLE
"Check for Update" does not see changes in "Update Channel" until a restart of PMP

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#312]
I had update channel set to stable (as there were too big of a bug in 1.1.0 earlier). Now when I knew build 272 was built I changed from Stable to Ninja and hit the "Check for update" button. It reported that there was no update to be downloaded.

However, after a restart of PMP the "Check for Update" seemed to check the correct Update channel.
So I suspect the "Check for updates" does not understand that I have switched update channel until I restart PMP.

**Comment by atrus05** [comment]
Here are the two logs. .4 should be the one where I switched channel and Check for Update still did not work. And .3 should be the one from after the restart.
[logs.zip](https://github.com/plexinc/plex-media-player/files/218791/logs.zip)

**Comment by firasdib** [comment]
Fixed https://github.com/plexinc/plex-web-client/pull/4610
