### ISSUE TITLE
Update web-client when nav-sounds preference and cleanup is merged

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#316]

**Comment by firasdib** [comment]
@Flamefork Status on the nav sounds 😄 ?

**Comment by Flamefork** [comment]
👀 by @kayone -> 🍆 -> :shipit:

**Comment by wm4** [comment]
Ping on status?

**Comment by kayone** [comment]
There are some minor changes regarding how we access the sound file in Konvergo that _might_ need to be made, @Flamefork is taking some time off, so it might take a bit of time before it's merged in. 

https://github.com/plexinc/plex-web-client/pull/4559#discussion_r60094412

**Comment by Flamefork** [comment]
Integrated the PR on the web side.
