### ISSUE TITLE
Navigation to pre-play is slower in 1.0.6 and 1.1 compared to 1.0.5

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#317]
Many reports about this in the forum. Matt is looking into this today, @firasdib will be responsible to merge it into our release.

**Comment by firasdib** [comment]
@mseeley any info for me?

**Comment by mseeley** [comment]
Nope nothing here. I compared navigation from dashboard-to-pre-play and browse-to-preplay on the following builds and noticed no difference.

* `PlexMediaPlayer-1.1.0.283-de5eaaa4-macosx-x86_64`
* `PlexMediaPlayer-1.0.5.210-9c69e092-macosx-x86_64`
* `PlexMediaPlayer-1.0.0.5-53192cb0-macosx-x86_64`
  * This build fades out the current view (ex dashboard to preplay). The newer builds did not.

**Comment by LongChair** [comment]
@mseeley : i assume we can close this now ?
