### ISSUE TITLE
Too-sparse UI

### ISSUE THREAD

**Issue by BobWatson** [plexinc/plex-media-player#32]
The UI in PMP is very sparse, at odds fulfilling it's role as a home theatre application (i.e. for use managing a library on a large screen) - there are fewer items on display than on an iPhone or iPad (and way fewer than in PHT), and there is a lot of wasted space between items. A large library is a real chore to browse when there is large imagery against each item.

Increasing information density and allowing more textual options would make browsing through large lists much easier and far faster.

**Comment by tru** [comment]
Thanks, this sounds like a feature request. We try to keep the issue tracker to technical bugs. Please direct those to the forum, there are a lot of discussions on how to improve the UI.
