### ISSUE TITLE
Completion clock remains static while playback is paused

### ISSUE THREAD

**Issue by Mediaconoclast** [plexinc/plex-media-player#321]
Below the OSD timeline, the clock reporting the estimated time of completion remains static while playback is paused (while the clock displaying the current time [top-right] updates to the correct TOD). For example, if you pause a video with 10 minutes when only five minutes remain, the completion-clock indicates you will finish watching it five minutes ago.

Perhaps it is not a clock but rather just a one-time grab when the OSD is first rendered...

Here's an example:
![static-clock-1](https://cloud.githubusercontent.com/assets/5336537/14616685/6a870124-0579-11e6-8616-f992301ca4f4.png)

**Comment by wm4** [comment]
(Tentatively assigning.)

**Comment by atrus05** [comment]
Saw the same thing today. Reproduced!
