### ISSUE TITLE
Implement fast forwarding and rewind

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#323]
While we have some of this functionality internally (like essentially seeking to the next/previous keyframe, or playing at faster speed), this has to be "PHT style" enough within user expectations.

Will probably take a look at this in a while or so.

**Comment by LongChair** [comment]
@markus101 : maybe we could have a link the the web issue for this here ? :)

**Comment by markus101** [comment]
Depending how the hotkeys are handled there may not be a web issue required. If the host intercepts the hotkeys that are used for fast forward/rewind and acts on them the web app doesn't need to do anything, if they're passed to the web app, we could call something on the host to handle it. I don't think there will be fast forward/rewind buttons in the OSD of the player.

**Comment by mseeley** [comment]
Closing out this nice to have enhancement.
