### ISSUE TITLE
Look into MVC/3D support on RPI

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#324]
Some 3D movies are encoded using MVC, a h264 extension that currently no open source decoder supports. Consequently we can't support it on all platforms.

However, the RPI's hardware decoder can, and it'd probably be relatively easy to make use of it. There have been requests on the forums to add support.

This would probably include signaling 3D over HDMI.

Main issues:
- lack of time
- lack of ways to test it (no damn 3D TV here)
- MVC sample files (that one is easy to fix)

**Comment by wm4** [comment]
One of the forum threads: https://forums.plex.tv/discussion/206046/plex-rpi2-3d-mvc-mkv-playback

**Comment by danjames92** [comment]
Sorry just curious, if there's no open source decoder, how come Kodi managed to implement it in their Windows test releases?

**Comment by wm4** [comment]
> how come Kodi managed to implement it in their Windows test releases?

I don't know? Maybe they're doing something similar to lavfilters and use Intel MediaSDK or a similar wrapper-like thing to decode it.

**Comment by wm4** [comment]
Also, just to make it clear: MVC is a h264 extension not supported by FFmpeg, while 3D can in general be achieved through other means (like simply dividing the video frame in 2 halves). The latter could be provided by PMP on all platforms.

**Comment by danjames92** [comment]
Is platform feature parity something Plex is aiming for with PMP? If a Windows hack can make 3D MVC full resolution work, would Plex implement that?

**Comment by wm4** [comment]
Nothing wrong with fully using a platform's capability, but doing something that does not work on all platforms also feels less attractive because all the effort would fix at most 1/3 of the whole problem.

**Comment by danjames92** [comment]
That didn't really answer my questions.

**Comment by wm4** [comment]
It answers the first question.

> If a Windows hack can make 3D MVC full resolution work, would Plex implement that?

Maybe. But I'm fairly sure we won't bother with using libmfx (which is the method lavfsplitter uses).

**Comment by LongChair** [comment]
Closing this issue as it's not been a very demanded feature and pretty old GHI.

**Comment by danjames92** [comment]
Very disappointing.

**Comment by LongChair** [comment]
@danjames92 : this is more an mpv bound feature anyways.
Should mpv support this feature on RPI, PMP could most likely use it.
If you want to voice that feature, then i would recommend you can ask it in the MPV issues repository https://github.com/mpv-player/mpv/issues
