### ISSUE TITLE
HW decoding does not work with CoDec versions

### ISSUE THREAD

**Issue by Mediaconoclast** [plexinc/plex-media-player#325]
1.1.0.276-aca4c847-windows-x64 provides HW acceleration.
1.1.0.275-50240074-windows-x64 does not.

It seems like the second is CoDec version, whereas the first is not. I have seen the same issue with all of the recent CoDec builds. Included are logs from both versions above playing the same file (x264 video with AC3 audio).

**Comment by wm4** [comment]
I can confirm this, but I'm not really sure why it happened. Maybe a build glitch.

**Comment by wm4** [comment]
Found it. It was very stupid, and it was my fault. Will be fixed in the next build.
