### ISSUE TITLE
1.1.0.288-470a750d: List View doesn't scroll

### ISSUE THREAD

**Issue by boots2x** [plexinc/plex-media-player#328]
OSX, Apple Remote, select List View and press [down] on the Apple Remote. The focus shifts down one item only, to advance further you must repeatedly click [down]. Expected behaviour would be as in other views, holding [down] would cause the list to scroll up or down depending on the button pressed.

**Comment by LongChair** [comment]
supposedly fixed now. Feel free to reopen if not.
