### ISSUE TITLE
API navigation methods does not work

### ISSUE THREAD

**Issue by Petter-W** [plexinc/plex-media-player#329]
Hi,

I can't seem to get the [API navigation commands](https://github.com/plexinc/plex-media-player/wiki/Remote-control-API#existing-commands) to work. They work fine on Plex Home Theater. I get a 406 error when I try to get commands like _http://[IP]:[PORT]/player/navigation/moveRight_. What am I doing wrong?

**Comment by LongChair** [comment]
This is getting pretty old, i suppose we can close this for cleanup.
Feel free to repon if you still have question.

**Comment by jitterjames** [comment]
Not sure why you are closing this since it is still an issue that has not been fixed.
