### ISSUE TITLE
Only stereo sound and crackling noise

### ISSUE THREAD

**Issue by tiberian83** [plexinc/plex-media-player#33]
I only get stereo sound output on PMP. PHT works great though. Also the audio has some crackling noises. It Looks like there is some quality problem with the downsampling. I used to have the same crackling sound issue with the old Plex Media Center when I Chose "audio boost" but with PMP I didn't choose anything like that. When I activate "Normalize Downmixed Volume" the crackling noise seems to be gone but then the audio volume is way too low.

I linked some log files here:
http://forums.plex.tv/discussion/188479/pmp-how-to-adjust-display-refresh-rate-to-match-video#latest
http://forums.plex.tv/discussion/188466/pmp-audio-decoding-vs-passthrough#latest

**Comment by tru** [comment]
@wm4 anything we can do to move this forward? is it still an issue?

**Comment by wm4** [comment]
On the RPI, it might have been because the audio volume was set to over 100% by default, which of course can result in clipping easily.

On other platforms, I simply don't believe PMP behaves different from other players which use this method of downmix, bit I'll gladly take objective proof.

**Comment by tru** [comment]
@tiberian83 please re-open this ticket if you still have problems with this in the recent versions and can give use some more information about it.
