### ISSUE TITLE
Blurry PNG image posters due to Pixel Shift

### ISSUE THREAD

**Issue by ShadyCrab** [plexinc/plex-media-player#332]
For some reason, every alternating column on the PMP GUI that uses PNG images has a 1pixel shift to the right, which heavily blur's the PNG image. This happens everywhere, whether its a Season selection screen, the 'All Series' view or the home page.

![screenshot 19](https://cloud.githubusercontent.com/assets/849166/14976668/febd36fa-1150-11e6-9c3b-374dbb70908c.png)
![screenshot 18](https://cloud.githubusercontent.com/assets/849166/14976667/febb8c1a-1150-11e6-8843-8d6a81d23e5d.png)

From these, you can see that the posters are blurred when they are in one column, and unblurred when shifted to an alternate column. Here's a close-up of the posters

Blurred, from first screenshot
![png blured](https://cloud.githubusercontent.com/assets/849166/14976643/cc3b3cd6-1150-11e6-86c1-a446e3348f68.png)
Unblurred from second screenshot due to different column
![png unblured](https://cloud.githubusercontent.com/assets/849166/14976646/cc90b184-1150-11e6-97ab-49454bd8a18f.png)

Here's the same issue on the Home Page. Notice the one with the two Re:Zero (purple) images on the same page, one is blurrier than the other (less prominent than the smaller poster view, downscaling could be a factor)
![screenshot 21](https://cloud.githubusercontent.com/assets/849166/14976723/871b37cc-1151-11e6-83c8-fa96d02fd865.png)
![screenshot 20](https://cloud.githubusercontent.com/assets/849166/14976724/877136ae-1151-11e6-9009-275485057d8d.png)

It might seem hard to notice, but when your browsing through the 'All Series/Shows' page and looking through the posters, you notice the blur.

Every posters are a PNG image added manually through Plex Web. This happens whether its a standard 1000x680 image or a slightly wider/taller image aspect-ratio wise.

PMP 1.1.0 (been an issue since it was first released)
Windows 10 64bit
Nvidia GTX 960, newest driver
i5 4590

**Comment by mseeley** [comment]
Nicely dissected. Beautiful artwork too, looks really kick-ass. We're working on some updated screens, I'll keep an eye out for the issue.

**Comment by LongChair** [comment]
Closing due to the lack of feedback.
Feel free to reopen with more details if needed.
