### ISSUE TITLE
Build error on Linux and possible solution

### ISSUE THREAD

**Issue by KittyKatt** [plexinc/plex-media-player#334]
So, to start off, I'm by no means a programmer or that familiar with C/C++. I'm familiar enough with build environment and building however, so I went to setup building PMP.

My system is an Arch Linux system, fully updated. Using [testing], [multilib], [multilib-testing], and [community-testing]. In Arch Linux at the moment, both a compatible mpv and Qt5.6 are installable packages, so I'm using the stuff from the repo instead of building them myself.

These packages included `qt5-base, qt5-webengine, qt5-webchannel, and mpv`. I think that should pull in all required Qt and mpv depends and libs. On Arch, QTROOT is /usr/lib/qt.

Now, the error occurred when I ran ninja (which is just ninja, not ninja-build, on Arch). I ran into a problem at DisplayComponent.cpp. The exact error was:

`[37/86] Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayComponent.cpp.o
FAILED: src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayComponent.cpp.o 
/usr/bin/c++   -DHAVE_CEC -DHAVE_LIRC -DHAVE_SDL -DPREFIX=\"/home/kittykatt/Projects/plex-media-player/build/output\" -DQS_LOG_LINE_NUMBERS -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_WEBCHANNEL_LIB -DQT_WEBENGINECORE_LIB -DQT_WEBENGINE_LIB -DQT_WIDGETS_LIB -DQT_XML_LIB -DUSE_X11POWER -DUSE_X11XRANDR -Isrc -I../src -I/usr/lib/qt/include -isystem /usr/include/qt -isystem /usr/include/qt/QtCore -isystem /usr/lib/qt/mkspecs/linux-g++ -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtWebChannel -isystem /usr/include/qt/QtQml -isystem /usr/include/qt/QtQuick -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtWebEngine -isystem /usr/include/qt/QtWebEngineCore -isystem /usr/include/qt/QtPositioning -isystem /usr/include/qt/QtWidgets -I/usr/include/mpv -I/usr/include/SDL2 -I../X11_X11_INCLUDE_PATH -I../X11_Xrandr_INCLUDE_PATH -I../external/qhttp/src -I../external/qslog -I../external/SPMediaKeyTap -I../external/HIDRemote -I../external/plistparser -I../src/player -I../src/core -I../src/shared -Wall -fno-omit-frame-pointer  -g -fPIE   -fPIC -std=gnu++14 -MMD -MT src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayComponent.cpp.o -MF src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayComponent.cpp.o.d -o src/CMakeFiles/PlexMediaPlayer.dir/display/DisplayComponent.cpp.o -c ../src/display/DisplayComponent.cpp
../src/display/DisplayComponent.cpp: In function ‘float modeDistance(const DMVideoMode&, const DMVideoMode&)’:
../src/display/DisplayComponent.cpp:320:52: error: ‘fabs’ was not declared in this scope
     return fabs(m1.m_refreshRate - m2.m_refreshRate);
`

I had no idea what fabs was, but the function kinda looked like a math function, so I went looking to see why that would not be in scope and a possible solution was that maybe math.h or cmath was not included. So I did what you'll probably think of as a dummy move and put `#include <cmath>` into 

`/home/kittykatt/Projects/plex-media-player/src/display/DisplayComponent.cpp
/home/kittykatt/Projects/plex-media-player/src/display/DisplayComponent.h
`

at the top near the includes. PMP actually manged to build just fine after that with a few warnings. Almost smooth enough that I'd consider making an AUR package for it. And, for the final test....boom! It starts and runs. Logged in watching my stuff. If you need any more information from me, please let me know.

**Comment by KittyKatt** [comment]
So, I just made an Arch Linux PKGBUILD package for this with a custom patch file for this issue, except I only patched `DisplayComponent.cpp`, so I'm guessing that's where it needs to be. Will be fiddling more with the PKGBUILD before I post it anywhere.

**Comment by wm4** [comment]
There's already a fix for this in the release branch: https://github.com/plexinc/plex-media-player/commit/8d2c4bc6b571479ac43c3f7f9e99101d84c228cd
Sorry for the inconvenience - we'll probably update master later.

**Comment by wm4** [comment]
Pushed to master.

**Comment by KittyKatt** [comment]
Oh! Shucks. Thanks. My bad. Well, I'm glad I was right, though. haha
