### ISSUE TITLE
Wait for network to start

### ISSUE THREAD

**Issue by ptr727** [plexinc/plex-media-player#335]
PMP embedded, UI starts before network is ready.
Add option to wait for network, just like in openELEC.

**Comment by ziggimon** [comment]
The issues on github are for development and bugs not feature requests. Can you move the request over to forums thanks.

**Comment by ptr727** [comment]
I appreciate the distinction, but why is this not a bug?

The bug is the client is broken on boot because the network starts after the client.
A proposed feature would be to add a configurable option in settings.
