### ISSUE TITLE
No audio after wake from suspend

### ISSUE THREAD

**Issue by mjrealm** [plexinc/plex-media-player#337]
Asus Chromebox w/ Embedded x86_64 PMP and FLIRC
version 1.1.1.329-cc2cc067 

I mapped **host:suspend** function to a button in my Harmony smart control remote w/ FLIRC. That button is then used as part of Plex "Activity" power on/off. When I **switch activity**, it suspends PMP. But upon wake, the audio doesn't work on media playback. When the mapped remote button is used to suspend/wake PMP again, it brings back the audio (note: not the activity switch button). Suspend via GUI have no problems too.

Attached the log files.

[logs.zip](https://github.com/plexinc/plex-media-player/files/256613/logs.zip)

**Comment by wm4** [comment]
There are two playback attempts in your log, and both appear to initialize audio successful, so I can't say more about this. Are you using a receiver?

**Comment by mjrealm** [comment]
Yes, I'm using a receiver and the box is connected via HDMI. My PMP settings use HDMI #0 as audio output..

**Comment by mjrealm** [comment]
Apparrently, this is a know Chromebox handshake issue. Had to change the powering order. No problem now.

**Comment by wm4** [comment]
Yeah, HDMI tends to cause such issues.
