### ISSUE TITLE
Inability to scroll lyrics

### ISSUE THREAD

**Issue by pooploser** [plexinc/plex-media-player#338]
Recent releases of PMP added lyrics views. Most lyrics are longer than a single screen height, so manual scrolling would be necessary for those albums that don't feature lyric timestamps. Right now, arrows up/down throw you out of the lyrics view.

**Comment by atrus05** [comment]
Tracked internally here: https://github.com/plexinc/plex-web-client/issues/4280

Devs to decide the fate of this ticket.

**Comment by mseeley** [comment]
No plans to address in v1. v2 will bring us manual/automatic scrolling text.
