### ISSUE TITLE
Debug overlay doesn't use the "safe overscan zone"

### ISSUE THREAD

**Issue by benadderson** [plexinc/plex-media-player#34]
See the discussion in this thread: http://forums.plex.tv/discussion/188760/potential-bug-debug-overlay-clipped-off-screen-on-pi-2

For me (embedded on Pi2) the debug overlay renders partly off-screen as a result.

**Comment by wm4** [comment]
It should be a pretty easy change, but I'm not sure how large the margin should be. Any suggestions?

**Comment by tru** [comment]
I think that the web app already is using a standard margin. @dogonwheels do you know what margin is used to inset the content?

**Comment by atrus05** [comment]
Remember to wrap long paths as well. For example the path to the file. It simply goes out of the screen now.

**Comment by wm4** [comment]
>Remember to wrap long paths as well. For example the path to the file. It simply goes out of the screen now.

I don't know. It might move the text below it out of the screen on the bottom. The URL isn't that useful anyway. At least you still see if it's a transcode or directplay endpoint; good enough IMHO.

**Comment by dogonwheels** [comment]
Overscan compensation/safe areas vary, but the Smart TV Alliance states 1216x666, which we try and stick to. Consoles are a bit different, going down to 1088x612.
