### ISSUE TITLE
PMP crash when using newest QT5.6 rpms for Fedora 23

### ISSUE THREAD

**Issue by truckershitch** [plexinc/plex-media-player#340]
I did an update and things went awry.  The older version worked fine.  Unfortunately, I can't seem to source the old QT 5.6 rpms.

This goes away when I use the QT5.6 beta that I compiled myself.  Log from terminal is here:
http://pastebin.com/SsJntdGc

I'll do a more proper backtrace if that is what you need.  I have not done one of those in a while so I would need a little assistance.

One more thing -- this is failing on my main HTPC but seems to work find in a F23 VM in virtualbox.

Thanks!

**Comment by wm4** [comment]
This backtrace has no debug symbols and is not enough to tell what's going wrong.

Seems to crash deep within Qt, though.

**Comment by truckershitch** [comment]
I remembered how to add the debug symbols and ran a backtrace with gdb.  Hopefully this will shed some light on the issue.

http://pastebin.com/uh7KGgAU

**Comment by wm4** [comment]
I'm going to chalk it up on a broken build or a bad compiler. Does the same happen if you try a QtWebengine demo/example program?

**Comment by truckershitch** [comment]
I'm not sure how to compile a QtWebEngine demo/example program easily.  I'll see if I can figure out what rpms I need to install to get the SDK or whatever is required.

I regularly compile PMP from git in a F23 VM in virtualbox, and then transfer it to my HTPC.  Both machines are updated every day.  I didn't see this problem until recently with the Qt 5.6.0 rpms.  I was using the Qt 5.6.0 beta, and then I installed the recently released Fedora rpms with success.  There was a slight version update to the rpms and then I noticed the problem.  What bothers me is that PMP will run with the Qt rpms on the VM just perfectly!

I tried the Fedora PMP rpm posted on the forum with yet another crash.  It doesn't seem to just be my compiler.

Should I be worried about bad memory/CPU, or might there just be some conflict on my HTPC that doesn't exist on the VM?  I am running nVidia drivers on the HTPC, and I saw some of those files mentioned in the backtrace.  Tomorrow, I'm going to install a fresh F23 to a new partition and play around a little bit, but I have the feeling that I'll hit a wall again.

**Comment by wm4** [comment]
There's a "quicknanobrowser" in the Qt source tree (qtwebengine/examples/webengine/quicknanobrowser/). Not sure if/where this is compiled.

> Should I be worried about bad memory/CPU

I wouldn't yet...

> or might there just be some conflict on my HTPC that doesn't exist on the VM?

Some sort of ABI mismatch could be possible, I guess.

**Comment by truckershitch** [comment]
Ok, there is an rpm just for webengine examples.  The executable was already compiled. Then I had to install quickcontrols to run the quicknanobrowser.

I got a similar crash.  I did not install all the debug symbols.  Output is here: http://pastebin.com/wMicVRHb  I know it doesn't really help -- it's just to illustrate.  I'll do that later if you need me to.

The browser runs fine in the VM.

I did a `dnf reinstall qt5*` yesterday just in case, but that didn't do the trick.

Thanks for the help!

**Comment by wm4** [comment]
Well, then I'm closing this, because it's definitely not our bug. I suggest you report this to Fedora, and if they can't help, Qt itself.

**Comment by truckershitch** [comment]
This seems to be a Fedora bug having to do with the chromium source code used in qtwebengine.  I used a patch on the source rpm and rebuilt it with success.

Here is the bug report if anyone is interested: https://bugzilla.redhat.com/show_bug.cgi?id=1337585

**Comment by wm4** [comment]
Alright, thanks for getting this tracked down.
