### ISSUE TITLE
plex media player doesn't show audio devices if they come online after starting plex

### ISSUE THREAD

**Issue by ismay** [plexinc/plex-media-player#343]
I have a usb dac connected to my htpc, which acts as an external sound card. The dac is selected as my default audio device in windows 10, and windows 10 switches audio output to it as soon as I turn it on.

However, if plex media player was started before my dac, it doesn't add the dac to the list of available audio devices. It took a lot of fiddling before I realised that this was the problem.

So the problem as I see it is twofold:
1. plex media player doesn't show audio devices if they come online after starting plex
2. there is no way to set plex media player to just output to the default sound device (which would solve this problem, as windows sets my dac as the default audio device as soon as I turn it on)

I think option 2 is an important feature to have, as it defers to the OS for the selection of the audio device, which seems like a sensible default setting for audio to me.

**Comment by wm4** [comment]
>plex media player doesn't show audio devices if they come online after starting plex

Well, we should have this. But obviously it doesn't work for some reason. Please post a PMP log while plugging in/out audio devices so we can debug this.

>there is no way to set plex media player to just output to the default sound device (which would solve this problem, as windows sets my dac as the default audio device as soon as I turn it on)

"Autoselect device" does use the default device. Maybe try disabling exclusive audio as well.

**Comment by ismay** [comment]
> Please post a PMP log while plugging in/out audio devices so we can debug this.

Allright, I will post it asap.

> "Autoselect device" does use the default device. Maybe try disabling exclusive audio as well.

Cool, I'll try that. Will post back with the results.

**Comment by ismay** [comment]
Haven't been able to reproduce this. Currently the device works, even when I turn it on after turning on pmp.

**Comment by bengaiser** [comment]
Have you tried making sure PMP helper isn't running before starting your test as well?  Not sure if this will matter, but it does stay running for a few minutes after PMP exits.

**Comment by LongChair** [comment]
Closing this as it doesn't seem reproducible now.
