### ISSUE TITLE
1.1.1 crashes whenever USB-CEC adapter is connected

### ISSUE THREAD

**Issue by martenjacobs** [plexinc/plex-media-player#346]
I decided to try PMP on my Intel NUC DN2820FYK. This works fine, but whenever I connect my PulseEight USB-CEC adapter, it crashes and refuses to start up again. The screen just stays blank. When I unplug my adapter, it starts up just fine. I'm using the embedded version of PMP downloaded from the Plex website. I have been using OpenELEC-based Plex Home Theater distributions before with this CEC-adapter, as well as some of the earliest public versions of PMP without incident.
Full content of plexmediaplayer.log:

> 2016-05-24 17:31:47 [ INFO  ] Log.cpp @ 115 - Starting Plex Media Player version: 1.1.1.329-cc2cc067 build date: 2016-05-03 
> 2016-05-24 17:31:47 [ INFO  ] Log.cpp @ 116 -   Running on: PlexMediaPlayer (official) - Version: 1.1.1 [4.1.18] arch x86_64 
> 2016-05-24 17:31:47 [ INFO  ] Log.cpp @ 117 -   Qt Version: 5.6.0 [x86_64-little_endian-lp64] 
> 2016-05-24 17:31:47 [ INFO  ] ComponentManager.cpp @ 41 - Component: settings inited 
> 2016-05-24 17:31:47 [ DEBUG ] HTTPServer.cpp @ 32 - Listening to port: 32433 
> 2016-05-24 17:31:47 [ INFO  ] InputMapping.cpp @ 113 - Loading inputmaps from: ":/inputmaps" 
> 2016-05-24 17:31:47 [ WARN  ] InputMapping.cpp @ 92 - Missing element 'idmatcher' from mapping file: ":/inputmaps/dualshock4-xbox-emulate.json" 
> 2016-05-24 17:31:47 [ INFO  ] InputMapping.cpp @ 113 - Loading inputmaps from: "/storage/.local/share/plexmediaplayer/inputmaps" 
> 2016-05-24 17:31:47 [ INFO  ] InputComponent.cpp @ 45 - Successfully inited input: Keyboard 
> 2016-05-24 17:31:47 [ INFO  ] LocalJsonServer.cpp @ 33 - Listening to socket: "/tmp/pmp_inputSocket_unknown.sock" 
> 2016-05-24 17:31:47 [ INFO  ] InputComponent.cpp @ 45 - Successfully inited input: socket 
> 2016-05-24 17:31:47 [ INFO  ] InputComponent.cpp @ 45 - Successfully inited input: roku 
> 2016-05-24 17:31:47 [ INFO  ] InputSDL.cpp @ 204 - SDL found  0  joysticks 
> 2016-05-24 17:31:47 [ INFO  ] InputComponent.cpp @ 45 - Successfully inited input: SDL 
> 2016-05-24 17:31:47 [ INFO  ] InputLIRC.cpp @ 70 - LIRC socket connected  
> 2016-05-24 17:31:47 [ INFO  ] InputComponent.cpp @ 45 - Successfully inited input: LIRC 
> 2016-05-24 17:31:47 [ INFO  ] InputCEC.cpp @ 101 - libCEC was successfully initialized, found version 196609 
> 2016-05-24 17:31:47 [ INFO  ] InputCEC.cpp @ 223 - libCEC NOTICE: connection opened 

excerpt from pmphelper.log:

> 2016-05-24 17:42:07 [ WARN  ] CrashUploader.cpp @ 120 - Failed to submit report with uuid: "0ee12802-4677-f7e9-346b76fa-22636786" will try again later 
> 2016-05-24 17:42:07 [ WARN  ] CrashUploader.cpp @ 120 - Failed to submit report with uuid: "10219b43-4723-97ef-43ed355a-72cf13d2" will try again later 
> 2016-05-24 17:42:07 [ WARN  ] CrashUploader.cpp @ 120 - Failed to submit report with uuid: "10e9ee17-141c-bc05-085889ac-724920de" will try again later 
> 2016-05-24 17:42:07 [ WARN  ] CrashUploader.cpp @ 120 - Failed to submit report with uuid: "14893008-0714-0711-0ea008c7-3b019c8e" will try again later 
> 2016-05-24 17:42:07 [ WARN  ] CrashUploader.cpp @ 120 - Failed to submit report with uuid: "14ff660f-669f-e5e6-4330aa6d-056fcbb3" will try again later

**Comment by wm4** [comment]
What OS, PMP version, etc. Are there any crash dump uploads noted in pmphelper.log?

**Comment by martenjacobs** [comment]
Attached the latest crash log
[14ff660f-669f-e5e6-4330aa6d-056fcbb3.dmp.zip](https://github.com/plexinc/plex-media-player/files/280099/14ff660f-669f-e5e6-4330aa6d-056fcbb3.dmp.zip)

**Comment by martenjacobs** [comment]
I've enabled debug logging of libCEC and a crash log has now been submitted with uuid 79eb63ae-55d3-7ee9-1ac17e2d-4592387c

**Comment by martenjacobs** [comment]
I've now changed the hdmiport setting of the CEC section of plexmediaplayer.conf to 1, and now PMP starts up and CEC works

**Comment by wm4** [comment]
Thanks for the detailed information.

I see the crash, but unfortunately we don't have symbols for libcec, so I can't see where exactly it crashes. Your mention of the hdmiport setting is interesting, though.

CC @LongChair

**Comment by martenjacobs** [comment]
You're welcome. My install is working now, but if you'd like me to test anything else, just let me know.
