### ISSUE TITLE
GPL compliance request

### ISSUE THREAD

**Issue by bsdf** [plexinc/plex-media-player#348]
under the terms of the GPLv2, the complete source code of the application and all modules must be made available upon request. this application's core functionality resides in an unmodifiable binary format in `plex-web-client-konvergo-4cbcd79.cpp`. please provide a method by which this source can be obtained, preferably through a download link.

**Comment by tru** [comment]
The web-client binary contains a webpage loaded via QtWebEngine. We could host that on our server but it's not a great user experience for people to have to have a internet connect at launch. We don't consider that part of the code part of the host application so while we publish all code to the host here on GitHub the web-client part will continue to be closed for now.

**Comment by bsdf** [comment]
with all due respect, that's not how the GPL works. the license grants me the freedom to modify and distribute the work as i wish and in order to do so, i must be provided the **complete** source code upon request. 

if i understand your comment correctly, you are more or less arguing that the program in question is a glorified web browser, and that any page it views would be considered a separate program and therefore not bound to the GPL license requirements. this technicality is not only wrong, but also against the spirit of free software. in this particular case, the page is actually compiled into the binary and under no circumstances could be considered a separate program.

i'm not trying to cause trouble or be a "gpl troll", i simply wanted to make modifications to the application and found that i was being prevented from doing so. i hope you reconsider your stance here

**Comment by tru** [comment]
I totally get where you are coming for and I wish I had a better answer for you. I am not the right person to discuss this with since I am just a developer, if you want to discuss this with someone that actually know about the licenses and makes the decisions I suggest emailing legal@plex.tv. Thanks for showing interest!
