### ISSUE TITLE
Pausing immediately on start keeps displaying the loading screen

### ISSUE THREAD

**Issue by wm4** [plexinc/plex-media-player#35]
Start playing something, and click on the screen while the loading animation is still showing. This will change into pause mode, and never hide the loading screen. I'm not sure how important it is, but maybe it's confusing to users.

**Comment by mseeley** [comment]
We hide the loading dots in response to position updates start coming from the player. It's the only trustworthy way to know if the video stack on CE devices is actually playing. Play / pause doesn't interact with the loading dots. It could for sure if the UX is better.

**Comment by tru** [comment]
I am not sure this is something we should handle? @mseeley?

**Comment by mseeley** [comment]
I'm calling this one fixed. We no longer wait for the first position update before going into a playing state in the view.
