### ISSUE TITLE
UI jumps in list view

### ISSUE THREAD

**Issue by bobbysteel** [plexinc/plex-media-player#352]
Version: PMP 1.1.1 (and last two at least)
OS: Mac OSX El Capitan (latest updates)

This has been happening for at least 2 different releases now, probably three. I assumed it would go away but seems to be unaddressed from what I can tell.

Description: when viewing TV Shows (for example) in list view, choosing a particular letter, then doing an activity (watching, marking as watched, etc.) then going back returns you to the letter 'A' and the scroll down option doesn't let you get back to where you were. Need to exit list view and return back.

It's really hard to describe but super annoying when you have a lot of programs.

PMP debug logs only show the button presses and nothing else in Debug mode that would be useful here.

For clarity, I'm linking to a video that demonstrates the problem: https://youtu.be/YrxP6EQsby8

In the video:

1) Go to TV show list view (starting with 'A' selected)
2) Scroll down to 'U' on right hand side
3) Select a show with 'U' title, go into a season, watch a show
4) Back button to come back to season then show then list view
5) Right hand side shows 'U' selected by list channel back to 'A'
6) Scrolling down from 'A' ends at 'B' - not possible to scroll past that
(not shown) - choosing any other letter on right hand side always brings up 'A' again in center channel

Only way to get back to see anything past 'B' is to hit back once again then come back to list view.

Thoughts? Wish I could give better logs, but nothing looks out of ordinary on PMP log or PMS log.

**Comment by tru** [comment]
Ping @flamefork

**Comment by mseeley** [comment]
There's something very wrong indeed. It looks like upon returning to the list we're loading the incorrect range of items. When I return from the `U` show I again see `#-A` items followed by `W-Z` items. The exact range of letters covering the items shown when returning from the `U` show will be different based on library content.

Rename to `*.mov` (it's really a `.mov` file named `.zip` to meet Github attachment filtering): [Plex Media Player2.zip](https://github.com/plexinc/plex-media-player/files/301325/Plex.Media.Player2.zip)

**Comment by mseeley** [comment]
I've filed an internal issue on the UI client to address this.

Thank you very much for filing with a repro case @bobbysteel!

**Comment by bobbysteel** [comment]
Cool Cheers guys. Glad you could reproduce as well and it wasn't just me!

**Comment by Flamefork** [comment]
Next release will have this fixed.

**Comment by bobbysteel** [comment]
Hm, it still seems to be present @Flamefork in the current release from last week

**Comment by mseeley** [comment]
Hi @bobbysteel. Sorry, to clarify it'll be the next release where the web client is updated. The latest PMS release doesn't contain this fix. The web client will go into testing at the end of the week.

**Comment by bobbysteel** [comment]
Thanks Matt - the web client fix will also fix the PMP view? I had assumed that the bug was in the PMP codebase.

**Comment by mseeley** [comment]
You assumed right, sorry, I spoke in tongues.

The PMP UI is sometimes not updated at each PMP release. We'll have a UI update ready shortly.

Thanks again for letting us know about this issue. :)

**Comment by LongChair** [comment]
@bobbysteel : i suppose this should be fixed by now ? :)

**Comment by bobbysteel** [comment]
yes thanks, has been fixed a while now!
