### ISSUE TITLE
"Couldn't retrieve the play queue for this item. Please try again" when casting channel content from iOS/iPad

### ISSUE THREAD

**Issue by andreas-henning** [plexinc/plex-media-player#355]
I initially reported this issue via the Plex forums, and it has since been successfully reproduced by the Plex team member sergiou87. The forum thread is here:

http://forums.plex.tv/discussion/comment/1195369#Comment_1195369

**Test environment**

| Function | Hardware | Version |
| --- | --- | --- |
| IR controlled stereo system | - | - |
| Plex Media Server | Synology NAS | 0.9.16.6 |
| Plex Media Player (renderer) | _Raspberry Pi3_ | 1.1.1.329 |
| Plex App (controller) | iPad/iOS | 4.1.2 |

**Issue**

When casting internet radio streams (e.g. shoutcast) to the PMP from my iPad, the stream starts playing for a split second, then stops, and on the iPad I'm shown the following error message:

"Couldn't retrieve the play queue for this item. Please try again."

Playing the same internet radio streams directly on the iPad (without casting) works as expected. Using my Windows 10 Mobile phone as the controller to cast the same internet radio streams to the PMP also works as expected, so this is very likely an issue specific to the Plex app on iOS.

According to sergiou87, this bug affects all channels (in addition to "Watch Later" and "Recommended" videos), and is caused by PMP incorrectly reporting the current "now playing" state to iOS.

Next steps?

**Comment by wm4** [comment]
Not really my area, but can you post a plexmediaplayer.log when this happens?

**Comment by sergiou87** [comment]
This is the issue in the web client repo: plexinc/plex-web-client#4780

I think @dogonwheels has sorted it out 😄

**Comment by andreas-henning** [comment]
Beat me to it. Thanks sergiou97!  ;-)

**Comment by dogonwheels** [comment]
Yup - no need for logs now. It'll be fixed in a future release. Sorry for the hassle!

**Comment by andreas-henning** [comment]
You know which version the fix will be in?

**Comment by sebastienbarre** [comment]
Any news on this one? I've been experiencing the same problem for a month or so.

**Comment by sebastienbarre** [comment]
I'm no longer using that client, so I guess that fixed it for me.

**Comment by LongChair** [comment]
Thanks for the feedback.
