### ISSUE TITLE
Can't build anymore

### ISSUE THREAD

**Issue by TARSooper** [plexinc/plex-media-player#358]
Today I tried to update plex-media-player to the latest git version, but unfortunately this time around I received these errors. May it have anything to do with the fact that I've just updated my QT stuff to 5.7?
Anyway, here's my emerge log (using Gentoo btw) http://pastebin.com/TwBUtWwP. Is there anything that I can do in order to fix these issues?

**Comment by tru** [comment]
That looks like a cmake issue with gcc6.1 to me. Not a PMP issue at least. Maybe try upgrading cmake?

**Comment by TARSooper** [comment]
Fixed it! Seems like it was an issue regarding to my qtwebengine.
