### ISSUE TITLE
PGS subtitles are to high up compared to PHT

### ISSUE THREAD

**Issue by niso01** [plexinc/plex-media-player#360]
PGS subtitles are to high up while using Plex Media Player. SRT subtitles are fine. When playing in PHT or in the Plex IOS app it is ok. SRT subtitles are viewed in the black areas when playing 2.35, which is great. Infuse on Apple TV 4 handels PGS subtitles simular to SRT subtitles in PMP. 
Is this possible to fix?

**Comment by tru** [comment]
Can you post comparisons screenshots?

**Comment by wm4** [comment]
Probably another resolution mismatch. A sample file would be appreciated.

**Comment by niso01** [comment]
This is tested on 2 different PC's.

![pgs_pht](https://cloud.githubusercontent.com/assets/20016419/16173163/501a6858-3599-11e6-92d7-d3e6b9627bc4.PNG)
![pgs_pmp](https://cloud.githubusercontent.com/assets/20016419/16173164/56cf8318-3599-11e6-8a1e-d40aab4b82c5.PNG)
![srt_pht](https://cloud.githubusercontent.com/assets/20016419/16173165/5af30528-3599-11e6-9af3-b4810715cd60.PNG)
![srt_pmp](https://cloud.githubusercontent.com/assets/20016419/16173166/5ed834b0-3599-11e6-9e23-ea865cd5aeca.PNG)

**Comment by wm4** [comment]
Actually this might be an aspect ratio mismatch between video and subtitles. Sample still appreciated. (Just cut a few MB from the start, as long as at least one subtitle is visible in the resulting file. Assuming this is mkv.)

**Comment by niso01** [comment]
Here is a sample.
Yes it is MKV. I use Handbrake and I think the tool crops the movie, but it is still strange that it behaves different in PHT and PMP. Infuse handles the PGS subtitle perfect with this movie and put down on the black bar.
[Sample_1.zip](https://github.com/plexinc/plex-media-player/files/322277/Sample_1.zip)

**Comment by wm4** [comment]
As I thought, this is an aspect ratio mismatch. The video has 1920x800 resolution, while the PGS subtitle canvas is 1920x1080. I'm not sure what PHT actually does here. Maybe it just crops the subtitle canvas (assuming the video has in fact been cropped, but not the subtitles)? But I'm not sure if that'd be the right thing to do. Another possibility is that it renders the subtitles on top of the screen instead of the video, so if the screen is 1920x1080, the result would look just right.

**Comment by niso01** [comment]
Hmm, I do understand that it can be a problem how the player handles PGS subtitles. I really like PMP so that's why I'm trying to solve this. The screen resolution is 1920x1080 on both test PC's. I also tested with 1600x900 and 2560x1440 and it gave the same result.
So, this looks right in PHT, Plex webplayer (tested with all different resolutions), Infuse and also PowerDVD but not in PMP. I wonder if PHT looks for the width and PMP for the height? 

Thanks for your interest in this question. I really appreciate that. I usually don’t use subtitles, it is the rest of the family who wants it:)

**Comment by wm4** [comment]
Well, PMP just tries to fit the subs into the video without cropping the subs or shifting positions. If the aspect ratio mismatches, the subs are essentially letter-boxed. You can put `stretch-image-subs-to-screen=yes` into mpv.conf (should be a text file next to plexmediaplayer.conf) to position the subs over the screen instead of the video.

**Comment by tru** [comment]
Should that option be the default maybe? I don't think the above would ever be correct? But I might be missing something.

**Comment by niso01** [comment]
That solved the problem! Thanks. I still think it's strange that this it's working in PHT and in the webplayer. But any way, thanks!

**Comment by niso01** [comment]
Maybe that is default in PHT and the webplayer.

**Comment by wm4** [comment]
Well I also wonder why it "works" in the webplayer. I can make some tests what the transcoder does.

**Comment by wm4** [comment]
I've actually tried it in Plex web, and the subtitles were stretched (as in their aspect ratio was changed).

**Comment by niso01** [comment]
This problem is solved.


________________________________
Från: Lionel CHAZALLON <notifications@github.com>
Skickat: den 11 april 2018 08:18
Till: plexinc/plex-media-player
Kopia: niso01; Mention
Ämne: Re: [plexinc/plex-media-player] PGS subtitles are to high up compared to PHT (#360)


@niso01<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fniso01&data=02%7C01%7C%7Cc6ce91a7e69744a7a29008d59f740583%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636590243004682692&sdata=vQvQ2vgPQWkjxyZqdGr7YaZUVnejzNmBoFfEaPbdFvc%3D&reserved=0> : could you please confirm if this is still an issue or if we can close this ?
