### ISSUE TITLE
OSD does not resize well every time when window resizes on OS X

### ISSUE THREAD

**Issue by ajslater** [plexinc/plex-media-player#362]
OS X 10.11.5, PMP 1.1.2. Plex 2.6.9

When resizing the plex window, sometimes the OSD controls resize proportionally to the window and everything is fine, but often they do not. This leaves the OSD half cut off by the edge of the window or sometimes floating away from the edges in the middle of the window.

Resizing the window a once or twice more fixes it.

**Comment by LongChair** [comment]
@ajslater : is that still an issue in recent builds ?

**Comment by ajslater** [comment]
I cannot recall having seen it recently.
