### ISSUE TITLE
Audio stops after about a second

### ISSUE THREAD

**Issue by tofagerl** [plexinc/plex-media-player#365]
So I started a video, and the audio stopped. I tried another, and the same thing happens. Tried the two files in Movist, and then in Plex on my phone - both works fine.. 
So I reboot, and everything works. Once. Next file, same problem. 

Including logs: https://dl.dropboxusercontent.com/u/117580/PlexLogs.zip

**Comment by tofagerl** [comment]
Rebooting doesn't seem to be the key, just restarting the app has the same chance of working. Still only once, though, the second file I play always stops the audio after a second.

**Comment by LongChair** [comment]
@tofagerl : are you still having the issue in recent builds ?

**Comment by LongChair** [comment]
Closing this due to the lack of feedback.
Feel free to reopen if you need.
