### ISSUE TITLE
Fail to download for several days

### ISSUE THREAD

**Issue by mdesdin** [plexinc/plex-media-player#366]
Hi there devs,
several days ago I started a new environment for PMP on my Ubuntu 14.04, but since then I get following error and cannot compile at all:

`-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/hash.txt to plexmediaplayer-qt-latest-hash.txt...
-- Dependency hash is: 6918177
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-6918177.tbz2.sha.txt to konvergo-qt--release-6918177.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:75 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-6918177.tbz2.sha.txt:
  "HTTP response code said error"

  Hostname was NOT found in DNS cache

    Trying 104.20.6.9...

  Connected to nightlies.plex.tv (104.20.6.9) port 443 (#1)

  successfully set certificate verify locations:

    CAfile: none
    CApath: /etc/ssl/certs

  SSLv3, TLS handshake, Client hello (1):

  
Call Stack (most recent call first):
  CMakeModules/FetchDependencies.cmake:133 (get_content_of_url)
  CMakeModules/QtConfiguration.cmake:9 (download_deps)
  CMakeLists.txt:41 (include)
`

anything special I should do on Ubuntu for downloading and compiling? (it was working in my previous environment, which was about the same)
TIA

**Comment by tru** [comment]
We don't supply a qt binary for Linux. You need to define -DQTROOT=<path> to your qt installation

**Comment by mdesdin** [comment]
oops, my very bad! I was using my old script for compiling and I have installed a different qt and the path has changed...
thanks a lot!
