### ISSUE TITLE
Compile error on linux ubuntu 14.04

### ISSUE THREAD

**Issue by mdesdin** [plexinc/plex-media-player#367]
hi, i get following error when compiling under linux ubuntu 14.04 and using qt 5.6.1 from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt561-trusty, with master, 1.1.x branch and 1.1.2 tag:

`[46/88] Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/display/x11/DisplayManagerX11.cpp.o
../src/display/x11/DisplayManagerX11.cpp: In member function ‘virtual int DisplayManagerX11::getDisplayFromPoint(int, int)’:
../src/display/x11/DisplayManagerX11.cpp:195:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               x < crtc->x + crtc->width &&
                                   ^
../src/display/x11/DisplayManagerX11.cpp:196:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               y < crtc->y + crtc->height;
                                   ^
[47/88] Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/utils/CachedRegexMatcher.cpp.o
FAILED: /usr/bin/c++   -DHAVE_CEC -DHAVE_LIRC -DHAVE_SDL -DPREFIX=\"/root/plex-media-player/build/output\" -DQS_LOG_LINE_NUMBERS -DQS_LOG_SEPARATE_THREAD -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_WEBCHANNEL_LIB -DQT_WEBENGINECORE_LIB -DQT_WEBENGINE_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -DUSE_X11EXTRAS -DUSE_X11POWER -DUSE_X11XRANDR -Wall -fno-omit-frame-pointer -fvisibility-inlines-hidden  -g -fPIE -Isrc -I../src -isystem /opt/qt56/include -isystem /opt/qt56/include/QtCore -isystem /opt/qt56/./mkspecs/linux-g++ -isystem /opt/qt56/include/QtNetwork -isystem /opt/qt56/include/QtWebChannel -isystem /opt/qt56/include/QtQml -isystem /opt/qt56/include/QtQuick -isystem /opt/qt56/include/QtGui -isystem /opt/qt56/include/QtXml -isystem /opt/qt56/include/QtWebEngine -isystem /opt/qt56/include/QtWebEngineCore -isystem /opt/qt56/include/QtPositioning -isystem /opt/qt56/include/QtWidgets -isystem /opt/qt56/include/QtX11Extras -I/usr/local/include/mpv -I/usr/include/SDL2 -I../X11_X11_INCLUDE_PATH -I../X11_Xrandr_INCLUDE_PATH -I../external/qhttp/src -I../external/qslog -I../external/SPMediaKeyTap -I../external/HIDRemote -I../external/plistparser -I../src/player -I../src/core -I../src/shared    -fPIC -std=gnu++1y -MMD -MT src/CMakeFiles/PlexMediaPlayer.dir/utils/CachedRegexMatcher.cpp.o -MF src/CMakeFiles/PlexMediaPlayer.dir/utils/CachedRegexMatcher.cpp.o.d -o src/CMakeFiles/PlexMediaPlayer.dir/utils/CachedRegexMatcher.cpp.o -c ../src/utils/CachedRegexMatcher.cpp
../src/utils/CachedRegexMatcher.cpp: In member function ‘bool CachedRegexMatcher::addMatcher(const QString&, const QVariant&)’:
../src/utils/CachedRegexMatcher.cpp:21:92: error: parameter declared ‘auto’
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                            ^
../src/utils/CachedRegexMatcher.cpp: In lambda function:
../src/utils/CachedRegexMatcher.cpp:23:14: error: ‘mp’ was not declared in this scope
       return mp.first.pattern() == pattern;
              ^
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = QList<QPair<QRegExp, QVariant> >::iterator; _Predicate = CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0]’:
../src/utils/CachedRegexMatcher.cpp:24:6:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:1150:33: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
         if(!bool(__pred(*__first)))
                                 ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__find_if(_RandomAccessIterator, _RandomAccessIterator, _Predicate, std::random_access_iterator_tag) [with _RandomAccessIterator = QList<QPair<QRegExp, QVariant> >::iterator; _Predicate = CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0]’:
/usr/include/c++/4.8/bits/stl_algo.h:4465:41:   required from ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = QList<QPair<QRegExp, QVariant> >::iterator; _Predicate = CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0]’
/usr/include/c++/4.8/bits/stl_algo.h:1144:64:   required from ‘_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = QList<QPair<QRegExp, QVariant> >::iterator; _Predicate = CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0]’
../src/utils/CachedRegexMatcher.cpp:24:6:   required from here
/usr/include/c++/4.8/bits/stl_algo.h:214:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h:218:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h:222:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h:226:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h:234:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h:238:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
In file included from /usr/include/c++/4.8/algorithm:62:0,
                 from /opt/qt56/include/QtCore/qglobal.h:88,
                 from /opt/qt56/include/QtCore/qregexp.h:37,
                 from /opt/qt56/include/QtCore/QRegExp:1,
                 from ../src/utils/CachedRegexMatcher.h:8,
                 from ../src/utils/CachedRegexMatcher.cpp:5:
/usr/include/c++/4.8/bits/stl_algo.h:242:23: error: no match for call to ‘(CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0) (QPair<QRegExp, QVariant>&)’
    if (__pred(*__first))
                       ^
../src/utils/CachedRegexMatcher.cpp:21:85: note: candidate is:
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                     ^
../src/utils/CachedRegexMatcher.cpp:21:94: note: CachedRegexMatcher::addMatcher(const QString&, const QVariant&)::__lambda0
     auto newEnd = std::remove_if(m_matcherList.begin(),m_matcherList.end(), [pattern](auto mp)
                                                                                              ^
../src/utils/CachedRegexMatcher.cpp:21:94: note:   candidate expects 0 arguments, 1 provided
[47/88] Building CXX object src/CMakeFiles/PlexMediaPlayer.dir/player/PlayerComponent.cpp.o
ninja: build stopped: subcommand failed.`

help please, any idea?

**Comment by tru** [comment]
Your GCC might be too old. It complains about C++11 features that we use. I am not sure when they where added in GCC.

**Comment by mdesdin** [comment]
thanks again for your help. my ubuntu had version 4.8.x, so i decided to start with the next version 4.9 and it compiles already, with few warnings, but i think i had the same warnings in the past when it compiled with 4.8.
i followed the instructions from this post for ubuntu: https://www.quora.com/How-do-I-install-GCC-4-9-0-in-Ubuntu-14-04-LTS-to-compile-C++
i see there are newer versions available in the toolchain ppa, but wanted to try first with the closest version to my environment.

**Comment by tru** [comment]
Good to know that 4.9 is required. We should add a check for that.
