### ISSUE TITLE
LibreElec PMP / Legacy NVIDIA Driver Issue

### ISSUE THREAD

**Issue by BrianInAz** [plexinc/plex-media-player#368]
[PMPLogs.zip](https://github.com/plexinc/plex-media-player/files/333835/PMPLogs.zip)
When I install embedded PMP Generic on my Atom D525 w/ ION2 it boots but I only get a black screen. It seems that the "Legacy NVIDIA" build drivers did not make it to 1.1.2 or are not working for some reason. 

Multiple reports in the forums:

https://forums.plex.tv/discussion/222844/pmp1-1-2-does-not-work-on-nvidia

> PlexMediaPlayer:~ # xrandr
Screen 0: minimum 8 x 8, current 1920 x 1080, maximum 8192 x 8192
DVI-I-0 disconnected primary (normal left inverted right x axis y axis)
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 160mm x 90mm
   1920x1080     60.00*+  59.94    29.97    23.97    60.05    60.00
   1680x1050     59.95
   1600x900      60.00
   1440x900      59.89
   1366x768      59.79
   1280x1024     75.02    60.02
   1280x800      59.81
   1280x720      60.00    59.94
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   800x600       75.00    72.19    60.32
   720x480       59.94    60.05
   640x480       75.00    72.81    59.94

**Comment by LongChair** [comment]
As far as i Know, The LE release we are based on don't require any specific NIVIDIA legacy build now. They should all be delievered in teh same build.

Now if it doesn't work on nvidia there has to be something we missed.

**Comment by tru** [comment]
Is this solved @BrianInAz ?

**Comment by BrianInAz** [comment]
It is solved. Thanks!
