### ISSUE TITLE
Xscreensaver not disabled in PMP

### ISSUE THREAD

**Issue by truckershitch** [plexinc/plex-media-player#375]
Xscreensaver is not disabled in PMP.  The screensaver is then unresponsive.  I can exit the application by clicking 'Back' and 'Exit'.

I can temporarily disable xscreensaver by a wrapper script like I used to do for Plex Home Theater but this was not necessary before.

Log is here: http://pastebin.com/wVgFm19h

**Comment by wm4** [comment]
Is the xdg-screensaver script installed and working? That's what PMP uses.

**Comment by truckershitch** [comment]
It seems to be.  Below is the output when run from the command line:

[me@myserver ~]$ xdg-screensaver
   xdg-screensaver - command line tool for controlling the
   screensaver

Synopsis

   xdg-screensaver suspend WindowID

   xdg-screensaver resume WindowID

   xdg-screensaver { activate | lock | reset | status }

   xdg-screensaver { --help | --manual | --version }

Use 'man xdg-screensaver' or 'xdg-screensaver --manual' for additional info.
[me@myserver ~]$

**Comment by wm4** [comment]
I just tested. PMP calls `xdg-screensaver reset` every 15 seconds during playback. This should be sufficient.

Maybe xdg-screensaver itself isn't working correctly.

I've tested by adding a printf when we call the program: http://sprunge.us/EZHd

**Comment by truckershitch** [comment]
I will try to run <code>xdg-screensaver reset</code> when xscreensaver kicks in to see what happens.  It should work from a ssh session, right?  I just have to wait a few minutes for it to come back on.

What seems to happen at the moment is that xscreensaver is unresponsive and will not exit until I blindly exit PMP, at which point xscreensaver stops and I'm back to normal.

**Comment by wm4** [comment]
> It should work from a ssh session, right?

Might need access to the X display and/or the dbus session bus.

**Comment by truckershitch** [comment]
Okay, I tested <code>xdg-screensaver reset</code> and it worked from ssh.  I let xscreensaver kick in from just an X session and the command stopped it, and when I ran PMP and xscreensaver kicked in erroneously, the command stopped it as well.

**Comment by truckershitch** [comment]
Okay, I added the code and I'm not seeing "reset!" in the terminal window at all.  I downloaded the source fresh from https://github.com/plexinc/plex-media-player/archive/v1.1.2.359-2b757d45.tar.gz  and made the change in /src/power/PowerComponentX11.cpp as you did.

The only other change I made is to /src/input/InputLIRC.cpp to fix a problem I have with LIRC input, but I doubt it would affect the screensaver.

**Comment by truckershitch** [comment]
Okay, the reset! only comes during playback.  It does not show up when PMP is idle.  Perhaps it should?

**Comment by wm4** [comment]
This was changed a while ago. You can get the old behavior if you set the `preventSystemScreensaver` option in the config file to `true`.

**Comment by truckershitch** [comment]
That did the trick.  Sorry for the noise.  I vaguely remember setting that option before.  I lost my original settings directory and had to do a fresh one this week.

Thanks for the help!
