### ISSUE TITLE
Feature Request: Better handling of 21:9.

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-media-player#376]
Hi there,

Sorry to sound like a rant but I'd love to see Plex Media Player support the 21:9 aspect ratio a bit better in the menus. As it stands everything is just 16:9 which is fine but we all love correctly scaled programs so if it's not too much to ask, I'd love the feature. If it's too much to implement, I understand but it would be really nice for us ultrawide owners. :+1:

**Comment by wm4** [comment]
It's on the list. Might even be released or previewed soon.

**Comment by danjames92** [comment]
Wow that's great news. Will it take full advantage of the screen real-estate or just an extended background?

**Comment by wm4** [comment]
I think the intention is pretty much to make the UI resolution-independent, but I don't know the details.
