### ISSUE TITLE
OS X: Volume cannot be controlled

### ISSUE THREAD

**Issue by ghost** [plexinc/plex-media-player#377]
Device: MacBook Air
OS: 10.11.5
Build: PMP 1.1.2.359-2b757d45

Current behavior:
Plex Media Player does not honor volume settings. For example, setting the volume to mute through the system still plays back music at moderate volume, and since there's no volume slider within the app the user has no control over the playback level.

Expected behavior:
User should be able to control volume setting using the keys on the keyboard, or a slider within the app.

![volume controls dont work](https://cloud.githubusercontent.com/assets/12398365/16630247/7750e978-436e-11e6-8269-b82eeeb3d565.jpg)

**Comment by wm4** [comment]
Disable exclusive mode in the PMP audio settings.

**Comment by nickkleshinski** [comment]
Is that setting supposed to be turned on by default?

**Comment by wm4** [comment]
Yes. We enable it by default because otherwise the user would have to change OS settings too to get multichannel output.

**Comment by nickkleshinski** [comment]
Ok.

**Comment by mseeley** [comment]
> Yes. We enable it by default because otherwise the user would have to change OS settings too to get multichannel output.

Reopening for a moment. This comes up time and time again. It's unexpected that volume keys are neutered. Firing up PHT and I can change volume w/o problems. Looks like it's defaulting to stereo:

![screen shot 2016-07-08 at 4 15 22 pm](https://cloud.githubusercontent.com/assets/30019/16705507/502457b2-4527-11e6-81c6-1196eb2bbf03.png)

Can we:

* Have a setup script which changes the OS setting to get multichannel output?
  * If a user changes their system setting will they get functional volume keys _and_ multichannel?
* Only trigger exclusive mode when playing multichannel output?
* _Anything_ else which makes sure the app responds to the hardware volume keys?

**Comment by wm4** [comment]
> Firing up PHT and I can change volume w/o problems. 

Shows the same behavior as PMP to me.

> Have a setup script which changes the OS setting to get multichannel output? 

I haven't found out how to do that. But looking at it from another perspective, asking the user to setup his audio correctly in the OS settings is the right thing to do. Our original goal was to make it work "out of the box" though, and we never revisited those original decisions.

> If a user changes their system setting will they get functional volume keys and multichannel?

Yes.

> Only trigger exclusive mode when playing multichannel output?

I've considered this. It'd definitely work, but of course you'd have the same issue with multichannel audio.

>  Anything else which makes sure the app responds to the hardware volume keys?

We could catch the volume keys ourselves and let them change the PMP volume controls. I think Tobias was looking into this, but he's on vacation currently.

**Comment by tru** [comment]
Yeah we could probably have AppleMediaKey input handle volume buttons. I will look into it.

**Comment by LongChair** [comment]
@ghost : could you tell me if this is still relevant in latest builds ?

**Comment by mseeley** [comment]
Closing stalled issue.
