### ISSUE TITLE
Blackscreen crash at startup

### ISSUE THREAD

**Issue by truckershitch** [plexinc/plex-media-player#378]
I can successfully run 1.1.2 but 1.1.3 gives the PMP crash info screen telling me to post a log.  I'm running Fedora 24 updated as of this morning.

Here is the log: http://pastebin.com/4K3w2AMd

Thanks!

**Comment by truckershitch** [comment]
To add to this:  The error says "The file or directory could not be found.  [-6]"

**Comment by wm4** [comment]
Could be a packaging error. You probably need to run the install function of the cmake build system, although for me it also works when just running it out of the build dir. This is most likely caused by our change to move the web-client to on-disk.

**Comment by truckershitch** [comment]
That seems to be the case.  After running <code>make install</code>, things work as before.

Thanks again!
