### ISSUE TITLE
Runtime Qt path for pmphelper on linux not set

### ISSUE THREAD

**Issue by mdesdin** [plexinc/plex-media-player#379]
When installing current master on Ubuntu 16.04 I get following report:

-- Installing: /usr/local/bin/plexmediaplayer
-- Set runtime path of "/usr/local/bin/plexmediaplayer" to "/opt/Qt5.6.1/5.6/gcc_64/lib"
-- Installing: /usr/local/bin/pmphelper
-- Set runtime path of "/usr/local/bin/pmphelper" to ""

This provokes that pmphelper cannot find the correct Qt library. This can be solved adding the path /opt/Qt5.6.1/5.6/gcc_64/lib to the environment or ldconfig, but would be better if set at install time.

**Comment by wm4** [comment]
Hm, obviously some cmake magic would be required to do this for pmphelper the same way it's done for plexmediaplayer, but I honestly don't know where it does this.

**Comment by tru** [comment]
Hmm, interesting. Rpath has always been a bit of a mystery to me, the cmake article is here: https://cmake.org/Wiki/CMake_RPATH_handling

If you can figure out how to set it correctly I would happily accept a patch.

**Comment by ProfessorKaos64** [comment]
`make install` doesn''t even give me that: http://slexy.org/view/s20MESVBQ3. I wonder if this is related to my issues in #406.

**Comment by jb044** [comment]
You can fix this by editing:

./build/src/tools/helper/cmake_install.cmake

This is were RPATH="" is set, but ofcourse somewere earlier on things definitly went wrong somehow....
sometimes you just want something to work anyway ;)

**Comment by LongChair** [comment]
@jb044 : could you check if adding 

`INSTALL_RPATH "${QTROOT}/lib"` here https://github.com/plexinc/plex-media-player/blob/47e2f6e39cb8f76fb7a71cb230fbc56fc6627af9/src/tools/helper/CMakeLists.txt#L18

like it's done for PMP here https://github.com/plexinc/plex-media-player/blob/78e125aae362ae83e9a7c159500da3551cdda374/src/CMakeLists.txt#L154-L157

would fix the issue and confirm please ? :)

**Comment by LongChair** [comment]
@mdesdin @mdeguzis : can anyone chack the patch i pasted above ? :)

**Comment by Enigma0** [comment]
Could you generate a `.patch` file?

**Comment by LongChair** [comment]
It’s just one line to add ! :)

**Comment by Enigma0** [comment]
Added as such:

```
set_target_properties(${HELPER_TARGET} PROPERTIES
  INSTALL_RPATH "${QTROOT}/lib"
  OUTPUT_NAME ${HELPER_NAME}
)
```
Not getting the messages any longer & looks good here:

```
-- Installing: /usr/local/share/plexmediaplayer/web-client/desktop/_FINISHED
-- Installing: /usr/local/bin/plexmediaplayer
-- Set runtime path of "/usr/local/bin/plexmediaplayer" to "/opt/Qt/5.9.5/gcc_64/lib"
-- Installing: /usr/local/bin/pmphelper
-- Set runtime path of "/usr/local/bin/pmphelper" to "/opt/Qt/5.9.5/gcc_64/lib"
```
