### ISSUE TITLE
Plex.icns missing from PMP 1.1.3 MacOS

### ISSUE THREAD

**Issue by danhenrydesign** [plexinc/plex-media-player#383]
Even though the Info.plist properly specifies the icon file, the icns file itself is missing from the Resources folder. The icon seems to be set by the app when running, but if the app is in the dock only a generic icon will be shown when the app isn't running.

<img width="93" alt="screen shot 2016-07-15 at 1 02 58 pm" src="https://cloud.githubusercontent.com/assets/12402777/16882350/8ce68e94-4a8c-11e6-9168-5eda0bee84fc.png">

**Comment by dicetomato** [comment]
I just came here to report the same thing. 10.11.6.

**Comment by tru** [comment]
Fixed in 1.1.4
