### ISSUE TITLE
Cannot download dependencies on Windows

### ISSUE THREAD

**Issue by dct2012** [plexinc/plex-media-player#385]
`Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/hash.txt to plexmediaplayer-qt-latest-hash.txt...
Dependency hash is: 72c86db
Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt-windows-i386-release-72c86db.tbz2.sha.txt to konvergo-qt-windows-i386-release-72c86db.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:75 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt-windows-i386-release-72c86db.tbz2.sha.txt:
  "HTTP response code said error"`

**Comment by wm4** [comment]
We don't have any 32 bit deps for PMP yet. You can build Qt yourself, or download a prebuilt official version. (We apply these patches, so not sure if official builds even work: https://github.com/plexinc/plex-media-player/blob/master/qt-patches/qt5-5.7.0.patch)
