### ISSUE TITLE
Subtitles do not support all languages 

### ISSUE THREAD

**Issue by matansh** [plexinc/plex-media-player#387]
English subs work great but languages like hebrew appear as gibberish.

This is usually caused because the used encoding is the default ASCII. changing it to something more modern like UTF-8 or UTF-16 will fix this.

If i had a clue on how to fix this myself i would contribute the fix myself but i am sure that one of the brave contributors will take this upon themselves :)

**Comment by tru** [comment]
The server tries to guess what language the subtitle is in, but it falls over for certain scrips, hebrew included. As you noted the workaround for now is to convert the subtitle to UTF-8 beforehand.

Another solution which we had in PHT is to have a fallback charset in the configuration where if we can't guess we use the fallback instead.

I am pretty sure MPV already supports this, so we would only need to implement a setting in PMP and send the correct option to mpv. @wm4 probably have the details on the MPV options.

**Comment by wm4** [comment]
Yeah, forcing a codepage like with `sub-codepage=utf8:cp1255` in mpv.conf could help.

**Comment by LongChair** [comment]
Closing due to the lack of feedback.
Feel free to reopen with more details if needed.

**Comment by MaximTs** [comment]
> Yeah, forcing a codepage like with sub-codepage=utf8:cp1255 in mpv.conf could help.
Thx. It's really worked!
Just create the empty file mpv.conf in folder C:\Users\%USERNAME%\AppData\Local\PlexMediaPlayer
and add that line.
