### ISSUE TITLE
PMP 1.1.3 (Auto Update from 1.1.1 - Results in no sound)

### ISSUE THREAD

**Issue by NutterV** [plexinc/plex-media-player#388]
# _Issue Summary_
On Auto update from version 1.1.1 to 1.1.3, the update appeared successful however no sound would go to the TV. I attempted all sources one at a time still no luck, not from basic (3.5mm Headphone Socket) nor via HDMI.

## _Workaround_ 
Format and clean install on to SD Card

## _Platform and OS_
Raspberry Pi 2 (OpenELEC 7.0)

## _Plex Media Player_
Version 1.1.3 (after update from 1.1.1 automatically)

**Comment by wm4** [comment]
Auto update from 1.1.1 or earlier installations is not supported, and the release notes explicitly say you must do a full reinstall.
