### ISSUE TITLE
Progress/Busy Indicator locks out mouse

### ISSUE THREAD

**Issue by Gerk** [plexinc/plex-media-player#389]
This has pretty much always happen.  If the indicator showing buffering or something else is working is up the mouse can't click on anything until that indicator is gone.

An example where this is a problem would be trying to use the mouse to fast forward a few jumps.  You have to wait for everything to "catch up" and for the video to start playing and the indicator to go away before you can skip forward again.  This is also a problem because if you have moused over the interface then the controls come up and stay up so you can't jump forward using the keyboard at that point either (pressing right arrow just moves your control focus to the next interface item).

Not a show stopper but super annoying and it causes interface issues.

**Comment by tru** [comment]
@mseeley what's your take on this, can it be improved?
