### ISSUE TITLE
Installation instructions for Fedora 24

### ISSUE THREAD

**Issue by crmne** [plexinc/plex-media-player#391]
I managed to build and run Plex Media Player successfully on Fedora 24 (with latest updates as of today) without manually building QT, mpv, or ffmpeg!

First add the [Fedora Handbrake][1] and [RPM Fusion (Free)][2] repositories:

    dnf config-manager --add-repo=http://negativo17.org/repos/fedora-handbrake.repo
    dnf install http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-24.noarch.rpm

Install the dependencies:

    dnf install autoconf automake libtool harfbuzz-devel freetype-devel fontconfig-devel libX11-devel libXrandr-devel libvdpau-devel libva-devel mesa-libEGL-devel mesa-libGL-devel yasm alsa-lib-devel pulseaudio-libs-devel uchardet-devel zlib-devel fribidi-devel git gnutls-devel cmake qt5-qtbase-devel qt5-qtwebchannel-devel qt5-qtwebengine-devel qt5-qtx11extras-devel libmpv-devel mpv ffmpeg-devel

And build the project:

    git clone git://github.com/plexinc/plex-media-player
    mkdir plex-media-player/build
    cd plex-media-player/build
    cmake -DQTROOT=/usr/ ..
    make -j4
    sudo make install

Enjoy!

[1]: http://negativo17.org/handbrake/
[2]: http://rpmfusion.org/

**Comment by wm4** [comment]
I'm a bit hesitant, because the mpv package is a bit outdated. This could lead to caveats or even malfunctions, especially later on.

**Comment by tru** [comment]
@crmne If you want to contribute build instructions I would add a bit about building mpv from source as well and then submit it as a PR. Follow the instructions in the wiki: https://github.com/plexinc/plex-media-player/wiki/Contributor-License-Agreement

Thanks for your contribution!

**Comment by wm4** [comment]
I'd pretty much recommend trying to adjust the Ubuntu instructions to Red Hat: https://github.com/plexinc/plex-media-player#building-on-linux
