### ISSUE TITLE
CLA discussion

### ISSUE THREAD

**Issue by RSully** [plexinc/plex-media-player#392]
In particular, I'd like to ask about the copyright assignment clause. I'd consider contributing here, but I don't want any chance that my work will become closed-sourced or used in a non-open product.

Whenever I think about copyright assignment all that comes to mind is Oracle's re-closing of Solaris. Not a good time.

**Comment by tru** [comment]
Hi, thanks for your interest. The CLA will allow us to close the source again in the future, but that's not the point of it. We want to have the possibility to change to another open source license in the future if needed without having to contact all contributors and chase them down.

For us to re-close the source we would also have to work out all the libraries we depend on that doesn't allow closing the source, like MPV (which is hugely central) and to some extent Qt/Chromium, at that point I don't think much of the application would be left or the same.

If you want a 100% guarantee we will never close the source and have that in writing that's not something I can oblige with, but I can tell you that currently closing the source is VERY distant and a huge effort working on removing a lot of dependencies and not something that would benefit us. Hope this satisfies you. Thanks again.
