### ISSUE TITLE
PMP doesn't have an app icon

### ISSUE THREAD

**Issue by nickkleshinski** [plexinc/plex-media-player#394]
Device: MacBook Air
OS: 10.11.6
Build: `PlexMediaPlayer-1.1.3.380-a2959899-macosx-x86_64`

Current behavior:
Downloading the app does not have an icon. The active download shows a published date of July 7 which means this has been public for almost a month. Is it possible to get a new build on `plex.tv/downloads` that resolves this?

![screen shot 2016-08-03 at 9 53 14 am](https://cloud.githubusercontent.com/assets/12398365/17374151/1e4d71d6-5960-11e6-8e39-43d4cbed6db3.jpg)

**Comment by wm4** [comment]
We are preparing for a new release, which fixes this.
