### ISSUE TITLE
PMP @Asus Chromebox - Hibernate don´t work

### ISSUE THREAD

**Issue by Massaguana** [plexinc/plex-media-player#396]
Hello Plex Team,

with my Asus ChromeBox and the new Firmware 20160719 runs PMP the Hibernating don´t work... the screen goes Black but the system run´s (can hear the Fan).

With oPHT 1.6.2 the hibernating works fine... just for your information.

Regards
Massaguana

**Comment by LongChair** [comment]
@Massaguana is that still the case with recent builds ?

**Comment by Massaguana** [comment]
I can´t test it because there are no Embedded PMP available at the moment...

**Comment by LongChair** [comment]
@Massaguana : as i see you have been able to check the other issue and closed it, would you mind checkign again this one as well please ? :)

**Comment by Massaguana** [comment]
The problems are still there but I just have no interest in PMP
