### ISSUE TITLE
Build error: 404 not found

### ISSUE THREAD

**Issue by HazCod** [plexinc/plex-media-player#397]
```
  GET
  /directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-72c86db.tbz2.sha.txt
  HTTP/1.1

  Host: nightlies.plex.tv

  User-Agent: curl/7.47.0

  Accept: */*

  

  [5 bytes data]

  The requested URL returned error: 404 Not Found
```

**Comment by tru** [comment]
Pass -DQTROOT=[path to Qt installation] to cmake.

**Comment by HazCod** [comment]
curl https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-72c86db.tbz2.sha.txt
```<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-72c86db.tbz2.sha.txt was not found on this server.</p>
</body></html>```

**Comment by tru** [comment]
if you pass the correct QTROOT it will not try to download. That error just means we don't build Qt for your platform.

**Comment by HazCod** [comment]
Oh, apologies. I specified the wrong directory. I am closing. On the other side, are there automated builds for non-plex-pass users? I am on debian/ubuntu.

**Comment by tru** [comment]
PMP is not yet available for non-plex-pass users.
