### ISSUE TITLE
[BUG] No/glitchy video on subsequent playbacks

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#398]
I'll play the first time after just starting it and it works but then the next thing I play (or sometimes a couple more down) I get garbled video and only audio. I have to restart the app for it to work again for 1-2 plays.

Tried forcing it to render opengl in the .conf but that doesn't seem to help.

Running on Debian 8 (SteamOS)

**Comment by wm4** [comment]
Playback log would help.

**Comment by Enigma0** [comment]
Yeah I'll try to get that. In the mean time I may have it working with the Deinterlace toggle on. Will need to test some more before I can say it fixed it though.

**Comment by Enigma0** [comment]
Turning on `Deinterlacing` fixes it for me. Still leaving this open so it gets fixed properly.

**Comment by wm4** [comment]
Can't be fixed without logs.

**Comment by Enigma0** [comment]
I don't have a SteamOS install anymore.

**Comment by LongChair** [comment]
Guess we'll close this then as we can't have more feedback :)
