### ISSUE TITLE
Exit menu: "Relaunch" button exit app without relaunching it

### ISSUE THREAD

**Issue by jleroy** [plexinc/plex-media-player#399]
As seen in `web-client-2.7.5-d44b692/js/main.a7810bf352055f007903.js`:

`return t.canRelaunch?i.push({action:"exit",label:d.default("Relaunch")})`

However, as "CAP_RELAUNCH" capability doesn't seems to be used anywhere in the application, maybe you should remove it ?

**Comment by Enigma0** [comment]
This may help you out: https://github.com/plexinc/plex-media-player/issues/354

The workaround doesn't make it relaunch but does properly say 'Exit' instead.

**Comment by LongChair** [comment]
@jleroy : is this still an issue with recent builds ?

**Comment by Enigma0** [comment]
Yes - still an issue.

**Comment by LongChair** [comment]
@markus101 : could you check this one please ? :)

**Comment by markus101** [comment]
Relaunch is only supported on embedded builds where the app is relaunched on exit. Relaunch shouldn't be shown outside of that environment, which is what #354 is about.
