### ISSUE TITLE
PHT/Win/MCE-compatible mappings for keyboard.json

### ISSUE THREAD

**Issue by Mediaconoclast** [plexinc/plex-media-player#40]
There are several posts in the forums about this, but the issue is essentially that PMP commands for similar functions are mapped differently than PHT. If you are running both PHT and PMP on the same platform, it is desirable to map similar functions to the same keys... And to make matters worse, some of the keystroke combinations are incompatible with MCE-remote setups.

1. `Ctrl+F` is not an available option with the MCE/MCE_KBD protocols, and PHT uses `Backslash`

    Solution: **` "\\\\": "host:fullscreen",`** and also possibly **`"Tab": "host:fullscreen",`**

2. `Ctrl+Q` is not an MCE option, and it's more intuitive for Mac users than Windows users.

    Solution: **`"Alt\\+F4": "host:close",`**

3. `Ctrl+Shift+D` is not an MCE option, and PHT uses 'I' for essentially the same function

    Solution: **`"I": "host:toggleDebug",`**

4. On PHT `FastForward` and `Rewind` are mapped to `F` and `R`

    Solution: **`"F": "step_forward",`** and **`"R": "step_backward",`**

Bonus: I have **`"PgDown": "step_backward",`** and **`"PgUp": "step_forward",`** added to the map, and assigned to ChannelDown and ChannelUp on my Harmony. This allows me to cycle through TV episodes with single clicks, as opposed to navigating to the GUI icons with the directional keys.

**Comment by Mediaconoclast** [comment]
So here's the `keyboard.json` I have in `...\AppData\Local\PlexMediaPlayer\inputmaps`:

```
{
  "name": "Keyboard Generic",
  "idmatcher": "Keyboard.*",
  "mapping":
  {
    // standard navigation, we allow num and shift modifiers
    "(Num\\+|Shift\\+)?Left": "left",
    "(Num\\+|Shift\\+)?Right": "right",
    "(Num\\+|Shift\\+)?Up": "up",
    "(Num\\+|Shift\\+)?Down": "down",
    "(Num\\+)?(Return|Enter)": "enter",
    "Space": "space",
    "(Esc|Backspace)": "back",

    // map Num+X and Shift+X to X. This allows normal number input
    "(?:Num\\+|Shift\\+)?([0-9])": "%1",

    // map Shift+Letter to action jump+letter
    "Shift\\+([A-Z])": "jump+%1",

    "P": "play_pause",
    "Ctrl\\+P": "pause",
    "X": "stop",
    "B": "back",
    "H": "home",
    "A": "cycle_audio",
    "Ctrl\\+A": "cycle_audio_back",
    "L": "cycle_subtitles",
    "Ctrl\\+L": "cycle_subtitles_back",
    "S": "toggle_subtitles",
    "Alt\\+A": "increase_audio_delay",
    "Alt+Shift\\+A": "decrease_audio_delay",
    "Alt\\+S": "increase_subtitles_delay",
    "Alt\\+Shift\\+S": "decrease_subtitles_delay",

    // application shortcuts
    "Ctrl\\+F": "host:fullscreen",
    "Ctrl\\+Q": "host:close",
    "Ctrl\\+Shift\\+R": "host:reload",
    "Ctrl\\+Shift\\+D": "host:toggleDebug",

    // debug command to crash the host. for testing
    "Ctrl\\+Alt\\+Shift\\+F1": "host:crash!",

    // Windows-PHT mappings
    "Alt\\+F4": "host:close",
    "\\\\": "host:fullscreen",
    "Tab": "host:fullscreen",
    "PgDown": "step_backward",
    "PgUp": "step_forward",
    "I": "host:toggleDebug",
    "F": "step_forward",
    "R": "step_backward"
  }
}
```

**Comment by sjorge** [comment]
Would be nice to choice a keyboard map to use: Plex Media Player, PHT/Kodi compatible, ... and also show whatever the user drops in the dir in addition too.

**Comment by todthomson** [comment]
> Would be nice to choice a keyboard map to use: Plex Media Player, PHT/Kodi compatible...

:+1: I'm loving the UI of the new player and the quality and stability of the playback, but losing the old PHT keyboard shortcuts I've been using for the last 5 years has thrown my brain into a tailspin...

The Kodi keymap is available here: http://kodi.wiki/view/Keyboard_controls (assuming same as PHT?).

Any good reason why PMP has changed the keyboard shortcuts from PHT?

It would be cool to have the PHT key map "out of the box".

Awesome job in PMP so far! Loving almost everything about the new player :+1:

**Comment by sjorge** [comment]
1.0.2 should actually fair better in that regards, I for example now brings up debug like in PHT, among others.

**Comment by Mediaconoclast** [comment]
Yes, efforts are underway to map MCE input, and given that finding the Holy Grail might be easier than accommodating out-of-the-box mapping for all the MCE remotes out there, I'm closing this now.
