### ISSUE TITLE
PMP exits & windows 10 to a black screen, requires hard reboot

### ISSUE THREAD

**Issue by wunderbred** [plexinc/plex-media-player#401]
Running PMP 1.1.4 on Windows 10 Home.  GTX 970 with latest nVidia drivers installed.

If I start PMP fullscreen, and alt+enter to a window, everything is fine.  Once I play a video, either going back to a window mode or exiting (via either the menu to "Exit" or Alt+F4) the program is immediately replaced by a black screen (no input / resolution change) that can't be resolved via CtrlAltDel or Alt+F4 or Alt+Tab or any other number of attempts at getting back into Windows.  

Attempted disabling Hardware Acceleration in PMP and issue was not resolved.  Persisted in v 1.1.3 as well.

**Comment by wm4** [comment]
This "should not happen". If PMP is terminated, and the screen is still not back, then it's definitely some sort of driver problem.

Is this with native GL enabled? (PMP settings dialog.)

**Comment by wunderbred** [comment]
Yes - Native OpenGL is enabled.  I will try doing a clean re-install of my display drivers, but no other GL or Direct3D applications are presenting similar issues.

**Comment by tru** [comment]
Are you still experiencing this?

**Comment by wunderbred** [comment]
I've disabled Native OpenGL and the issue has stopped.  Have not re-enabled to see if issue persists, but was planning on trying when a new version came out.

**Comment by tru** [comment]
So most likely this is a bug in the OpenGL driver you use. Not surprisingly most windows OpenGL drivers are buggy and horrible. Stay on non-native if it works, should not effect you negatively.
