### ISSUE TITLE
Debug info screen cut off in 21:9 displays.

### ISSUE THREAD

**Issue by danjames92** [plexinc/plex-media-player#409]
Let me know if you require a log. Resolution is 3440 x 1440. Blocked the network address just in case.

![plex](https://cloud.githubusercontent.com/assets/16107603/17910529/22f00f4c-6981-11e6-886f-2aa1cc330d35.png)

**Comment by LongChair** [comment]
@danjames92 : the layout of the debug screen is not intended to match 21:9 sorry :)
21:9 screens are pretty rare, there is no plans to adress this in the short term.

I will close this for now.
