### ISSUE TITLE
Application doesn't launch in fullscreen

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#410]
Instead, I get a maximized window with the right edge cut off partially. Manually toggling `fullscreen` in settings gets it working for the session but next time I start it up it is again maximized rather than in fullscreen.

Built with latest today using supplied steps on Ubuntu GNOME 16.04.1.

**Comment by tru** [comment]
Known issue with current master. Stay on 1.1.4 if you want it to work. I hope I have time to find / fix this issue today.

**Comment by Enigma0** [comment]
@tru Pulled and rebuilt and appears to be fixed.
