### ISSUE TITLE
Remove letterboxing on OS X

### ISSUE THREAD

**Issue by nickkleshinski** [plexinc/plex-media-player#412]
Device: MacBook Air
Screen resolution: 1440 x 900
Build: 1.1.4.393-12c41f9f

Current behavior:
When launching PMP for the first time, the splash screen and the PIN screen both appear as letterboxed (black bars at top and bottom). Unless there is a design reason for this, would it be possible to remove them?

Expected behavior:
Image would be slightly zoomed in to fill entire screen.

![remove letterboxing](https://cloud.githubusercontent.com/assets/12398365/18184176/d1238eb4-7065-11e6-9d1f-004f4fb0e213.jpg)

**Comment by tru** [comment]
PMP is currently locked in 16:9 and this is probably what you see here. It will be addressed with the new UI. If you have a 16:9 resolution and this is still a problem, reopen this issue
