### ISSUE TITLE
Audio Initialization changes input on Marantz Receiver via Optical connection

### ISSUE THREAD

**Issue by techdef** [plexinc/plex-media-player#413]
When I hit Play and get the 3 little loading dots in PMP my Marantz changes input and sets volume to -18dB. It changes from the correct Optical input to Net/USB (which is also marantz slang for airplay). Optical out is default between my mac mini and the marantz.

If it helps diagnose, changing input on the Marantz back to the proper one (for the optical cable) while the 3 dots are still bouncing will cause an error in PMP (paraphrasing): Audio Output failed to Initialize, then bounces out to main menu. If I hit play again and let it change input, start playing and then change input back it plays OK. Also, seems that if I pause & resume it doesnt happen again with the same video file.

Also, 3 times now its happened that if I try and change the input back early (while the 3 dots are dancing) it crashes PMS but leaves PMP running.

**Comment by LongChair** [comment]
@techdef : is that still an issue with recent builds ?

**Comment by techdef** [comment]
Unsure. I got too annoyed and went over to Plex on appletv.

Jamie B. Myer

On Apr 10, 2018, at 9:53 AM, Lionel CHAZALLON <notifications@github.com<mailto:notifications@github.com>> wrote:


@techdef<https://github.com/techdef> : is that still an issue with recent builds ?

**Comment by LongChair** [comment]
Ok closing then :)
