### ISSUE TITLE
Add more hidden audio delay settings

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#416]
It seems that quite a few setups are suffering from bad audio delay values. In hidden settings today we support:

```"audio_delay.24hz": 0,
"audio_delay.normal": 0,```

I suggest we add:

```"audio_delay.24hz": 0,
"audio_delay.25hz": 0,
"audio_delay.30hz": 0,
"audio_delay.50hz": 0,
"audio_delay.60hz": 0,
"audio_delay.others": 0,```

**Comment by tru** [comment]
Uggh

**Comment by wm4** [comment]
We've added 25hz, as that seems to have some merit (according to past Slack discussions). We'll skip the others for now.
