### ISSUE TITLE
Exclusive mode does not prevent system volume being used

### ISSUE THREAD

**Issue by DaveBinM** [plexinc/plex-media-player#417]
When the "Exclusive Mode" audio setting is enabled, I'm still able to use the system volume to increase or decrease the volume. I actually have to do this in order to hear things properly.

**Environment:**
macOS Sierra 10.12 Beta (16A313a)
PMP v1.1.5.397-04fb5bd1

**Logs:**
[PMP Logs.zip](https://github.com/plexinc/plex-media-player/files/477124/PMP.Logs.zip)

**Comment by wm4** [comment]
None of the logs you posted contain a playback attempt.

**Comment by wm4** [comment]
Also, to avoid confusion: "exclusive audio" becomes active during playback only. Outside of that PMP behaves normally, as far as audio is concerned.

**Comment by DaveBinM** [comment]
Ah. Disregard this then. I was under the impression that "Exclusive" took effect as soon as it was toggled.
