### ISSUE TITLE
Stutter when using: Sync Mode = Display

### ISSUE THREAD

**Issue by hovedmannen** [plexinc/plex-media-player#418]
I get severe stutter when using this mode.

**Comment by hovedmannen** [comment]
[PlexMediaPlayer.zip](https://github.com/plexinc/plex-media-player/files/478643/PlexMediaPlayer.zip)

**Comment by wm4** [comment]
Try one of the two things (or both):
- use less heavy settings (just comments the ``vo-defaults`` line in your mpv.conf for testing and restart PMP)
- try with native opengl (can be changed in the PMP settings, also requires restarting PMP)

**Comment by LongChair** [comment]
closing due to the lack of feedback
