### ISSUE TITLE
Sound only plays for 3 seconds.

### ISSUE THREAD

**Issue by dadrepus** [plexinc/plex-media-player#419]
Recent upgrade to OSX to 10.11.6. Current install of player. Upon restart (unknown if related) sound only plays for 3 seconds in any tv or movie but plays complete for music. I also have an older version of Home Theater that plays all files complete, no problems. Files play fine via server and web. Server and player on same computer.

**Comment by wm4** [comment]
Does disabling exclusive mode in the PMP audio settings help?

**Comment by dadrepus** [comment]
Yes, thanks it works now for all media.

**Comment by wm4** [comment]
That's nice, but there really should be no reason why it doesn't work out of the box. Can you post a playback log when it does _not_ work?

**Comment by dadrepus** [comment]
Well, with that last comment I decided to give exclusive a try again. And now it works again as it was supposed to. So now I have no clue why but it works and this is enough for me.
Thanks all.
