### ISSUE TITLE
Can't Change Audio Stream

### ISSUE THREAD

**Issue by DisplacedHusker** [plexinc/plex-media-player#421]
I am using Plex Media Player on a Mac Mini. Which has been working fine the past few month. I was experimenting with the setting the other day and everything was fine. We I turned it on yesterday I can not get the audio surround mode or the subtitles to change, I get an error. "There was a problem selecting the stream for this item"
If I use Plex Home Theater they change fine. I have the latest version of Plex and Mac software. Using HDMI out to 7.1. Denon receiver.

**Comment by wm4** [comment]
Sounds like a known problem. Can you post a PMP playback log, where you try to switch the audio stream?

**Comment by DisplacedHusker** [comment]
Would it help to use an earlier version of PMP? Here is the log

[Plex Media Server Logs_2016-09-27_10-44-11 (1).zip](https://github.com/plexinc/plex-media-player/files/496186/Plex.Media.Server.Logs_2016-09-27_10-44-11.1.zip)

**Comment by Halfe85** [comment]
I also have a with PMP  when starting a second audio stream. The Stream is equal or lower quality from the default. When starting the Default the audio is normal. but when starting the second. Its dead silence. What do you need of logs? I use Raspberry Pi3 with a edited profile. (https://forums.plex.tv/discussion/238816/h265-hevc-audio#latest)

**Comment by hjelmn** [comment]
I am seeing the same issue with Plex Media Player on a Mac. I can not change the audio stream on m4v files created by Handbrake. Seems to be working for mkv and other m4v files.

**Comment by LongChair** [comment]
@DisplacedHusker : pretty sure this is not an issue anymore, closing this for clarity.
Feel free to reopen if im' wrong.
