### ISSUE TITLE
.desktop isn't showing icon in Ubuntu GNOME 16.04

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#423]
Built latest 1.1.6 today and I have no icon for PMP. Says missing `.desktop` when I right click & Show Details.

Tried setting the icon to something manually and it shows up in Nautilus but not in the GNOME Shell.

Example:
https://imgur.com/a/CPvox

**Comment by LongChair** [comment]
Well I am not sure there is much we can do about this. 
The build system wouldn't create anything specific like a `.desktop` file that you'd want.

**Comment by Enigma0** [comment]
This, if anything, was some GNOME issue.
