### ISSUE TITLE
1.1.5 and 1.1.6: Constant play bar and full screen bugs

### ISSUE THREAD

**Issue by SeaLightEditor** [plexinc/plex-media-player#424]
In 1.1.5 I noticed that the play bar with title and time info was always visible, but that seems to be fixed in 1.1.6. However, when you're already in full screen mode and you go to watch a movie, it forces my Mac to think that it's going into full screen mode again and refreshes all monitors instead of just playing like it did in 1.1.4. Is there a way to revert to 1.1.4 until this is fixed?

Mac OS X 10.11.6

[Plex Media Player Logs.zip](https://github.com/plexinc/plex-media-player/files/511038/Plex.Media.Player.Logs.zip)

**Comment by Enigma0** [comment]
Does the option labeled "Display Mode Switching" (I think) have any difference?

**Comment by SeaLightEditor** [comment]
That did it! Thanks!
