### ISSUE TITLE
Question or Request (Acess power dialogue everywhere also providing a function usable in inputmap)

### ISSUE THREAD

**Issue by cpfaff** [plexinc/plex-media-player#428]
I already have an own input map for my remote. I saw there is the different power options as separate functions available to map. It would be really convenient and save buttons if there would be a way that I could map the power dialogue rather then the separate functions to a button in my remote. From there I could do the selection what I want to do. Is this already possible?

**Comment by OttoKerner** [comment]
If you can map a sequence instead of a single button, you only need
Home - Back 
to get to the 'Power Down' dialog

**Comment by cpfaff** [comment]
Is that possible in general? That would be great. However a direct command might be a bit faster? 

Am 8. Oktober 2016 15:15:32 MESZ, schrieb OttoKerner <notifications@github.com>:
>If you can map a sequence instead of a single button, you only need
>Home - Back 
>to get to the 'Power Down' dialog
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/plexinc/plex-media-player/issues/428#issuecomment-252424003

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by OttoKerner** [comment]
> Is that possible in general?
Unfortunately not. Only some programmable remotes support this, like the bigger Harmony models.

**Comment by cpfaff** [comment]
Hm OK. I think that accessing the power dialogue from everywhere would be very helpful plus a function to call it up.
