### ISSUE TITLE
Access watch later from left navigation on homescreen

### ISSUE THREAD

**Issue by cpfaff** [plexinc/plex-media-player#429]
Maybe I missed that there is an option. But currently it looks like the watch later part can only be accessed from the home screen scrolling completely to the right. That is somewhat hidden and hard to acess if you use that playlist a lot. Is there a way to have it as categoy on left side on the home screen? That would be nice.

**Comment by LongChair** [comment]
@cpfaff : i suppose this can be cloased now that the new UI is out ?

**Comment by LongChair** [comment]
Closing this due to the lack of feedback, feel free to reopen if needed.
