### ISSUE TITLE
problem with second audio stream

### ISSUE THREAD

**Issue by Halfe85** [plexinc/plex-media-player#430]
Hi. 
Hope this will help some. I have problem with PMP when playing the second audio stream on my files. My backup collection consist of movies for the children so i also have audio in my language. 
My server is a Desktop PC:
Amd FX-8350 8core
16GB RAM
2xGTX960 4GB
Win10.

Player is Raspberry Pi3 running your BETA PMP-embedded. over LAN.

Logs are zipped. 
1: Playing with Default Audio Stream
2: playing with Second Audio Stream
[1 PMP.zip](https://github.com/plexinc/plex-media-player/files/522882/1.PMP.zip)

I also use Plex Andriod as Remote and ive noticed that when using PMP i cannot change audio streams there.
![screenshot_2016-10-11-22-25-18](https://cloud.githubusercontent.com/assets/10784130/19287413/ef96b072-9001-11e6-9419-9c4619ce989c.png)

**Comment by wm4** [comment]
Sorry, but what is the problem? Just that you can't select it via remote control?

**Comment by LongChair** [comment]
Closing due to the lack of feedback, feel free to reopen if you have some :)
