### ISSUE TITLE
Playback API requirements

### ISSUE THREAD

**Issue by RSully** [plexinc/plex-media-player#431]
I'm not sure if this is expected behavior, but it is really odd to me. I am working on an application to control Plex Media Player - just play/pause/seekto events. I tried using curl to test these commands out, and was getting nothing but 406 responses (perhaps like #329). 

I figured out that these commands only work after a request is made to `/player/timeline/poll`, after which `/player/playback/play` and the rest start working. 

It is worth noting, I am connecting via loopback, and not using any authentication. I do not need to store any token or anything from the timeline request, I just have to _make the request_ before the other requests work. I also have to _keep making this request_ otherwise they stop working, too. 

This is just adding needless complexity for me, but I'd love to at least start a discussion about this and make sure I'm not going crazy: is this expected behavior, and could you guys provide some context?

**Comment by RSully** [comment]
Also apparently you guys require a lot of headers for these requests (specifically the initial request with a new client-id), even though I can pass any values to them. I'm not sure the complete list is actually documented anywhere, I had to use this [Python Plex API file](https://github.com/mjs7231/python-plexapi/blob/aa37f1b4341014f3bac04ca5675372ed71ecc5af/plexapi/config.py#L40) to find them.

**Comment by LongChair** [comment]
This API is a standard one for all Plex players.
PMP just implements it :)

Thanks for the feedback though, but not much we can do about it now.

**Comment by RSully** [comment]
Is there an updated documentation for this API?

**Comment by LongChair** [comment]
I don’t think there is anything public available. Sorry.
