### ISSUE TITLE
Feature : Changing from total video time to time left

### ISSUE THREAD

**Issue by suvojit-0x55aa** [plexinc/plex-media-player#433]
Currently the video player shows only the total length of the video during playback.
It would be great if it is interchangeable between the total time and the time left.
Would like to hear your thoughts about this...

**Comment by OttoKerner** [comment]
It currently shows you the clocktime at which the video will be finished. 
Much more useful, IMHO.

**Comment by LongChair** [comment]
Closing this as it's quite old now and for clarity.
