### ISSUE TITLE
Crash when attempting to play some streaming media in SVT Play channel

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#435]
Trying to play back some of the streams using the SVT Play channel in PMP results in PMP just vanishing. No crash dialogue is presented. PMP log contains some ugly error messages.
For this test I tried to play a "Timmy time" episode (in the SVT Play channel the show is called "Timmy lamm".

https://gist.github.com/atrus05/23efbcd782be80b064e537896d208ea7

**Comment by tru** [comment]
Did you get something in `pmphelper.log?`

**Comment by atrus05** [comment]
@tru Yep https://gist.github.com/atrus05/b9e71bf80e46fdb5ebf475c0c1267d7e

**Comment by wm4** [comment]
Does it still happen with the latest builds?

**Comment by atrus05** [comment]
This does indeed seem to work now. I will report back in case I find it not to.
