### ISSUE TITLE
volume doesn't work - PHT is better IMO

### ISSUE THREAD

**Issue by fireheadman** [plexinc/plex-media-player#436]
Installed this on my macbook pro and mac-mini (x2).
Everything except volume appears to work....  looks like the app is too scaled down, reminds me of the plex app that comes on smart tvs vs PHT.

I am unable to adjust the volume using the volume function keys as I was previously able to in PHT.   Perhaps PHT just allows for the OS volume to be used and PMP has its own channels which are not mapping volume to the vol keys anymore??

If this can be corrected, I believe the app to have some value.

**Comment by Enigma0** [comment]
So I think it's just that PMP has a wonky volume management system. First you probably want to ensure that you have `Exclusive Mode` enabled. Second, the volume buttons have no effect and you need to use `+` and `-`.

I battled a good deal with `Exclusive Mode` enabled/disabled and regularly had issues with audio not changing when I wanted it to. After giving in and remapping my remote to `+`/`-` things are good.

**Comment by fireheadman** [comment]
thanks for the tip on +/- keys.... I will check it out this evening.
The exclusive mode is enabled out of the box, so I left that as is.

**Comment by Enigma0** [comment]
If you want to use the systems `Vol+`/`Vol-` functions then you'd need to disable `Exclusive Mode`.

**Comment by fireheadman** [comment]
Was able to install PMP on my other laptop.   Here is what I am seeing/getting

- With exclusive mode enabled, I can use +/- keys for vol and system volume does not allow vol control  (not sure if it is me, but seems like max vol isn't really loud)
- With exclusive mode disabled, I can use the system volume buttons and the +/- keys do nothing.  (This seems to be a higher vol level??)

Thank you for chiming in one this, helps a ton!

**Comment by Enigma0** [comment]
Sounds about right. In `Exclusive Mode` I think the system assumes max base volume but it could also just revert to whatever the volume level happened to be at the time of launching PMP.

**Comment by LongChair** [comment]
@fireheadman : is this still an issue or can we close it ?

**Comment by fireheadman** [comment]
Surprised this is still open.  Closing
