### ISSUE TITLE
[embedded] version number appears during video playback if video is not 16:9

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#437]
tested with 1.1.7, but was already an issue on earlier version numbers 
Platform: Raspberry Pi 2

![version_overlay](https://cloud.githubusercontent.com/assets/10280992/19858486/ecc73576-9f81-11e6-94ec-95505c8c478e.jpg)
This video has had its black bars on top/bottom 'cut'.

**Comment by tru** [comment]
Isn't that the text that shows up on boot? So the framebuffer is not cleared correctly or something?

**Comment by OttoKerner** [comment]
If so, it appears to be a different framebuffer than what the user interface draws into. 
The text is covered as long as the user is in the menu/library. Only when video playback starts, this text is revealed.

**Comment by LongChair** [comment]
Hmm I can probably check that with LE dudes

**Comment by LongChair** [comment]
@OttoKerner : any chance you can share a lib with such a video ... didn't find anything that could show the issue in mine ?

**Comment by OttoKerner** [comment]
my server is not fit for remote access atm, so here is one for download https://drive.google.com/open?id=0B7NKohkDHT4cX0VVSWt1OTZsQVE
28 MB 1080p (1920*796px) H.264, AAC 2.0

**Comment by LongChair** [comment]
@OttoKerner : i haven't seen that one recently. Coudl you confirm it's been fixed ?

**Comment by OttoKerner** [comment]
I think it was fixed quite a while ago.

**Comment by LongChair** [comment]
Closing then :)
