### ISSUE TITLE
FTBFS with 404

### ISSUE THREAD

**Issue by cwayne18** [plexinc/plex-media-player#439]
When trying to build following the instructions, it fails with the following cmake error:

CMake Error at CMakeModules/FetchDependencies.cmake:58 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-72c86db.tbz2.sha.txt:
  "HTTP response code said error"

    Trying 104.20.6.9...

  Connected to nightlies.plex.tv (104.20.6.9) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  TLSv1.2 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [108 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2477 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server accepted to use http/1.1

  Server certificate:

   subject: C=CH; ST=Switzerland; L=Stans; O=Plex, GmbH; CN=*.plex.tv
   start date: May  6 00:00:00 2014 GMT
   expire date: May  9 12:00:00 2017 GMT
   subjectAltName: host "nightlies.plex.tv" matched cert's "*.plex.tv"
   issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
   SSL certificate verify ok.

  [5 bytes data]

  GET
  /directdl/plex-dependencies/plexmediaplayer-qt/latest/konvergo-qt--release-72c86db.tbz2.sha.txt
  HTTP/1.1

  Host: nightlies.plex.tv

  User-Agent: curl/7.50.1

  Accept: */*

  

  [5 bytes data]

  The requested URL returned error: 404 Not Found

  Closing connection 0

  [5 bytes data]

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

Call Stack (most recent call first):
  CMakeModules/FetchDependencies.cmake:116 (get_content_of_url)
  CMakeModules/QtConfiguration.cmake:9 (download_deps)
  CMakeLists.txt:56 (include)

-- Configuring incomplete, errors occurred!

**Comment by tru** [comment]
You need to pass -DQTROOT=<path> to your Qt installation.

**Comment by cwayne18** [comment]
I thought if you omit it it just uses the system's qt?

**Comment by tru** [comment]
No if you omit it, we try to download a binary package. Not available for Linux though.

**Comment by wm4** [comment]
Right, I think you need to use `-DQTROOT=/usr` or so.
