### ISSUE TITLE
Can't type non-alphanumeric characters in search

### ISSUE THREAD

**Issue by rcombs** [plexinc/plex-media-player#443]
In particular, I can't type periods and other punctuation (which should be easy), or anything in non-Latin script (which is harder, but the OS does all the heavy lifting through the regular text entry interface).

**Comment by ddolcimascolo** [comment]
:+1:

**Comment by LongChair** [comment]
@markus101 : any thought about rodger point ? :)

**Comment by markus101** [comment]
We can look into this when we rework the v2 search. Closing this out in favour of the internal issue.
