### ISSUE TITLE
Companion server should translate `X-Plex-` query parameters to headers before processing commands

### ISSUE THREAD

**Issue by sergiou87** [plexinc/plex-media-player#444]
Since version 4.4 of Plex for iOS we started sending the `X-Plex-Device-Name` as a query parameter due to some limitations of the networking stack of iOS that doesn't allow non-ascii characters in the headers (silently chopped off at the point where the character occurs… for example `Sergio's iPhone` would just become `Sergio`).

After that change, it seems PMP remote control stopped playing because PMP checks for the device name as a header (https://github.com/plexinc/plex-media-player/blob/47e2f6e39cb8f76fb7a71cb230fbc56fc6627af9/src/remote/RemoteComponent.cpp#L370).

PMP should be pre-processing the requests to detect any `X-Plex-` query parameter and convert it into a header before processing the command.

**Comment by IanDBird** [comment]
Great work in identifying @sergiou87, I noticed the recent 1 star iOS app store reviews that seemed to be related. @tru - Any chance you could take a quick peek at this to see when it would be possible to get scheduled?

**Comment by sebastienbarre** [comment]
The iOS app is pretty much dead with this update. No way to remote-control streams. Do you guys have a suggestion on how to revert back?
