### ISSUE TITLE
Error starting Windows Media Player on Win10

### ISSUE THREAD

**Issue by TallGeekyCool** [plexinc/plex-media-player#447]
EDIT: I forgot the PMP version number: 1.0.2.70-15a01542

I've been getting an error on my Windows 10 HTPC when I try to start Windows Media Player. I've uninstalled and reinstalled several times and I've tried the repair option as well. 

When I start the program, I see an error message that reads something like "You should not see this error" and a second message which shows what looks like a resolution of 1440 (something that isn't supported by my TV) and reminder to include the logs which is attached to this post.

[PlexMediaPlayer.log.txt](https://github.com/plexinc/plex-media-player/files/601861/PlexMediaPlayer.log.txt)

**Comment by tru** [comment]
1.0.2 is very very old. Please try the latest version from https://plex.tv/download

**Comment by LongChair** [comment]
closing due to the lack of feedback
