### ISSUE TITLE
[PMP 1.1.7] No sound on file

### ISSUE THREAD

**Issue by dfgsaerh** [plexinc/plex-media-player#448]
Hey,
First time filing a bug so hopefully this is all the information you need. Keep up the great work btw.
This isn't a new issue for me in 1.1.7 but when I try to play a particular file - there's no sound.

Platform and OS version - Windows 10 PMS 1.2.7.2987
Plex Media Player app version - 1.1.7

File plays fine in VLC player

[PlexMediaPlayer.log.txt](https://github.com/plexinc/plex-media-player/files/607545/PlexMediaPlayer.log.txt)
[Plex Media Server.log.txt](https://github.com/plexinc/plex-media-player/files/607546/Plex.Media.Server.log.txt)

**Comment by wm4** [comment]
Looks like it could be a problem with the Windows mp3 decoder. Can you upload the file or a part of it?

**Comment by dfgsaerh** [comment]
Thanks for the reply
Could be onto something as a friend uses PMP on a mac mini and these files play fine with sound
Here's a sample:
https://drive.google.com/file/d/0Bz-eZC4uXhkoNmtLS3FkSVJBNXM/view?usp=sharing

**Comment by wm4** [comment]
Thanks, the sample was very useful. Fixed internally.

**Comment by dfgsaerh** [comment]
Wow thanks for the quick fix.
Do you know will this fix be included in the next nightly build? 
Thanks again

**Comment by wm4** [comment]
> Do you know will this fix be included in the next nightly build?

Probably yes, but these nightly builds aren't really done regularly. Only if we want forum users to test something specific.

**Comment by wm4** [comment]
Made a new test build here: https://nightlies.plex.tv/public-test/plexmediaplayer/public-testing/1.1.7.452-8a2b00e5/

**Comment by dfgsaerh** [comment]
Thanks so much - can watch the rest of the season of this show now.
Cheers
