### ISSUE TITLE
Media keys should always be caught when playing music

### ISSUE THREAD

**Issue by kayone** [plexinc/plex-media-player#449]
@rcombs commented on [Tue Nov 29 2016](https://github.com/plexinc/plex-web-client/issues/5865)

I noticed this on Mac with media keys and BT controls, but it also applies on RPi with a CEC remote. The Pause button doesn't pause music playback unless the player screen is active; I would expect the media controls to always work properly when playback is in progress (or paused, but not stopped). Some keys are bound to a different use outside the player screen, but it seems reasonable to expect some intelligent handling (e.g. "Pause" always pauses, "Play/Pause" always toggles play/pause, but "Play" when already playing could play the highlighted item if applicable).

**Comment by mseeley** [comment]
Closing in favor of original issue.
