### ISSUE TITLE
Raspberry PI2 issues

### ISSUE THREAD

**Issue by stokbaek** [plexinc/plex-media-player#450]
I dont know if this is the right place to post this but here we go.

I installed the newest embedded img from plex.tv on my raspberry PI2 and it wouldn't boot cause it couldnt mount /dev/mmcblk0p2. I took the mount option for this partition out of the cmdline.txt file and now it boots fine, only issue is that the root partition is booted as a loop device so every time it boots is it a new device.

```/dev/mmcblk0p1 on /flash type vfat (ro,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)```

```/dev/loop0 on / type squashfs (ro,relatime)```

```Model: SD SA16G (sd/mmc)
Disk /dev/mmcblk0: 15.5GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start   End    Size    Type     File system  Flags
 1      1049kB  538MB  537MB   primary  fat16        boot, lba
 2      539MB   573MB  33.6MB  primary
```

Hope anyone can help me fix this.

**Comment by LongChair** [comment]
That looks like a bad Sdcard flash to me.
Closing it as it's been a while, feel free to reopen if you are still experiencing the issue.
