### ISSUE TITLE
Stuck on PIN entry dialog after switching between tv and desktop view (OSX)

### ISSUE THREAD

**Issue by chrissearle** [plexinc/plex-media-player#451]
Updated to 1.2 today. Running on sierra and am in a home.

If I start PMP - it starts in full tv view.

I enter my PIN and I get the normal TV layout.

Switch to desktop view - and enter PIN again - get the desktop/web layout.

Switch back to full tv view and enter PIN again - back to normal TV layout.

Then choose Settings > Main > Check for Update - and when you get the No Update Found dialog hit Esc.

At that point I get thrown back to a PIN entry form - offset to the right quite a bit and not taking input. Have to force quit PMP.

Screencap as zip (since github won't take mp4 format directly):

[pmp.mp4.zip](https://github.com/plexinc/plex-media-player/files/622620/pmp.mp4.zip)

**Comment by LongChair** [comment]
@chrissearle : i suppsoe we can close this now right ? :)

**Comment by LongChair** [comment]
I think this should be fixed by now, closing :)
