### ISSUE TITLE
Plex media player turns off the display when running in the webui mode

### ISSUE THREAD

**Issue by ghost** [plexinc/plex-media-player#452]
Windows 10
Plex media player 1.20

When you are watching something in fullscreen using the webui mode the display will turn off even if you watching a movie when it shouldn't turn off if you are watching a movie etc.

**Comment by tomaspapan** [comment]
same for mac os x

**Comment by KingJ** [comment]
[Allegedly fixed in v1.2.1](http://forums.plex.tv/discussion/comment/1323053#Comment_1323053).
