### ISSUE TITLE
Change seek times

### ISSUE THREAD

**Issue by viveksjain** [plexinc/plex-media-player#453]
Is there any way to configure what the default forward and back seek times are?

**Comment by RickDB** [comment]
Wondering the same thing, tried adding a input.conf based on mpv example like below but doesn't seem to get used:

`
## Seek units are in seconds, but note that these are limited by keyframes
RIGHT seek  15
LEFT  seek -15
UP    seek  60
DOWN  seek -60

# Do smaller, always exact (non-keyframe-limited), seeks with shift.
# Don't show them on the OSD (no-osd).
Shift+RIGHT no-osd seek  5 exact
Shift+LEFT  no-osd seek -1 exact
Shift+UP    no-osd seek  5 exact
Shift+DOWN  no-osd seek -5 exact
`

**Comment by wm4** [comment]
It's indeed unused. You need to edit the PMP inputmaps instead.

**Comment by RickDB** [comment]
In keyboard.json it only shows seek_backward / seek_forward for example, any idea how I can specify seek times?

**Comment by wm4** [comment]
No idea, but you should still be able to issue seek commands like in input.conf by prefixing them witjh `host:player`, like `host:player seek 15`.

**Comment by RickDB** [comment]
Thanks, left / right / up / down I can't seem to remap as it will no longer allow me to navigate and can't figure out yet how to make them conditional.
These work so just have to re-map EventGhost:

`
    "Ctrl\\+Shift\\+B": "host:player seek -15",
    "Ctrl\\+Shift\\+G": "host:player seek 15",
`
