### ISSUE TITLE
Windows Away-Mode not supported - breaks CEC functionality

### ISSUE THREAD

**Issue by tomillr** [plexinc/plex-media-player#454]
Latest PMP build still doesn't support Windows Away-Mode, which has been a part of Windows since XP MCE. This breaks CEC functionality and makes CEC functionality basically useless on Windows machines:

When Windows tries to wake up system in Away-Mode (to perform a schedules Windows Update or tv recording for example), PMP doesn't recognize away-mode call and overwrites it.

Instead of system remaining "silent", PMP instead sends out CEC command and wakes up connected tv and avr.

PMP needs to register to receive away-mode status:

`RegisterPowerSettingNotification(m_hWnd, &GUID_SYSTEM_AWAYMODE, DEVICE_NOTIFY_WINDOW_HANDLE);`

The powermanager then needs to check for the Away-Mode call like this:

```
case PBT_POWERSETTINGCHANGE:
{
POWERBROADCAST_SETTING* s = (POWERBROADCAST_SETTING*)nEventData;
if( s != NULL && IsEqualGUID( s->PowerSetting, GUID_SYSTEM_AWAYMODE ) )
// The computer is entering "away" mode.
```

Further technical documentation is available in the attached documents or over on MSDN:

[Microsoft documentation](https://msdn.microsoft.com/de-de/library/windows/desktop/aa373208%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

[awaymode.pdf](https://github.com/Pulse-Eight/libcec/files/405454/awaymode.pdf)
[AvailabilityRequests.pdf](https://github.com/Pulse-Eight/libcec/files/405455/AvailabilityRequests.pdf)

**Comment by wm4** [comment]
Thanks for all the info.

@LongChair can we easily disable CEC temporarily for this mode?

**Comment by tomillr** [comment]
Any news on this? Or something I can do to help out?

**Comment by wm4** [comment]
Seems like it's a moderate effort, but I wouldn't even know how to test it and it's not a priority. So I probably won't look at this any time soon. In theory, you could contribute a patch to add it. Unfortunately it's pretty hard to build PMP on Windows.

**Comment by LongChair** [comment]
@tomillr : is this issue still relevant currently ?
Don’t get me wrong, we didn’t implement anything yet, but i find it kind of strange that this would break CEC, so maybe some fixes could have been made on windows side.

**Comment by LongChair** [comment]
@tomillr : as I see no feedback i suppose there is no more interest in that feature or no more issue.
Closing it for now, feel free to reopen if needed.
