### ISSUE TITLE
Web UI on the New Update with 4K display

### ISSUE THREAD

**Issue by Endda** [plexinc/plex-media-player#456]
Using the new update and switching over the the Web UI, everything is very small on my 4K monitor

**Comment by Endda** [comment]
So this was fixed in the second update, but has now been broken again the third update to Plex Media Player. This is driving me nuts!

**Comment by wm4** [comment]
Which version exactly broke/fixed this?

**Comment by Endda** [comment]
When Plex Media Player was updated with the Web UI, it made everything on the Web UI tiny on 4K displays. I don't know what version that was. Then, the very next update PMP received fixed this issue. Again, I don't know what version that was. PMP has now just received its second update (after being updated with the Web UI option), that makes it very difficult to read/see things on a 4K display in the Web UI mode. This version is 1.2.3.

Everything looks fine when it's expanded into the TV mode (or whatever it is called). But when you switch to Web UI mode it makes everything tiny. Even when I drag that scale slider all the way to the right

**Comment by wm4** [comment]
Ah, maybe it's just the hidpi flag.

**Comment by Endda** [comment]
I see the latest update just fixed the issue for the movie/TV show images, but the text is still incredibly small

**Comment by LongChair** [comment]
@Endda : how about recent builds, is that still an issue ?

**Comment by Endda** [comment]
Hey, it was fixed in recent builds. Thanks!

**Comment by LongChair** [comment]
Thanks !
