### ISSUE TITLE
PMP Client Settings not available when in non-fullscreen mode.

### ISSUE THREAD

**Issue by scottocs11** [plexinc/plex-media-player#457]
Platform and OS version: Mac OS 10.11.6

Plex Media Player app version: 1.2.0.481

Brief description of the issue or bug:
Plex Media Player client settings are not available when in "Web Client" or not in fullscreen mode.

Steps to reproduce (these will make it easier for development to track down):
When in Fullscreen mode, clicking your username at the top right shows the "Settings" option to change PMP Settings.
When NOT in Fullscreen mode, clicking the username symbol at the top right shows the account settings.

Resolution: Make PMP Client settings available in non-fullscreen mode.

**Comment by mseeley** [comment]
Similar to #766. The settings handling inconsistency is a very sore point for certain.
