### ISSUE TITLE
Implement setting to completely disable the mouse

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#46]
We should have a new option in the main category (let's fix that with a Input category later) that should be `Disable mouse` default to off, when this option is enabled the mouse should never show up or allow mouse input into our window.

**Comment by LongChair** [comment]
@dogonwheels : the setting is there in `main` section, named `disablemouse`. It needs some nice labelling from the web side :), so handing this issue over to you :)

**Comment by dogonwheels** [comment]
Description fixed in https://github.com/plexinc/plex-web-client/commit/fd66b1e7847b5bc294df7e9595fe4dbc2046e6d3
