### ISSUE TITLE
Make desktop-mode an opt-out

### ISSUE THREAD

**Issue by ddolcimascolo** [plexinc/plex-media-player#460]
Hey guys,

Thanks for the good work, using Plex everyday here and loving it !

Would you mind adding a setting to disable desktop mode in the next release?

I was used to pressing ctrl + shift + F to switch between fullscreen and windowed mode and that worked very well, allowing me to keep on watching something while doing something else... Though the desktop mode is a nice improvement, I do believe you should let users choose if they want to use it. 

Thanks,
David

**Comment by paviro** [comment]
(y)

**Comment by paviro** [comment]
I agree!

**Comment by ddolcimascolo** [comment]
According to https://forums.plex.tv/discussion/190085/plex-media-player this is fixed in 1.2.1 with the addition of the new `--tv` CLI flag and associated setting.

I'll give this a try tonight and report here. Closing for now and thanks Plex for your great work!
