### ISSUE TITLE
Can't find the Settings / Manual Servers

### ISSUE THREAD

**Issue by fbricon** [plexinc/plex-media-player#461]
My server is not logged in online (on purpose). on PMP (1.2.0.481-b45bbf24-macosx-x86_64), after logging in in TV mode, I get this error message:

<img width="966" alt="00000483" src="https://cloud.githubusercontent.com/assets/148698/20823353/3df029c8-b821-11e6-8ff2-c1e92be58da2.png">

Switching to web mode, I can see no such "Manual Servers" entry in the Settings. I sense it must be there, looking at some JS files in the PMP app, but I'm clueless on how to access it.

So, could be a bug, or more likely a PEBCAK, in which case there could be some UX improvements here.

**Comment by LongChair** [comment]
@fbricon : is that still an issue or can we close it ? :)

**Comment by LongChair** [comment]
Closing due to the lack of feedback, feel free to reopen if needed.
