### ISSUE TITLE
[Raspberry Pi] [v1.2] Problem playing this item error

### ISSUE THREAD

**Issue by AlexOwen** [plexinc/plex-media-player#463]
If the pause or stop button are pressed while the video is loading (before playback starts) then an error saying "There was a problem playing this item" is shown instead of the correct action.

Hardware: Raspberry Pi 2, wired network
Software: v1.2, updated from v1.1.7

**Comment by wm4** [comment]
Can't reproduce. Though I guess it does depend heavily on the timing. Log?

**Comment by LongChair** [comment]
@AlexOwen : are you still having this issue ?

**Comment by LongChair** [comment]
Closing this due to the lack of feedback. 
Feel free to reopen if needed :)
