### ISSUE TITLE
Theme Music Option Missing in Web UI

### ISSUE THREAD

**Issue by KingJ** [plexinc/plex-media-player#465]
# Environment
- Platform: Windows 10 version 1607
- Plex Media Player app version: 1.2.0

# Brief Description
When using PMP in Web UI mode, theme music is not played. On the settings page, the option to enable Theme Music is missing.

# Reproduction
1) Browse to any TV show that would normally trigger a theme to be played when using Plex Web. No Theme Music will be played.
2) Browse to Settings -> Web -> General. The "Play Theme Music" option present in Plex Web's settings is absent from this page.

The lack of theme music and suppression of the option could be intentional however, and if so please treat this as a feature request rather than a bug report!

**Comment by MichaelRumpler** [comment]
My server has version 1.5.5.3634 and the Web interface 3.2.1 and I do have the option for Theme Music exactly where you described. Just try to update to the most recent version.
Maybe they added it back in the meantime and just ignore this issue?

**Comment by KingJ** [comment]
My server is currently running Version 1.7.2.3878, and both Plex Web as served by the server and the Plex Web bundled with Plex Media Player are running Version 3.7.0 of the Plex Web client. However, the "Play Theme Music" option is still missing from the Plex Media Player settings.

Here's a screenshot comparison of the settings page in Plex Media Player and Plex Web;

**Plex Media Player**
![plex media player settings](https://cloud.githubusercontent.com/assets/6966796/26714448/545b2172-4769-11e7-8858-ab94f5909373.png)

**Plex Web**
![plex web settings](https://cloud.githubusercontent.com/assets/6966796/26714451/560c676a-4769-11e7-9e8f-ecd61e89395e.PNG)

**Comment by MichaelRumpler** [comment]
Sorry, you are correct. I was looking in the Web interface. The Plex Media Player doesn't have it.

**Comment by KingJ** [comment]
No worries - your comment prompted me to add some screenshots which better demonstrates the problem anyway 😄 .

**Comment by atrus05** [comment]
Theme music in PMP has not yet been implemented. And with the risk of coming off as an asshole: The github repo is not for feature requests. Use the forum to convey your wishes for that.
(but rest assured that the team knows about the wishes to get theme music implemented)

Closing this one.

**Comment by KingJ** [comment]
@atrus05 My apologies, I originally thought the Theme Music omission was a bug when PMP first launched support for the Web UI. I'll check on the forums if there's an existing feature request and log a new one if not (but glad to hear that you're aware of the desite to get Theme Music on PMP already!).
