### ISSUE TITLE
Can't play file when server is not authenticated

### ISSUE THREAD

**Issue by bouscram** [plexinc/plex-media-player#466]
When Plex server is not authenticated (running on the same machine as PMP or remotely), it is impossible to play files. PMP connects to the server and shows the content (remotely, it works only if PMP is authenticated which I feel is not normal but may be "by design"), but when you try to play anything, there is a message saying "There was a problem" and that's all. The problem happens in web or TV UI.
When looking at the log file it looks like an authorisation problem.

My problem is on macOS, but another user has reported it in the Plex forums on Windows 10

[Plex Media Player.log.zip](https://github.com/plexinc/plex-media-player/files/629699/Plex.Media.Player.log.zip)

**Comment by anomaly15** [comment]
I've just recently purchased a Samsung Tizen TV running the PMP app and I have the exact same issue. Running Plex via web or uPnP works without an issue. I can't play any single file no matter what type or format.

I have tested trying to change file types (mkv, mp4 etc), encryption methods, ensuring that Plex has a location for the Temp Trans-coding directory and everything else I can think of with no success. I have a similar message given in the logs:


Jan 11, 2017 22:19:30.179 [7432] WARN - [ui-safari-tizen] [Connections] Possible connection error for NODE_Plex, retrying connection tests
Jan 11, 2017 22:19:30.210 [2040] WARN - [ui-safari-tizen] [PlayMedia] { "readyState": 4, "rid": "r377", "responseText": "<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>", "status": 401, "statusText": "error", "line": 381, "sourceURL": "file:///opt/usr/apps/kIciSQlYEM/res/wgt/plex-web/js/main.8274cebc94295fd0a9ed.js", "stack": "g@file:///opt/usr/apps/kIciSQlYEM/res/wgt/plex-web/js/main.8274cebc94295fd0a9ed.js:381:8\nu@file:///opt/usr/apps/kIciSQlYEM/res/wgt/plex-web/js/main.8274cebc94295fd0a9ed.js:416:86\nfile:///opt/usr/apps/kIciSQlYEM/res/wgt/plex-web/js/main.8274cebc94295fd0a9ed.js:416:414\nn@file:///opt/usr/apps/kIciSQlYEM/res/wgt/plex-web/index.html:29:26416" }
Jan 11, 2017 22:19:30.288 [7432] WARN - [ui-safari-tizen] [PlayMedia] Unable to queue item; failed to get next unwatched item
Jan 11, 2017 22:19:30.304 [2040] WARN - [ui-safari-tizen] [PlayMedia] Couldn't get the next item to play. code: 401
Jan 11, 2017 22:19:30.304 [7432] ERROR - [ui-safari-tizen] [PlayMediaCommand] Playmedia failed Couldn't get the next item to play. code: 401

**Comment by wm4** [comment]
I don't think that's PMP...

**Comment by nvnoorloos** [comment]
I am having the same issue on macOS after upgrading Plex server. I did not update my PMP version (using v1.2.2.555-d1355001, the latest).
The previous version of Plex server that was running, combined with this client, worked without problems. Unfortunately i am not sure which version of Plex Server this was...

**Comment by bouscram** [comment]
@anomaly15 : is your server authenticated ? Your client is different but the symptom seems very similar...

**Comment by anomaly15** [comment]
@bouscram Yes server is authenticated on local network.

**Comment by baurmatt** [comment]
I think i having the same issues. Running latest versions of PMP and PMS. If i try to play something on PMP it tells me "Sorry, there was a problem playing this item". Strange thing: If I use the iPhone Plex app as a remote control i can get PMP to play the media.

PMP log:

```
2017-04-13 23:20:53 [ DEBUG ] HTTPServer.cpp @ 165 - Incoming request to: "/player/navigation/select?commandID=473&X-Plex-Device-Name=Matthiass iPhone" from "192.168.2.4" 
2017-04-13 23:20:53 [ INFO  ] JS: [Commands] Executing playMedia 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Active connection to "st01" lost authorization 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Possible connection error for st01, retrying connection tests 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Testing all 2 connection(s) for st01 
2017-04-13 23:20:53 [ INFO  ] JS: [Servers] Found all servers = st01, plex.tv 
2017-04-13 23:20:53 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-04-13 23:20:53 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Active connection to "st01" lost authorization 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Possible connection error for st01, retrying connection tests 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Testing all 2 connection(s) for st01 
2017-04-13 23:20:53 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-04-13 23:20:53 [ INFO  ] JS: [Commands] Executing testServerConnection 
2017-04-13 23:20:53 [ INFO  ] JS: [PlayMedia] {
  "readyState": 4,
  "rid": "r1719",
  "responseText": "<html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>",
  "status": 401,
  "statusText": "error"
} 
2017-04-13 23:20:53 [ INFO  ] JS: [PlayMedia] Unable to queue or get next item to play. code: 401 
2017-04-13 23:20:53 [ INFO  ] JS: [PlayMediaCommand] Playmedia failed Unable to queue or get next item to play. code: 401 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Testing connection for st01 at http://127.0.0.1:32400/ 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] Testing connection for st01 at http://192.168.2.6:32400/ 
2017-04-13 23:20:53 [ INFO  ] JS: [Connections] st01 is unavailable at http://127.0.0.1:32400/ (Status 0) 
2017-04-13 23:20:54 [ INFO  ] JS: [Connections] st01 connected at http://192.168.2.6:32400/ 
2017-04-13 23:20:54 [ INFO  ] JS: [Servers] Found all servers = st01, plex.tv 
```

PMS log:

```
Apr 13, 2017 23:20:20.543 [0x7fa5443ff700] DEBUG - Request: [192.168.2.11:53138 (Allowed Network)] GET /library/metadata/12116?includeOnDeck=1 (8 live) GZIP
Apr 13, 2017 23:20:20.557 [0x7fa5443ff700] DEBUG - There were 1 top-level paths for Empire.
Apr 13, 2017 23:20:20.563 [0x7fa5443ff700] DEBUG - We're going to try to auto-select an audio stream for account 1.
Apr 13, 2017 23:20:20.563 [0x7fa5443ff700] DEBUG - Selecting best audio stream for part ID 12256 (autoselect: 0 language: en)
Apr 13, 2017 23:20:20.563 [0x7fa5443ff700] DEBUG - Audio Stream: 27423, Subtitle Stream: -1
Apr 13, 2017 23:20:20.563 [0x7fa5443ff700] DEBUG - It took 0.0 sec to serialize a list with 1 elements.
Apr 13, 2017 23:20:20.564 [0x7fa55bbfe700] DEBUG - Completed: [192.168.2.11:53138] 200 GET /library/metadata/12116?includeOnDeck=1 (8 live) GZIP 21ms 2701 bytes (pipelined: 90)
Apr 13, 2017 23:20:20.634 [0x7fa55c3ff700] DEBUG - Request came in with unrecognized domain / IP 'file' in header Origin; treating as non-local
Apr 13, 2017 23:20:20.635 [0x7fa55c3ff700] DEBUG - Request: [192.168.2.11:53138 (Allowed Network)] POST /playQueues?type=video&uri=library%3A%2F%2F9cfad10e-c96f-46a6-a10a-6fe5fd7ddfee%2Fitem%2F%252Flibrary%252Fmetadata%252F12663&key=%2Flibrary%2Fmetadata%2F12681&shuffle=0&repeat=0&includeChapters=1 (8 live) GZIP
Apr 13, 2017 23:20:20.635 [0x7fa55c3ff700] DEBUG - Completed: [192.168.2.11:53138] 401 POST /playQueues?type=video&uri=library%3A%2F%2F9cfad10e-c96f-46a6-a10a-6fe5fd7ddfee%2Fitem%2F%252Flibrary%252Fmetadata%252F12663&key=%2Flibrary%2Fmetadata%2F12681&shuffle=0&repeat=0&includeChapters=1 (8 live) GZIP 0ms 435 bytes (pipelined: 91)
Apr 13, 2017 23:20:20.758 [0x7fa5443ff700] DEBUG - Request: [192.168.2.11:53138 (Allowed Network)] GET / (8 live) GZIP
Apr 13, 2017 23:20:20.758 [0x7fa5443ff700] DEBUG - (Capabilities) Platform 'Konvergo' not matched by plugin platform requirements
Apr 13, 2017 23:20:20.759 [0x7fa5443ff700] DEBUG - (Capabilities) Platform 'Konvergo' not matched by plugin platform requirements
Apr 13, 2017 23:20:20.759 [0x7fa5443ff700] DEBUG - It took 0.0 sec to serialize a list with 22 elements.
Apr 13, 2017 23:20:20.760 [0x7fa55bbfe700] DEBUG - Completed: [192.168.2.11:53138] 200 GET / (8 live) GZIP 1ms 1200 bytes (pipelined: 92)
```

**Comment by anomaly15** [comment]
I eventually solved this problem, although it's not publically listed
anywhere I could find..

To use the smart TV apps you need to pay for a Plex subscription. Stupid it
does not tell you that anywhere as I spent countless hours trying to figure
out the problem

**Comment by lokkju** [comment]
I "claimed" my server with a plex account, and it worked.  Using Plex apps should not require that the plex server has been claimed.

**Comment by andrewleith** [comment]
Why oh why do I need internet access to view my local content through Plex running on my local machine? I get the direction you are moving in, but don't break basic use-cases.

**Comment by LongChair** [comment]
We haven't been able to reproduce that in latest versions.
We're closing this. Please check with latest versions when available and reopen an issue if needed.
