### ISSUE TITLE
PMP 1.2.0 at end segfault (Linux Ubuntu 14.04 (no blocking but can generate other problem)

### ISSUE THREAD

**Issue by father-mande** [plexinc/plex-media-player#467]
Hi,
Information more than real issue 
 When I exit P.M.P. (nothing visible on screen but in the output of command line)
______________________________________
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

Segmentation fault
______________________________________

Philippe.

**Comment by wm4** [comment]
Can you try running in gdb and getting a backtrace?

I don't get this on Linux - it always exits cleanly.

**Comment by father-mande** [comment]
Hi,

I will try ... it's a little complex ... so be patient, the "box" (NAS) use a good level of libraries from Ubunt 14.04 ... but was cleaned from lot of part of the Linux O.S. not need in a box like a NAS ...

I will return here when I get more information ...
BUT as I said ... this is not visible by "user" only if I launch manually PMP with the standard output on console ... (no trace on this in plexmediaplayer.log (even build with DEBUG))
AND as I can see after my own test ... PMP work fine with video acceleration ... 

so it's clearly an information ... more than a bug ... I don't know if in future Linux version come ... perhaps I am faulty in my build for NAS  ... 

Thanks a lot for this quick response ... and thanks to all the team for this incredible work.

Philippe.

**Comment by LongChair** [comment]
@father-mande : closing this as it's probably fixed by now.
