### ISSUE TITLE
Keymaps not working ("step_backward"  and "step_forward")

### ISSUE THREAD

**Issue by diagdave** [plexinc/plex-media-player#468]
Platform and OS version: Windows 10 [Version 10.0.14393]
Plex Media Player app version: Plex Media Player version: 1.2.0.481-b45bbf24 build date: 2016-11-30 
Brief description of the issue or bug:

Keys that are mapped have no affect (Custom in inbuilt)
Pressing the "Down" button during playback has the affect described: "jump backwards 10 minutes (or to the next chapter, if available)" 
Pressing the button keycode: "Media Previous" or any button assigned as  "step_backward" has no affect during playback.

Log:
2016-12-06 19:13:50 [ DEBUG ] InputComponent.cpp @ 152 - Input received: source: "Keyboard" keycode: "Media Previous" : InputBase::InputkeyState(KeyDown) 
2016-12-06 19:13:50 [ DEBUG ] InputComponent.cpp @ 223 - Emit input action: ("step_backward", "step_backward") 

Also the descriptions on https://support.plex.tv/hc/en-us/articles/216459997-Create-your-own-inputmap are the wrong way round for "step_backward"  and "step_forward"

**Comment by LongChair** [comment]
@diagdave : i guess this is fixed now, can we close this ?

**Comment by diagdave** [comment]
To be honest I haven't tried - I switched devices after a period of waiting for a fix.

**Comment by LongChair** [comment]
Thanks, haven't seen such reports recently, will close it.
