### ISSUE TITLE
Fullscreen state isn't preserved across relaunches

### ISSUE THREAD

**Issue by rcombs** [plexinc/plex-media-player#469]
I don't know what the platform convention on Windows is, but on macOS the standard behavior is to do this.

**Comment by tru** [comment]
it's is here.

**Comment by rcombs** [comment]
Not in desktop mode.

**Comment by tru** [comment]
Hmm. One thought: does this happen when you use the fullscreen button on the window compared to hotkey or the button in the UI?

**Comment by rcombs** [comment]
If I use the fullscreen button in the Web UI, or the hotkey, the app shifts into TV mode for some reason. Even then, on a relaunch, it returns to windowed mode (though it remains in TV mode).

**Comment by tru** [comment]
It works here. So I am not sure why.

**Comment by LongChair** [comment]
@rcombs : can we close this now ?

**Comment by rcombs** [comment]
Yeah this was fixed with my changes to let macOS handle window state reloading.
