### ISSUE TITLE
Support mouse wheel on scrollable areas

### ISSUE THREAD

**Issue by dogonwheels** [plexinc/plex-media-player#47]
PMP is intended to scroll when using the mouse wheel on scrollable containers.

**Comment by mseeley** [comment]
We support some lists although supporting it on all lists is absolutely a feature request.

**Comment by kayone** [comment]
The exact scrolling that is explained in the forums here https://forums.plex.tv/discussion/190164/feature-request-scroll-wheel-support works right now in chrome,

there are a few lists that don't support scrolling, (vertical lists and photo thumb strip thing) but what he describes can be solved by passing the proper scroll events to js code.

**Comment by tru** [comment]
Right now PMP disables all scrolling events in the host because it scrolled the viewport earlier. Maybe we can revisit that?

**Comment by mseeley** [comment]
Sounds like it could be interesting. Fair warning, we have only one device which scrolls via wheel so the implementation hasn't gotten a lot of love.

**Comment by edwin4321** [comment]
The scrolling should work horizontally in the main screen like it does on the windows plex app. without it it is very awkward to go through the list.

**Comment by tru** [comment]
@firasdib this is something to put on your back-burner I think. Let me know when you want to look into it and I can give you a build that enables the scrolling events again.

**Comment by firasdib** [comment]
Just a thought, you _should_ be able to disable viewport scrolling by setting `overflow: hidden` on body. I have not gone into this issue yet though, just thought I'd comment for the future.

**Comment by zerosquared** [comment]
Would really love to have this feature.

**Comment by Enigma0** [comment]
Very desirable functionality. No one has to use it but it should be possible for those that do.

**Comment by LongChair** [comment]
@markus101 : can we check if adding such feature is still possible ?

**Comment by markus101** [comment]
At this time we do not have plans to add mouse wheel support in the TV (fullscreen) mode.
