### ISSUE TITLE
UI mode not switching successfully [16.04]

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#471]
PMP freezes when I try to switch from one UI to another.

```
/usr/local/bin/pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by /usr/local/bin/pmphelper)
/usr/local/bin/pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/local/bin/pmphelper)
/usr/local/bin/pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by /usr/local/bin/pmphelper)
```

I just get those messages over and over when launching via command line. Where is it looking? I have qt 5.7 in `/opt/qt/`.

**Comment by edouardl** [comment]
use ldconfig : 
create a xxx.conf file in /etc/ld.so.conf.d/
inside write the path to your installation Qt 5.7.1 lib (example /opt/Qt5.7.1/5.7/gcc_64/lib)
and execute a "sudo ldconfig"

**Comment by Enigma0** [comment]
`xxx.conf` as in name it anything? `qt.conf` would work, no?

**Comment by mdesdin** [comment]
yes

**Comment by wm4** [comment]
I think you're confusing two things here:
- pmphelper not working
- GUI switching not working (as the title says?)

The latter is broken with qt 5.7.0 - you need a qt 5.7.1 snapshot.

**Comment by Enigma0** [comment]
@wm4 Well, technically the title is correct. PMP freezes when I try to switch from one UI to another.

I also happen to be seeing those pmphelper logs being printed repeatedly and drew the conclusion that they were related.

**Comment by mdesdin** [comment]
@wm4 i would say that @Enigma0 is mixing things together, @edouardl and I responded to the previous title and what we understand from the description, but the title was changed and now description and title are not related...

**Comment by mdesdin** [comment]
@Enigma0 IMO you should have closed this issue (when fixed of course) and open a new one for the new title, these 2 things are different

**Comment by Enigma0** [comment]
@mdesdin I changed the title because:

1. PMP launched to web view by default the first time
2. Switched to TV UI > PMP froze (created bug describing this)
3. Opened PMP again which defaulted to TV UI (worked - bug report was wrong)
4. Switched to web view -> PMP froze again (changed bug title to reflect)

It's not that the first issue was resolved, it's that there was no first issue.

**Comment by mdesdin** [comment]
@Enigma0 ok, understand, and probably natural...
But yes, there was a first issue and it is solvable with the answer given, but this issue was not relevant to the other issue you were observing and wanted to report.
And in general my suggestion still applies, for the issues to make sense to developers and to users looking for solutions, it is important for the title and description to be consistent. And for the thread to be focused... And this is becoming already off-topic, so I am stopping...

**Comment by Enigma0** [comment]
Installed Qt 5.7.1 snapshot per @wm4's suggestion: https://download.qt.io/snapshots/qt/5.7/5.7.1/588/qt-opensource-linux-x64-5.7.1_588.run

Recompiled and it's working now.
