### ISSUE TITLE
Can't change language in desktop mode

### ISSUE THREAD

**Issue by paviro** [plexinc/plex-media-player#473]
When I change the language in desktop mode and then click on save, it just endlessly displays the "saving spinner" and never actually saves anything..

Version: 2.1.0
System: macOS 10.12

**Comment by Skaronator** [comment]
Can confirm this on Windows 10 *and* 7

**Comment by rikyoz** [comment]
Same here on Windows 10.

**Comment by shapeace** [comment]
Plex Media Player For Mac is same.

**Comment by Skaronator** [comment]
I think it has been fixed in the next release. See https://github.com/plexinc/plex-media-player/commit/ac33741e504a845f92d8274f47cdc4ce3d710eac#diff-c0bce8c772740b70dc2817511b5c604bR9

**Comment by LongChair** [comment]
@paviro : can you confirm this is fixed now ?

**Comment by paviro** [comment]
Haven’t used the desktop client since then and I use another computer now so not sure if I can still verify :/

**Comment by shapeace** [comment]
Now disapeared Korean language in mac desktop mode. :(

**Comment by LongChair** [comment]
@markus101 : do we have an internal issue for that one ?

**Comment by LongChair** [comment]
@shapeace : korean language seems to be showing up here.
Which version are you running ?

**Comment by LongChair** [comment]
@shapeace : i’ll close that issue as the former issu’ is fixed;

feel free to open a new one for korean language with more details if needed
