### ISSUE TITLE
Settings not persistent between desktop mode and fullscreen mode

### ISSUE THREAD

**Issue by paviro** [plexinc/plex-media-player#474]
It is really irritating that settings changed in fullscreen mode have no effects on the desktop mode and desktop mode settings have no effect on the fullscreen mode. 

One application should not feel like two completely different apps after pressing a button.

Version: 2.1.0
System: macOS 10.12

**Comment by LongChair** [comment]
Dupplicated of https://github.com/plexinc/plex-media-player/issues/457. Closing.
