### ISSUE TITLE
Current PMP code not compatible with libcec-4.0.0

### ISSUE THREAD

**Issue by truckershitch** [plexinc/plex-media-player#475]
PMP will not compile with the new libcec version.  I am staying on libcec-3.1.0 for now.  Are there plans to move forward with this?

Thanks!

**Comment by wm4** [comment]
The new release is obviously API-incompatible to the older one. Which means we have to adjust the code, test it, etc. So yes we will, but it might take a while. Until then you need to use either 3.1.0, or disable libcec use. Hope that answers your question.

**Comment by LongChair** [comment]
@truckershitch : this is the commit that is needed to fix the build. But we need to sync all our builds to it before we merge that to master.

https://github.com/plexinc/plex-media-player/commit/819f4d07ea037a43c81badb3734a54bd91b78517
