### ISSUE TITLE
curl error when trying to grab nightlies

### ISSUE THREAD

**Issue by m00dawg** [plexinc/plex-media-player#476]
I've been trying to build PMP for a while but I keep running into the following, my guess due to connecting over IPv6 versus IPv4 perhaps?

###############################################################
tim@lindawg ~/git/plex-media-player/build $ cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.6.1/5.6/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Success
-- Not using bundled deps
-- Dependency hash is: 86a9354
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/86/konvergo-qt--release-86a9354.tbz2.sha.txt to konvergo-qt--release-86a9354.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:58 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/86/konvergo-qt--release-86a9354.tbz2.sha.txt:
  "HTTP response code said error"

    Trying 2400:cb00:2048:1::6814:609...

  Connected to nightlies.plex.tv (2400:cb00:2048:1::6814:609) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
###############################################################

The actually error, it looks like, isn't related to the project, but to a plex.tv issue, but since it affects the ability to build this, I thought I would log it here first.

**Comment by blackPantherOS** [comment]
Same error, I get 404 code as well

**Comment by tru** [comment]
Make sure that `QTROOT` option actually points to your Qt installation. Otherwise it tries to download one from our servers and we don't provide precompiled Qt versions for linux.

**Comment by blackPantherOS** [comment]
Right! Thank You.. 
I tried again, and now I have a probem with conan install because my account is "wrong".  
The packaging as standalone player for Linux users, I think so it is not possible without any active account. This is correct?

**Comment by tru** [comment]
you should be fine if you tried it earlier just try to blow away your ~/.conan dir and try again with the instructions.

**Comment by Skaronator** [comment]
Got the same issue on Windows:
```
D:\Workspace\plex-media-player\build>cmake -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=output ..
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Failed
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
dependencies are:
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/windows-redist/latest/hash.txt to windows-redist-latest-hash.txt...
-- Dependency hash is: 1
-- Directory D:/Workspace/plex-media-player/build/dependencies/windows-x86_x64-windows-redist/latest/windows-redist-2015-windows-x86_x64-release-1 already exists, remove it to redownload
-- Not using bundled deps
-- Dependency hash is: 86a9354
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/86/konvergo-qt-windows-i386-release-86a9354.tbz2.sha.txt to konvergo-qt-windows-i386-release-86a9354.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:58 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/86/konvergo-qt-windows-i386-release-86a9354.tbz2.sha.txt:
  "HTTP response code said error"
```

It is pretty unclear how to do it on Windows. Readme says:
```
Qt 5.6 (on OSX and windows it will be automatically downloaded when you run CMake)
cmake 3.1 or newer
ninja is recommended for building
FFmpeg 3.x and mpv from github
```

cmake -> okay
ninja -> drop ninja.exe in build folder (works)
scrolling down to linux install setup and see, that I need conan -> okay 'simple' install it via pip
... got some issues that a dependency of conan doesn't work with python 3.6 so downgrading to 3.5.3 and now it finally works.
Setup conan and install plex dependencys.

Now only FFmpeg and mpv left.. "download from github" but what to do with it? Compile it and drop the files... where?

**Comment by wm4** [comment]
You're not setting `QTROOT`. This is required.

> Now only FFmpeg and mpv left.. "download from github" but what to do with it? Compile it and drop the files... where?

Where cmake can find them. I'm not exactly sure where it does that by default on Windows. You can see the `MPV_INCLUDE_DIR` and `MPV_LIBRARY_DIRS` variables manually too. (PMP doesn't use FFmpeg directly, only libmpv.)

**Comment by Skaronator** [comment]
I though it will be automatically downloaded and enabled according to the Readme? (`on OSX and windows it will be automatically downloaded when you run CMake`)

I was drilling a bit deeper and it looks like the QT packages are downloaded in CMakeList Line 79 but my error (missing QT) start throwing a error in line ~58 so it can't even reach the point to download QT.

**Comment by wm4** [comment]
That statement isn't true anymore and hasn't been for quite a while. You need to provide Qt (and set `QTROOT`). I updated the instructions.

**Comment by Skaronator** [comment]
Pretty confusing if you start from zero.

Got Qt up and running the only thing left are`MPV_INCLUDE_DIR` and `MPV_LIBRARY_DIRS`. Should `INCLUDE_DIR` linking to the Github Repo and `LIBRARY_DIRS` to my compiled file folder? Or is it self compiling?

**Comment by wm4** [comment]
Both variables point to directories on the filesystem. You have to compile libmpv yourself, or get prebuilt binaries from somewhere else.

**Comment by Skaronator** [comment]
Alright got it now nearly working. Only have one issue with the file location of my compiled mpv

Compiled with: `cmake -GNinja -DMPV_INCLUDE_DIR=C:\msys64\home\Skaronator -DMPV_LIBRARY_DIRS=C:\msys64\home\Skaronator\mpv\libmpv\ -DQTROOT=C:\Qt\Qt5.7.1\5.7\msvc2015_64 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=output ..`

```
CMake Error at CMakeModules/PlayerConfiguration.cmake:19 (message):
  Missing mpv/qthelper.h - maybe your mpv version is to old?
Call Stack (most recent call first):
  CMakeLists.txt:63 (include)
```

It's looking for `mpv/qthelper.h` but the file is in reality at `mpv/libmpv/qthelper.h`


Whatsoever just copy pasting this folder in the root folder.. ¯\_(ツ)_/¯

**Comment by wm4** [comment]
The include path is normally `mpv/qthelper.h`, so you need to rename that directory.

**Comment by LongChair** [comment]
That should be fixed by now.
