### ISSUE TITLE
Can no longer use Desktop mode in fullscreen

### ISSUE THREAD

**Issue by RZeroX** [plexinc/plex-media-player#477]
Worked fine in 1.2.0 it would go fullscreen in desktop mode but in the latest version it can only be windowed and when pressing alt+enter it will set itself to the tv mode when I would rather use the desktop mode as I'm not running this on any sort of tv.

**Comment by RobinHoutevelts** [comment]
I'm having the same issue after updating to `1.2.1.494-7e6bbc6f`

**Comment by Steltek** [comment]
Same issue here.in 1.2.3. It even seems to have an option to lock the non-fullscreen version to TV mode, but no option to get rid of TV mode.

**Comment by wm4** [comment]
Have you tried Shift+F11? (On Mac it's Ctrl+Cmd+F11)

**Comment by Steltek** [comment]
I didn't. It didn't cross my mind that there might be a different keyboard shortcut affecting this behaviour, and the 'layout' option that I found merely had 'automatic' and 'tv' as options.

I can confirm that that does work though. (User discoverability could be improved though.)
