### ISSUE TITLE
Plex Media Player does not launch on macOS

### ISSUE THREAD

**Issue by prasselpikachu** [plexinc/plex-media-player#478]
I'm running macOS Sierra 10.12.2 and PMP 1.2.1.494

After acknowledging Gatekeeper, PMP just instantly closes itself. This also happens every time I relaunch the application.

There are no logs in ~/Library/Logs/Plex Media Player, in fact the directory does not even get created.
When directly launching the executable from Terminal (working directory /Applications/Plex Media Player.app/Contents/MacOS, ./Plex\ Media\ Player), the only output I get is this:

```
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by tru** [comment]
That's a non-issue. Can you check if you have crash dumps in ~/Library/Caches/Plex Media Player?

**Comment by prasselpikachu** [comment]
A directory structure is created (Caches/Plex Media Player/crashdumps/incoming/1.2.1-7e6bbc6f) but there is nothing inside

**Comment by tru** [comment]
it means it's uploaded already. I'll have a look in our system if I can find your report.

**Comment by prasselpikachu** [comment]
Did you find something or should I give you any more details to help find the report?

**Comment by prasselpikachu** [comment]
I don't know what you did or if you even did something, but it suddenly works now...
