### ISSUE TITLE
PMP hijacks audio and forces macOS into accesibilty mode

### ISSUE THREAD

**Issue by thibmaek** [plexinc/plex-media-player#479]
https://forums.plex.tv/discussion/249756/bug-plex-media-player-puts-macos-in-sound-accessibility-mode-behind-the-screens#latest

**Comment by wm4** [comment]
Is exclusive mode enabled or disabled in the PMP audio settings?

**Comment by thibmaek** [comment]
Couldn't find that setting, below is a screenshot of my settings
![image](https://cloud.githubusercontent.com/assets/6213695/21766581/a3a49fee-d66f-11e6-80ad-7096be980033.png)

**Comment by wm4** [comment]
We currently have the unfortunate situation that this setting can be only viewed/changed in TV mode. So you need to switch to TV mode, and then look at the TV mode settings. Most of them also apply to desktop mode.

**Comment by thibmaek** [comment]
This fixed it. Would still keep this open as a bug though since this occurred on a clean (first) install of PMP without touching settings and ever switching to TV mode.

**Comment by wm4** [comment]
We've set the default to exclusive mode off a few releases ago. This might have been a leftover from an older installation. Or possibly confusion due to TV mode settings being inaccessible in desktop mode, but still affecting it.

Cleaning up the settings handling is still work in progress, but I think the root of this particular issue has been found. Closing this then.

**Comment by thibmaek** [comment]
So exclusive is the default? If this is the case I think it's rather a blunt move to disable system audio in favor of the Plex app… Having my system audio fail me after I watched a movie or show is not justified

**Comment by wm4** [comment]
No - it used to be on by default, now it's off by default. But the new default doesn't affect config files migrated from old/updated installations.

**Comment by thibmaek** [comment]
Does it also count for Plex Home Theater installs then? I never used PMP before I had this issue, only PHT

**Comment by wm4** [comment]
No, only PMP installs.
