### ISSUE TITLE
Request to PIN on every startup

### ISSUE THREAD

**Issue by dogonwheels** [plexinc/plex-media-player#48]
from - https://forums.plex.tv/discussion/188494/plex-media-player-is-requesting-to-be-paired-every-time-it-starts

"I enter the pin at plex.tv/pin and media player continues on. I exit from the player and it requests to be paired the next time it starts. I'm running Win10 x64."

Log here:
https://15254b2dcaab7f5478ab-24461f391e20b7336331d5789078af53.ssl.cf1.rackcdn.com/plex.vanillacommunity.com/editor/mp/mtpboob8m0el.log

**Comment by tru** [comment]
Possibly related to #11 ?

**Comment by tru** [comment]
I think that this was fixed so I will close this one and we can re-open if this is still a problem.
