### ISSUE TITLE
Unable to download web clients for PMP 1.2.0

### ISSUE THREAD

**Issue by jleroy** [plexinc/plex-media-player#480]
I want to upgrade my PMP RPM to 1.2.0, which is the last version compatible with Fedora 23 and 24, which does not ship Qt 5.7.

But Conan ask for a username/password: 
```
+ conan install ..
web-client-tv/2.10.8-7de1963@plex/stable: Not found, looking in remotes...
web-client-tv/2.10.8-7de1963@plex/stable: Trying with 'conan.io'...
web-client-tv/2.10.8-7de1963@plex/stable: Trying with 'plex'...
Please log in to "plex" to perform this action. Execute "conan user" command.
Remote 'plex' username:
```

I don't have this problem with PMP 1.2.1. Could you please remove this protection?

**Comment by tru** [comment]
Change stable to public in the conanfile.py

**Comment by mfelipec** [comment]
I was already with the public

from conans import ConanFile, CMake
import os

class PlexMediaPlayer(ConanFile):
  settings = "os", "compiler", "build_type", "arch"
  options = {"include_desktop": [True, False]}
  default_options = "include_desktop=True"
  generators = "cmake"

  def requirements(self):
    self.requires("web-client-tv/2.10.8-ade70eb@plex/public")

    if self.options.include_desktop:
      self.requires("web-client-desktop/2.12.5-9b613e8@plex/public")

**Comment by jleroy** [comment]
Thank you @tru.
