### ISSUE TITLE
cmake Error 443

### ISSUE THREAD

**Issue by mfelipec** [plexinc/plex-media-player#483]
$ cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.6.1/5.6/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..

`-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Success
-- Not using bundled deps
-- Dependency hash is: 86a9354
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/86/konvergo-qt--release-86a9354.tbz2.sha.txt to konvergo-qt--release-86a9354.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:58 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/86/konvergo-qt--release-86a9354.tbz2.sha.txt:
  "HTTP response code said error"

    Trying 104.20.7.9...

  Connected to nightlies.plex.tv (104.20.7.9) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  TLSv1.2 (OUT), TLS header, Certificate Status (22):
`

**Comment by tru** [comment]
See #476
