### ISSUE TITLE
Regression: HLS: Can't fast forward

### ISSUE THREAD

**Issue by meriko** [plexinc/plex-media-player#486]
https://github.com/plexinc/plex-media-player/issues/384

The issue is back, just try any channel utilizing HLS

**Comment by meriko** [comment]
My test channel is very good for verifying both live streams and on demand:
https://github.com/meriko/HLSTestChannel.bundle

**Comment by meriko** [comment]
https://forums.plex.tv/discussion/248522/kanaler

**Comment by wm4** [comment]
Logs and such?

I know I said this in #384, but we should probably update FFmpeg. The version used for current PMP builds is getting pretty old.

**Comment by meriko** [comment]
This works correctly now
