### ISSUE TITLE
Fullscreen on Windows cannot be reverted

### ISSUE THREAD

**Issue by m3xiz** [plexinc/plex-media-player#487]
The 2-arrow button to put a video in fullscreen is now working. However when the video reaches the end, it closed and pmp stays in fullscreen. There is no way to go back in normal mode without having a video playing.

**Comment by tru** [comment]
You can use F11 for now. We are adding another button later.

**Comment by m3xiz** [comment]
@LongChair : yes this is solved. A double arrow has being added.

Thanks

**Comment by LongChair** [comment]
Thanks
