### ISSUE TITLE
ellipse menu in left action bar is not visible, in preplay screen

### ISSUE THREAD

**Issue by billyvnillly** [plexinc/plex-media-player#489]
windows 10, only the top two menu options are visible. the rest of the menu is off the screen.

**Comment by OttoKerner** [comment]
this is a Plex Web issue. And it is already known.
Disable screen scaling on your machine.

**Comment by billyvnillly** [comment]
its a htpc, I have no intention of shrinking font/scale across the board to fix this, but thanks for the reply ;)
