### ISSUE TITLE
Custom script for play/pause/stop

### ISSUE THREAD

**Issue by Ruvetuve** [plexinc/plex-media-player#49]
Running a Python or Bash file when you play/pause or stop an episode or movie.

e.g. To send commands to the Philips Hue Bridge for turning lights on/off or dim the lights when a movie is paused.

**Comment by sjorge** [comment]
Why stop for play/pause/stop.

It would be nice to hook into all sorts of events in PMP. e.g. server found, server left, remote connected,... cec changes...

**Comment by RSully** [comment]
I'd like get/set access to play, pause, and current timestamp for [ShowSync](https://github.com/pickledcode/showsync). Currently using [PHT's websockets](https://github.com/PickledCode/ShowSync/blob/59523aeaf0a00ec437e4c159ecf5047f75076c0d/ShowSync/Interfaces/Plex/SSPlexInterface.m#L55).

**Comment by Ruvetuve** [comment]
Not urgent anymore for myself, i use this plugin for Philips Hue integration: https://github.com/ledge74/HelloHue

**Comment by tru** [comment]
I don't think we have this on our roadmap for now. You can get the status via the companion protocol for now.

**Comment by RSully** [comment]
@tru where can I learn about using that? The only result from a quick web search is [this thread](https://forums.plex.tv/discussion/118659/plex-companion-protocol-api) with no replies. 

Does that allow control, or just fetching status? I'd need both for my app. I presume this is what the iOS remote uses, so surely it can do all of the above?

**Comment by tru** [comment]
https://github.com/plexinc/plex-media-player/wiki/Remote-control-API
