### ISSUE TITLE
Please revert annoying change to navigation of "On Deck" items

### ISSUE THREAD

**Issue by martenjacobs** [plexinc/plex-media-player#491]
After having skipped a few versions of PMP, I recently updated my clients. After this, I noticed an annoying change in behavior to navigation when accessing an episode from the "On Deck" section of the home screen. 
Previously, I was able to continue watching an episode from a show, and after finishing I'd use the right arrow in the top right corner to advance to the next episode of the same show. In this version, however, doing this navigates to the next episode available in the "On Deck" section, which is usually from a completely different TV show. 
This is really annoying, as the show I was watching has now disappeared from "On Deck", so I have to navigate to the TV Shows section, find the show in the list, guess which season I was watching, and find the correct episode to continue watching. This may only happen to TV shows that are being re-watched (and have already been marked as watched).
I suggest reverting to the previous behavior, or at least creating a setting to restore previous behavior.

**Comment by jabbera** [comment]
I've got to echo this comment.

**Comment by martenjacobs** [comment]
Any update on this?

**Comment by martenjacobs** [comment]
I think it still works this way in version 1.
2 is not released on embedded platforms yet, so it's still current.

**Comment by martenjacobs** [comment]
After some further inspection, it seems that so far as I can see, there is no further development on v1.3.x. As the cause for this issue does not exist in v2 because of the many UI-changes, I think it can be closed.

**Comment by LongChair** [comment]
Thanks
