### ISSUE TITLE
Add typical generic MCE remote keys to default LIRC config

### ISSUE THREAD

**Issue by ptr727** [plexinc/plex-media-player#492]
I am using a MCE compatible remote, typical (openELEC) mappings in LIRC.json for home and debug are missing.

Please add to https://github.com/plexinc/plex-media-player/blob/master/resources/inputmaps/LIRC.json

"KEY_MENU": "home"
"KEY_INFO": "host:toggleDebug"
"KEY_HOME": "home"
"KEY_DVD": "home"
"KEY_EPG": "home"

Attached is my config.
[LIRC.txt](https://github.com/plexinc/plex-media-player/files/672387/LIRC.txt)

**Comment by wm4** [comment]
Can you make a PR with this change? (Also read https://forums.plex.tv/discussion/188192/plex-media-player-open-source-contributions-and-building-faq#latest)

**Comment by ptr727** [comment]
Ok
https://github.com/plexinc/plex-media-player/pull/498

**Comment by wm4** [comment]
The PR was merged, closing this.
