### ISSUE TITLE
FR: Skip on-deck library sub-pages

### ISSUE THREAD

**Issue by miigotu** [plexinc/plex-media-player#502]
If there is a way for me to make a modification to this behavior and compile myself, please point me to the location of the code to start, thanks.

I think it is enough to have on-deck widget on the front page, which already switches to whatever library you have selected on the left column.  There is no need to show the same on-deck for that library when you click into the library, I think it should go right into `Browse All` rather than having a sort of interstitial page.  Trying to watch an episode by not using on-deck is cumbersome because of this.

Click into library
Click browse all (without on-deck interstitial this can be avoided, and there is no lost functionality)
Click show

Click play
OR
Click season
Click episode

Could this be added as an option in the settings if nothing else? I know you want to keep options to a minimum :1st_place_medal: but this would be awesome.

**Comment by LongChair** [comment]
@miigotu : as most of the interface changed with v2 can we close this ?

**Comment by miigotu** [comment]
https://github.com/plexinc/plex-media-player/issues/501#issuecomment-380349313

**Comment by miigotu** [comment]
Ill check now

**Comment by miigotu** [comment]
v2 is sufficent to close this FR. highlighting the option shows the old categories and clicking goes to the browse all view. I'll reserve my thoughts on the vertical scroll, it's going to take some getting used to haha.
