### ISSUE TITLE
502 error from conan.io on install

### ISSUE THREAD

**Issue by trustdarkness** [plexinc/plex-media-player#505]
Following build instructions, conan install .. step fails as below.  Same with AUR.

$ conan install ..
web-client-tv/2.10.8-fd540f9@plex/public: Not found, looking in remotes...
web-client-tv/2.10.8-fd540f9@plex/public: Trying with 'conan.io'...
ERROR: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
. [Remote: conan.io]

**Comment by trustdarkness** [comment]
conan remove remote conan.io fixed this, but will leave open just in case you want to fix something on the backend.

**Comment by LongChair** [comment]
We're not using anymore conan for now so clising this :)
