### ISSUE TITLE
Yellow lightning icon in top right corner on Raspberry Pi 2 has no information

### ISSUE THREAD

**Issue by jakobrosenberg** [plexinc/plex-media-player#506]
I have a consistent flashing yellow lightning icon in the top right corner of Plex Media Player. The plexmediaplayer.log shows no information about this icon.

**Comment by jabbera** [comment]
You need a better power supply or USB cable for power.

https://www.raspberrypi.org/forums/viewtopic.php?t=82373

**Comment by wm4** [comment]
Yep, nothing PMP related.
