### ISSUE TITLE
Mouse arrow visible in interface and during playback

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#508]
The mouse arrow is visible in the interface and sometimes during playback on my Mac Mini, OSX Sierra. This was an issue in El Cap as well.

Fool proof way of making it happen. Well one of the ways at least:

1. Open PMP. Make sure the mouse arrow shows, and then disappears after a few seconds.
2. CMD-TAB out to desktop, then CMD-TAB back to PMP.

Expected result: Mouse arrow should show, then disappear after a few seconds.

Actual result: Mouse arrow shows, and never disappears.

This happens with the latest special build (1.2.2.566-0451a0df) and with latest Ninja build as well (.555)

**Comment by atrus05** [comment]
The arrow also appear and never goes away if a OSX system reminder has shown up on top of PMP. Even if the reminder then goes away, the arrow remains and I have to go find the keyboard.

**Comment by atrus05** [comment]
I can still get this to happen by starting PMP and leaving the mouse pointer in the place where the PMP icon is in the Dock.

**Comment by LongChair** [comment]
related to #503 and #210

**Comment by mseeley** [comment]
Closing in favor of #503 and #210.
