### ISSUE TITLE
"ffmpeg: tls: Unable to decrypt message" leads to "unrecognized file format" in interface

### ISSUE THREAD

**Issue by Arno500** [plexinc/plex-media-player#509]
Hello !
On an Optimus laptop (Asus N75SF) with broken video card, I can't get any video playing.
The player is on Windows 7 with PMP 2.12.6 and the server is on Arch-Linux (and playing works fine with other devices).
The error occurs when playing ANY video, of ANY format (even the most common H.264
 with AAC which plays fine in Google Chrome in Direct Play, I tried MPEG4 with MP3 sound, everything).
The log is attached here (which look more practical than putting into code marks) :
[PlexMediaPlayer.txt](https://github.com/plexinc/plex-media-player/files/740343/PlexMediaPlayer.txt)

It doesn't looks like the problem is lied to the graphic card (which is anyway disabled and only used for HDMI output, so no problems so far + hardware acceleration disabled).

Thanks,
Arno

**Comment by Arno500** [comment]
Just a quick update to add that it doesn't work with the graphic card after repair.

**Comment by wm4** [comment]
Yeah, this appears to be a problem with HTTPS. The Windows API call `DecryptMessage` is failing. Reason unknown. Is there anything broken with Secure Channel aka Schannel on your system?

**Comment by Arno500** [comment]
I don't know how to teste it, nor found a way. I also don't know why it is failing like that. The problem I now have is that the ribbon cable of the keyboard is broken (and since this is a laptop, this is what power on the computer).
While waiting for a repair, do you know if the classic sfc /scannow and dism /restore-health could help ?

**Comment by wm4** [comment]
No, I don't know if that helps.

**Comment by Arno500** [comment]
Oops, forgot to add status... Sorry.
I don't know the current state since I don't use that machine anymore, but I think this is : 
- Fixed by a new release,
- Or a problem in the system of the laptop (and it has nothing to do on Plex's Github),

So yeah, I'm closing the issue

Thanks for your fast support 👍 !
