### ISSUE TITLE
refresh "on deck" after screensaver

### ISSUE THREAD

**Issue by Skaronator** [plexinc/plex-media-player#510]
My Pi3 is running 24/7 and it would be good if it refresh the whole UI after reactivating from screensaver.

Example: Watching a episode on a different devices and going back to TV and it would still show the old stuff in "On Deck"

**Comment by perrottg** [comment]
Also need to refresh after switching users or adding new content to the server.   

The only way I can get PMP to reliable refresh is to reboot.   This is for the embedded version.

**Comment by LongChair** [comment]
Ok closing then :)
