### ISSUE TITLE
On MacOS, ⌘+W should close the window, not quit

### ISSUE THREAD

**Issue by steveh** [plexinc/plex-media-player#513]
This is pretty much the same as minimizing it with the yellow button.

Having it quit is pretty frustrating when you just want the window out of the way.

**Comment by vguerci** [comment]
On OSX, <kbd>⌘</kbd>+<kbd>W</kbd> (close window, that does not work on Plex), usually does not quit, but it does on apps like Plex, single window ones... And it is a normal behaviour, look at OSX System Preferences for instance.
Alternatively, <kbd>⌘</kbd>+<kbd>H</kbd> (hide) works for the scenario you describe.

**Comment by tru** [comment]
CMD+M should also work to minimize. We might rework this later - but it's not something happening soon.
