### ISSUE TITLE
Plex Media Player App on Nvidia Shield Issue

### ISSUE THREAD

**Issue by jdcranke07** [plexinc/plex-media-player#514]
I'm not sure if my issue is a known one or not and I just wanted to bring it to light if it isn't. I don't know how to get logs from the Nvidia Shield either, so hopefully my description is detailed enough to help.

My problem: When trying to skip to the next episode in a TV show season, before the current episode is finished (i.e. skipping the credits type of thing), and before the 10 second countdown for the next episode starts, my player on my Nvidia Shield gives an error that says it cannot connect to my server and asks to "Retry" or "Cancel". I hit "Retry" and the same error just persists till I hit "Cancel" and back out to the individual episode menu/description and manually start the next episode. If I do not attempt to skip the last few seconds of the current episode and let the countdown just auto-play into the next episode, nothing goes wrong.

My setup: I have a wired high speed cable modem attached to the wall (Model: Arris Surfboard 6190). This is connected to my Netgear Nighthawk X6 (R8000), which has my Nvidia Shield and my Asus RT-AC88U (setup in AP mode) hard lined with CAT7 directly. From the Asus AP, I have my media server and my workstation hard lined. I only use Wifi for my network printer and mobile devices such as laptops and phones. All devices have current versions of their operating systems; the Shield uses Android OS and my media server uses Windows 10 Pro.

My media server specs:
CPU: Intel i7-4790K OC'd to 4.8Ghz
Motherboard: Gigabyte GA-Z97MX-Gaming 5
RAM: G.SKILL Ripjaws Z Series 8GB (4 x 2GB) 2133Mhz (Model F3-17000CL9Q-8GBZH)
GPU: EVGA GeForce GTX 970 4GB SC+ GAMING ACX 2.0
NIC: Intel Ethernet Server Adapter I340-T4
Storage: Samsung SM951 128GB M.2 (x1); Seagate 2TB NAS HDD SATA 6Gb/s 64MB (x4 in RAID5)
PSU: EVGA SuperNOVA 650 P2

**Comment by wm4** [comment]
There is no PMP on Shield - that's another Plex client.

**Comment by jdcranke07** [comment]
1. What do you mean by PMP?
2. What are you talking about that's another client? To my knowledge the app that is on the Shield is the same as the one you can get on your Android phone since they both come from the exact same place.

The point I seem to be failing at is that you need to explain it instead of just saying that's different. How about pointing me in the right direction, if you either don't know or I am in the wrong place. Unfortunately, there is no correct place other than here, since this deals with Plex in general and I have seen all versions spoken about here. So, elaborate.

**Comment by LongChair** [comment]
Insulting people over here won't get you anywhere.

As mentionned before, there is No Plex Media Player for ShielD TV.
What you are probably looking for is the Android TV Plex Client for which you can get support there : http://forums.plex.tv/categories/google-tv-amazon-fire-tv

Make sure to use a proper language next time you ask for help.

**Comment by jdcranke07** [comment]
Considering I'm not part of your discourse that becomes difficult to decipher that you have your own language, so my apologies for not downloading that first. My point to WM4 was that they should've done what you had and actually been helpful considering it was apparent I had no idea where to post, which was stated in my OP.

As far as the Shield goes, I see no indication that it is a PMP or Plex TV or anything other than an application that is put on the Google Play Store for Androids to use. If you mean that PMP is only the web browser version that can be pulled up on a PC, that's understandable, but without clarification and not knowing your "language" makes that hard to relay to you folks. But, it is a full fledged application you can download onto your Shield, just like all other mobile and streaming devices and just like the one you can download from the Microsoft Store for Windows 8.1 and 10.

I'll take a look at the link you provided and thank you for your efforts, but remember that not everyone is involved with your mom's basement circle jerks.

**Comment by LongChair** [comment]
Here is one more link that would give you an overview of how many client Apps Plex provides.

https://support.plex.tv/hc/en-us/categories/200006953-Plex-Apps
