### ISSUE TITLE
PMP Continue Watching state being continually sent/kept alive even though nothing playing

### ISSUE THREAD

**Issue by BigWheel88** [plexinc/plex-media-player#520]
This is a weird issue so might not be describing issue symptoms completely. Here is forum post regarding it. https://forums.plex.tv/discussion/257851/watched-files-keep-returning-to-continue-watching-watched-times-keep-changing

STR

1. load PMP  (change to Windowed mode )
2. Start watching something, scan through a few minutes 
3. Click  X cross top right to stop watching, film/episode will show in continue watching screen
4. repeat for different film/show episode, now 2 items in "continue watching"
5. Click on ... for first item watched and click "mark watched"
6. watch something else for a few seconds then close with X top right
7. you will now find 2 items in "continue watching" (including the one you "marked watched") and one may be having the odd progress bar change as seen in video linked below 

( video is of desktop mode of PMP, not the web app in browser )

https://www.youtube.com/watch?v=uKSMm2jGykA

**Comment by daften** [comment]
I have the same issue with PMP on Mac OS X. As long as it is open, marking something as watched does basically nothing. It's like even though nothing is playing, it keeps reporting those items as having a certain progress.
Closing PMP and marking as watched from Plex Web (through plex.tv) works. Haven't tried any other clients to see which ones have the issue, but so far, it seems isolated to PMP.

**Comment by kazdegroot** [comment]
Same here

**Comment by iFredOS** [comment]
Same here! This problem happened after the version 1.4.2 of the Server. I going crazy to see 6 movies in Continue Watching reappear after they are already marked watched. 🙄

**Comment by LongChair** [comment]
@BigWheel88 : i suppose this has been fixed since then right ?

**Comment by LongChair** [comment]
@daften @kazdegroot @iFredOS : could you guys update me on this issue please ? is that still valid ?

**Comment by kazdegroot** [comment]
Haven't had issues with it in the past few months.

**Comment by LongChair** [comment]
ok will close it then, feel free to reopen if needed.
