### ISSUE TITLE
Playback issues with AC3 files 

### ISSUE THREAD

**Issue by ViktorRibchev** [plexinc/plex-media-player#529]
Hi, 
I'm having playback issues with Plex v. 5.6.1.505 on my Android TV 55PUS6501 (version:000.006.152.000 Android 6.0.1) when viewing files with AC3 audio. Plex server is running on Win 10 PC (OS Build 14393.693). 
When playing files with AC3 audio from Plex app on the TV the sound plays well but the picture freezes. Tried with Passthrough option set to Auto/Disabled, but the result is the same. This occurs with every file with AC3 audio. 

Plex settings on TV:
* Direct play - Auto
* Direct stream - On
* Refresh rate switching - Off
* Local quality - Original
* Remote quality - Original

The PC and TV are connected via gigabit router. 
I'm playing files with AAC audio without any troubles. 
There are no issues when casting from the PC to the TV. 
Log file: [Plex log.txt](https://github.com/plexinc/plex-media-player/files/836456/Plex.log.txt)

**Comment by DaveBinM** [comment]
That's not Plex Media Player, but Plex for Android. PMP is only for windows, macOS, Linux, or as an embedded player. 

For Android TV issues, please log to the forum 😊

**Comment by ViktorRibchev** [comment]
Oh ok, thanks please close the issue.
