### ISSUE TITLE
PMP 1.3.0, 1.2.5 & 1.2.4 crashes! (was: PMP 1.2.3 breaks HLS streams => ffmpeg HTTP error 403 Forbidden)

### ISSUE THREAD

**Issue by magnuslsjoberg** [plexinc/plex-media-player#533]
With PMP 1.2.3 some HLS streams are no longer working. Something with authentication may have changed between 1.2.2 and 1.2.3.

With 1.2.2 it works perfectly well but with 1.2.3 the streams will not start. Switching back to 1.2.2 and it works again. The behaviour is exactly the same on both Mac OSX and Raspberry Pi 3.

One major difference between the logs is the following line in 1.2.3:
[ WARN  ] PlayerComponent.cpp @ 504 - ffmpeg: http: HTTP error 403 Forbidden 

Log (excerpts) from PMP 1.2.2 and 1.2.3 attached. Both tests run on my MacBook with nothing else changed.

I will try to continue troubleshooting and see if I can find the actual cause...

[PMP1.2.2.zip](https://github.com/plexinc/plex-media-player/files/862986/PMP1.2.2.zip)
[PMP1.2.3.zip](https://github.com/plexinc/plex-media-player/files/862985/PMP1.2.3.zip)

**Comment by magnuslsjoberg** [comment]
Reviewing the diffs between 1.2.3 and 1.2.2 I can't find any change in the PMP source code that could cause this error. 

PlayerComponent.cpp @ 504 is a MPV_EVENT_LOG_MESSAGE from mpv and since the log line also says ffmpeg: I guess that something has changed in either mpv or ffmpeg.

If anyone knows where I can find the exact versions of mpv used in 1.2.2 and 1.2.3 it would greatly help further analysis.

**Comment by wm4** [comment]
Yes, that's pretty weird. Maybe some HTTP headers are not correctly set. Can you create a mpv-conf text file in the PMP settings dir, and put the line `msg-level=all=trace` into it, and then post new PMP logs while trying to play it? That should dump the HTTP requests.

**Comment by magnuslsjoberg** [comment]
Excellent!

I will try that once I get home from work.

The stream comes from a pay site and since the url is intact it make sense that something is missing in the headers.

Thank you for your fast and helpful reply!

**Comment by magnuslsjoberg** [comment]
Here comes the PMP log with msg-level=all=trace enabled. 

[Plex Media Player.log.txt](https://github.com/plexinc/plex-media-player/files/862460/Plex.Media.Player.log.txt)

**Comment by magnuslsjoberg** [comment]
After analysis of the logs in my last post I found a possible cause!
In PMP1.2.3 the user agent is different between two consecutive calls and I guess that is why Akamai returns 403.

1.2.3:
```
2017-03-22 19:22:29 [ DEBUG ] PlayerComponent.cpp @ 500 - ffmpeg: User-Agent: mpv git-5e677e5
...
2017-03-22 19:22:30 [ DEBUG ] PlayerComponent.cpp @ 500 - ffmpeg: User-Agent: Lavf/57.57.100
...
2017-03-22 19:22:30 [ DEBUG ] PlayerComponent.cpp @ 500 - ffmpeg: http: header='HTTP/1.0 403 Forbidden' 
```
while in 1.2.2:
```
2017-03-22 20:52:37 [ DEBUG ] PlayerComponent.cpp @ 512 - ffmpeg: User-Agent: mpv git-07f2251
...
2017-03-22 20:52:37 [ DEBUG ] PlayerComponent.cpp @ 512 - ffmpeg: User-Agent: mpv git-07f2251
...
2017-03-22 20:52:37 [ DEBUG ] PlayerComponent.cpp @ 512 - ffmpeg: http: header='HTTP/1.0 200 OK'
```

**Comment by magnuslsjoberg** [comment]
I added 
```
[protocol.http]
user-agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0'
``` to mpv.conf and all ffmpeg http requests will use that user agent except the same one as before which is still using `User-Agent: Lavf/57.57.100`

I would guess that this is a bug in the ffmpeg version used in PMP1.2.3

**Comment by magnuslsjoberg** [comment]
Also tried setting
```
[protocol.http]
user-agent='Lavf/57.57.100'
````

But then PMP will crash...

[PMP1.2.3-lavf.log.txt](https://github.com/plexinc/plex-media-player/files/863638/PMP1.2.3-lavf.log.txt)

**Comment by wm4** [comment]
Ah, I remember a user-agent issue with ffmpeg not propagating it down to secondary request. Also, it shouldn't crash. I'll try to reproduce and fix these issues.

**Comment by magnuslsjoberg** [comment]
Thank you for looking into this!

Please let me know if you want me to do any other tests, otherwise I will stop my investigations for now.

**Comment by magnuslsjoberg** [comment]
Related: https://trac.ffmpeg.org/ticket/5358

**Comment by wm4** [comment]
Yes, it was recently fixed in FFmpeg.

I couldn't reproduce a crash though, only wrong user agents.

**Comment by wm4** [comment]
So if you compile PMP yourself, updating ffmpeg/mpv will be sufficient, otherwise you'll have to wait until we make new builds with updated deps.

**Comment by magnuslsjoberg** [comment]
Thanks a lot for your help!

Haven't really felt the need to compile myself, but perhaps now is the time to setup the build environment...

**Comment by magnuslsjoberg** [comment]
Unfortunately things have gone from bad to worse...
PMP 1.2.4 will instead crash when trying to play the stream... (and other streams from the same website)
[PMP1.2.4.log.txt](https://github.com/plexinc/plex-media-player/files/888618/PMP1.2.4.log.txt)

**Comment by magnuslsjoberg** [comment]
PMP 1.2.5 has exactly the same behaviour as 1.2.4 and just abrubtly crashes with no interesting info in the log. I didn't manage to get a working build when I tried with 1.2.4 but I will try again to see if I can find out what is going on...

[PMP1.2.5.log.txt](https://github.com/plexinc/plex-media-player/files/908518/PMP1.2.5.log.txt)

**Comment by wm4** [comment]
Crash UUIDs might be helpful (if shitty sentry doesn't rate-limit-filter them...)

**Comment by magnuslsjoberg** [comment]
2017-04-09 22:14:28 [ DEBUG ] CrashUploader.cpp @ 70 - Crashdump: "/Users/Magnus/Library/Caches/Plex Media Player/crashdumps/processing/1.2.5-0b42eb77/019809A1-044F-4E4E-B281-22E620B212C4.dmp" 
2017-04-09 22:14:28 [ INFO  ] CrashUploader.cpp @ 80 - Uploading crashdump: "/Users/Magnus/Library/Caches/Plex Media Player/crashdumps/processing/1.2.5-0b42eb77/019809A1-044F-4E4E-B281-22E620B212C4.dmp" 
2017-04-09 22:14:38 [ INFO  ] CrashUploader.cpp @ 133 - Submitted crash report with uuid: "019809A1-044F-4E4E-B281-22E620B212C4"

**Comment by wm4** [comment]
Apparently sentry filtered this one, and I can't find it.

Anyway, things you could do:
- Update to Sierra (50/50 chance the bug is fixed)
- Build PMP yourself (99% chance this will fix the bug)
- Send more crash UUIDs

**Comment by wm4** [comment]
Actually we probably have a solution for this, but it has to wait until next week.

**Comment by magnuslsjoberg** [comment]
!.3.0 crashes in the same manner.
`2017-04-19 21:00:37 [ DEBUG ] CrashUploader.cpp @ 70 - Crashdump: "/Users/Magnus/Library/Caches/Plex Media Player/crashdumps/processing/1.3.0-dc59dda3/87C57AE0-2491-4801-8BCD-7EDCB4ABF29A.dmp" 
2017-04-19 21:00:37 [ INFO  ] CrashUploader.cpp @ 80 - Uploading crashdump: "/Users/Magnus/Library/Caches/Plex Media Player/crashdumps/processing/1.3.0-dc59dda3/87C57AE0-2491-4801-8BCD-7EDCB4ABF29A.dmp" `

`Apr 19 21:00:34 MagBook Plex Media Player[44821]: dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
	  Referenced from: /Applications/Plex Media Player 1.3.0.app/Contents/MacOS/../Frameworks/libavutil.55.dylib
Apr 19 21:00:34 MagBook Plex Media Player[44821]: dyld: Symbol not found: _clock_gettime
	  Referenced from: /Applications/Plex Media Player 1.3.0.app/Contents/MacOS/../Frameworks/libavutil.55.dylib
Apr 19 21:00:34 MagBook com.apple.xpc.launchd[1] (tv.plex.player.200992[44821]): Service exited with abnormal code: 6`

[PMP1.3.0.log.txt](https://github.com/plexinc/plex-media-player/files/937514/PMP1.3.0.log.txt)

**Comment by wm4** [comment]
Actually that looks new, and is a completely different issue. Looks like a known ffmpeg build issue an Apple change recently introduced.

**Comment by magnuslsjoberg** [comment]
All solved by the version given in https://github.com/plexinc/plex-media-player/issues/547#issuecomment-296779197

**Comment by magnuslsjoberg** [comment]
The official 1.3.0 versions for Mac and Raspberry both work so I consider this issue solved.
