### ISSUE TITLE
PMP crashes at startup

### ISSUE THREAD

**Issue by mrThirsty** [plexinc/plex-media-player#534]
Hi,

I have just updated to the Plex Pass release of 16 March 2017, and now PMP crashes at startup.

Platform: MacBook Pro, Mac OS X 10.12.3
PMP: 1.2.3.589-59a54305
To reproduce: start PMP

I have attached all the logs from today for PMP.

[PMP logs.zip](https://github.com/plexinc/plex-media-player/files/861104/PMP.logs.zip)

**Comment by atrus05** [comment]
@mrThirsty Do you have the same issue with the latest release? If not, please close this GHI.

**Comment by WangQiru** [comment]
@mrThirsty Any chance you are running an app called Contexts?

**Comment by atrus05** [comment]
Closing this since the GHI creator has not replied.
