### ISSUE TITLE
Watched/Unwatched issues

### ISSUE THREAD

**Issue by rjwerth** [plexinc/plex-media-player#535]
In a TV series, the total number of Unwatched episodes does not reflect the actual amount of episodes unwatched.  The only way to "fix" this is to mark all episodes as watched/unwatched.

**Comment by LongChair** [comment]
Is that still an issue with recent builds or can we close this ?

**Comment by rjwerth** [comment]
Which issue are you asking about?

Robert Wertheimer
Spectacle Lighting Design
734-547-5657

**Comment by LongChair** [comment]
@rjwerth : well the GH issue we're talking in about Watched / unwatched :)

**Comment by LongChair** [comment]
Closing this due to the lack of feedback, feel free to reopen if needed.
