### ISSUE TITLE
Plexmediaplayer cannot find libmpv.so.1, crashes on start

### ISSUE THREAD

**Issue by anthonybilinski** [plexinc/plex-media-player#538]
Running ubuntu 16.04, following the readme installation guide for linux, and installing Qt 5.8.0, I compiled pmp and libmpv from tip (1847d0509cebbe7de82d7908135d8f9295c9f18f) and am getting the following error when running plexmediaplayer:

`$ plexmediaplayer`
`plexmediaplayer: error while loading shared libraries: libmpv.so.1: cannot open shared object file: No such file or directory`

even though ldd can find libmpv which is under /usr/local/lib
`$ ldd /usr/local/bin/plexmediaplayer | grep libmpv`
`	libmpv.so.1 => /usr/local/lib/libmpv.so.1 (0x00007f3824477000)`

Strace shows a permission problem:
`open("/usr/local/lib/libmpv.so.1", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)`

but the file is world read and executable:
`ls -l /usr/local/lib/libmpv.so.1`
`lrwxrwxrwx 1 root root 16 Feb  9 20:37 /usr/local/lib/libmpv.so.1 -> libmpv.so.1.24.0`
`ls -l /usr/local/lib/libmpv.so.1.24.0`
`-rwxr-xr-x 1 root root 27872856 Mar 22 22:17 /usr/local/lib/libmpv.so.1.24.0`

**Comment by wm4** [comment]
> open("/usr/local/lib/libmpv.so.1", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)

That's just how the system's dynamic linker opens shared libs. So this must be a problem entirely related to your system (and nothing with PMP or mpv).

It's really strange how
1. ldd does not print an error (it also opens the libmpv!)
2. starting plexmediaplayer shows a mismatching error from strace (EACCES != "No such file or directory")
3. there is nothing that indicates it shouldn't work

I guess try whether `md5sum /usr/local/lib/libmpv.so.1` in the same terminal/context as where you're trying to run pmp works (or anything similar that reads the file contents). Also make sure `which plexmediaplayer` shows the right location.

That's just some generic Linux help, and there's most likely no PMP problem, so closing this.

**Comment by anthonybilinski** [comment]
This was kind of a last ditch effort, I agree it's probably an environment problem.

In case anyone else comes across this ticket:

- md5sum libmpv.so.1 or file libmpv.so.1 (and file libmpv.so.1.24.0 through the symlink) all work
- which plexmediaplayer gives /usr/local/bin/plexmediaplayer which is the one I'm running (tried again with absolute path)

**Comment by anthonybilinski** [comment]
This was due to badly custom configured apparmor for plexmediaplayer, FYI. Nothing to do with this project.
