### ISSUE TITLE
Weird Background Artwork Issue

### ISSUE THREAD

**Issue by tsromana** [plexinc/plex-media-player#539]
I love Plex Media Player as it plays everything without transcoding and as it has the web-ui interface as well.
However, I'm having issue with the background artwork.

Example:
![image](https://cloud.githubusercontent.com/assets/12875008/24317066/6317a8aa-10ca-11e7-95d8-9b5a056690cb.png)

**Comment by tsromana** [comment]
**Updates to latest version:**
Windows 7 SP1 or later (64-bit only).
1.2.5.606-0b42eb77
April 5, 2017

**_However, still facing the same issue._**

**Comment by LongChair** [comment]
@tsromana : is that still an issue with recent builds ?

**Comment by tsromana** [comment]
i was facing this issue on plex cloud but currently i have stopped using it and the issue does not occur on self hosed instance.

**Comment by LongChair** [comment]
Thanks for the feedback !

@markus101 : does this ring any bell ?

**Comment by markus101** [comment]
It doesn't, the fact that it was only happening with the cloud server leads me to believe it was an issue with the image transcoding to get a blurred image for the background, not a web issue. If we can get confirmation that it's still an issue then I think we need to file an issue in the right repo, but given the age it may have already been fixed.

**Comment by LongChair** [comment]
@tsromana : any chance you can get this rechecked ?
If not i’ll probably close this.

**Comment by LongChair** [comment]
@tsromana : will close it for now, if you get a chance to retest it and reproduce it, feel free to reopen it :)
