### ISSUE TITLE
audio playlist issues

### ISSUE THREAD

**Issue by Gerk** [plexinc/plex-media-player#54]
Overall strange behaviour noted so far with 1.0.13

Play icon showing up in wrong location.
![screen shot 2015-10-23 at 6 41 45 pm](https://cloud.githubusercontent.com/assets/172505/10706691/f57ff2da-79b6-11e5-8937-b173e3f169b2.png)

When hitting the last song in the list it was "lost" (no longer showed up in the list as the item playing).  After this the first 7 items in the list also disappeared (Plex Mix list), and then numbers 8-14 were duplicated twice.  Pics included.

![screen shot 2015-10-23 at 6 46 34 pm](https://cloud.githubusercontent.com/assets/172505/10706673/d3b10676-79b6-11e5-9a38-44aeeab35d17.png)

![screen shot 2015-10-23 at 6 47 15 pm](https://cloud.githubusercontent.com/assets/172505/10706676/d6257d74-79b6-11e5-9227-c76a9e0d43f9.png)

**Comment by Gerk** [comment]
Steps to reproduce the play icon in wrong spot:

1. Navigate to an album within a music section
2. Navigate to a specific song, press enter to start playing
3. after entering play screen press esc to go back

**Comment by tru** [comment]
@firasdib can you check if this is still a problem and maybe we can get a easy fix for it.

**Comment by firasdib** [comment]
I can't reproduce this specific issue, can you still reproduce it @Gerk (please try with the latest version)?

**Comment by atrus05** [comment]
It has already been fixed: https://github.com/plexinc/plex-web-client/issues/3632

**Comment by firasdib** [comment]
Thanks @atrus05
