### ISSUE TITLE
PMP don't start on macOS with latest FFMPEG

### ISSUE THREAD

**Issue by JSMSC** [plexinc/plex-media-player#542]
I'm building PMP from source for a long time. 
Work's well with Qt 5.7.1 and also 5.9-beta.
But when I build PMP wit the latest HEAD of FFMPEG it won't start. Just get the beachball and have to force quit PMP. 
The only solution at this time is copying the components from FFMPEG HEAD 03.27.2017.

Any ideas or suggestions?

**Comment by wm4** [comment]
Did you try to rebuild both ffmpeg and then libmpv properly?

**Comment by JSMSC** [comment]
Yes of course, my common way to build PMP is:
FFMPEG HEAD at first,
then build mpv,
check that mpv is working with the related FFMPEG libraries
and at least build PMP. 
Worked perfectly well until FFMPEG HEAD 03.27.2017. After that date I get PMP not working with the new libraries.

**Comment by wm4** [comment]
What does it say.

**Comment by JSMSC** [comment]
Nothing. Only got the Beachball until I force quit. 
The log is also nearly empty:

2017-04-03 02:48:49 [ INFO  ] Log.cpp @ 115 - Starting Plex Media Player version: 1.2.4.dev-22aa60bb build date: 2017-04-03 
2017-04-03 02:48:49 [ INFO  ] Log.cpp @ 116 -   Running on: macOS Sierra (10.12) [16.6.0] arch x86_64 
2017-04-03 02:48:49 [ INFO  ] Log.cpp @ 117 -   Qt Version: 5.7.1 [x86_64-little_endian-lp64] 
2017-04-03 02:48:49 [ DEBUG ] UpdateManager.cpp @ 45 - No Update directory found, exiting

**Comment by wm4** [comment]
That last message only means it's exiting the update code, not PMP.

This is a bit hard to debug...

Does the official build work?

**Comment by JSMSC** [comment]
The official builds are working. 
Also the ones I build on my on are working if I replace the actual dylib's:
 
libavcodec.57.dylib
libavfilter.6.dylib
libavformat.57.dylib
libavresample.3.dylib
libavutil.55.dylib
libmpv.1.dylib
libswresample.2.dylib
libswscale.4.dylib
libuchardet.0.dylib

with the shared libraries which are dated on the 03.27.2017.

Seems that one of them confuses the player.

**Comment by JSMSC** [comment]
My actual ffmpeg libraries are:

ffmpeg version: N-45084-g08117a401

libavutil      55. 60.100
libavcodec     57. 92.100
libavformat    57. 72.100
libavdevice    57.  7.100
libavfilter     6. 84.100
libavresample   3.  6.  0
libswscale      4.  7.100
libswresample   2.  8.100
libpostproc    54.  6.100

mpv git-bb3e152

libmpv            1.24.0

which ones are included in the actual 1.2.5 nightly build?

**Comment by wm4** [comment]
mpv something based on 94e82bcdb8, ffmpeg not sure right now.

**Comment by JSMSC** [comment]
Working again with latest FFmpeg (N-45359-g492553700) and latest mpv (git-591d99a) since commit **bcaf7ca** on Sierra with Qt-5.9 beta2.

**Comment by wm4** [comment]
I think it was actually a problem with libmpv - an odd corner case at startup that only PMP triggered.
