### ISSUE TITLE
No sound since 1.2.3

### ISSUE THREAD

**Issue by vguerci** [plexinc/plex-media-player#543]
For _some_ reason, plex will not list my S/PDIF output, because of mpv I presume:
```
$ mpv --audio-device=help
List of detected audio devices:
  'auto' (Autoselect device)
  'alsa' (Default (alsa))
  'alsa/hdmi:CARD=PCH,DEV=0' (HDA Intel PCH, HDMI 0/HDMI Audio Output)
  'alsa/hdmi:CARD=PCH,DEV=1' (HDA Intel PCH, HDMI 1/HDMI Audio Output)
  'jack' (Default (jack))

$ aplay -L
... >> removed some entries
iec958:CARD=PCH,DEV=0
    HDA Intel PCH, ALC889 Digital
    IEC958 (S/PDIF) Digital Audio Output
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
```

So setting manually in conf `"device": "alsa/iec958:CARD=PCH,DEV=0"` was doing the trick.
But since 1.2.3, because of 419948d96747a437859d7b1977fc9902db140f0a, it does not anymore, no audio, device being now listed as `Disconnected device:`.
Any ideas?

_([Side note about logs](https://github.com/plexinc/plex-media-player/commit/419948d96747a437859d7b1977fc9902db140f0a#commitcomment-21585035))_

**Comment by wm4** [comment]
mpv git master should (since a while ago) not blacklist iec958 in device listing anymore, so this should work.

**Comment by LongChair** [comment]
@vguerci : i guess we can close this now ?

**Comment by vguerci** [comment]
Gave up on Plex on that box one year ago...
Upgraded to 2.8 today and issue is solved, everything is working :)

**Comment by LongChair** [comment]
@vguerci : good to hear thanks :)
