### ISSUE TITLE
[Suggestion] Plex on Nintendo Switch

### ISSUE THREAD

**Issue by AxelBriche** [plexinc/plex-media-player#546]
Hello, any chance to see Plex on the new Nintendo Switch?

Nintendo Switch can:
- Display 720p in portable mode on a beautifull screen
- Display 1080p on TV like ps4 and xbox one.

Nintendo has sell +100 millions Nintendo Wii in the world and the Nintendo Switch have a better launch (http://www.polygon.com/2017/3/6/14837026/nintendo-switch-sales-record-zelda-breath-of-the-wild).

Imagine you watching a movie with Plex on your TV with the Nintendo Switch and take the Switch for continue the movie in an another room of the house (or outside the house! Like car, garden, etc.) without stop the movie playback. With the Nintendo Switch, it's possible.

**Comment by wm4** [comment]
Whether we would do this would very much depend on the technical details. Anyway, I don't think we answer product planning questions on this issue tracker, so I'm closing this.

**Comment by justinkterry** [comment]
@AxelBriche If you want to make a formal feature request post it on the plex pass feature request forum. Those are actually read.
