### ISSUE TITLE
Plex Media Player Crashes when starting a show on the NBC (or ABC) Channel

### ISSUE THREAD

**Issue by CunninghamHome** [plexinc/plex-media-player#547]
I am trying to run Plex Media Player on my iMac but it crashes when initiating any show on the NBC channel. 

The iMac is running El Capitan 10.11.6

The Plex Media Player says version 3.0.1 but I installed it from PlexMediaPlayer-1.2.4.597-5c146f2c-macosx-x86_64.zip

Steps to repeat:
click Plex icon, Plex opens to user selection page
Select user (any will do,  all operate the same)
select channels
select NBC
select Blindspot (any will do, all operate the same)
select full episodes
select the play button, circle rotates for about 5 seconds then app window disappears

[Plex Media Player.log.zip](https://github.com/plexinc/plex-media-player/files/904581/Plex.Media.Player.log.zip)

I have a Macbook Pro running Sierra and a Windows PC that work correctly

**Comment by wm4** [comment]
So it works on Sierra? Any reason you want to continue using El Capitan?

**Comment by CunninghamHome** [comment]
Apple won't let me update my 2009 iMac to Sierra.

**Comment by magnuslsjoberg** [comment]
Not trying to hijack anything, but this looks a lot like my problems (see #533).

Please add a file 'mpv.conf' next to your 'plexmediaplayer.conf' and add 'msg-level=all=trace' as @wm4 suggested to me and upload new logs. 

If we compare the logs I think we will see the same pattern. (which is that ffmpeg just dies without warning...)

**Comment by CunninghamHome** [comment]
I created a mpv.conf text file in the PMP settings dir, and put the line msg-level=all=trace into it, see log file.  Also I updated to the latest version of PMP, i.e. PlexMediaPlayer-1.2.5.606-0b42eb77-macosx-x86_64
[Plex Media Player.log.zip](https://github.com/plexinc/plex-media-player/files/945927/Plex.Media.Player.log.zip)

**Comment by wm4** [comment]
Is it intentional that you closed this?

We'll post a new test build soon enough (not sure if today).

**Comment by CunninghamHome** [comment]
Sorry didn't mean to close it

**Comment by wm4** [comment]
Wanted to make a new test build, but CI failed. Blargh. Maybe next week.

**Comment by wm4** [comment]
New test build, 200% untested: https://nightlies.plex.tv/public-test/plexmediaplayer/public-testing/1.3.0.630-4e57adb1/
(I don't even know if it starts.)

**Comment by magnuslsjoberg** [comment]
Well, that definitely solved all problems I had in #533.
Thanks a lot for your excellent work!

**Comment by CunninghamHome** [comment]
Great, now ABC and NBC work, so far so good.  Thanx for your efforts!

**Comment by wm4** [comment]
Thanks for testing and for your patience.
