### ISSUE TITLE
Post-Play UI Freeze

### ISSUE THREAD

**Issue by BrianInAz** [plexinc/plex-media-player#548]
I experienced a post-play freezing issue this evening. I finished watching a show at just after midnight (2017-04-08). When the media item's pre-play screen came back up, the <> arrows at the top were not drawn and my remote presses did not have any effect for ~30 seconds and then at around 12:01 the <> drew on the screen and all my remote keypresses sped through. Really felt like it was hung up trying to process something.

I have no idea what is causing this. It happens intermittently but always after I have watched something and it brings up the pre-play screen. Otto seemed to feel that it happened when you had played something from a hub. Paul noted experiencing this as well (same behavior re: <> delayed drawing and everything).

[PMPLogfiles.zip](https://github.com/plexinc/plex-media-player/files/907297/PMPLogfiles.zip)
[Plex Media Server Logs_2017-04-08_00-03-45.zip](https://github.com/plexinc/plex-media-player/files/907298/Plex.Media.Server.Logs_2017-04-08_00-03-45.zip)

*I've enabled debug logging on PMS to hopefully get some more detail on whats happening.

**Comment by BrianInAz** [comment]
During chat in Slack, it was discussed that changing the date and reloading PMP to get a correct clock may be contributing to this (or I should at least rule it out). 

I will reload PMP and see if this UI freezing continues.

**Comment by timgonzales** [comment]
Can confirm this happens to me as well. Re-installing latest version of PMP on my HTPC running Win10 still exhibits the same issue: the <> navigation icons in the bar up top on some media items takes a while to render, at which time any remote inputs I make aren't registered as the UI is pretty much frozen. Once the <> icons do show up, any remote inputs I made go through. This issue is inconsistent though; it only happens on some library items.

**Comment by timgonzales** [comment]
Hopefully a dev eventually sees this, because even after several updates to Plex Media Player, this issue still exists on my HTPC.

**Comment by LongChair** [comment]
@BrianInAz : is this still relevant or can we close ?

**Comment by BrianInAz** [comment]
It still happens in the PMP on my rPI3. Seems to happen when navigating via hubs. I believe Otto also sees it. 

I can try to grab some logs the next time it happens if you like. Had difficulty replicating it 100% of the time, but I encounter it regularly during my daily use.

**Comment by LongChair** [comment]
@BrianInAz : yeah logs would be appreciated to see if we can spot anything obvious there :)

**Comment by LongChair** [comment]
@markus101 : is that one known ?

**Comment by markus101** [comment]
I don't think I've seen or heard of this one before now.

**Comment by LongChair** [comment]
@BrianInAz does this also happens with tv2 now ?

**Comment by markus101** [comment]
Closing as this was a v1 issue based on the logs.
