### ISSUE TITLE
conan.plex.tv seems to not work

### ISSUE THREAD

**Issue by wjwwood** [plexinc/plex-media-player#549]
I was trying to build plex-media-player from source using the instructions in the README.md:

https://github.com/plexinc/plex-media-player#install-conan-dependency-fetcher

but I get this when trying to setup conan:

```
$ conan remote add plex https://conan.plex.tv

It seems to be the first time you've ran conan
Auto detecting your dev setup to initialize conan.conf
Found gcc 5.4
Default conan.conf settings
  os=Linux
  arch=x86_64
  compiler=gcc
  compiler.version=5.4
  compiler.libcxx=libstdc++
  build_type=Release
*** You can change them in ~/.conan/conan.conf ***
*** Or override with -s compiler='other' -s ...s***


WARN: Remotes registry file missing, creating default one in /home/SOMEUSER/.conan/registry.txt

$ conan search -r plex *@*/public
ERROR: HTTPSConnectionPool(host='conan.plex.tv', port=443): Max retries exceeded with url: /v1/conans/search?q=%2A%40%2A%2Fpublic (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efd783d6210>: Failed to establish a new connection: [Errno 113] No route to host',))

Unable to connect to plex=https://conan.plex.tv
```

I tried removing my ~/.conan` folder and starting over as was suggested here:

https://forums.plex.tv/discussion/247285/build-pmp-from-scratch

But that didn't work.

Some other details:

```
$ conan --version
Conan version 0.21.2

$ cat `which conan` |grep python
#!/usr/bin/python

$ git remote -v; git log -1; git branch; git status
origin	git://github.com/plexinc/plex-media-player (fetch)
origin	git://github.com/plexinc/plex-media-player (push)

commit e6ac73c2996768bd470bc18e1e21958fc65af29e
Author: Mark McDowall <markus.mcd5@gmail.com>
Date:   Thu Apr 13 09:14:13 2017 -0700

    Set version to 1.3.0

* master

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by Starbix** [comment]
Yeah also doesn't work for me. I kinda think they made that on purpose.

**Comment by tru** [comment]
Def not on purpose. It might be down. I will ask someone on call to investigate. Most of our staff is off on Easter Holiday and conan server being down would block new build internally as well.

**Comment by wesleung** [comment]
Please try again as I think I fixed the issue.  Due to DHCP change that had a ripple effect of changing the VM ip

**Comment by Starbix** [comment]
Thank you for fixing it. I thought you took it down because you don't want people to build PMP with newer versions

**Comment by Starbix** [comment]
You guys nailed the new design. I love it. The scaling still needs some work on macOS though

**Comment by wjwwood** [comment]
Yup, it's working again for me too, thanks!
