### ISSUE TITLE
Pressing Shift + Letter doesn't jump to proper place in channels

### ISSUE THREAD

**Issue by Gerk** [plexinc/plex-media-player#55]
Just like the comment says, works in all the library views as expected, but within channels it doesn't work.

**Comment by mseeley** [comment]
I wonder how this shortcut would work with a list sorted by usage vs alphabetical.

**Comment by Gerk** [comment]
poorly :)  (but it jumps to the first item with that letter)

**Comment by mseeley** [comment]
Was 'fraid of that.  A big part of me wants to file an separate bug to disable Shift + Letter for non-alpha sorts. We hide the A-Z bar in this case as well.

Maybe then support sorting channels by alpha and last-used. Allow Shift+Letter jumping in all alpha sorted lists seems logical.

**Comment by Gerk** [comment]
I'm behind any of that.  I wasn't even sure that there was any kind of sorting option in channels, it doesn't make sense for a lot of that stuff as there's not enough metadata to do much aside from alpha sort -- it's not required to have dates and stuff, it can be pretty loosey-goosey.  But on alpha listings it would be great for sure.  Actually now that I think about it there's also no A-Z bar in channels -- don't forget that these are a bit of an exception, once you're in a channel there's pretty much nothing except the "list" view currently.

**Comment by tru** [comment]
@mseeley do you want me to keep this open, is it something we plan to address?

**Comment by mseeley** [comment]
Hi Tobias. No, no plans to address. Although this:

> Was 'fraid of that. A big part of me wants to file an separate bug to disable Shift + Letter for non-alpha sorts. We hide the A-Z bar in this case as well.

Could be a reasonable path. Popping myself off the assignee.
