### ISSUE TITLE
No Audio Settings, incorrect version reported

### ISSUE THREAD

**Issue by sprig** [plexinc/plex-media-player#550]
See attached on OSX 10.12.4

<img width="1264" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2652983/25356720/f05ed1d4-2943-11e7-8b58-9f99b02367b8.png">

I see no way to get a version other than displayed above, which is inconsistent with release versions.

**Comment by LongChair** [comment]
This is the web application version, which is unrelated to PMP version.
Audio settings are only available in tv app.

I’m unsure to understand what you are expecting from us here... can you please be more specific ?

**Comment by LongChair** [comment]
Closing due to the lack of feedback.
Feel free to reopen with more details if needed.
