### ISSUE TITLE
Casting UI visible despite PMP not being able to cast.

### ISSUE THREAD

**Issue by sprig** [plexinc/plex-media-player#552]
See photo below
<img width="437" alt="screenshot" src="https://cloud.githubusercontent.com/assets/2652983/25456166/ccc65100-2ada-11e7-8432-b79a4381fe80.png">

**Comment by markus101** [comment]
PMP in Desktop is capable of casting, but only to other Plex clients, not Chromecast devices.

**Comment by sprig** [comment]
Thanks!
