### ISSUE TITLE
CEC with Plex Companion

### ISSUE THREAD

**Issue by tomb18** [plexinc/plex-media-player#555]
Hello,
I am attempting to use the android app as a Plex Companion with the latest PMP to adjust the volume on my Denon AVR. Changing the volume does not work on the receiver.  Is it not supposed to?

**Comment by LongChair** [comment]
CEC is a protocol between your TV and your receiver. When you use your TV remote to adjust volume, it will send the CEC command throught the HDMI line to your receiver.
Using companion will use a totally different protocol. 
So yes, currently this is expected.
