### ISSUE TITLE
Wrong Artwork in DVD Order

### ISSUE THREAD

**Issue by Javerre** [plexinc/plex-media-player#556]
Shows such as "Foyles War" which have different seasons from Aired order to DVD order show the wrong artwork for episodes. The artwork for the Aired Order episode is displayed instead of the artwork for the DVD Order episode. Other metadata (episode description, episode name) is fetched correctly.

See for example:
![s05e02 broken souls](https://cloud.githubusercontent.com/assets/28461216/25765434/08e02b1e-31e5-11e7-9a1a-6a9a96574baf.png)
vs TVDB info
![tvdb](https://cloud.githubusercontent.com/assets/28461216/25765460/219cebec-31e5-11e7-94ff-ab683902933c.png)

**Comment by atrus05** [comment]
@javerre I assume the only mate is also wrong in your PMS interface. PMP shows what PMS has. If that is the case, then this is not a PMP issue.

**Comment by Javerre** [comment]
Apologies, not a PMP issue
