### ISSUE TITLE
[REQ] Instructions on how to build PMP for Amlogic

### ISSUE THREAD

**Issue by brimur** [plexinc/plex-media-player#559]
With access to the latest LibreELEC 8 source code for the Wetek Hub (Amlogic S905H) thanks to Raybuntu here 
https://github.com/Raybuntu/LibreELEC.tv can someone provide build instructions so I can use the code above to build an embedded PMP installation for my Wetek Hub? 

Thanks

**Comment by LongChair** [comment]
There is no official version for amlogic and Wetek Hub.
Kodi / LE use different decoding engines than ours.
The hardware decoding is not supported due to the "bad" API that amlogic provides.
So i'll be closing this :)
