### ISSUE TITLE
[HDMI-CEC] not configurable to poweroff HTPC/tv/receive

### ISSUE THREAD

**Issue by sjorge** [plexinc/plex-media-player#56]
It would be nice if PMP closed (or better shutdown the HTPC) when it gets the power off command via CEC.

The otherway around would also be nice if you close PMP/shutdown it sends the signal to TV (and AV Receiver)

**Comment by LongChair** [comment]
PMP will have settings in the configuration file in next build so that when it gets the CEC standby command it shutdowns / Suspend the PMP machine (should it support it).

Those settings will not be available from GUI at first, but you will be bale to edit them in config file manually.

**Comment by sjorge** [comment]
By next build... do you mean the one released today?

**Comment by tru** [comment]
No it will be in 1.0.2

**Comment by sjorge** [comment]
On Windows EventGhost can take control CEC and do all those things, until PMP supports it. For those looking for a work around.

**Comment by LongChair** [comment]
@sjorge : this is the same issue as #675 , so will close this one and we can follow up there.
