### ISSUE TITLE
Performing Test QT5_HAVE_OPTIMALORIENTATION - Failed

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#560]
Following the steps to build & using `Qt5.8.0` in `/opt`

Does this failure matter?

Is it documented somewhere?

Build seems to complete despite other log issues but wondering if the application would see benefits from this?

```
-- Qt root directory: /opt/Qt5.8.0/5.8/gcc_64/
-- Qt version: 5.8.0
-- Performing Test QT5_HAVE_OPTIMALORIENTATION
-- Performing Test QT5_HAVE_OPTIMALORIENTATION - Failed
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found MPV: /usr/local/include  
-- /opt/Qt5.8.0/5.8/gcc_64/
```

**Comment by wm4** [comment]
This matters only on Windows with ANGLE. On Windows, ANGLE will by default perform a GPU copy of the screen to invert the coordinate system, because OpenGL and Direct3D have flipped coordinate systems. On Linux, this is not needed because native OpenGL is always used.
