### ISSUE TITLE
Could NOT find SDL2 (missing:  SDL2_INCLUDE_DIR SDL2_LIBRARY)

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#561]
Installing `libsdl2-dev` resolved the error but isn't listed in the [dependencies](https://github.com/plexinc/plex-media-player#building-on-linux).

**Comment by LongChair** [comment]
it is listed in the dependencies.

**Comment by Enigma0** [comment]
Woops >.>

**Comment by JohnD0it** [comment]
I got the error:
Could NOT find SDL2 (missing: SDL2_INCLUDE_DIR SDL2_LIBRARY)

Trying to install libsdl2-dev:
root@deb:/home/luser/yuzu/build# aptitude install libsdl2-dev
Se instalarán los siguiente paquetes NUEVOS:      
  libasound2-dev{a} libgles2-mesa{ab} libgles2-mesa-dev{a} 
  libibus-1.0-dev{a} libpulse-dev{a} libsdl2-dev 
  libsndio-dev{a} libudev-dev{a} libxss-dev{a} libxt-dev{a} 
  libxv-dev{a} x11proto-scrnsaver-dev{a} 
0 paquetes actualizados, 12 nuevos instalados, 0 para eliminar y 0 sin actualizar.
Necesito descargar 2.106 kB de ficheros. Después de desempaquetar se usarán 10,2 MB.
No se satisfacen las dependencias de los siguientes paquetes:
 libgles2-mesa : Depende: libglapi-mesa (= 13.0.6-1+b2) but 18.2.5-3 is installed
                 Entra en conflicto: libgles2 but 1.1.0-1 is installed
 libgles2 : Rompe: libgles2-mesa (< 17.2.0~rc4-1) but 13.0.6-1+b2 is to be installed
 libglvnd-dev : Rompe: libgles2-mesa-dev (< 17.2.0~rc4-1) but 13.0.6-1+b2 is to be installed
 x11proto-dev : Rompe: x11proto-scrnsaver-dev (< 2018.3) but 1.2.2-1 is to be installed

**_1 First solution:_**

Las acciones siguientes resolverán estas dependencias
Mantener los paquetes siguientes en la versión actual:                     _# Keep packets in actual version_
1)     libgles2-mesa [Sin instalar]                        
2)     libgles2-mesa-dev [Sin instalar]                    
3)     libsdl2-dev [Sin instalar]                          
4)     libxss-dev [Sin instalar]                           
5)     x11proto-scrnsaver-dev [Sin instalar]               
¿Acepta esta solución? [Y/n/q/?]

**_2 Another solution is:_**

Las acciones siguientes resolverán estas dependencias
 Instalar los paquetes siguientes:                                                           _# Install this packets_

1)     libgles2-mesa-dev [18.2.6-1 (testing)]              
2)     x11proto-scrnsaver-dev [2018.4-4 (testing)]         
Mantener los paquetes siguientes en la versión actual:                     _# Keep packets in actual version_
3)     libgles2-mesa [Sin instalar]

**_3 Another solution is:_**

Las acciones siguientes resolverán estas dependencias
Instalar los paquetes siguientes:                                                             _# Install this packets:_
1)     libgles2-mesa [18.2.6-1 (testing)]         
2)     libgles2-mesa-dev [18.2.6-1 (testing)]     
3)     x11proto-scrnsaver-dev [2018.4-4 (testing)]

**_4 Last solution:_**

Las acciones siguientes resolverán estas dependencias

      Eliminar los paquetes siguientes:                                                       _# Remove this packets:_
1)      libegl-mesa0 [18.2.5-3 (now)]                             
2)      libegl1 [1.1.0-1 (now, testing)]                          
3)      libgl1 [1.1.0-1 (now, testing)]                           
4)      libgles2 [1.1.0-1 (now, testing)]                         
5)      libglvnd-dev [1.1.0-1 (now, testing)]                     
6)      libglx-mesa0 [18.2.5-3 (now)]                             
7)      libglx0 [1.1.0-1 (now, testing)]                          
8)      libwayland-egl1 [1.16.0-1 (now, testing)]                 

      Instalar los paquetes siguientes:                                                    _# Install this packets_
9)      x11proto-dri2-dev [2018.4-4 (testing)]                    
10)     x11proto-gl-dev [2018.4-4 (testing)]                      
11)     x11proto-scrnsaver-dev [2018.4-4 (testing)]               

Desactualizar los paquetes siguientes:                                                  _# Downgrade packets_ 
12)     libegl1-mesa [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)]     
13)     libegl1-mesa-dev [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)] 
14)     libgbm1 [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)]          
15)     libgl1-mesa-dev [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)]  
16)     libgl1-mesa-glx [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)]  
17)     libglapi-mesa [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)]    
18)     libwayland-bin [1.16.0-1 (now, testing) -> 1.12.0-1 (stabl
19)     libwayland-client0 [1.16.0-1 (now, testing) -> 1.12.0-1 (s
20)     libwayland-cursor0 [1.16.0-1 (now, testing) -> 1.12.0-1 (s
21)     libwayland-dev [1.16.0-1 (now, testing) -> 1.12.0-1 (stabl
22)     libwayland-egl1-mesa [18.2.5-3 (now) -> 13.0.6-1+b2 (stabl
23)     libwayland-server0 [1.16.0-1 (now, testing) -> 1.12.0-1 (s
24)     mesa-common-dev [18.2.5-3 (now) -> 13.0.6-1+b2 (stable)]  
25)     xserver-xorg-core [2:1.20.3-1 (now, testing) -> 2:1.19.2-1
26)     xserver-xorg-video-amdgpu [18.1.0-1 (now, testing) -> 1.2.
27)     xserver-xorg-video-ati [1:18.1.0-1 (now, testing) -> 1:7.8
28)     xserver-xorg-video-fbdev [1:0.5.0-1 (now, testing) -> 1:0.
29)     xserver-xorg-video-intel [2:2.99.917+git20180925-2 (now, t
30)     xserver-xorg-video-nouveau [1:1.0.15-3 (now, testing) -> 1
31)     xserver-xorg-video-qxl [0.1.5-2+b1 (now, testing) -> 0.1.4
32)     xserver-xorg-video-radeon [1:18.1.0-1 (now, testing) -> 1:
33)     xserver-xorg-video-vesa [1:2.4.0-1 (now, testing) -> 1:2.3
34)     xserver-xorg-video-vmware [1:13.3.0-2 (now, testing) -> 1:

I don't want to break anything, I don't have an updated backup of debian. What should I do 1, 2, 3, 4? Or cancel it and link sdl2 in some way.
(Excuse the Spanish)
Thank you.
