### ISSUE TITLE
PMP 1.3.0.642-70f8057 crash when playing SVT play videos

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#562]
A fairly new crash bug for me. SVT play videos have started crashing PMP 1.3.0.642-70f8057.

https://gist.github.com/atrus05/74618a2dd650605dfaba0a6d37bc5623

Happens reliably on every video we have tried. YouTubeTV plugin still works though, so I guess the ffmpeg version used in this version does not like SVT play videos?

**Comment by wm4** [comment]
Seems like a bug with Apple's AAC decoder, or how we use it.

**Comment by atrus05** [comment]
This now works. The startup time for each video is ridiculous though. Will create a separate GHI about that when I have time to look into it though.
