### ISSUE TITLE
MacOS 5k Display

### ISSUE THREAD

**Issue by j-r0dd** [plexinc/plex-media-player#564]
If you have at full screen or anywhere near full screen there are all sorts of graphical glitches. I have to size down the window to about half the size. The app just doesn't like being at 5k resolution.

**Comment by pvarela** [comment]
For me it starts to break somewhere between a horizontal size of the windows between 2075px and 2275px.

**Comment by mrnoisytiger** [comment]
Having the exact same issue here, about 60% down the screen. If I take it out of fullscreen mode or shrink it down a bit, it's fine.

**Comment by mseeley** [comment]
Hi folks. @wm4 has updated our configuration to avoid rendering garbage on 5K displays. Will update here when we've shared the build publicly. Thanks!

**Comment by wm4** [comment]
We had a nightly build somewhere here, which should fix _all_ 5K issues: https://nightlies.plex.tv/public-test/plexmediaplayer/public-testing/

Unfortunately I can't remember which of those is the correct one. Probably could be found by looking at the corresponding forum posts.

**Comment by atrus05** [comment]
@j-r0dd @pvarela @mrnoisytiger Please let me know if this issue persits or if we can close it. I will close it down in a few days if you guys do not respond.

**Comment by j-r0dd** [comment]
It stopped for me after I updated to High Sierra or maybe it was a build right around when it dropped. Either way I’m good. 

--Jared

**Comment by atrus05** [comment]
Excellent. I will close this for now then.
