### ISSUE TITLE
volume keys not working on macOS

### ISSUE THREAD

**Issue by yaccin** [plexinc/plex-media-player#569]
Since the last update (1.3.2.657) pmp does ignore the volume (and mute) keys on macOS and always play at the volume that was set before launching pmp. Even the mute key does not work anymore once it is launched.

//edit
It looks like all or most keyboard input stopped working. For example using the space bar to pause does no longer seem to work as well.

**Comment by LongChair** [comment]
@yaccin : is that still an issue with recent versions ?

**Comment by LongChair** [comment]
Closing this due to the lack of feedback, feel free to reopen if needed.
