### ISSUE TITLE
No full screen mode on Ubuntu

### ISSUE THREAD

**Issue by N4ide** [plexinc/plex-media-player#570]
Full screen doesn't work unfortunately in default mode. When i press F11 the issue is that the layout isnt fullscreen (See the picture). Is it possible to solve this issue? I compiled the newest version from github.
![screenshot from 2017-05-27 00-12-40](https://cloud.githubusercontent.com/assets/28990294/26514406/e1d876d2-4271-11e7-926e-5c4600ffe58b.png)

**Comment by father-mande** [comment]
Hi,
Did you try to start pmp with --tv AND --scale-factor=1

Philippe.

**Comment by N4ide** [comment]
This doesn't work unfortunately. The problem is that the video player can't go full screen in the normal plex layout and the TV layout is windowed with a very low resolution.

**Comment by LongChair** [comment]
The arguments given above should at least change scale.

**Comment by LongChair** [comment]
@N4ide : did you try with a more recent build and eventually `--tv --scale-factor=1` ?

**Comment by LongChair** [comment]
Closing due to the lack of feedback.
Feel free to reopen if needed.
