### ISSUE TITLE
Missing dependencies for SOCKS support

### ISSUE THREAD

**Issue by fionera** [plexinc/plex-media-player#572]
web-client-desktop/3.7.0-d711f4a@plex/public: Not found, looking in remotes...
web-client-desktop/3.7.0-d711f4a@plex/public: Trying with 'conan.io'...
ERROR: Missing dependencies for SOCKS support.

How can I use the Player with a Proxy?

**Comment by LongChair** [comment]
we're not using conan anymore, closing.
