### ISSUE TITLE
Theme Music on Fire TV

### ISSUE THREAD

**Issue by MichaelRumpler** [plexinc/plex-media-player#574]
I have the Plex app for Fire TV, version 5.10.1.264 and there's no option to turn on Theme Music and no music plays. When I use a web browser and open the same tv series, then the music plays as expected.

According to https://forums.plex.tv/discussion/216659/amazon-fire-tv-theme-music-no-longer-plays-after-upgrade-to-fire-os-5 the theme music stopped working in April 2016. It seems to be a known issue, but I didn't find it here and don't want it to be forgotten.

**Comment by DaveBinM** [comment]
@MichaelRumpler This repository is purely for the Plex Media Player application, not for the Plex for FireTV app.

**Comment by MichaelRumpler** [comment]
I didn't find a better place for it. Can you point me to the correct site?

**Comment by DaveBinM** [comment]
The forums are sufficient for this. Tracking of bugs like that are done on internal, private, repositories by Plex. 🙂

**Comment by wm4** [comment]
Yes, that goes on the correct plextv forum.
