### ISSUE TITLE
Redraw Errors Using 4k Screens

### ISSUE THREAD

**Issue by Simiil** [plexinc/plex-media-player#575]
Hi there.
Seems to be the same issue as #10, but it is said there that new issues should be opened when the problem occurs.

the hardware is much different than in the other issue:

    Arch-Linux with the standard 4.11.2-1 Arch Kernel
    Intel(R) Core(TM) i7-6700K 
    GeForce GTX 660

    4k ASUS Screen, 3840x2160 Resolution

    Plex Media Player version: 1.3.2.dev-21cb31b8

As the videos of issue #10 are not available, i cant be sure if the behaviour is the same. It is mostly black flashes and visual artifacts while pages load. Also the background is loaded in visible chunks, whereas on a lower resolution it fades the background

Everything is fine on a second screen with a `1080p` resolution

Additionally, The context menu appears on the wrong position, roughly at half of the dimensions where it should. I.e. if i right click on the lower right of the screen, the context menu opens in the middle of the screen

**Comment by danarnold** [comment]
I'm experiencing the same thing on arch with a 4K display. I don't have a 1080p to compare to, though, so i can't personally confirm that the issue goes away on a lower resolution display.

My hardware:

````
OS: Arch Linux x86_64
Kernel Release: 4.11.9-1-ARCH
DE: GNOME
RAM: 16 GB
Processor: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
````

**Comment by jmiskinis** [comment]
Can confirm that this is indeed an issue.

My specs:

`OS: Arch Linux x86_64
Kernel Release: 4.15.12-1-ARCH
DE: GNOME
RAM: 16 GB
Processor Type: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Display Resolution: 3840x2160
Plex Media Player: 2.7.0
`
Running on either integrated Intel graphics or Nvidia GPU makes no difference.

Short clip: https://giphy.com/gifs/3kw18L0lTaMtcbnNmE/html5

**Comment by LongChair** [comment]
I am afraid this is related to Qt 4k support.
We should bump Qt sometimes in a near future, hopefully will bring better support

**Comment by LongChair** [comment]
I have no archlinux to check this, and even if we had a few issues oringially with this on OSX as well with HighDPI screens, we nabled HIGHDPI support in PMP.

So I believe there is not much we can do here, you might want to voice archlinux HighDPI support to Qt here : https://bugreports.qt.io/

i'll close this as there is not much we can do until this is fixed upstream.
