### ISSUE TITLE
Display Mode Switching Issue

### ISSUE THREAD

**Issue by madFloyd** [plexinc/plex-media-player#576]
When I turn on Display Mode switching PMP will change from 60p to 24p as expected.  This will continue to work in the same session, but if my display is turned off (in my case a projector), when I return for a new session, this setting appears to be ignored.

The only work around is to close PMP and re-start it.   

This is on Windows 7.

It would be great to fix this as going back to the desktop requires a mouse....

**Comment by wm4** [comment]
That's an interesting case. Do you have a clean log for it, which demonstrates the issue? I suspect it gets stuck in the state where it thinks it has to switch back, but can't.

**Comment by wm4** [comment]
Same as this? https://forums.plex.tv/discussion/comment/1454223/#Comment_1454223

**Comment by madFloyd** [comment]
Yes, the same.  I will repro and grab a log this evening.  Thanks!

**Comment by madFloyd** [comment]
I attached a log to the other discussion referenced in the above link.

**Comment by LongChair** [comment]
@madFloyd : is this still relevant on recent builds?

**Comment by LongChair** [comment]
There will be no further updates on tv1.
Should HDR support come into mpv, it will be in tv2 (new UI).
Should I assume i can close this then ?

**Comment by madFloyd** [comment]
Yes thanks
