### ISSUE TITLE
Protocol doesn't allow for discrete pin entry

### ISSUE THREAD

**Issue by audiossis** [plexinc/plex-media-player#577]
Why was the HTTP control protocol written such that we cannot send a PIN discretely using the number pin on a remote control?

It seems rather pointless having a PIN locked account... when everybody sitting in the room can see the PIN as it's entered on the TV screen....

**Comment by LongChair** [comment]
@markus101 : any thoughts about this one ? :)

**Comment by markus101** [comment]
I'm using an MCE remote (with PMP on Windows) and I'm able to enter my PIN discretely.

If there is additional information we can reopen it, but closing as it's working in my tests.

**Comment by audiossis** [comment]
Sorry to reopen this after so long. I've just returned to this issue.
The question in that case then is, where precisely is this documented? I cannot find examples or explanations anywhere of how to send alphanumeric data via HTTP post, nor can I see any POST method to enter a PIN

**Comment by audiossis** [comment]
No comment?
