### ISSUE TITLE
Embedded PMP 1.3.3/1.3.4 MPEG2-Video Corruption when using HW decoding

### ISSUE THREAD

**Issue by lqvnguyen** [plexinc/plex-media-player#578]
User on forums reported video corruption using embedded PMP 1.3.3 and 1.3.4. User provided clips to test. I was able to reproduce the issue. If transcoded it plays fine. It also seems to play fine from the Shield and VLC.

Logs and Sample Clips posted by the user on the forum.

https://forums.plex.tv/discussion/276186/hardware-decoding-issues-with-mpeg2#latest

**Comment by wm4** [comment]
Can reproduce. The problem is probably with ffmpeg. I don't think that's easily fixable without getting deep into hwaccel APIs and mpeg2 codec details, so I don't expect a fast solution. vlc shows only green with this file and hwdec enabled, btw.

**Comment by LongChair** [comment]
@lqvnguyen : can we close this ? :)

**Comment by lqvnguyen** [comment]
Rare remuxes show this but I am not sure there is much that can be done

**Comment by lqvnguyen** [comment]
This is a VAAPI issue.
