### ISSUE TITLE
Going from fullscreen to windowed mode aborts music and video playback

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#579]
It seems that the switch from 10 feet mode to web mode (going from fullscreen to windowed mode by hitting CMD-F on my Mac) aborts music and video playback.
I am not sure if this is intended or not, filing just to be sure.

Unsure how long it has been like this as I extremely seldom plays music AND switches to windowed mode. But it has been like this at least since build 645 and the behaviour is still like this in 2.0.1

**Comment by wm4** [comment]
That is well known. Web-client would have to become aware of the current playback as it's restarted. Not sure if we can do something about it (pinging random web people, @markus101 @ericmatthys @mseeley ).

We could just change CMD-F to not change modes though.

**Comment by markus101** [comment]
I'm not sure what our future plans are for handling active playback when switching modes, but a review of the hotkeys for switching modes might be good interim step as there are a number of different hotkeys and some interest in a concrete hotkey to switch to TV mode and another to switch to desktop mode as mentioned here: https://github.com/plexinc/plex-media-player/issues/519

**Comment by markus101** [comment]
The two different web apps don't communicate progress. At this time there are no plans to do that so I'm closing this out.
