### ISSUE TITLE
Installation issues with Qt5 on Ubuntu when running the cmake dbug command

### ISSUE THREAD

**Issue by neeldug** [plexinc/plex-media-player#581]
So I made sure Qt was the correct version (5.7+) by running `qmake --version` which returned 5.7.1; however when I ran the cmake command, it threw many issue; of which I could comprehend nothing from.

Here's what the output was:
`-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Success
-- Not using bundled deps
-- Qt root directory: /usr/lib/i386-linux-gnu/qt5
CMake Error at CMakeModules/QtConfiguration.cmake:53 (find_package):
  By not providing "FindQt5WebChannel.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebChannel", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebChannel"
  (requested version 5.7.0) with any of the following names:

    Qt5WebChannelConfig.cmake
    qt5webchannel-config.cmake

  Add the installation prefix of "Qt5WebChannel" to CMAKE_PREFIX_PATH or set
  "Qt5WebChannel_DIR" to a directory containing one of the above files.  If
  "Qt5WebChannel" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:60 (include)
`

**Comment by wm4** [comment]
Are you sure you have Qt5WebChannel installed?

**Comment by InTheLittleWood** [comment]
I'm afraid I don't know whether I have it installed since I can't run the online installer for Qt using 32-bit Ubuntu, I tried installing from sources, but for some reason it's using some qt that was there before, 5.7.1 which appears to not have Qt5WebChannel...

**Comment by tylermenezes** [comment]
The following packages are also required, and not listed in the README:

- libqt5webchannel5-dev
- qtwebengine5-dev
- libqt5x11extras5-dev
- (if you're using built-in mpv, libmpv-dev)

Clean out your build directory after installing these files. I also found that I needed to set DQTROOT to `/usr/share/qt5` to get it to work on Debian, or the install step would fail.

**Comment by wm4** [comment]
Well, these are all part of Qt. libmpv-dev is only required if you use distro packages - which you should not, because they are usually outdated, and in PMP we're not going to go the extra way of supporting old mpv releases.

**Comment by InTheLittleWood** [comment]
Ok, so when I tried doing this again, now when I run `conan install ..`, it returns `ERROR: Invalid configuration, missing settings_defaults`, even after a fresh clone and redoing all commands

**Comment by tylermenezes** [comment]
@wm4 the readme specifically says to use distro QT packages if they're newer than 5.7.1.

**Comment by InTheLittleWood** [comment]
Edit: now when running the cmake dbug command, I am presented with more missing packages, as it would appear:

```
 Qt5PositioningConfig.cmake
    qt5positioning-config.cmake
```
are missing, anyone know of what the aptitude package names are for these.

**Comment by tylermenezes** [comment]
On deb-based platforms, use `apt-file search` to find which packages contain files.

**Comment by InTheLittleWood** [comment]
Okay, so now I'm getting this:

`CMake Error at src/CMakeLists.txt:129 (message):
  Could not find the web-client! Run conan!`

However, I've tried running `conan install ..` which returns: `ERROR: Invalid configuration, missing settings_defaults`

**Comment by wm4** [comment]
Well, it works here...

**Comment by InTheLittleWood** [comment]
Yeah, I've tried reinstalling the plex-media-player folder, but been getting continual issues surrounding `conan install ..`, when I ran the command; it returned the exact same as before:

`ERROR: Invalid configuration, missing settings_defaults`, honestly I have no idea when it comes to conan. Any help would be much appreciated.

**Comment by Enigma0** [comment]
@neeldug May not help but try running this:

```
sudo apt-get install python-pip | tee pmp_conan.log
sudo -H pip install --upgrade pip | tee -a pmp_conan.log
sudo -H pip install -U conan | tee -a pmp_conan.log
pip install -U conan | tee -a pmp_conan.log
conan remote add plex https://conan.plex.tv | tee -a pmp_conan.log
conan remote update plex https://conan.plex.tv | tee -a pmp_conan.log
conan search -r plex *@*/public | tee -a pmp_conan.log
```

**Comment by tomk00** [comment]
`ERROR: Invalid configuration, missing settings_defaults` I fixed by adding at the end of file 

> ~/.conan/conan.conf 

```
[settings_defaults]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=8.0
os=Macos
```

**Comment by LongChair** [comment]
conan isn't used anymore, so closing this.
