### ISSUE TITLE
PMP 1.3.4 Windows Sleep on continuous play and min/max toggle issues (they are back)

### ISSUE THREAD

**Issue by craigmcewen** [plexinc/plex-media-player#585]
Prior to this updated version when viewing media that automatically continues to the episode automatically every now and then randomly when plex checks to make sure you are still alive and gets you to click to load the next video to play otherwise it ceases with the next, at this point screensaver would kick in same as if you pause or don't interact with your pc as per normal.. Well this is no more... A setting has been broken somewhere with the updated version that won't give the signal to the pc to allow sleep mode due to inactivity.. Still works on pause or anywhere else as normal, just not on continuous play.
I would provide logs if you want, I had a look through and nothing telling me of its evil plans to not sleep... 

Also issue with toggling in and out of "maximise screen" (not to be mistaken with "enter full screen"). 
It goes into max ok, will not release out of it without exiting from the media using the X instead of the max icon bottom right. This issue was so bad for such a long time I hope it's not going to start back up again.... 
Again the logs are hiding the truth from me! That or the input command is not even reaching an error cos it's broken from the get go and it can't tell anyone :P

**Comment by LongChair** [comment]
@markus101  : is this a known issue ?

**Comment by LongChair** [comment]
@craigmcewen : is that still relevant with recent builds btw ?

**Comment by markus101** [comment]
Not 100% sure which mode this is referring to, Desktop (similar to https://app.plex.tv/desktop) or TV, but I don't think it's known either way.

**Comment by LongChair** [comment]
@craigmcewen : closing this due to the lack of feedback, feel free to reopen if needed.
