### ISSUE TITLE
runtime path for pmphelper not pointing to same Qt lib directory as plexmediaplayer

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#590]
When building:

```
Installing: /usr/local/bin/plexmediaplayer
Set runtime path of "/usr/local/bin/plexmediaplayer" to "/opt/Qt5.9.1/5.9.1/gcc_64/lib"
Installing: /usr/local/bin/pmphelper
Set runtime path of "/usr/local/bin/pmphelper" to ""
```

When running:

```
/usr/local/bin/pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/local/bin/pmphelper)
```

`/usr/lib/x86_64-linux-gnu/libQt5Core.so.5` is `5.7.1`

Built with `cmake ... -DQTROOT=/opt/Qt5.9.1/5.9.1/gcc_64 ...`

**Comment by Lynkz83** [comment]
I'm having an issue with the runtime path aswell..
`-- Installing: /usr/local/bin/plexmediaplayer
-- Set runtime path of "/usr/local/bin/plexmediaplayer" to "/opt/Qt5.9.1/5.9.1/gcc_64/lib"
-- Installing: /usr/local/bin/pmphelper
-- Removed runtime path from "/usr/local/bin/pmphelper"
`
It apparently gets set but later gets removed at the end of installation

**Comment by LongChair** [comment]
@Enigma0 : is this still an issue in recent builds ?

**Comment by Enigma0** [comment]
I see this now when running with 5.9.5:

`
/usr/local/bin/pmphelper: relocation error: /usr/local/bin/pmphelper: symbol _ZdlPvm version Qt_5 not defined in file libQt5Core.so.5 with link time reference
`

**Comment by LongChair** [comment]
@Enigma0 : This looks like an LTO issue to me. probably not related to RPATH.
I think the cmake patch i gave in the other thread should fix RPATH issue right ?

**Comment by LongChair** [comment]
Dupplicated of https://github.com/plexinc/plex-media-player/issues/379 anyways, Lets close this one and follow in the other one.
