### ISSUE TITLE
PMP: 3.14.1, MacOS 10.12.6: Not able to cast to all available devices

### ISSUE THREAD

**Issue by ltomes** [plexinc/plex-media-player#593]
## Versions
OS: MacOS: 10.12.6
Plex Media Player: 3.14.1
Plex Media Server: 1.8.0.4109

## Behavior:
Unable to cast to Google Home devices

## Expected behavior:
Google Home is listed as a castable device (Either via 'Cast...' or as a device in the list (Note, web player version is 3.17.2)

Apologies if this issue has been reported already, I did not find a similar ticket after searching for cast, chromecast, google home.

![screen shot 2017-08-04 at 10 27 39 am](https://user-images.githubusercontent.com/4184677/28975448-a5e1e18a-78ff-11e7-85e8-94c90f67a986.png)

**Comment by LongChair** [comment]
@ltomes : is this still an issue or can we close this ?

**Comment by ltomes** [comment]
@LongChair I still can't cast to home devices on 3.44.1 (or any version in between).
No one else seems to be effected so I would just say close it. 👍

**Comment by LongChair** [comment]
ok, thanks :)
