### ISSUE TITLE
[Feature][Picture Library Settings] Add a poster picture from the Library collection

### ISSUE THREAD

**Issue by kmence** [plexinc/plex-media-player#594]
Hi guys,

A very interesting feature for pictures lovers and photographers would be getting the possibility to select a poster for the photo album collection (folder).

![image](https://user-images.githubusercontent.com/3858916/29004917-2be77bc4-7ad0-11e7-942b-cbe05cfea2eb.png)

Plex loads a random picture as a poster by Default but we could let the users choose themselves.
Actually for Personal pictures, it's not very useful to upload an image.
So after clicking Edit> Poster on a Picture Library collection, I suggest to show a 5-pictures carousel in the of thumbnails in the ".artwork-options-list" element  and the user will choose what he wants.
What do you think about that ?
Is it possible to add this feature ?

After, as Facebook do, it would be interesting to propose the most interesting pics using image recognition for example. But that is just an idea. :-)

**Comment by LongChair** [comment]
@kmence : thanks for your feedback we appreciate.
I don't think such a feature is part of the current plan.
Will close it for now for clarity :)
