### ISSUE TITLE
PMP Windows 10 - Description bug

### ISSUE THREAD

**Issue by SoEleqanT** [plexinc/plex-media-player#595]
PC: Windows 10 Pro - 1703 x64
LANG: HUN
APP VERSION: 3.2.20

![capture](https://user-images.githubusercontent.com/19515207/29269531-4a49683e-80f2-11e7-9fe9-8c42b9fb04cc.PNG)

**Comment by OttoKerner** [comment]
This is not from Plex Media Player.
This is from the 'Plex for Windows' app from the Microsoft App Store.
Different app altogether.

**Comment by SoEleqanT** [comment]
Ohh.. thx and sorry!
