### ISSUE TITLE
NVidia Fast sync causes crash to desktop

### ISSUE THREAD

**Issue by Ca-pp** [plexinc/plex-media-player#599]
In NVidia control Panel -> Manage 3D Settings -> Global Settings

Set Vertical Sync to 'Fast' and Apply

Open Plex Media Player and it will crash back to desktop after a moment.

Version 1.3.5
Windows 10
Nvidia Driver 385.28

[PlexMediaPlayer.Log.txt](https://github.com/plexinc/plex-media-player/files/1238224/PlexMediaPlayer.Log.txt)

**Comment by spoonypirate** [comment]
I'll second this as still being an issue. Changing to (for example) Adaptive VSync allows fullscreen to work with Plex Media Player.

Windows 10
PMP Version 2.1.1
Nvidia Driver 384.76

**Comment by rnyberg** [comment]
Just found this ticket and deactivated fast vsync, now my PMP no longer crashesh instantly, so I guess.. I hird this. ;)

**Comment by LongChair** [comment]
Would you guys mind checking if https://github.com/plexinc/plex-media-player/issues/677#issuecomment-384927456 is making any difference for this Nvidia specific issue ?

Thansk to provide me with some feedback :)

**Comment by LongChair** [comment]
@AndyHeap @redfellow @spoonypirate : could anyone of you please check with replacing the dlls i mentionned and let me know ?

**Comment by redfellow** [comment]
I'll test the DLLs tonight if I have time for it, thanks for your effort.

**Comment by spoonypirate** [comment]
@LongChair I checked out the mentioned build and I can go into fullscreen no problems with Fast Sync enabled.

**Comment by LongChair** [comment]
@spoonypirate : awesome news :) thanks for checking !

**Comment by LongChair** [comment]
@spoonypirate @redfellow : Here s the latest build which should incldue the fix.

https://www.dropbox.com/s/w7neafa3ymv86mk/PlexMediaPlayer-2.10.0.854-c1633f57-windows-x64.exe?dl=0

Please be patient until this land.

**Comment by LongChair** [comment]
PR addressing this issue was merged. Closing :)
