### ISSUE TITLE
Not building latest v2 UI

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#601]
Git doesn't seem to build the PlexPass v2 UI - is it possible?

**Comment by Enigma0** [comment]
@wm4 is this possible yet? None of my systems run Windows or Mac.

**Comment by wm4** [comment]
I just pushed the `tv2` branch, which should contain this. This is a temporary branch. We'll probably merge to master as soon as we've taken care of Embedded.

**Comment by mdesdin** [comment]
i get
`web-client-tv2/3.19.2-cff0356a@plex/stable: Not found, looking in remotes...`
`web-client-tv2/3.19.2-cff0356a@plex/stable: Trying with 'conan.io'...`
`web-client-tv2/3.19.2-cff0356a@plex/stable: Trying with 'plex'...`
`Please log in to "plex" to perform this action. Execute "conan user" command.`
when trying this new branch and cannot login…

**Comment by Enigma0** [comment]
@wm4 Should re-open to track tv2 build issues maybe? (haven't tried yet myself)
