### ISSUE TITLE
apple remote can't change volume

### ISSUE THREAD

**Issue by xzcvczx** [plexinc/plex-media-player#603]
There is no way to change the volume with the apple remote, this makes it practically unusable running PMP on macOS, i was going to see about making a patch for myself but unfortunately that part of the code is in the closed source web interface it seems.

Maybe the input mappings need a "x:y" thing where if there is a ':' and something after it it is only used in the non-menu player interface so it can be set to something different while watching a video

**Comment by LongChair** [comment]
@xzcvczx do you see any activity which would be keypress related in the logs when you press volume keys ?

**Comment by xzcvczx** [comment]
the keypresses work fine, the problem is it has been remapped to go forward or back in large chunks of time and is not configurable to be volume up and down without making it no longer able to be up and down in the ui

**Comment by LongChair** [comment]
@markus101 : i suppose default arrows behavior are not prone to change.
Do you think it's a good idea to have those configurable so that users can change it ?

**Comment by markus101** [comment]
I think we'd need to have alternate hotkey actions based on the current view of the app (and whether the OSD was open or not in this case), but I don't think that's anything we have planned at this time.

**Comment by mseeley** [comment]
No planned enhancement to support configuring this keys as described above.
