### ISSUE TITLE
Something missing in the instructions

### ISSUE THREAD

**Issue by ClintGit** [plexinc/plex-media-player#604]
getting error right at the end of all the tasks:
make -j4
make: *** No targets specified and no makefile found.  Stop.
sudo make install
make: *** No rule to make target 'install'.  Stop.

**Comment by ClintGit** [comment]
Sorry I will close this I was using the wrong folder for:
cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.6.1/5.6/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..

Thanks for these instructions!

**Comment by Enigma0** [comment]
@ClintGit I wrote a script that automates the checkout/config/build process: https://github.com/Enigma0/build-scripts

Feel free to try it. Works for first time builds & rebuilds.
