### ISSUE TITLE
PlexMediaPlayer-1.3.5.723 breaks Embedded-PMP Install 

### ISSUE THREAD

**Issue by cawilliamson** [plexinc/plex-media-player#606]
I'm hoping someone can help me here because I'm facing a repeated problem on my ASUS Chromebox. It seems like whenever Embedded Plex Media Player tries to perform an update it fails with the following issues:

1.) /storage/.cache/cores is 100% full with files like:

`-rw-------    1 root     root      90324992 Aug 29 14:44 core.!usr!bin!plexmediaplayer.1504017846.3580`

2.) plexmediaplayer fails to start:

```
PlexMediaPlayer:~ # /usr/bin/plexmediaplayer --fullscreen --tv --scale-factor=1
libva info: VA-API version 0.39.4
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/va/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_39
libva info: va_openDriver() returns 0
libpng warning: iCCP: known incorrect sRGB profile
Logging to /storage/.local/share/plexmediaplayer/logs/plexmediaplayer.log
Bus error (core dumped)
```

A clean reinstall always resolves the issue but performing a clean install every upgrade (with all of the wifi faff too) isn't really viable.

Also worth noting - I can SSH to the box after this issue, xorg is running, etc. Looks to just be a Plex package upgrade issue. Likely related to point 1 in some way I guess.

Any help here would be greatly appreciated.

**Comment by wm4** [comment]
Is that with the official builds? A bit surprised that core dumps are enabled at all.

CC @LongChair

**Comment by LongChair** [comment]
Core dumps are enabled by default on LE.
Although the LE image wasn't updated in months in terms of system so pretty wierd.

**Comment by cawilliamson** [comment]
Yep - official builds.

Now that I think about it - obviously "cores" is core dumps - makes sense.

So it sounds like the disk filling issue is simply a result of whatever is causing plexmediaplayer not to start. As I mentioned - each time I perform a fresh install it works for a while and I'm fairly convinced that the upgrade process kills it (I do have auto-upgrade enabled.)

**Comment by KonradIT** [comment]
Any progress on this?

Just updated to Gnome 3.26 and it started showing this:

    libpng warning: iCCP: known incorrect sRGB profile

**Comment by wm4** [comment]
> libpng warning: iCCP: known incorrect sRGB profile

That is harmless.

**Comment by KonradIT** [comment]
@wm4 it reboots the machine. Not harmless.

**Comment by wm4** [comment]
What makes you think the same code that prints this message reboots the machine? It's harmless and unrelated to the crash.

**Comment by LongChair** [comment]
@cawilliamson : still having an issue there or can we close this ?

**Comment by LongChair** [comment]
Closing due to the lack of feedback, feel free to reopen if needed.
