### ISSUE TITLE
Menu bar shows after turning on AV-receiver

### ISSUE THREAD

**Issue by generator85** [plexinc/plex-media-player#608]
I've noticed that when I turn on my AV-receiver with Plex in fullscreen mode, the menubar appears (like when you move your cursor to the top of the screen in any OSX app in fullscreen mode). It doesn't go away until I move my mouse.

 I'm running OSX El Capitan 10.11.6 and Plex Media Player 2.1.0.

**Comment by LongChair** [comment]
@generator85 : is that still an issue with latest builds ?

**Comment by generator85** [comment]
Seems to be fixed! I'll close the issue.
