### ISSUE TITLE
Library scan info shows up over top video

### ISSUE THREAD

**Issue by Saltystew** [plexinc/plex-media-player#614]
Windows 10 64-Bit
Plex Media Player Version 1.3.6

The black bar that shows up on the bottom center of the screen that gives information on what is currently being scanned as a library scan is going on shows up even while playing video now. Pretty sure it didn't do that before. Seems like a bug cause otherwise I can't imagine anyone wanting that to happen.

[Example](https://i.imgur.com/zELIojx.jpg).

It happens consistently for me, all I do is start a scan and then go watch something. Comes up every time.

**Comment by simmessa** [comment]
I'm having the same issue after the recent plex player update...any ideas?

**Comment by lawltrox** [comment]
Also having this issue for a couple of weeks but it just started bothering me now that i've been adding a couple new shows. Here's the versions of my client/server:

Server (Windows 2016 Standard) running Plex Media Server Version 1.9.2.4285
Clients (Mostly Windows 10 Pro but some Windows 7 as well) running either Plex Media Player 1.3.9.714-a326d45f or Plex Web 3.20.8

**Comment by LongChair** [comment]
@markus101 : do we have an internal GHI for this ?

**Comment by markus101** [comment]
There is. but it was fixed in October, so closing it out.
