### ISSUE TITLE
PMP 3.20 on firefox throws "shaka3014" errors

### ISSUE THREAD

**Issue by Tensordry** [plexinc/plex-media-player#615]
FreeBSD Vs. 1.81 ... 1.91
PMP 3.20. on Firefox on Windows-7
PMP 3.20 on IE on Windows-7

The last known good server version, that did not throw "shaka3014" errors when trying to play Audio-Files coded in .aac format, was vs. 1.75. Audio Files manually convertet into the mp4 container from this .aac format, do not cause errors.

Its got impossible to hear music now, without having first to manually interact and handling the error messages for each .aac file. Those messages startet stopping the player with roundabout vs. 1.81 ... 1.84, and got even worser since. 

This really is annoying and a perfect show-stopper now.

**Comment by DaveBinM** [comment]
What you’re referring to as PMP is actually the web app. PMP is a stand alone application that does not run in a web browser. I’d suggest you might be able to get some help specific to the web app in the forums. 🙂

**Comment by Tensordry** [comment]
Thank you for your hint !  :-)
