### ISSUE TITLE
Unable to seek or use the 10s/30s skip button in Mac Plex Player

### ISSUE THREAD

**Issue by hiakuryu** [plexinc/plex-media-player#616]
I'm unable to use the seek bar or 10s/30s skip button in the Mac App Plex Player.

Using Version 2.1.1.703-79cdfa5c Plex Media Player on Mac running Sierra Mac Book Air early 2014.

Using Version 1.9.2.4285 Plex Media Server on Windows 10 desktop.

Using the plex web client I am able to seek.

This is in the logs.

2017-09-26 09:44:32 [ DEBUG ] PlayerComponent.cpp @ 526 - cplayer: Run command: seek, flags=0, args=[4531.000000, absolute+exact, unused] 
2017-09-26 09:44:32 [ ERROR ] PlayerComponent.cpp @ 532 - cplayer: Cannot seek in this file. 
2017-09-26 09:44:32 [ ERROR ] PlayerComponent.cpp @ 532 - cplayer: You can forcibly enable it with '--force-seekable=yes'. 

[Plex Media Player 9.log](https://github.com/plexinc/plex-media-player/files/1336883/Plex.Media.Player.9.log)

See attached log file

Please advise on how to fix this.

**Comment by Tobithy** [comment]
I get the same issue using the Windows Plex Media Player. For me, this only occurs when the stream is being transcoded, NOT if it is played at Original quality. This seems like a pretty annoying issue.

**Comment by TheRoaringLion** [comment]
I do confirm this being an issue I have the same.

**Comment by mseeley** [comment]
Hi folks. We apologize for the buggy seek behavior! We're looking at getting a fix out this week. As a workaround, the TV layout uses an older video player code base. It should support skipping as intended. It's not an excellent workaround if you are working in the desktop layout but the 10' layout is an option.

**Comment by Tobithy** [comment]
Thanks Matt for the update! Another workaround I found is that the Web Player doesn't have any issues.

**Comment by atrus05** [comment]
@Tobithy @TheRoaringLion @hiakuryu Can any one of you guys please repond when you agree that this one is solved. Thanks a bunch in advance.

**Comment by Tobithy** [comment]
@atrus05 I can confirm that on the standard (non-Plex Pass) Plex Media Player that the issue no longer occurs. This is version 1.3.11.729-4be89b5c, dated October 26, 2017. However, the Plex Pass track (2.1.1.703-79cdfa5c) hasn't been updated since September 25, and still has this issue. I'm not sure how things like this get pushed into each version, but I imagine that next time that the Plex Pass version is updated it will also resolve the issue.
