### ISSUE TITLE
Clunky Navigation in full screen mode

### ISSUE THREAD

**Issue by quinnmj** [plexinc/plex-media-player#618]
Windows 10 64-bit, PMP 1.3.7 (Desktop version, not tablet) Using Flirc with Harmony remote

Pick on "On Deck" (probably happens with other categories as well) TV Show.  Click on it to view the description of the episode -  Click the "back" button - the "Focus" goes all the way back to the TV Show icon at the top - it should go back so the focus is on the TV Show I was looking at in "On Deck", so that a right-arrow would take me to the next TV Show.  Instead I have to maneuver back down to "On Deck" and over to the next show.....

**Comment by LongChair** [comment]
@quinnmj : is that still an issue in recent versions ?

**Comment by quinnmj** [comment]
Yes, still occurs.....

**Comment by LongChair** [comment]
@markus101 : does this behavior looks familiar ?

**Comment by markus101** [comment]
Yeah, this is known. I've linked this to the internal issue.

**Comment by mseeley** [comment]
We'll track this internally. Definitely an annoying behavior.
