### ISSUE TITLE
ninja fails on Debian 8

### ISSUE THREAD

**Issue by ProfessorKaos64** [plexinc/plex-media-player#62]
Steps:
```
git clone https://github.com/plexinc/plex-media-player
cd plex-media-player
mkdir build && cd build
cmake -GNinja \
-DCMAKE_BUILD_TYPE=Debug \
-DQTROOT=/usr/local/Qt-5.6.0 \
-DCMAKE_INSTALL_PREFIX=output ..
ninja
```

Output:
http://slexy.org/view/s2bgaAncm5

**Comment by tru** [comment]
What version of CMake do you have?

**Comment by ProfessorKaos64** [comment]
```
desktop@steamos:~/plex-media-player/build$  apt-cache policy cmake
cmake:
  Installed: 3.0.2-1
  Candidate: 3.0.2-1
  Version table:
 *** 3.0.2-1 0
        110 ftp://mirror.nl.leaseweb.net/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by tru** [comment]
I wonder when CXX_STANDARD was added to CMake. It seems like that is the problem here.

**Comment by tru** [comment]
Answering my own question: 3.1. We should increase our CMake version check to that.

**Comment by ProfessorKaos64** [comment]
So I need 3.1? Guess I will search for the source code to build that then :)

**Comment by tru** [comment]
Yeah you need 3.1. I will make a change so that I we check for that. Thanks for reporting.

**Comment by ProfessorKaos64** [comment]
No problem. I am building cmake from source now, easy enough. Like qmake, it probably would be trivial to include a version as a fallback, or like you said, just failout if the version is not compatible. Thank you for looking into this. Trying a build now with upstream cmake.

**Comment by tru** [comment]
Yeah we could probably remove the requirement for CMake 3.1 if we wanted to, but checking different compilers for c++11 features and the different flags they need is not that fun, I would probably accept a path if it seemed sane. Seems like there are more pressing matters though :)

**Comment by ProfessorKaos64** [comment]
Tried with the latest cmake, and the 3.1 release tag, I get t he below output. I know you have more pressing matters, but if/when you check it out,  it shows a download hash mismatch:
https://gist.github.com/ProfessorKaos64/3a659ce32d3e91719e6f

**Comment by tru** [comment]
You need to build CMake with ssl support. It needs to download the web client part from our servers and we do that over https

**Comment by ProfessorKaos64** [comment]
Hmm I did build cmake with `./configure -- -DCMAKE_USE_OPENSSL=ON`. Maybe I am missing a package?

**Comment by ProfessorKaos64** [comment]
Got it, built cmake alright. On to building :)

**Comment by tru** [comment]
To old version of mpv. We should add a check for that as well.

**Comment by tru** [comment]
I have pushed two fixes to PMP this morning that now checks for CMake 3.1 or newer and also makes sure that mpv/qthelper.hpp is included before it passes configuration. I will close this issue now, open new ones if you have other things that you think are bugs in our cmake scripts.

**Comment by wm4** [comment]
Note that PMP might not work optimally if PMP is slightly too old. E.g. for today, I plan a change in PMP that would make all multichannel audio most likely fail when it's used with older libmpv, because it makes use of features that are only in newer libmpv. So always use mpv git with PMP.

This will probably get relaxed as PMP matures.

**Comment by ProfessorKaos64** [comment]
In case anyone see's this, a package is built and in testing, along with some feeback info. This was built atop Debian 8 / SteamOS:

https://github.com/ProfessorKaos64/SteamOS-Tools/issues/135
