### ISSUE TITLE
PMP MacOS - icon is hardcoded, cannot change

### ISSUE THREAD

**Issue by edrozenberg** [plexinc/plex-media-player#622]
The icon is too large compared to other items in my dock, so I've made a smaller Plex.icns.

Have put my custom Plex.icns in the PMP Finder app info, and have also replaced the Plex.icns in the app bundle /Contents/Resources

The new icon is fine while app is NOT running. But when PMP is running, it replaces my icon with its own in the Dock. I'm guessing the executable has a hardcoded icon that overrides my icon settings.

Would be great if the app could respect the icon settings the user has made. Thanks!

**Comment by LongChair** [comment]
@edrozenberg : is that still an issue with recent builds ?

**Comment by edrozenberg** [comment]
Thanks for checking. Same issue with the latest update (just updated a few minutes ago). Version 3.44.1

My custom icon shows only when the Plex webapp ("app") is NOT running. As soon as I launch the app, it overrides the dock icon with the default icon.

**Comment by LongChair** [comment]
I haven’t seen that on my OSX machine. Are you sing any specific dock configuration ?

**Comment by edrozenberg** [comment]
@Realinho Plex MP is not a real Mac app, it's a web app made to look like a real app. Web apps frequently have issues properly integrating with the MacOS, and this is one example. Most likely the wrapper is providing its own hardcoded icon, and since it's not a standard Mac app there's no way to override that with the user's own icon, at least until PMP makes a change.

The Plex folks are busy enough so can't fault them too much for not making a real Mac app, but it's a sad trend to see bloated, slow, inconsistent Web apps slowly creeping everywhere. Other "shining" examples are Slack for Mac desktop, and the new Skype v8 (luckily can still download and use skype 7, for now). At least the Plex iOS and Apple TV apps are "real apps", I'm really thankful for that. Minor rant over :).

**Comment by LongChair** [comment]
I am sorry but that looks like a wrong statement :)
Unless you consider safari as such, PMP is an application embedding a browser for the PMP app it self.
It’s based on Qt like many other apps and as such should have the same behavior.
I did not have time to look at the issue yet, but there is no reason that this couldn’t be fixed imho.
Icon is part of the Qt app and not the web app.

**Comment by LongChair** [comment]
i had a quick look, and i think that the behavior you are seeing is related to : https://github.com/plexinc/plex-media-player/blob/master/src/main.cpp#L168

Seems like PMP will force it's icon on startup to the packaged PNG icon which is here :

https://github.com/plexinc/plex-media-player/blob/master/resources/images/icon.png

**Comment by Realinho** [comment]
Ah, many thanks for the insight; this does satisfy my curiosity and OCD. I thought, at the time, that I had never seen a macOS app do that, but I did remember after posting here that I had something similar once happen with a Java based one.

Again, not a big deal at all, although it would be nice to be able to change the icon (I prefer the rounded one found on the Media Server app to the squarish one on the Media Player one; feel it fits in better, specially in the dock):
![image](https://user-images.githubusercontent.com/22327048/38775649-c31c3ef6-407f-11e8-8dfb-76ff272a0f96.png) ![image](https://user-images.githubusercontent.com/22327048/38775641-b40d8d48-407f-11e8-8228-815f28ed445a.png)

**Comment by LongChair** [comment]
Another quick test here seems to show that removing this line fixes the issue with icon jiggling on startup .

I'll try to make a test build next week so that you guys can test if that is fixing the issue you're having.
Ping me on Wednesday if i forgot to do it :)

**Comment by LongChair** [comment]
@Realinho @edrozenberg : would you guys mind checking if that build fixes the icon issue ?

https://www.dropbox.com/s/8qin8girdx39ofr/PlexMediaPlayer-2.9.0.825-06ff6bc0-macosx-x86_64.zip?dl=0

... and let me know :)

**Comment by edrozenberg** [comment]
@LongChair Thanks for your work on this! This fixes the icon issue at runtime. I was able to set various icons and they did not change when running the app.

**Comment by LongChair** [comment]
Good to hear, will PR that to master.
Thanks for the feedback.

**Comment by Realinho** [comment]
Sure does, @LongChair , good job.
Unrelated to this, also noticed a couple of days ago that the app will not update with a custom .icns file inside the Resources folder. Which is now irrelevant, since you made it possible to change the icon directly from the Info window.

Thanks!
