### ISSUE TITLE
Install Icons/Desktop File

### ISSUE THREAD

**Issue by Cogitri** [plexinc/plex-media-player#625]
It would be nice if Plexmediaplayer installed a .desktop file and the application icons itself on Linux

**Comment by Enigma0** [comment]
It sure would. You can use this one in the meantime: https://github.com/Enigma0/build-scripts/blob/master/plexmediaplayer.desktop

It has 3 different launch modes as well.

The script in that same repo also automates building, installing the .desktop & an icon.

**Comment by knapsu** [comment]
@Cogitri, you might also be interested in PMP AppImage package. It will create desktop menu entries automatically.
http://forums.plex.tv/discussion/278570/plex-media-player-packages-for-linux/p1

**Comment by Cogitri** [comment]
Oh, sorry that that wasn't clear, I don't need an alternative installer, I just want to minimize the amount of downstream patches ( in this case an additional desktop file ) my distro has to package. Thanks for the recommendation though @knapsu

**Comment by LongChair** [comment]
If you have a downstream patch to submit, we’ll be happy to review it.

**Comment by LongChair** [comment]
@Cogitri : will close this one as you submitted a PR :)

**Comment by LongChair** [comment]
Merged :)

**Comment by Cogitri** [comment]
Thanks :)
