### ISSUE TITLE
Plex Media Player crashes when repeatedly using back/forward buttons

### ISSUE THREAD

**Issue by ysimidjiyski** [plexinc/plex-media-player#627]
Hi team,

I've been seeing crashes in Plex Media Player on Windows when I use the back/forward button repeatedly ever since the new Plex Media Player came out.  The issue stopped reproducing around February of this year, but has started happening again and I unfortunately can't pin down exactly when it was reintroduced.  I'm happy to provide a crash dump too if that would be helpful, or I can look into it myself if someone can point me to debugging symbols for PMP.

This harms the music playback experience pretty severely.  I have not seen the issue repro on the Plex iOS app, so I suspect it is unique to PMP.

### System Info:
* **Server:**  Synology DiskStation 415play
* **Server OS version:**  DSM 6.1.3-15152 Update 7
* **Client OS Version:** Windows 8.1 [6.3.9600] x64
* **Plex Media Server version:**  1.9.4.4325-1bf240a65
* **Plex Media Player version:**  3.21.2
* **Logs:**  [PlexMediaPlayer.log.txt](https://github.com/plexinc/plex-media-player/files/1388800/PlexMediaPlayer.log.txt)

### Repro steps:
1)  Begin playback of an album or playlist using Plex Media Player on Windows
2)  Press "back" and/or "forward" quickly several times in a row (i.e. before a song can buffer and start playing)
3)  PMP crashes eventually.

**Comment by wm4** [comment]
Can't reproduce. Not sure if this is because I'm on Windows 10, or because it's an issue with the reproduction steps.

**Comment by ysimidjiyski** [comment]
Here's a 20 second video demonstrating the issue:  https://youtu.be/JjAxDZ8VCPs

Note that it is _not_ an extremely consistent repro.  The first few times I tried to take the video, it took upwards of a minute of my pressing back/forward in order to generate the crash.  So I do think there's something more to it than just pressing back/forward, but I haven't been able to isolate what that is.

**Comment by LongChair** [comment]
@ysimidjiyski : just to make sure, is that still the case with recent builds ?

**Comment by LongChair** [comment]
Closing this due to the lack of feedback, feel free to reopen if needed.
