### ISSUE TITLE
Heavy UI flickering on MacOS with Retina screens

### ISSUE THREAD

**Issue by mourner** [plexinc/plex-media-player#629]
The Plex Media Player UI flickers very heavily on MacOS on laptops with Retina screen (in my case, Macbook Pro 15'', both 2012 and 2017 models exhibit the issue). It's so bad that I dread using the app every time. 

The symptoms look the same as in #10, which was closed 2 years ago. Maybe the bug came back in some kind of a regression?

Here's a screen capture of the issue: https://www.dropbox.com/s/qi8z7djvu26x7ed/plex-flicker.mov?dl=0

**PMP version:** v1.3.10.720-dfcd90a6

cc @tru @jturcotte @wm4 @markus101 @rcombs

**Comment by wm4** [comment]
That version doesn't contain all the fixes. Also refrain from pinging random people.

**Comment by mourner** [comment]
> That version doesn't contain all the fixes.

What do you mean it doesn't contain all the fixes? Which does? And why close an issue that's not resolved?

**Comment by wm4** [comment]
> What do you mean it doesn't contain all the fixes?

It's based on old code.

> And why close an issue that's not resolved?

It's resolved, the fixes just didn't trickle down yet. There are also links to test builds in the various forum threads about this which contain fixes.

**Comment by mourner** [comment]
> It's resolved, the fixes just didn't trickle down yet.

I see, thanks. Any ETA on when the new version based on the new code will be released?
