### ISSUE TITLE
PMP/PMS suggestion - let browser cache media thumbnails

### ISSUE THREAD

**Issue by edrozenberg** [plexinc/plex-media-player#631]
Currently when scrolling a longer list of media thumbnails (movies for ex), the thumbnails keep having to load when I scroll up and down - they do not stay visible once loaded.

This is different from the way a browser typically works, where once it has loaded all the images it would be able to continue showing all the images when the user scrolls quickly up and down.

The current behavior makes it slow and much less fun to browse the thumbnails, having to wait for them to load constantly while scrolling.

**Comment by edrozenberg** [comment]
Maybe it's done this way in case a user has many thousands of items, fair enough. 

If that's the case the scrolling should anticipate the user's scrolling motion and preload some pages of thumnails and keep preloading as the user scrolls so that the user doesn't have to keep pausing the scrolling to wait for images to load.

**Comment by mseeley** [comment]
I think the main case you're concerned about is navigating through a grid the first time, eg: scrolling down. When I scroll up into already loaded regions the posters display immediately.

The PMP UI is HTML. It offloads all image caching to the browser. Plex Media Servers serve the images with future expires header. The browser is already handling caching for us.

But, I think your real concern is that navigating through a grid initially requires you stop scrolling for a moment for data to be loaded. Loading data during scrolling janks the grid animation. We'll look into strategies to improve this in the future.

Thank you for your feedback. I'm going to close this issue as we focus on bug reports in Github.

**Comment by edrozenberg** [comment]
Thanks, for me scrolling back to already seen areas displays the images after a brief pause (.5 - 1 second) - it is not instantaneous, the images always start out black and then appear after a brief delay, even the ones that were previously viewed.
