### ISSUE TITLE
Add SVG icon

### ISSUE THREAD

**Issue by knapsu** [plexinc/plex-media-player#632]
Some Linux desktop environments displays very large program icons. In such situations the 256x256 [PNG icon](https://github.com/plexinc/plex-media-player/blob/master/resources/images/icon.png) is displayed blurry.

Would it be possible to add a vector SVG icon to [/resources/images](https://github.com/plexinc/plex-media-player/tree/master/resources/images)? There is already a PNG and SVG for splash but only a PNG for icon.

**Comment by wm4** [comment]
Added a SVG icon to tv2 branch.

**Comment by knapsu** [comment]
@wm4 can it be also cherry-picked to the `master` branch?
