### ISSUE TITLE
Failed to open VDPAU backend libvdpau_nvidia.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#633]
The primary issue being my system is using an AMD GPU so it looks like PMP doesn't know that? Why is it trying?

```
Phoronix Test Suite v7.4.0
System Information

  PROCESSOR:          AMD Ryzen 7 1700X Eight-Core @ 3.40GHz
    Core Count:       8
    Thread Count:     16
    Extensions:       SSE 4.2 + AVX2 + AVX + RDRAND + FSGSBASE
    Cache Size:       512 KB
    Microcode:        0x8001126
    Scaling Driver:   acpi-cpufreq ondemand

  GRAPHICS:           AMD Radeon 8192MB
    OpenGL:           4.5 Mesa 17.2.2 (LLVM 5.0.0)
    Display Driver:   amdgpu 1.4.0
    Monitor:          MT276 + EmulatorBuild
    Screen:           3840x1080

  MOTHERBOARD:        ASUS PRIME B350M-A
    Memory:           32768MB
    Chipset:          AMD Device 1450
    Network:          Realtek RTL8111/8168/8411

  OPERATING SYSTEM:   Ubuntu 17.10
    Kernel:           4.13.0-16-generic (x86_64)
    Desktop:          GNOME Shell 3.26.1
    Display Server:   Wayland
    Compiler:         GCC 7.2.0
```

Other than that, I'm not sure what would be required in sorting this out.

**Comment by wm4** [comment]
I really, really, really can't give support for generic Linux issues on this bug tracker.

**Comment by Enigma0** [comment]
@wm4 How do you know it's not a PMP issue?

Sure seems like PMP is trying to open a vdpau backend that it shouldn't be. How do I know hardware acceleration is working in PMP?

**Comment by wm4** [comment]
>Sure seems like PMP is trying to open a vdpau backend that it shouldn't be.

That is the task of the driver loader, which is a library PMP uses and which we don't control.

>How do I know hardware acceleration is working in PMP?

See debug overlay.

**Comment by Enigma0** [comment]
@wm4 Not getting hardware acceleration.

I am able to get hardware acceleration for other 2D applications though. How can I fix this for PMP?

**Comment by wm4** [comment]
Well, first you have to make sure your driver installation is not broken (since that is the prime reason such things won't work). E.g. try `vdpauinfo` or possibly run mpv CLI with ``--hwdec=auto`` and see what it does.

**Comment by alexandr-kara** [comment]
For some reason, the driver wasn't selected automatically in my case, so I had to execute this (and then put it into ~/.bashrc or ~/.profile):

```
export VDPAU_DRIVER=radeonsi
export LIBVA_DRIVER_NAME=radeonsi
```
