### ISSUE TITLE
Plex Media Player 1.3.11 will not start on osx 10.9.5

### ISSUE THREAD

**Issue by ATH4fun** [plexinc/plex-media-player#635]
Received a prompt to update plex media player today and after the update finished I am no longer able to open PMP. I get a crash when trying to open pmp (1.3.11.729)

I don't know what version I had before the update. Tried to find instructions for rollback but did not find any (no backup exists under ~/Library/Application Support/PlexMediaPlayer)

Tried to look for a previous PMP version to download but there are none to be found. Really annoying. 

So what should I do?
---------------------------------
Process:         Plex Media Player [1486]
Path:            /Applications/Plex Media Player.app/Contents/MacOS/Plex Media Player
Identifier:      tv.plex.player
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [534]
Responsible:     Plex Media Player [1486]
User ID:         501

Date/Time:       2017-11-05 17:39:58.162 +0100
OS Version:      Mac OS X 10.9.5 (13F1911)
Report Version:  11
Anonymous UUID:  723CC1C6-B2E1-EB26-1A81-093A5EF6A648

Sleep/Wake UUID: C15FC3B0-1710-411A-B276-0DEE193F103D

Crashed Thread:  0

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
  Referenced from: /Applications/Plex Media Player.app/Contents/MacOS/Plex Media Player
  Reason: image not found

Binary Images:
    0x7fff6cf1c000 -     0x7fff6cf4f887  dyld (239.5) <1D3130FE-FE7E-3C4C-8E74-EB51895B6BA5> /usr/lib/dyld
    0x7fff8e91a000 -     0x7fff8e91afff  com.apple.Cocoa (6.8 - 20) <E90E99D7-A425-3301-A025-D9E0CD11918E> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff9011b000 -     0x7fff9041bff7  com.apple.Foundation (6.9 - 1056.17) <E0B0FAF6-5CA8-3EEB-8BF2-104C0AEEF925> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff917da000 -     0x7fff917dafff  com.apple.Carbon (154 - 157) <EFC1A1C0-CB07-395A-B038-CFA2E71D3E69> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff93b97000 -     0x7fff93ba5fff  com.apple.opengl (9.6.5 - 9.6.5) <4FAEADD8-EEB3-3FD9-ADC6-BA65806228CC> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff96a88000 -     0x7fff975feff7  com.apple.AppKit (6.9 - 1265.21) <9DC13B27-841D-3839-93B2-3EDE66157BDE> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff98494000 -     0x7fff98500fff  com.apple.framework.IOKit (2.0.1 - 907.100.14) <10932113-9F7E-38A0-A158-A019A555CAC3> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff987d9000 -     0x7fff98a49ffd  com.apple.security (7.0 - 55471.14.40) <58F50B4A-FC1E-3AE0-A5DB-DD737E50AC17> /System/Library/Frameworks/Security.framework/Versions/A/Security

Model: Macmini4,1, BootROM MM41.0042.B03, 2 processors, Intel Core 2 Duo, 2.4 GHz, 8 GB, SMC 1.65f2
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x0198, 0x393955353432382D3034302E4130314C4620
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x0198, 0x393955353432382D3034302E4130314C4620
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 5.2.7f4 15858, 3 services, 23 devices, 1 incoming serial ports
Network Service: EthernetATH, Ethernet, en0
Network Service: Ethernet_fake_workaround, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: TOSHIBA MK3255GSXF, 320,07 GB
Serial ATA Device: HL-DT-STDVDRW  GA32N
USB Device: Ext HDD 1021
USB Device: Mini Keyboard
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
Thunderbolt Bus:

**Comment by WangQiru** [comment]
Any chance you are running an app called Contexts?

**Comment by ATH4fun** [comment]
No. I hardly run any apps.

Tried to restart my Mac mini of course but that did not help either.

Mvh / Best Regards,
Attila Füleki
________________________________

**Comment by atrus05** [comment]
As seen when downloading the app from plex.tv/downloads, PMP no requires 10.10 Yosemite or newer to be run. When using the inapp updater (which I suspect you are using) there is no gatekeeper yet which prohibits it from downloading a version which will not work on your 4 year old operating system. This is something that the devs are aware of and are looking into.

**Comment by ATH4fun** [comment]
Thanks!  I have chosen not to update my OS on purpose.  And I am fine with new versions of PMP not supporting my old OSX. However, I would like to be able to rollback - with a backup or by downloading a previous version of PMP. Any chances of finding a previous version somewhere?

This is the exact reason why I don't want to update SW - there is always a risk of breaking something. If it ain't broken .... don't mess with it ;-)

**Comment by atrus05** [comment]
Let me know which version you had before and I will try and dig something up for you. You should be able to see it in an old plex media server.log file.

**Comment by ATH4fun** [comment]
thanks, but I managed to find a version that works. (3.3.0) online somewhere.
Appreciate your offer though!

**Comment by ATH4fun** [comment]
I have found a solution to my problem and hereby close this thread.
if anybody else has this problem you can find the 1.3.5 version here:
https://www.macworld.co.uk/download/audio-video-photo/plex-media-player-135-3249966/

**Comment by ATH4fun** [comment]
.
