### ISSUE TITLE
dist-2.2.0-rc Smart Playlist Shuffle randomization is broken

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#636]
Currently, the shuffle will only cycle through shows in the playlist that are immediately visible on screen regardless of how many shows/episodes are in the playlist in general.

Latest PMS (Version 1.9.7.4441)
PMP built from dist-2.2.0-rc

Using managed/non-account user to shuffle play the smart playlist.

**Comment by Enigma0** [comment]
Is there maybe going to be a fix for this branch or should I be using a different branch?

**Comment by Enigma0** [comment]
Is this fixed in the latest release?

**Comment by LongChair** [comment]
@Enigma0: sorry for teh VERY late reply. 

I suppose this can be closed now ?

**Comment by Enigma0** [comment]
It's working correctly with latest builds that I've used.
