### ISSUE TITLE
Exit command does not exit in build 730

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#638]
When triggering Exit during playback in build 730, it opens up the bottom OSD instead of jumping out of the video. If the OSD is already up however, it will exit.

PMP log:
https://gist.github.com/atrus05/5273635b45178731ecee4b7a9c0f55be

OS: OSX 10.12.6
Hardware: Mac Mini Quad i7 (2012) hooked up straight to a Panasonic VT50 via HDMI

**Comment by LongChair** [comment]
i guess this should be fixed now :) closing.

**Comment by atrus05** [comment]
It is indeed fixed now :)
