### ISSUE TITLE
PMP embedded not sending status info

### ISSUE THREAD

**Issue by avie** [plexinc/plex-media-player#639]
I'm using the Plex API to build a remote.  After doing a .../timeline/subscribe/... I am able to receive status messages from the client when PMP is running on Windows.  However, if I use the embedded client I do not get the messages.  The embedded client does correctly handle other messages (e.g., navigation and playback messages).

**Comment by LongChair** [comment]
@avie : i think this should be fixed now, can you confirm we can close this please ?

**Comment by avie** [comment]
Thank you for the fix.  I currently have no way to test this but if you have tested it yourself then I am fine with you closing it.
