### ISSUE TITLE
Screensaver options

### ISSUE THREAD

**Issue by NedtheNerd** [plexinc/plex-media-player#64]
Can we please have screensaver options for the following

1. Have an option to turn off screensaver,
2. Have an option to dim the display (i.e. dim screen by 70%, other selectable %'s would be ideal,
3. Have an option to display FanArt, preferably selectable by library,
4. Have an option to display photos, preferably by library/folder within library.

Regards

**Comment by dogonwheels** [comment]
The last two are more feature request like than bug fixes, arguably - but they would be lovely to have.

You can turn off the screensaver right now in settings by selecting 'None'. For the 2nd, we have some auto dimming already, based on 95% of the sleep time (I think?) and it dims to 50%.

**Comment by NedtheNerd** [comment]
Yeah, sorry about 1.

The dim function is there but the floating Plex screensaver then kicks in, that's why the request for 2.

I didn't mention that they were bug fixes.

**Comment by dogonwheels** [comment]
> I didn't mention that they were bug fixes.

Sorry, I accidentally implied that. We're trying to keep this tracker just for bugs rather than feature requests. Feature requests can still live in the forums, for now, https://forums.plex.tv/discussion/186805/reporting-plex-media-player-issues - although we're still all feeling our way around this new process!

For 2, you're thinking just dim, and not show the bounce at all?

**Comment by tru** [comment]
Yeah let's try to keep github for technical issues right now.

Please post the feature requests to our forums.

**Comment by NedtheNerd** [comment]
You can tag as 'Enhancement' or close if you wish.

If using GitHub correctly and you don't want users from filing issues then you could get someone from Plex Inc to raise the 'Enhancements' from the forum in Github, using language that is understood by your Devs.  That way they do not get lost and gives you a reference to post in a forum response.

Regards

Regards

**Comment by NedtheNerd** [comment]
Are you also closing all of the other issues that are flagged as 'Enhancements'?

**Comment by elan** [comment]
I will +1 your (3) and (4) on a feature request post :laughing:
