### ISSUE TITLE
Use arrows as seek buttons in the Desktop mode

### ISSUE THREAD

**Issue by enchained** [plexinc/plex-media-player#643]
I can control seeking using my keyboard arrows in the TV mode, but this mode is not comfortable enough for keyboard and mouse usage. But when I switch to the Desktop mode, arrows skip between files instead, and I have to use , and . to seek. But it's counter-intuitive, since every other player uses arrows, and I forget every time and accidentally switch files which is annoying.

As far as I understand, "not using arrows by default" comes from the original plex web player buffering issues when seeking. Does PMP Desktop have those issues? Cause as far as I understand, it uses mpv just like the TV mode, which can use the arrows for seeking just fine.

Could you please look into this, and revise desktop mode player capabilities based on its current mpv backend, instead of inheriting the web player UI limitations?

**Comment by Enigma0** [comment]
Please. OR at least provide a setting that lets people choose.

**Comment by mseeley** [comment]
I'm closing down this issue and opening another internal issue to track this down. Let's keep the Github issues limited to bug reports.

Arrow key seeking is typical in video players, let me see what I can do.
