### ISSUE TITLE
Missing prebuilt  package web-client-desktop/3.29.7-98ffa9d@plex/public

### ISSUE THREAD

**Issue by comio** [plexinc/plex-media-player#645]
Hi devs,
can you provide a prebuilt web-client-desktop/3.29.7-98ffa9d package?
I'm trying to update my plex-media-client package for Gentoo (see `https://github.com/fkmclane/overlay/tree/master/media-tv/plex-media-player`) but I cannot finalize without the web-client-desktop component.

Thanks,

ciao

luigi

**Comment by Supportlik** [comment]
Should be a duplicate to #641

**Comment by comio** [comment]
Yes and No.
Both bugs refer to missing web-client-desktop prebuilt images. But I prefer to have a separate Issue for each missing, hoping in a solution for each.

**Comment by markus101** [comment]
Apologies for the delay, but we're moving away from conan for web client dependencies, the changes are currently in the `tv2` branch and we're working on getting those changes into `master`.

See: https://github.com/plexinc/plex-media-player/issues/656 for more details
