### ISSUE TITLE
Can't run `conan install` due to a conflicting package

### ISSUE THREAD

**Issue by Cogitri** [plexinc/plex-media-player#646]
Hello,

when I run ```conan install``` with the latest version ( 2.2.1.758-5dad2d62 ) I get the following error:
```
ERROR: Conflict in web-client-desktop/3.29.7-98ffa9d@plex/public
    Requirement plexconantool/1.1@plex/public conflicts with already defined plexconantool/1.0@plex/public
    Keeping plexconantool/1.0@plex/public
    To change it, override it in your base requirements
```

I'm using conan 0.30.2

**Comment by JSMSC** [comment]
I have the same issue since I updated conan today. 
I'm now unable to build any version of PMP by myself.

**Comment by father-mande** [comment]
Hi,

This **conflict** seem to come from a old version of python
... python 2.7.5 or .6 fail with this message
... python 2.7.13 ... by pass this error BUT fall with another one explain in other posts : 
here attached a full trace of : **conan install ..** on a fresh Ubuntu 14.04 + Python 2.7.13
[trace_conan_install.txt](https://github.com/plexinc/plex-media-player/files/1583969/trace_conan_install.txt)

**fall in error :** 
plexconantool/1.1@plex/public: Package '5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9' created
web-client-desktop/3.29.7-98ffa9d@plex/public: WARN: Can't find a 'web-client-desktop/3.29.7-98ffa9d@plex/public' package for the specified options and settings:
- Settings: 
- Options: 
ERROR: Missing prebuilt package for 'web-client-desktop/3.29.7-98ffa9d@plex/public'
Try to build it from sources with "--build web-client-desktop"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

**Comment by JSMSC** [comment]
Did the switch --build web-client-desktop work for anyone? 
I get an error about missing privileges.
At the moment nothing seems to work (tried various Python and conan versions).

**Comment by yochananmarqos** [comment]
@JSMSC No, it didn't. See the results [here](https://github.com/plexinc/plex-media-player/issues/641#issuecomment-351888545).

**Comment by markus101** [comment]
This conflict is coming from an issue with the tv2 package. This will be addressed in the next release.
