### ISSUE TITLE
Location of config for 'remember me' user

### ISSUE THREAD

**Issue by OJFord** [plexinc/plex-media-player#647]
Where is it stored that a user is authenticated, or what a user's password is, however it's done?

I'm using PMP in a Docker container, so in order to use this setting I need to make it's storage a Docker volume, or bound to somewhere on the host machine.

cf. nicjo814/docker-plexmediaplayer#2

Many thanks.

**Comment by LongChair** [comment]
All what's needed to remember user is stored in th configuration file.
