### ISSUE TITLE
Shuffle a single season of a TV show is broken

### ISSUE THREAD

**Issue by ddolcimascolo** [plexinc/plex-media-player#648]
Hey guys,

There's a regression in a recent PMP release: shuffling a single TV show season shuffles the whole show instead.
Though I'm unsure of the exact version, I strongly believe it landed in 2.2.0.

This is so sad, I'm using this exact feature every day...  

Can you confirm the regression and release a fix? I can provide any log files, screenshots, whatever. Feel free to ask, but the reproduction is so easy you might not need anything :) 
I also found #636 talking about shuffle issues but I can't understand if it's related and seems to old to be linked. My issue appeared like 2 days ago. 

Thanks, 
Regards, 

David

**Comment by Enigma0** [comment]
#636 is relating to shuffling a large list but only selecting items that have been rendered seemingly.

This seems a little different but related possibly.

**Comment by ddolcimascolo** [comment]
Hey guys,

In case it helps, I noticed the bug is trickier than I initially thought. It doesn't actually shuffle the whole show, it shuffles the seasons greater than or equal to the selected season.
E.g.: try to shuffle season 4 of a 6 seasons series, PMP will shuffle seasons 4, 5 and 6.

Regards, 
David

**Comment by ddolcimascolo** [comment]
Any news?

**Comment by LongChair** [comment]
@markus101 : is that a known issue ?

**Comment by markus101** [comment]
Yeah, this is a known issue, there is an internal issue tracking it.

**Comment by LongChair** [comment]
@markus101 ; internal issue being closed, should we close this ?

**Comment by markus101** [comment]
Yes it should be. Closing it now.
