### ISSUE TITLE
Trailers fail to play before movie

### ISSUE THREAD

**Issue by Enigma0** [plexinc/plex-media-player#649]
I just get a playback failed message.

Trailers work in other players (web) so it's not a server issue.

**Comment by LongChair** [comment]
@Enigma0 : is that still an issue with recent builds ?

**Comment by LongChair** [comment]
Also some log would be uselful

**Comment by Enigma0** [comment]
Was an on-again off-again issue but has been working stable for several months now.

**Comment by LongChair** [comment]
Thanks, will close it for now then.
Feel free to reopen if it shows up again.
