### ISSUE TITLE
Double keypresses on Raspberry Pi 2

### ISSUE THREAD

**Issue by spacecakes** [plexinc/plex-media-player#65]
Plex Media Player interprets keypresses twice. The problem is intermittent and is fixed by restarting Plex Media Player.
#### Version info
- Plex: 2.4.27
- Plex Media Player: 1.0.0.4
- OS: OpenELEC
- Hardware: Raspberry Pi 2
#### Details
- I am using a FLIRC to convert IR commands to keypresses. I believed this to be the culprit at first, but it doesn't seem to be since the problem goes away by restarting PMP. 
- Rebooting the RPi2 is not necessary. Simply restarting PMP is enough.
- The problem seems to appear at random. Sometimes just for select keypresses after which it goes back to normal, and sometimes for _all_ keypresses, requiring a restart.
- No changes applied to keymaps or anything else not available through the GUI.

**Comment by dogonwheels** [comment]
When this happens again, could you please grab the log files and put them here? Thanks!

**Comment by spacecakes** [comment]
Sure! 
There are a few log files in the folder on my Pi 2. Does PMP begin on a new file after each restart? If so, __plexmediaplayer.log.1__ should be the one.

**Comment by wm4** [comment]
> Does PMP begin on a new file after each restart?

Yes. It also rotates the log file when it's been running for longer.

**Comment by spacecakes** [comment]
Then this should be it: https://dl.dropboxusercontent.com/u/3076112/plexmediaplayer.txt

Sorry, I seem unable to attach anything but images here.

**Comment by tru** [comment]
Hmmm, that definitely looks like we are getting double commands in from the FLIRC. Are you using a harmony? IN that case you can try to tweak the number of retries it does for a certain command.

**Comment by NedtheNerd** [comment]
Looks like the 'suppress repeat' needs a different value (possibly 6).

**Comment by spacecakes** [comment]
No Harmony, but a B&O TV with an IR repeater built in. I.e. the TV controls the FLIRC. 

That's interesting though. If it's the Flirc, then I don't understand why a restart of Plex resolves it. Weird.

**Comment by tru** [comment]
Is this a problem still?
