### ISSUE TITLE
volume bar not remembered across different media

### ISSUE THREAD

**Issue by billyvnillly** [plexinc/plex-media-player#650]
Play music
Set volume to 50%
Stop music
Start playing movie
--For me, the volume icon shows 100%, yet the movie is only playing at 50% volume.  If I click the volume bar the volume returns to normal 100% (or where ever i click it to).

Windows 10 64-bit
version 1.11.0.4633

**Comment by LongChair** [comment]
@billyvnillly : is that issue still relevant with recent builds ? or can we close this?

**Comment by mseeley** [comment]
Closing this out. Volume works consistently across media types.
