### ISSUE TITLE
Conan conflicting when attempting to install

### ISSUE THREAD

**Issue by KevOBrien** [plexinc/plex-media-player#651]
I keep getting the following error on two different machines that I installed Manjaro on in the last few days:

    Requirement plexconantool/1.1@plex/public conflicts with already defined plexconantool/1.0@plex/public
    Keeping plexconantool/1.0@plex/public
    To change it, override it in your base requirements

Installation is then aborted.

**Comment by father-mande** [comment]
Hi,

**EVEN the problem exist and not yet solved by Plex team** ... you can temporary use a workaround
https://github.com/plexinc/plex-media-player/issues/641

Be attention to : 
have a Python 2.7 updated (.13)
adapt to the PMP you want to build (here it's for PMP2) ... minimal target change are needed for PMP1
before choosing to follow initial recommendation, be sure it's needed in your environment (lib in search lib path or not, vaapi-copy supported or not by your GPU (you can set it later using mpv.conf file), etc.)

... perhaps some other adaptation linked to Manjaro distribution ... I don't know
Philippe.

**Comment by markus101** [comment]
This conflict is coming from an issue with the tv2 package. This will be addressed in the next release.
