### ISSUE TITLE
Repository conan.plex.tv is unavailable

### ISSUE THREAD

**Issue by knapsu** [plexinc/plex-media-player#653]
The Conan repository https://conan.plex.tv/ appears to be down for several days now. Any package request will result in `Error: 404 Not Found`. This makes it impossible to build Plex Media Player from sources as `web-client-desktop/*@plex/public` package can't be downloaded.

**Comment by father-mande** [comment]
Hi,

Even it's always true ... a workaround (NOT a solution always wanted from Plex.tv team) exist ...
I use them to build PMP for QNAP and Asustor (the base is an Ubuntu 14.04 (but I have tested on 16.04)
... but I don't retest build (last build 22 days ago)
#641 

It's really strange that Plex don't do anything to solve this ... but now it's 2018 so we can hope ...

Philippe.

**Comment by markus101** [comment]
Apologies for the delay, but we're moving away from conan for web client dependencies, the changes are currently in the `tv2` branch and we're working on getting those changes into `master`.

See: https://github.com/plexinc/plex-media-player/issues/656 for more details
