### ISSUE TITLE
Remember/save music playback settings

### ISSUE THREAD

**Issue by vaites** [plexinc/plex-media-player#654]
The music playback interface is great but does not remember the settings and I must change it every time. I mean: list mode, random and repeat toggles. I think these settings must be remembered or be configurable in settings.

I'm using a self-compiled version of 2.2 version on Linux (Ubuntu 16.04 LTS).

Thanks for your great work!

**Comment by LongChair** [comment]
@markus101 : anything we can do there ? ;)

**Comment by markus101** [comment]
It looks like this is consistent across many clients (settings aren't maintained between playback), I'll mention it, but closing this out.

Plexamp may already do this https://www.plex.tv/plex-labs/
