### ISSUE TITLE
Web-client downloads are broken for macos

### ISSUE THREAD

**Issue by LongChair** [plexinc/plex-media-player#656]
While trying to make a few tests builds over the weekend, i noticed CI wouldn't be able to grab webclient from the conan server. 

This seems only to affect OSX builds, windows build went fine . Here is some CI log 👍 

```
+ conan remote add plex https://conan.plex.tv
ERROR: Remote 'plex' already exists in remotes (use update to modify)
+ true
+ conan user plex -r plex -p <secret key>
ERROR: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.10.1</center>
</body>
</html>
. [Remote: plex]
Build step 'Conditional steps (multiple)' marked build as failure
Skipped archiving because build is not successful
Finished: FAILURE
```
This should be fixed ASAP as it will avoid any further CI build.

**Comment by tru** [comment]
Currently the web-client is built on the old CI, uploaded to the old conan server that is only being used by PMP right now. I think the sanest thing to do is to move the building to the new ci and move the upload to artifactory so that we can shut down the old conan server. This will be something we want to do soon anyway.

**Comment by markus101** [comment]
I'm seeing this on Windows when I attempt to authenticate with `conan user`.

**Comment by jleroy** [comment]
Is there a workaround for this issue? 
This prevent me from building RPM packages for the latest release.

**Comment by tru** [comment]
Pull latest tv2 branch. We reworked it and now you don’t need conan for web-client anymore.

**Comment by jleroy** [comment]
Indeed, it works without Conan.
Maybe you should update the README.

**Comment by tru** [comment]
Pretty sure I did on that branch.

**Comment by jleroy** [comment]
Yep, sorry.

**Comment by LongChair** [comment]
that should be fixed currently, closing it
