### ISSUE TITLE
move dependencies over to conan

### ISSUE THREAD

**Issue by LongChair** [plexinc/plex-media-player#657]
After checking #656 with @tru, it seems that moving dependencies to the new conan/artifactory would be a smart move.
Looks like old conan server will be shut down in a near future and we probably don't wanna be blocked by this.

I am not sure what this involves and will let @tru give more details.

pinging @mseeley and @markus101 here so that they can voice their thoughts :)

**Comment by tru** [comment]
Currently the only thing used with conan in PMP is the web-client. That is something we need to handle in #656 

The dependencies (Qt, FFmpeg, mpv etc) is built with the old plex-dependency-builder in the old CI. This is bad in a few different ways:

1) We are looking at winding down the old CI and we no longer support it that actively.
2) Currently there is no way to share codecs / ffmpeg between pmp and server. Conan could fix this
3) We have a lot more resources to put behind the new ci - so move there and the build reliability and build times would improve.

It's a bit of work - I would say maybe a week of work from my side. I think it's worth doing - but I need a PM to sign off on doing it before we start a job like that.

**Comment by LongChair** [comment]
@tru : any update on this or forecast ? ;)

**Comment by LongChair** [comment]
This is going to happen in a near future, no need to track it here :) Closing.
