### ISSUE TITLE
Add build (or config) option to disable WebUI mode

### ISSUE THREAD

**Issue by dgw** [plexinc/plex-media-player#663]
99% of the time, when PMP goes into WebUI mode, it's not what I wanted it to do. Usually I'm just trying to move the window between monitors, or hit the <kbd>\\</kbd> key by accident.

Would there be any support for a build option that removes the WebUI mode (with the added benefit of being a much more open source–friendly build without the proprietary dependencies that requires), or at least a config/runtime option to disable the WebUI mode for those of us running PMP in settings where the WebUI is not useful to have in a player device?

**Comment by enchained** [comment]
Are you saying that hitting <kbd>\\</kbd> switches your mode from TV to WebUI? Cause it doesn't happen in my setup. I can open the web mode only in one case - I explicitly use the mouse, on mouse move a button with arrows appears next to the user avatar, and only by clicking on it I can go to the web mode.
If you do not misclick on that ui button too, there's no need for a WebUI disabling - just go to Settings - Main - Layout: TV (default Auto auto-switches the modes I guess). My PMP version is 2.4.1 by the way.

**Comment by dgw** [comment]
Changing the "Layout" setting has indeed gotten rid of PMP switching into Web mode when I make it into a window, either on purpose or by accident. Thanks for that!

I still see a case for a compile-time flag that removes the dependency on closed-source blobs from Plex.

**Comment by LongChair** [comment]
@dgw `-DWEB_CLIENT_DISABLE_DESKTOP=on` should allow you to do this.
Can we close this ?

**Comment by dgw** [comment]
Yep! :+1:
