### ISSUE TITLE
2.7.0 on QNAP (ubuntu 14.04) 4k/30H/H265 don't play when kodi18 can play it (new tests)

### ISSUE THREAD

**Issue by father-mande** [plexinc/plex-media-player#667]
Hi,

**PMP2 2.7.0 works as well on QNAP** (Ubuntu 14.04 based) **BUT** a user (not easy with posting issue) have problem only when Playing H265/4K/30Hz/mkv (no video screen blue) and interface refresh works badly) ... I can't test don't have a 4K TV ...
ref. : https://forum.qnap.com/viewtopic.php?f=121&t=135441&p=660237#p660146
BUT on same system Kodi18 ALPHA build 20180203 (as PMP build by me so same libraries) play same without problem.
Log list lot of error on **opengl-cb**.

Join files : PMP log / Kodi.log (to compare?) / plexmediaplayer.conf (suffixed by .log to be accepted)) and here after vainfo
[kodi.log](https://github.com/plexinc/plex-media-player/files/1755840/kodi.log)
[PMP.log](https://github.com/plexinc/plex-media-player/files/1755841/PMP.log)
[plexmediaplayer.conf.log](https://github.com/plexinc/plex-media-player/files/1755842/plexmediaplayer.conf.log)

libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
vainfo: VA-API version: 0.40 (libva )
vainfo: Driver version: Intel i965 driver for Intel(R) Broxton - 1.8.0
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileH264MultiviewHigh      : VAEntrypointVLD
      VAProfileH264MultiviewHigh      : VAEntrypointEncSlice
      VAProfileH264StereoHigh         : VAEntrypointVLD
      VAProfileH264StereoHigh         : VAEntrypointEncSlice
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileVP8Version0_3          : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD

Any advice, option for mpv or way to analyse my build ...
Philippe.

**Comment by softgiggio** [comment]
Hi, if it can be useful, the TV is LG OLED 55C6V and the Qnap is TS-253B

**Comment by father-mande** [comment]
Hi,

I have done some more tests, due to lack of 4K screen it's based on 1080P / HEVC file
File use : test HEVC **Tear Of Steel** (http://www.h265files.com)
Model NAS **AMD RX-421BD**
... with Video Acceleration for HEVC Main 8
Playing file with PMP 2.7.0.
... Info ... lot of frame drop (even less when using Pulse in place of Alsa)
Test using MPV with same library 1.29
**1** : use GPU (so without V.A.)
_root@NAS473aPhil:/opt/mpv/bin# ./mpv /share/Multimedia/TearsOfSteel_720p-h265.mkv
Playing: /share/Multimedia/TearsOfSteel_720p-h265.mkv
 (+) Video --vid=1 (*) (hevc 1280x720 24.000fps)
 (+) Audio --aid=1 (*) (aac 6ch 48000Hz)
AO: [pulse] 48000Hz 5.1 6ch float
VO: [gpu] 1280x720 yuv420p
AV: 00:00:44 / 00:12:14 (6%) A-V:  0.000 Cache: 689s+115MB_
---- run as well but use lot of CPU
**2** : use vaapi
_root@NAS473aPhil:/opt/mpv/bin# ./mpv -vo=vaapi -hwdec=vaapi /share/Multimedia/TearsOfSteel_720p-h265.mkv
Playing: /share/Multimedia/TearsOfSteel_720p-h265.mkv
 (+) Video --vid=1 (*) (hevc 1280x720 24.000fps)
 (+) Audio --aid=1 (*) (aac 6ch 48000Hz)
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
Using hardware decoding (vaapi).
AO: [pulse] 48000Hz 5.1 6ch float
VO: [vaapi] 1280x720 vaapi[nv12]
AV: 00:00:14 / 00:12:14 (2%) A-V:  0.000 Dropped: 43 Cache: 719s+119MB_
--- RESULT is frame drop exactly as with P.M.P. 2.7.0.
**3** : force use of vdpau
_root@NAS473aPhil:/opt/mpv/bin# ./mpv -vo=vdpau -hwdec=vdpau /share/Multimedia/TearsOfSteel_720p-h265.mkv
Playing: /share/Multimedia/TearsOfSteel_720p-h265.mkv
 (+) Video --vid=1 (*) (hevc 1280x720 24.000fps)
 (+) Audio --aid=1 (*) (aac 6ch 48000Hz)
AO: [pulse] 48000Hz 5.1 6ch float
VO: [vdpau] 1280x720 yuv420p
AV: 00:00:31 / 00:12:14 (4%) A-V:  0.000 Cache: 702s+117MB_
--- RESULT loww CPU no frame drop ... all run as expected
**4** : test vaapi + alsa (so like in working Kodi18)
_root@NAS473aPhil:/opt/mpv/bin# ./mpv -vo=vaapi -hwdec=vaapi -audio-device=alsa /share/Multimedia/TearsOfSteel_720p-h265.mkv
Playing: /share/Multimedia/TearsOfSteel_720p-h265.mkv
 (+) Video --vid=1 (*) (hevc 1280x720 24.000fps)
 (+) Audio --aid=1 (*) (aac 6ch 48000Hz)
libva info: VA-API version 0.40.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_0_40
libva info: va_openDriver() returns 0
Using hardware decoding (vaapi).
AO: [alsa] 48000Hz stereo 2ch float
VO: [vaapi] 1280x720 vaapi[nv12]
AV: 00:00:01 / 00:12:14 (0%) A-V:  0.000 Cache: 732s+121MB
[ao/alsa] Write error: Broken pipe
AV: 00:00:01 / 00:12:14 (0%) A-V:  0.290 Dropped: 4 Cache: 731s+121MB
[ao/alsa] Write error: Broken pipe
AV: 00:00:03 / 00:12:14 (0%) A-V:  0.000 Dropped: 11 Cache: 730s+121MB
[ao/alsa] Write error: Broken pipe
AV: 00:00:03 / 00:12:14 (0%) A-V:  0.290 Dropped: 15 Cache: 729s+121MB
[ao/alsa] Write error: Broken pipe
AV: 00:00:05 / 00:12:14 (0%) A-V:  0.000 Dropped: 22 Cache: 728s+121MB
[ao/alsa] Write error: Broken pipe
AV: 00:00:05 / 00:12:14 (0%) A-V:  0.290 Dropped: 26 Cache: 727s+121MB
[ao/alsa] Write error: Broken pipe
AV: 00:00:07 / 00:12:14 (1%) A-V:  0.164 Dropped: 34 Cache: 726s+120MB_
--- RESULT more frame dropped ... and Alsa error

MPV.CONF is not read or perhaps read but don't accept vo or hwdec parameters ... so not possible to change PMP settings ...

**Summary** : 
PMP "normal" usage : frame dropped
MPV GPU (so not possible with 4K / Main10) run without dropped frame
MPV vaapi ... same as PMP and worst if in PMP or MPV we use ALSA
MPV vdapau ... works as well (low CPU / NO frame dropped) but don't seem to be forced in PMP ...

Philippe.

**Comment by LongChair** [comment]
is that still an issue or can we close this ?

**Comment by father-mande** [comment]
Hi,

NO ... result is same with 2.8.0. ... when running ALPHA kodi18 on same system (same Xorg / same VAAPI/ same libraries) 4K (same movie) works as well ...

This problem is also near the other problem with how to return to vdpau using mpv.conf (read but ignored) ... this can be a workaround ... even if it's not a full solution ...

I am an integrator and run tests on my own system (2 QNAP one Intel the second AMD) and one Asustor ... so some problem exist with other models (for ex.supporting 4K and HEVC ... when I own only 1080P ...

SO I try a first analyse (due to the specific platform ... NAS (I start with OpenPHT, then PMP1 and now PMP2 ... ) that have a sort of specific embedded Linux ... but I can't solve some problems ... due to my limited skill, the fact that I am a user not a developer ... nor a "professional" 

Perhaps it's not a good idea to try to use PMP2 on this kind of platform ... even if it works ... to avoid this kind of additional problems to you.

Philippe.

**Comment by LongChair** [comment]
So that is related to https://github.com/plexinc/plex-media-player/issues/671 ?

**Comment by father-mande** [comment]
Hi,

For a workaround (if result test will be good) ... YES
For the normal usage ... NO because libmpv must be able to play 4K without frame drops ...

Philippe.

**Comment by LongChair** [comment]
This sounds like an mpv issue, you should probably report it on the mpv bugtracker.
When it works in mpv properly, just let us know which version fixes the issue.
We bump it from time to time, but don’t fix mpv issues

**Comment by LongChair** [comment]
@father-mande : if you create an issue in mpv repo for this, thanks to link it from here so that we can track progress :)

**Comment by LongChair** [comment]
Will close this now because it is an mpv related issue, which should be reported to mpv :)
