### ISSUE TITLE
WiFi drops

### ISSUE THREAD

**Issue by timinski** [plexinc/plex-media-player#668]
Have issues with following setup: 
PMS Linux
- cabled to router
PMP embedded Pi3B, Allo DAC
- Pi3B wifi connection to router
PMP embedded Pi3B, HiFiBerry Amp+ Pro
- Pi3B wifi connection to router

Issues:
- PMP devices both show as Plex Media Player on Plex Web as targets for flinging.  How to name one differently?
- PMP devices only show intermittently as fling targets on Plex Web.  Does the WiFi channel need to be forced in LibreElec?  If so, how does one do this with the default PMP LibreElec (installed from plex.tv download)?

**Comment by LongChair** [comment]
You can change the name that the device will have editing the `.local/share/plexmediaplayer/plexmediaplayer.conf` file. The entry should be `systemname` IIRC.
You second issue could be related to the first one. There is no specific requirement for Wifi configuration as long as it's setup normally.

**Comment by timinski** [comment]
@LongChair 
Thank you so much for your reply.  I have remoted to the site and changed plexmediaplayer.conf via ssh and rebooted it.  Will see how it goes tomorrow....and post the results here for others to see.

Of note: I also changed the wifi channel on the router from its default to 8

**Comment by timinski** [comment]
@LongChair 
-- before I retire for the evening, a question occurs to me: should I have mounted the flash rw before making the plexmediaplayer.conf change?  I had no problem changing the file but perhaps I was only editing a cached version?

**Comment by LongChair** [comment]
to make sure that PMP will not save configuration on exit, just do the following :

- SSH in
- run `systemctl stop plex` to to PMP 
- edit `plexmediaplayer.conf`
- reboot

The configuration file is not stored on the flash mount, and `/storage` is already rw, so remounting it rw is useless :)

**Comment by LongChair** [comment]
Closing this as it seems fixed.
