### ISSUE TITLE
PMP fails to connect to my server through indirect connection

### ISSUE THREAD

**Issue by vlebourl** [plexinc/plex-media-player#672]
Although plex web (on chrome) connects without issue, desktop plex media player (macOS 10.12) is unable to establish connection.

![image](https://user-images.githubusercontent.com/5701372/37142631-ef8f0714-22b8-11e8-87cd-1f5ce5e15906.png)

**Comment by LongChair** [comment]
Could you post the log files to see what's happening ?

**Comment by vlebourl** [comment]
here you go
[log.log](https://github.com/plexinc/plex-media-player/files/1796126/log.log)

**Comment by vlebourl** [comment]
and the one of the working web player (on chrome).
[log.log](https://github.com/plexinc/plex-media-player/files/1796137/log.log)

**Comment by LongChair** [comment]
I would need full logs, things might happen earlier please.

**Comment by vlebourl** [comment]
where can I get that?

**Comment by LongChair** [comment]
https://support.plex.tv/articles/207338748-plex-media-player-logs/

**Comment by vlebourl** [comment]
[Plex Media Player.log](https://github.com/plexinc/plex-media-player/files/1797688/Plex.Media.Player.log)
[pmphelper.log](https://github.com/plexinc/plex-media-player/files/1797689/pmphelper.log)

**Comment by LongChair** [comment]
Hi,
Are you still having that issue ?

Looking at the logs et looks like there are a lot of network related errors.
PMP seems not to be able to even connect to loopback.

You might want to check your firewall settings to make sure port 32400 isn't blocked ?

**Comment by LongChair** [comment]
Closing due to the lack of feedback, feel free to reopen if needed.
