### ISSUE TITLE
[BUG] Plex Media Player (UWP) - visual bug

### ISSUE THREAD

**Issue by Seeveen** [plexinc/plex-media-player#673]
i notice that new tv shows do not show episode numbers or that is a new tv show or season

this is how Plex Media Player (UWP) display
![capture](https://user-images.githubusercontent.com/24566404/37254812-1ab9a758-253b-11e8-92f5-6770ee49d265.JPG)
and this is how Plex Media Player desktop (ROKU, iOS) is displayed
![capture1](https://user-images.githubusercontent.com/24566404/37254825-2cd31fc8-253b-11e8-88d4-55e0ec311d58.JPG)

**Comment by OttoKerner** [comment]
This is for the real Plex Media Player only.
The Windows UWP app is something completely different.
