### ISSUE TITLE
Double Input Problem with Custom Input Map

### ISSUE THREAD

**Issue by paulallison99** [plexinc/plex-media-player#674]
A user logged this problem on the forums. https://forums.plex.tv/discussion/311338/custom-input-map-isnt-working-what-am-i-missing#latest

A few of us couldn't reproduce it but most of us didn't have the right combination of Windows and a PS controller. I'm logging it in case anyone can reproduce as I'm aware we had double input issues in the past. 

The user followed these instructions ( https://support.plex.tv/articles/216459997-create-your-own-inputmap/ ) to create his own input map.  He appears to have the correct idmatcher, "Microsoft PC-joystick driver". and placed it in the correct "C:\Users\USERNAME\AppData\Local\PlexMediaPlayer\inputmaps" folder.

The following double-inputs occur:
Square "KEY_BUTTON_2": "stop", -> this cycles the audio
Select "KEY_BUTTON_6": "toggle_subtitles", -> toggles the subtitles AND debug overlay

The controllers are genuine PS3 controllers connected to windows both wired and wireless via SCPToolkit which tricks Windows into thinking that the controller is an XBox controller. Installation instructions for SCPToolkit were from this video ( https://www.youtube.com/watch?v=yH0pTK62DAQ&t=4s ). 

[Playstation Controller json.txt](https://github.com/plexinc/plex-media-player/files/1802499/Playstation.Controller.json.txt)
[PlexMediaPlayer - Controller Input Test.log](https://github.com/plexinc/plex-media-player/files/1802500/PlexMediaPlayer.-.Controller.Input.Test.log)
[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/1802503/PlexMediaPlayer.log)

**Comment by LongChair** [comment]
I have tried that on OSX with 2.6.0 and couldn't reporduce the issue either.
I did have a PS3 controlelr hooked to it.

I don"t have a windows machine so it's not easy to reproduce for me.

**Comment by LongChair** [comment]
None of us which tried to reproduce that problem could make this happen.
I suspect this is something setup related and I have no idea what we can do about this ... 

Will close for clarity.
