### ISSUE TITLE
Rpi - ensure we fully and correctly limit transcodes

### ISSUE THREAD

**Issue by dogonwheels** [plexinc/plex-media-player#68]
We just updated the limitations to include 10bit and max h264 level, but we should also pass bitrate and resolution.

@rcombs points out we can update bitrate to 62500, at least to match the supported level, even if it's an inexact lumpy thing. Should be passed as `maxVideoBitrate=x`

We can also pass resolution like `videoResolution=1920x1080`.

Both should be shlurped from the client player profile to avoid stale copy pastas.

**Comment by mseeley** [comment]
> Both should be shlurped from the client player profile to avoid stale copy pastas.

10,000 yesses. This gets a little tough because the maxes can live on any container, a codec in the container, or the generic object. Sticking the data in the latter might be good enough so it applies to all container+codec combos.

**Comment by firasdib** [comment]
This issue has progress somewhat I reckon, with the latest profile update for RPi. However, I can still see the profile listing `maxBitrate: 40000,` -- should I update this to `62500`? @rcombs Any thoughts?

Max bit depth is still 8 though, which I believe is the correct level?

**Comment by mseeley** [comment]
So lumpy stuff. The `maxBitrate: 40000,` in the JS is working off of the average bitrate reported by PMS.

We did a lot of work @atrus05 especially to test various bitrates on the rpi. In this case 40000 was a stable max when direct playing. These videos are our go-to source for bitrate ramp testing: http://jell.yfish.us/. We tread this path before, Daniel do you recall behavior above 40000?

Right, 8 is absolutely the correct level.

Passing the max width and height to the transcoder from `KonvergoVideoPlayerController#profileExtra()` is still a valid task that would help when the server has to transcode > 1080p content.

**Comment by atrus05** [comment]
@mseeley I seem to recall having the first issue around 50. If it was 45, 50 or 55 I can't say for sure. But bumping to 62 sounds excessive.
If a bump is to be made I recommend trying the files linked on a RPi2 that is not overclocked. I suspect 45 will be safe.

**Comment by mseeley** [comment]
Thanks @atrus05. :)

Okay sounds like the actionable part of this issue is:

> Passing the max width and height to the transcoder from KonvergoVideoPlayerController#profileExtra() is still a valid task that would help when the server has to transcode > 1080p content.

Let's hold off on spending time retreading the bitrate cap on RPi2. We _could_ consider testing bitrate on the RPi3 in a separate issue to keep this one single purpose and quick to close. Thanks!

**Comment by firasdib** [comment]
Alright, I agree. Bitrate stuff can be left the same, I'll fix the other stuff though :smile:

**Comment by firasdib** [comment]
How do you tell the server to limit the resolution to max 1080p? Maybe @rcombs can chime in?

**Comment by mseeley** [comment]
It would be sent to the server as a profile augmentation, handled by `KonvergoVideoPlayerController#profileExtra()`. The profile augmentation syntax is here: https://github.com/plexinc/specs/blob/master/Server/Client%20Profile%20Augmentation.md.
