### ISSUE TITLE
pmphelper don't link QT5.9 when plexmediaplayer do it Ubuntu 1604

### ISSUE THREAD

**Issue by father-mande** [plexinc/plex-media-player#683]
Hi,

Creating (success) plexmediaplayer on Ubuntu 16.04 (and pmphelper)
when I verify lib use (Qt added in /opt for Qt5.9)
plexmediaplayer is linked with QT in /opt NOT pmphelper ????
----------------
# ldd pmphelper | grep Qt
./pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./pmphelper)
./pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9' not found (required by ./pmphelper)
./pmphelper: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: version `Qt_5' not found (required by ./pmphelper)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f097ceb6000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f097c93a000)
# ldd plexmediaplayer | grep Qt
	libQt5Xml.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Xml.so.5 (0x00007f816c9d6000)
	libQt5WebEngine.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5WebEngine.so.5 (0x00007f816c776000)
	libQt5Widgets.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Widgets.so.5 (0x00007f816bf45000)
	libQt5X11Extras.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5X11Extras.so.5 (0x00007f816bd41000)
	libQt5DBus.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5DBus.so.5 (0x00007f816bab8000)
	libQt5WebEngineCore.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5WebEngineCore.so.5 (0x00007f81643c1000)
	libQt5WebChannel.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5WebChannel.so.5 (0x00007f81641a3000)
	libQt5Quick.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Quick.so.5 (0x00007f8163b70000)
	libQt5Qml.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Qml.so.5 (0x00007f8163580000)
	libQt5Network.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Network.so.5 (0x00007f81631ef000)
	libQt5Gui.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Gui.so.5 (0x00007f8162a42000)
	libQt5Core.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Core.so.5 (0x00007f816230a000)
	libQt5Positioning.so.5 => /opt/Qt/5.9/gcc_64//lib/libQt5Positioning.so.5 (0x00007f815bf96000)
	libicui18n.so.56 => /opt/Qt/5.9/gcc_64//lib/libicui18n.so.56 (0x00007f81588d1000)
	libicuuc.so.56 => /opt/Qt/5.9/gcc_64//lib/libicuuc.so.56 (0x00007f8158519000)
	libicudata.so.56 => /opt/Qt/5.9/gcc_64//lib/libicudata.so.56 (0x00007f8156b36000)
--------
using LD_LIBRARY_PATH solve the problem ... but not friendly ...
Philippe.

**Comment by father-mande** [comment]
Hi,

ADD in complement this can be solve also by updating the RPATH in pmphelper (seem not set at build tme) compare to plexmediaplayer
---------
 # patchelf --print-rpath plexmediaplayer
/opt/Qt/5.9/gcc_64//lib
 # patchelf --print-rpath pmphelper

 #
-----------

Philippe.

**Comment by LongChair** [comment]
one question though, what do you need PMPHelper on linux for ?

**Comment by father-mande** [comment]
Hi,

I am not "enter" in the code ... I am just an integrator ... using Ubuntu as base for NAS (QNAP and Asustor)
... so I used the procedure proposed by Plexteam for Linux in the readme ... 
This procedure generate plexmediaplayer and pmphelper ... and when we start plexmediaplayer ... pmphelper is called (and create its own log) ... ...
So, because I check as I can the result, it's for me a problem todon't have a correct pmphelper exec.

BUT if you can explain why it's not used on Linux (so also why it is generated ??? ) ... I can don't deliver it and forgot the problem ... I have not discover in the documentation something about the no use of pmphelper in Linux
F.Y.I. plexmediaplayer.log have a line : 
2018-04-05 17:26:54 [ DEBUG ] HelperLauncher.cpp @ 158 - Launching helper: "/share/CACHEDEV1_DATA/.qpkg/pmp2/opt/pmp2/bin/pmphelper"
indicate that it launch the helper ?????

So I am confuse about your question, thanks to explain.

Philippe.

**Comment by LongChair** [comment]
PMP helper is mainly used to handle automatic updates (which you won't have as we don't have official linux builds). it will also handle crashdumps, but you won't be able to analyze those.

So i would believe you don't need it.
You can avoid pmp to launch it building with `-DENABLE_HELPER=off`. With that set it won't try to launch it on startup.

If that works for you, we can just close this :)

**Comment by father-mande** [comment]
Hi,

YES ... I understand and I will disable helper ... thanks for the information on it ...
... even if in the future ... it can be good to put the correct RPATH as you do in plexmediaplyer ... to avoid false problems like this.

Thanks.
And close this ticket.

Philippe.
