### ISSUE TITLE
macOS - PMP loses all window widgets when shrinking from ⌘F

### ISSUE THREAD

**Issue by ajslater** [plexinc/plex-media-player#685]
- If you maximize PMP with ⌘F it maximizes correctly, but loses all its window widgets. which doesn't matter because you can't do anything with a maximized window.
- But If you then un-maximize PMP with ⌘F, PMP shrinks to a window size but lacks all window widgets. It cannot be dragged or controlled by the macOS window manager. There is no window border or window header.

However, if you maximize PMP with the green maximize button it retains its window widgets and borders and can be un-maximized correctly.

I think the bug happens with ⌘F maximizing, it does something different than maximizing with the green button and destroys the window widgets.

**Comment by kinglouie** [comment]
can confirm this issue, PMPs fullscreen behaves very weird. It seems it doesn't use macOS native Fullscreenapi

**Comment by ajslater** [comment]
Possibly related to https://github.com/plexinc/plex-media-player/issues/664

**Comment by ajslater** [comment]
Sorry, my bad. It used to be Cmd F. It was changed to Cmd-Shift-F (for some reason I don't fully agree with), but the behavior is the same as I described.

**Comment by LongChair** [comment]
@ajslater @kinglouie : can you please check if that build fixed the issue ? 

https://www.dropbox.com/s/6154vjdoc4v6ori/PlexMediaPlayer-2.10.0.854-c1633f57-macosx-x86_64.zip?dl=0

**Comment by ajslater** [comment]
Yes it keeps all window border widgets when maximizing and un-maximizing
with Cmd-Shift-F. Huzzah! :D Thanks.

Bug with this build:
The Movie index display contains some duplicate entries with this build.
Using the current Plex Plus Channel build these ghost duplicates do not
appear.
Underneath most movies the year of screening appears. Underneath the
duplicate movies in the experimental build the subscript "1 movie" or
occasionally "2 movies" appears. Clicking on them just plays the regular
movie. The movies with duplicates do not seem special in any way, they do
not have extras or alternate versions.

**Comment by kinglouie** [comment]
This build fixes the issue for me as well. 👍

**Comment by LongChair** [comment]
PR addressing this issue was merged. Closing :)
