### ISSUE TITLE
player: Unable to play Video in PhotoPlayer

### ISSUE THREAD

**Issue by SonnyBrooks** [plexinc/plex-media-player#689]
### Test environment
**PMS Version:** 1.12.3.4973
**PMP Version:** 6.15.2.4143 (9459e30a)
**Platform (Windows/OSX/Embedded):** Android TV

### Steps to reproduce
1. Play Slideshow of folder that contains mixed content
2. Pictures will play, once it gets to a .gif, .webm, or other animated file type the slideshow will not advance and a message will display saying "Unable to play media"

### Current behavior

1. Pictures will play, once it gets to a .gif, .webm, or other animated file type the slideshow will not advance and a message will display saying "Unable to play media"
2. Logs show "Unable to play Video in PhotoPlayer

### Expected behavior

1. The player should play the animated filetype and continue with the slideshow. 

It used to work fine. Not sure when/what happened. Tried to reinstall and reset TV to factory settings.

**Comment by SonnyBrooks** [comment]
Stack Trace from Error
```
04-15 11:58:59.061  e: An exception occurred: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.plexapp.plex.net.bn.a(java.lang.String, int)' on a null object reference
04-15 11:58:59.137  e: Stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.plexapp.plex.net.bn.a(java.lang.String, int)' on a null object reference
	at com.plexapp.plex.net.i.a(SourceFile:530)
	at com.plexapp.plex.net.i.a(SourceFile:94)
	at com.plexapp.plex.mediaselection.c.d(SourceFile:653)
	at com.plexapp.plex.mediaselection.c.a(SourceFile:100)
	at com.plexapp.plex.mediaselection.h.a(SourceFile:848)
	at com.plexapp.plex.mediaselection.h.doInBackground(SourceFile:820)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

04-15 11:58:59.187  e: [video] Unable to decide on a video for playback: /library/metadata/20452
04-15 11:58:59.228  i: Showing toast: Unable to play media
04-15 11:58:59.229  e: Unable to play video on PhotoPlayer. Message: An error occurred while attempting to play this video. Please try restarting both the Plex Media Server and this app.
```

**Comment by LongChair** [comment]
@markus101 : i think that one is for you :)

**Comment by markus101** [comment]
Closing as this is an android TV issue, not a PMP issue.
