### ISSUE TITLE
player: Full-Screen mode for Plex Media Player not working correctly on macOS

### ISSUE THREAD

**Issue by paulallison99** [plexinc/plex-media-player#695]
2 users are complaining about this issue on the this thread ( https://forums.plex.tv/discussion/307347/full-screen-mode-for-plex-media-player-not-working-correctly-on-macos-high-sierra ) and say it's still not fixed.

### Test environment
**PMS Version:** 1.11.2.4772 on macOS High Sierra
**PMP Version:** 2.4.1.787
**Platform (Windows/OSX/Embedded):** OSX

### Steps to reproduce
1. Open Plex Media Player in Desktop Mode. 
![image](https://user-images.githubusercontent.com/33132075/38945085-68cc81c6-432d-11e8-9072-13a3d015f158.png)

2. Click the green fullscreen button to make it go into full-screen mode. 
![image](https://user-images.githubusercontent.com/33132075/38945110-7af6c78a-432d-11e8-9d1e-2b1d7fbd7e8a.png)

![image](https://user-images.githubusercontent.com/33132075/38945115-8207b4da-432d-11e8-9947-ffc44ba9f5b5.png)

3. Quite out with Cmd+Q.

4. Open Plex Media Player and it will try to open but then fail and do a weird animation. (There is where the attached Gif comes in.) 

### Current behavior
The application does a weird minimize animation and then doesn't allow full-screen mode. There is an animation of this at https://forums.plex.tv/discussion/307347/full-screen-mode-for-plex-media-player-not-working-correctly-on-macos-high-sierra

### Expected behavior
Should go right into full-screen mode just fine and have no problems.

**Comment by LongChair** [comment]
Probably related to https://github.com/plexinc/plex-media-player/issues/688

**Comment by torarnv** [comment]
I've triaged this issue on the Qt side and I'm working on a fix upstream

**Comment by LongChair** [comment]
Thanks @torarnv , nice to see feedback from Qt people :)

**Comment by LongChair** [comment]
@paulallison99 : can you check if that build fixes the issue ?

https://www.dropbox.com/s/6154vjdoc4v6ori/PlexMediaPlayer-2.10.0.854-c1633f57-macosx-x86_64.zip?dl=0

**Comment by kicjow** [comment]
@LongChair I just tested it on mine and it works perfectly now. 

BTW I am the one who made the thread that @paulallison99 posted.

**Comment by LongChair** [comment]
@kicjow : I am glad to hear this is fixed.
Thanks for the feedback :)

Will close this when fix is merged

**Comment by LongChair** [comment]
@carbonbaseunit : did you try the same version on windows?

**Comment by torarnv** [comment]
The fixes I've made are for macOS only. If there are Windows issues in the are of window states, please report upstream :)

**Comment by LongChair** [comment]
PR addressing this issue was merged. Closing :)
