### ISSUE TITLE
player: Pause OSD not hiding on resuming playback

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#703]
### Test environment
**PMS Version:**   1.12.3.4973
**PMP Version:**  Bug started in PMP 2.6 onwards, currently using PMP 2.9
**Platform (Windows/OSX/Embedded):** Win 10 x64

### Steps to reproduce
1. Play a Video, press Pause on MCE Remote, wait small amount of time, press Play

### Current behavior

1. OSD does not disappear since PMP 2.6 release, was fine in PMP releases prior to this

### Expected behavior

1. OSD should automatically disappear when resuming playback

https://forums.plex.tv/discussion/312083/pmp2-6-2-9-pause-osd-not-hiding-on-resuming-playback

**Comment by LongChair** [comment]
ping @markus101

**Comment by RumpaLump** [comment]
This is very annoying, I hope you look into it. This has been a problem for me on all my setups since PMP 2.6. I'm using Windows 10 in all my environments.

**Comment by markus101** [comment]
Internal issue is closed, closing this as well.
