### ISSUE TITLE
no audio when direct playing HEVC with EAC3 from Plex DVR

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#705]
### Test environment
**PMS Version:** 1.13.0.4987
**PMP Version:** 2.9.0.824
**Platform:** Windows

Files recorded by the Plex DVR feature from german OTA free tv (they are in HEVC 1080p50 with E-AC3 audio) often don't play audio when direct played in PMP. As soon as you enable transcoding they do have audio. 
There is also no issue when using other player software like MPC-HC or VLC.

### Steps to reproduce
1. add the linked file into a Plex library https://drive.google.com/open?id=1ViIA5DljnybkeoXBHmkd4QpEDr_iM0MJ
2. play it in PMP with Direct Play

### Current behavior
1. Audio track is muted

### Expected behavior
1. audio should play

**Comment by LongChair** [comment]
@OttoKerner : can you get a full PMP log please ? :)

**Comment by OttoKerner** [comment]
[PlexMediaPlayer.zip](https://github.com/plexinc/plex-media-player/files/1946966/PlexMediaPlayer.zip)

Here is a log file from a successful playback of a movie with EAC3 audio track

**Comment by OttoKerner** [comment]
a playback test with a smaller sample file (50MB)
Non-working (video HEVC, audio EAC3 stereo, container TS)
sample file: https://drive.google.com/open?id=1jZMAyVaTJvwop6Hf3fgtcJCchUhx5Dmf
PMP log [PlexMediaPlayer.log_nonworking.zip](https://github.com/plexinc/plex-media-player/files/1947018/PlexMediaPlayer.log_nonworking.zip)

A different test file which is working (50MB)
(Video AVC, audio EAC3 5.1, container MKV)
sample file https://drive.google.com/open?id=1fd-xIr8cQuF2cv_Dqds89JtcQuZyM0Zx
PMP log [PlexMediaPlayerlog_working.zip](https://github.com/plexinc/plex-media-player/files/1947021/PlexMediaPlayerlog_working.zip)

**Comment by OttoKerner** [comment]
solved in build 2.10.0.843-8e241395

**Comment by LongChair** [comment]
closing this one then :) thanks @rcombs
