### ISSUE TITLE
Keyboard focus lost when Continue Watching vanishes

### ISSUE THREAD

**Issue by WayneD** [plexinc/plex-media-player#709]
The keyboard focus can be lost when the Continue Watching poster vanishes if the current focus is on the last poster in that section. When this happens there is no way to move the focus nor go back nor go home using keystrokes. Seems like I have to either use the mouse to set the focus to a new element, or exit the app and restart it (i.e. Ctrl-Q or Alt+F4 still works).

I've seen this happen in 2 different ways: if you move the focus to one last poster in the Continue Watching section and press 'w' to mark it as watched, the poster will vanish, which leaves you in keyboard limbo.  In some older versions I have also seen the issue occur when pressing Play on the last poster -- once the episode is done it would return to the home screen with the section gone and the same issue. However, recent versions leave the section open with the already-watched show still present, which avoids the issue but seems like the wrong thing to do.

PMS: 1.12.3.4973
PMP: 2.9.0.824
Platform: Windows 10

**Comment by LongChair** [comment]
ping @markus101

**Comment by mseeley** [comment]
I run into this pretty regularly on webOS the only recovery is restoring focus using the pointer.

**Comment by markus101** [comment]
Closing this as it was fixed in 2.24.0 with `Fixed an issue where focus would be lost after removing the last item from a list`.
