### ISSUE TITLE
Focus is not restored when going back to dashboard

### ISSUE THREAD

**Issue by WayneD** [plexinc/plex-media-player#710]
When drilling down into a show's info, pressing Backspace or Esc does not take you back to the show's poster like it should -- it takes you to the top focus item on the page. You can duplicate the issue by starting at most any page (Home, Movies, even a "More..." page).  Use the arrow keys to move down to a poster and then press Enter followed by Backspace (or Esc). The position changes to the top element of the prior screen, losing track of where you were in the grid of posters.

PMS: 1.12.3.4973
PMP: 2.9.0.824 (though all 2.x versions have had this problem)
Platform: Windows 10

**Comment by LongChair** [comment]
ping @markus101

**Comment by markus101** [comment]
This is a limitation of our focus handling, it's on our radar, but no ETA on when it will be addressed.

**Comment by markus101** [comment]
This is currently expected behaviour, tracking this internally and closing this out.

**Comment by WayneD** [comment]
Wow. This is such a horrible usability fail that it should really be an all-hands-on-deck-until-it-is-fixed bug. Unbelievable.
