### ISSUE TITLE
Watch Later Filters are Missing

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#711]
### Test environment
**PMS Version:**  1.12.3.4973
**PMP Version:** v2.10
**Platform (Windows/OSX/Embedded):** Windows

### Steps to reproduce
1. in TV fullscreen mode, enter Watch Later

### Current behavior

1. all watch later videos are displaying, there is no option to view them by all/unwatched/watched like
their is in plexweb and other plex apps. it makes it difficult to navigate and know what you might have already seen etc, it is difficult to use if you have alot of watch later videos, trying to find something you may not have watched yet

### Expected behavior

1. there should be a view option where you can select all/unwatched/watched, and it should remember this last selected view next time you go into Watch Later

**Comment by LongChair** [comment]
ping @markus101

**Comment by mseeley** [comment]
I've moved this feature request to the internal UI repo. You're right, we're not at parity with the v1 app in this regard.
