### ISSUE TITLE
player: no audio with truehd track

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#712]
No audio is heard when playing a file with a TrueHD audio track.
Audio is not passed-through, but simply sent to the computer's audio interface.

sample file (66MB)
https://drive.google.com/open?id=1WprZuscdDxberJ8oX0UWyFQJHZLtVqf8

### Test environment
**PMS Version:** 1.13.0.4995
**PMP Version:** 2.10.0.843-8e241395
**Platform:** Windows

PMP log file
[PlexMediaPlayer.zip](https://github.com/plexinc/plex-media-player/files/1954834/PlexMediaPlayer.zip)

**Comment by LongChair** [comment]
Ping @rcombs : this is with latest dist-mpv fix for eac3. If you can have a look ;)

**Comment by OttoKerner** [comment]
Unfortunately, no change with build 2.10.0.848-46adcac1
[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/1963531/PlexMediaPlayer.log)

**Comment by dan-the-man-nz** [comment]
FYI I played a couple movies with TRUEHD recently, i didnt have any issues, but that sample file does not play audio for me.

**Comment by LongChair** [comment]
@OttoKerner : i think we got that one fixed right ?

**Comment by OttoKerner** [comment]
Yes, issue resolved.
