### ISSUE TITLE
Watch later -  unwatched content has no unwatched flag (orange triangle)

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#719]
Test environment
PMS Version: 1.13.0.5003
PMP Version: 2.10 
Platform (Windows/OSX/Embedded): Windows

### Steps to reproduce
1.  Add something new to Watch Later - in my case it was a youtube video

### Current behavior

1.  in PMP, go to watch later, unwatched content does not have a unwatched indicator (orange flag)

### Expected behavior

1. Watch later - content that is unwatched should be showing the unwatched indicator

![image](https://user-images.githubusercontent.com/906806/39563723-725b6368-4f05-11e8-8200-b8b5b7c66c55.png)

**Comment by paulallison99** [comment]
Shipped.
