### ISSUE TITLE
Watch later - Menu to Delete Videos was removed since 2.10 release

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#720]
### Test environment
**PMS Version:**  1.13.0.5003
**PMP Version:**  2.10
**Platform (Windows/OSX/Embedded):**  Windows 10

### Steps to reproduce
1. Go to Watch Later

### Current behavior

1. there is no option to delete a video from watch later 

### Expected behavior

1. in versions of PMP 2.9 and below, you had the ability to delete videos in watch later

**Comment by paulallison99** [comment]
@luisherrero @craighill a problem here is the new Watch Later/Recommended pages don't have a preplay page for before the video plays. Clicking a video automatically plays it, so the new Delete button needs to be on the main page. I'm just wondering should it be contained in a `...` more menu for consistency (which may be strange as it's the only option), or should I just add a Delete icon beside play (I'd need a new `play-icon-delete-560` icon for that). 
![deletebutton](https://user-images.githubusercontent.com/33132075/40358987-0be4d660-5db9-11e8-82fd-e3fc034f4b73.png)

**Comment by dan-the-man-nz** [comment]
if i can make a suggestion, i think it should be in the ... more menu like above, it would also mean you add add other missing features in watch later, such as Mark as Watched, Mark as UnWatched

personally i would like it like this so its consistant with the rest of PMP

![image](https://user-images.githubusercontent.com/906806/40386231-3cbc4166-5e5d-11e8-8afd-6e0467254c5c.png)

**Comment by paulallison99** [comment]
Thanks @dan-the-man-nz , I think we can go with that, as the V1 menu was also the `...` button with just `Delete`. 
![deletev1](https://user-images.githubusercontent.com/33132075/40590017-db14ed96-61ef-11e8-96c4-32240392a267.png)

**Comment by dan-the-man-nz** [comment]
Hi paul

i tried this change in nightly, seems to work :)

however im not sure the PROMPT messages is clear

Delete Clip
"Are you sure you want to delete this from **your filesystem? "**

its watch later, so its not really on your file system?

**Comment by paulallison99** [comment]
Hi Dan, I see what you mean. That text is hard-coded into the modal for deleting, I can look into making it changeable for this case.

**Comment by craighill** [comment]
Sorry guys - completely missed this ping last week. 

Basically I think you’ve landed where I would have suggested anyway. :)

Paul - Let me know if you need some copy of you work out how to edit that modal. 

One thing, I’d perhaps reword the action to “Remove Video” rather than delete clip.

**Comment by craighill** [comment]
Ahhh - sorry, delete clip is in the modal, not the button action
