### ISSUE TITLE
audio passthrough settings not available in GUI 

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#724]
### Test environment
**PMS Version:**  1.13.0.5003
**PMP Version:**  2.10
**Platform (Windows/OSX/Embedded):**  Windows 10

### Steps to reproduce
1.  Go to Settings - Audio

### Current behavior

1. There is no setting available regarding Passthrough

### Expected behavior

1. Maybe its openpht flashbacks, but i was sure there used to be a setting for this, but its been many moons since i would have checked this, and i saw some posts on the forum regarding it

the PMP docs @ https://support.plex.tv/articles/212072167-audio-configuration-guide-plex-media-player/  talk about passthrough quite a bit, also

![image](https://user-images.githubusercontent.com/906806/39730916-5e3f9fc8-52b8-11e8-8e6e-c6e2d66100d8.png)

![image](https://user-images.githubusercontent.com/906806/39730922-66e0afa0-52b8-11e8-95e4-f517962c9cf1.png)

in the plexmediaplay.conf
![image](https://user-images.githubusercontent.com/906806/39730939-8f555346-52b8-11e8-9e18-8416c09014ee.png)

**Comment by LongChair** [comment]
You need to activate the advanced settings in audio settings to have them

**Comment by dan-the-man-nz** [comment]
here is all the settings i have available in audio, 

this is from my main htpc, which currently has passthrough enabled

![image](https://user-images.githubusercontent.com/906806/39743032-bb18f45c-52f3-11e8-8f6a-a5fece611b2e.png)

**Comment by dan-the-man-nz** [comment]
these are the passthrough settings, they are just not labeled passthrough as one might expect based on other media players, closing issue, sorry.

![image](https://user-images.githubusercontent.com/906806/39749542-110e3062-5307-11e8-9206-c7dd511ac965.png)
