### ISSUE TITLE
Plex Media Player: global subtitle settings not honored

### ISSUE THREAD

**Issue by mseeley** [plexinc/plex-media-player#73]
Moved from: https://github.com/plexinc/plex-web-client/issues/3694

Device: MacBook Air
OS: Windows 7 (VMware)
Build: 1.0.1.13-c066d9c9/

Current behavior: Setting subtitle placement, color, and size does is not reflected during media playback for videos.

Steps to reproduce:
1. Set subtitle in global app settings
2. Start playback of a video
[notice difference]

![screen shot 2015-10-25 at 2 43 06 pm](https://cloud.githubusercontent.com/assets/12398365/10717231/8c93e03e-7b27-11e5-84ed-9ff7f0280f57.jpg)
![screen shot 2015-10-25 at 2 42 56 pm](https://cloud.githubusercontent.com/assets/12398365/10717232/8c98a830-7b27-11e5-925a-022c7206b1fd.jpg)

Referencing https://github.com/plexinc/qa-automation/issues/37

**Comment by wm4** [comment]
Some subtitle formats do not allow changing the styling at all (bitmap subs), while some others do not allow overriding styling by default (SSA/ASS). So clarifying what format it is should be done first. In fact, just upload a playback log.

**Comment by atrus05** [comment]
I tried with srt subs and the settings are honored for me on both my MBP and on my Mac Mini.

**Comment by tru** [comment]
I am going to guess this is  bitmap subtitles then, PGS or something similar. If I am wrong, reopen this issue.
