### ISSUE TITLE
Watch later - new videos did not automatically appear in watch later until PMP was restarted

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#730]
### Test environment
**PMS Version:**  1.13.0.5023
**PMP Version:**  2.10
**Platform (Windows/OSX/Embedded):**  Windows

### Steps to reproduce
1. in PMP, go to watch later, then out of it
2.  Add some videos to watch later, check they are showing in plex web.
3. in PMP, go back into watch later

### Current behavior

1. went to watch later in PMP, new videos were not showing, only old ones, i then restarted PMP
and those newly added videos showed up immediatly

### Expected behavior

1.  PMP should work the same as other plex apps and show up to date video listings in watch later

**Comment by paulallison99** [comment]
Shipped.
