### ISSUE TITLE
Implement mpv's screenshot function

### ISSUE THREAD

**Issue by matthewdias** [plexinc/plex-media-player#733]
It would be useful to be able to bind it in the inputmap. Currently the only way to get screenshots of pmp is using a system screenshot tool which is suboptimal for obvious reasons. I could possibly implement this if someone gives the go ahead.

**Comment by mseeley** [comment]
Hi @matthewdias sorry for the long delay. If you'd like to implement please give it a go, I don't think anyone would complain. ;)

I'm going to close this fella out since we try to keep the repository limited to defect resolution.
