### ISSUE TITLE
Watch Later - No Ability to Mark as Watched, Mark as UnWatched (TV layout)

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#737]
### Test environment
**PMS Version:** 2.10
**PMP Version:**  1.13.1.5063
**Platform (Windows/OSX/Embedded):**  Windows

### Steps to reproduce
1. Go to Watch Later in TV Layout

### Current behavior

1. There is no ability / menu to set a video Watched or Unwatched as their is in other videos in PMP

### Expected behavior

1. There should be the ability to Mark As Watched or Mark As UnWatched as their is in Desktop Mode and other Plex Applications

example, something like the below picture is needed.
![image](https://user-images.githubusercontent.com/906806/40386970-49ae2ac2-5e5f-11e8-8ac0-f9754214db9f.png)

**Comment by paulallison99** [comment]
Shipped.
