### ISSUE TITLE
PMP doesn't reload images at higher quality when window size increases

### ISSUE THREAD

**Issue by oxguy3** [plexinc/plex-media-player#74]
If you increase the size of PMP's window, it will continue to load the same low-quality images it was loading when the window was much smaller. PMP will start loading correct resolution images only once you go to a different menu.

Here's a screenshot of the main menu of the application immediately after increasing the window from 720p to 1440p: https://drive.google.com/file/d/0B9TlHhAutWS-aEhJcDItc1UxVWc/view (hit the download button to see the full 1440p image; Google Drive's preview is reduced resolution). As you can see, all the posters and my avatar picture are really low-quality and have lots of artifacts. Compare to this other screenshot, after I've gone to another menu then returned to the main menu, where all the images look much cleaner: https://drive.google.com/file/d/0B9TlHhAutWS-aTMxTExaX0Z6Qms/view

**Comment by mseeley** [comment]
Hi @oxguy3 thanks for the issue. It's been irking me for a while but never been prioritized since it's very easy to recover.

Related internal issue regarding stale devicePixelRatio: https://github.com/plexinc/plex-web-client/issues/3628
