### ISSUE TITLE
PMP 2.10 Embedded failed to load VAAPI-EGL

### ISSUE THREAD

**Issue by Wolf666** [plexinc/plex-media-player#740]
### Test environment
**PMS Version: 1.13.1
[plexmediaplayer.log](https://github.com/plexinc/plex-media-player/files/2031962/plexmediaplayer.log)

**PMP Version: 2.10.0.873-21333ad5 build date: 2018-05-17
**Platform (Windows/OSX/Embedded):Embedded

### Steps to reproduce
1.

### Current behavior

1. 2018-05-23 18:18:04 [ DEBUG ] PlayerComponent.cpp @ 591 - libmpv_render: Loading hwdec driver 'vaapi-egl' 
2018-05-23 18:18:04 [ DEBUG ] PlayerComponent.cpp @ 591 - libmpv_render: Loading failed. 

### Expected behavior

1.

**Comment by LongChair** [comment]
Yes this is happening with a new test build.
This has been fixed and need some more internal testing.
Closing this :)
