### ISSUE TITLE
ASUS Chromebox No audio passthrough at all

### ISSUE THREAD

**Issue by bimmer1189** [plexinc/plex-media-player#741]
### Test environment
**PMS Version:** Server 1.13.1.5063
**Platform (Windows/OSX/Embedded):** PMP Embedded (ASUS Chromebox M004U)

### Steps to reproduce
1. No steps needed to reproduce

### Current behavior

1. At first was getting no audio and had to select HDMI 0 under device but still even with all codecs selected I cannot get any passthrough to happen. It is all just PCM. It worked on OpenELEC PHT but not PMP now. PMP ASUS Chromebox M004U

### Expected behavior

1. My files with TrueHD and DTS-MA should passthrough to my receiver since I have them selected to passthrough.

**Comment by bimmer1189** [comment]
I will grab those later tonight when I can access in and submit them over. Thank you

**Comment by mseeley** [comment]
Please feel free to reopen with logs.
