### ISSUE TITLE
player: Fast forward and rewind keys are broken when video is paused and OSD has disappeared

### ISSUE THREAD

**Issue by uncleungie** [plexinc/plex-media-player#745]
### Test environment
**PMS Version:** 1.13.2.5102
**PMP Version:** 2.11.0.867-f27f8d2a
**Platform (Windows/OSX/Embedded):** macOS High Sierra 10.13.1 

### Steps to reproduce
1. Pause a video
2. Wait a few seconds for the onscreen player controls to disappear
3. Press the page up/page down or left/right arrow keys (or whatever keys you have mapped to rewind/fast forward).

### Current behavior

1. The fast forward/rewind keys instead skip to the beginning of the video or take you to the next video

### Expected behavior

1. The keys should fast forward or rewind within the video as is their behavior at all other times during playback.

**Comment by mseeley** [comment]
Thanks for filing. We landed a fix for this in 2.15. Sorry about that!
