### ISSUE TITLE
Plex Media Player 2.11.0.867 fullscreen broken on Windows

### ISSUE THREAD

**Issue by nikki2150** [plexinc/plex-media-player#747]
## How to file an issue - REMOVE THIS SECTION
 - Add a prefix to the title scoping the issue, e.g. `gui: `, `player: ` ... 
 - use a title that is clear enough
 - If appropriate, add a topic label to group the issue with a larger effort and allow filtering by that topic.

### Test environment
**PMS Version:**
**PMP Version:**
**Platform (Windows/OSX/Embedded):**

### Steps to reproduce
1.

### Current behavior

1.

### Expected behavior

1.

**Comment by LongChair** [comment]
Please file the issue properly :)
