### ISSUE TITLE
PMP 2.11: Fullscreen mode freezes in Win7

### ISSUE THREAD

**Issue by nikki2150** [plexinc/plex-media-player#748]
### Test environment
PMS version 1.9.7.4460
PMP version 2.11.0.867-f27f8d2a
Platform: Windows 7 OS

### Steps to reproduce
1. launch PMP 2.11 in any mode.

### Current behavior

1. switching between desktop and fullscreen modes causes the plex screen to freeze completely. 
2. example: open plex in fullscreen mode, switch to desktop mode, attempt to go back to fullscreen mode and the plex screen freezes. [Plex Media Player Logs_2018-06-04.zip](https://github.com/plexinc/plex-media-player/files/2068461/Plex.Media.Player.Logs_2018-06-04.zip)

### Expected behavior

I think this occurred with a new update but don't know which one. I have tested PlexMediaPlayer-2.5.0.792 which doesn't have the problem. Thanks for your attention.

**Comment by mseeley** [comment]
Sorry you have this switching trouble @nikki2150. I don't believe we'll be circling back on Windows 7 to debug.
