### ISSUE TITLE
Make set volume persist

### ISSUE THREAD

**Issue by cpfaff** [plexinc/plex-media-player#75]
Recently added following lines to the mapping file to make my volume buttons on my remote work.

```
"KEY_VOLUMEUP" : "host:player:add volume 1",
"KEY_VOLUMEDOWN" : "host:player:add volume -1",
"KEY_MUTE" : "host:player:cycle mute",
```

Increasing and decreasing volume works however it is not persistent. By that I mean that for example if I adjust volume playing one video and after that play another one then I have to adjust the volume again. The same goes for language tracks. Switching these also lets plex home theater forget about the previous set volume.

**Comment by wm4** [comment]
This depends on the platform, and possibly some more things. And as long as this is not an official feature, this probably won't be done.

**Comment by wm4** [comment]
PS: you _could_ set the volume in mpv.conf, with something like ``volume=83``. Of course it still won't remember the volume (mpv.conf itself is never written automatically by anything).

**Comment by cpfaff** [comment]
I run the preview under a PI2. I will give the configuration file a try. However I consider setting the volume as something really basic. Is this something to come or is it not intended to provide an own volume control for the player.

**Comment by tru** [comment]
I think this is rather a bigger issue "Make volume controls available". We just have to figure out how to integrate it so that it makes sense. With PHT we had a lot of problems with people not understanding that the app had it's own mixer and started it muted etc. With PMP we tried to avoid this by not making another mixer in the app since most people use their receiver and / or TV to change volume.

What's the direct use-case for you with a built-in mixer in PMP?

**Comment by wm4** [comment]
(For the record: the PI2 does provide a system mixer, but mpv does not use it with default settings, because the mixer control has a non-default name.)

**Comment by cpfaff** [comment]
In my setup the PI2 is connected to a 24" monitor via HDMI. The monitor audio jack is connected to an amp which is firing my speakers. A USB infra red receiver is connected to the PI so I can control the media player. With PHT it was simple to set the right volume on the receiver once and then use the built in volume controls. The benefit from doing so is that I only had one remote to use. Now I would need two. One to control PMP and one for the amp just for setting the volume.

**Comment by cpfaff** [comment]
@wm4  You mean the alsamixer?

**Comment by wm4** [comment]
>@wm4 You mean the alsamixer?

Yes. It controls the GPU's builtin hardware mixer.

**Comment by LongChair** [comment]
@cpfaff : could you please tell me if this is still relevant or if we can close it ?

**Comment by LongChair** [comment]
@cpfaff : will close this due to the lack of feedback.
There are also other GHI which are volume related.
Feel free to reopen if needed.
