### ISSUE TITLE
No Episode Image if using other 'My Home' User accounts

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#750]
### Test environment
**PMS Version:**  1.13.2.5142
**PMP Version:** 2.11 and versions before it
**Platform (Windows/OSX/Embedded):**  Windows

### Steps to reproduce
1. in PMP, select another Home User (not the primary plex account)

### Current behavior

1. when you go to the preplay screen on a tv series, no episode image shows

### Expected behavior

1. the episode image should show no matter what user is currently logged into plex

Note: people have been reporting this on the forum for quite a while now.
https://forums.plex.tv/discussion/308038/bug-no-episode-image-for-home-accounts#latest
https://forums.plex.tv/discussion/324397/home-page-doesn-t-load-and-episode-art-and-details-display-oddly

here is a example, PMP is signed into "Kids" and no episode image is showing in the preplay screen

![image](https://user-images.githubusercontent.com/906806/41122423-a6933a06-6aef-11e8-8b8a-7118ee61be22.png)

Here is the same episode signed in via my Primary dan-the-man account

![image](https://user-images.githubusercontent.com/906806/41122526-e9c61de8-6aef-11e8-8dc2-40006e36d51b.png)
[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2081878/PlexMediaPlayer.log)

**Comment by mseeley** [comment]
I believe the latest PMS builds have resolved the dependency we were awaiting to solve this.
