### ISSUE TITLE
PMP 2.11 video quality upscaling blocky & pixelated

### ISSUE THREAD

**Issue by Sada-Mio** [plexinc/plex-media-player#751]
### Test environment
**PMS Version:** 1.10.1.4602
**PMP Version:** 2.11.1.870
**Platform (Windows/OSX/Embedded):** Win10 

### Steps to reproduce
- Play 720p video on 1080p screen, direct original play.

### Current behavior

- Video quality subpar. Looks pixelated or blocky or low res. Not crisp.
- Noticed 2.11.0.867 updated Qt to 5.9.5, is this the cause?

### Expected behavior

- Plex Media Player 2.10.0.849 was the last version the video looks smooth and crisp. Reverted back and video quality no longer subpar. 
- Kodi Plex plugin video quality without issue
- OpenPHT video quality without issue.

**Comment by Konack** [comment]
Can confirm this issue is found in PMP 2.25.0, I believe it has to do with mpv's config or how Plex handles it's interaction with mpv. Since the backend of PMP is mpv if you try playing the same file using the same config the mpv version will look better than the PMP version.

**Comment by OttoKerner** [comment]
Yes. 
You need to put PMP into the 'TV' mode first. Then it is under the user avatar - Settings - Main
