### ISSUE TITLE
qt 5.11 support

### ISSUE THREAD

**Issue by vguerci** [plexinc/plex-media-player#753]
### Test environment
**PMP Version: 2.11+**
**Platform (Windows/OSX/Embedded): Archlinux**
This is especially needed for linux systems where pmp and KDE for instance will share the same QT version, which is a pain with distribs following a rolling-release model such as Archlinux ([see AUR comments](https://aur.archlinux.org/packages/plex-media-player/))

### Steps to reproduce
build / install pmp with qt5.11

### Current behavior
pmp won't start with error #743

### Expected behavior
pmp should start

**Comment by erenfro** [comment]
Also for reference on Solus 3:
https://dev.solus-project.com/T6542

**Comment by mseeley** [comment]
Closing in favor of the linked issue #743.
