### ISSUE TITLE
player: Crash while accessing invalid memory

### ISSUE THREAD

**Issue by nkbolg** [plexinc/plex-media-player#756]
### Test environment
**PMS Version: 1.13.2.5154-1 (AUR package for Arch Linux)** / running on Arch Linux 4.17.2-1

**PMP Version: 2.12.1.871-6c71195e** / running on Windows 6.1.7601.24150

### Steps to reproduce
1. Switched to next track by pressing right arrow key

### Current behavior

1. PMP crashed

### Expected behavior

1. PMP shouldn't crash

[dump.zip](https://github.com/plexinc/plex-media-player/files/2112408/dump.zip)
[logs.zip](https://github.com/plexinc/plex-media-player/files/2112426/logs.zip)

**Comment by mseeley** [comment]
Hi @nkbolg, thanks for filing; I'm sorry you're hitting an issue. I'm closing out Windows 7 support issues.
