### ISSUE TITLE
Collections - List View - Poster is cropped into Fanart Dimensions

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#759]
### Test environment
**PMS Version:**   1.13.2.5154
**PMP Version:** 2.12
**Platform (Windows/OSX/Embedded):**  Windows 10 x64

### Steps to reproduce
1.  Go to Movies, Collections, Set view to List mode

### Current behavior

1.   The Collections Poster is displayed using fanart dimensions, looks messy

### Expected behavior

1. It would be cleaner to just show the original Portrait Poster instead of it been cropped to fit
the fanart dimensions

![image](https://user-images.githubusercontent.com/906806/41816320-41071844-77d6-11e8-992c-2533643bc7e2.png)

**Comment by mseeley** [comment]
I've created an internal issue to track this with the UI team.
