### ISSUE TITLE
Pressing play on preplay screen not working

### ISSUE THREAD

**Issue by cpfaff** [plexinc/plex-media-player#76]
Pressing the play button on my remote when the focus is on the navigation buttons on tv-shows `<`/`>`
is not starting the episode. It is only working when the focus is either on the play button or the more `...` button. (PI2)

**Comment by tru** [comment]
Hmm sounds like your play button is hooked up to select. What input are you using?

**Comment by cpfaff** [comment]
Well I think that is not exactly right. When "select" that you mention selects the element which is currently active. Then this would mean that It would get me to the next or previous episode when pressing play when the corresponding buttons are active but that is not happening. Nothing happens then. It would also mean the same for the "more" button. When this one is active pressing play (select) would offer me more options but that does not happen either. But in that case play works as expected and plays the content.

**Comment by cpfaff** [comment]
I checked my `LIRC.json` to see if I made a mistake on my mapping. However my remote play button is mapped to:

```
 "KEY_PLAY": "play_pause",
```

This is OK I would say.

**Comment by cpfaff** [comment]
I would try next to map it to `play` only as it was originally and see if this works then no matter which button is active in pre-play.

**Comment by plex-konvergo** [comment]
Max

**Comment by cpfaff** [comment]
What was that?

**Comment by cpfaff** [comment]
Well just tried with the mapping to "play" and does not work as well. So seems the play command is only catched when the focus either is on the play button or the more button but when somewhere else.

**Comment by tru** [comment]
@dogonwheels can you confirm this is a real bug and maybe claim it? :)

**Comment by atrus05** [comment]
@cpfaff And you are sure the Lirc.json is the correct file for your setup? Which remote are you using and on what system?

**Comment by cpfaff** [comment]
I have the file copied from the examples folder to the inputmaps folder. I can confirm that this is the right file and that the system is using it as the mappings in it work as well as because changes I do there take effect.

**Comment by cpfaff** [comment]
Oh and @atrus05 the system is a PI2 and the remote is an X10 (I think no longer sold, cannot find it somewhere atm).

**Comment by cpfaff** [comment]
Oh and I just removed the file now and restarted in original state just to see if it was my mapping. The default map also does not work for me.

**Comment by dogonwheels** [comment]
Raised elsewhere as https://github.com/plexinc/plex-web-client/issues/3699

**Comment by mseeley** [comment]
This is resolved.
