### ISSUE TITLE
gui: Plex Media Player does not go to Windowed mode only Full screen

### ISSUE THREAD

**Issue by jarlosc** [plexinc/plex-media-player#761]
### Test environment
**PMS Version:1.13.2.5154
**PMP Version:3.57.1
**Platform (Windows/OSX/Embedded):Windows 10 Enterprise

### Steps to reproduce
1. Start Application: "C:\Program Files\Plex\Plex Media Player\PlexMediaPlayer.exe"
2. Application start in Full Screen Mode and requests User credentials
3. Enter User Credentials, GUI is presented in Full screen mode
4. Use Upper left hand side icon with 2 arrows pointing away from each other to toggle between Full Screen and Windowed mode (not working)
5. Attempt to exit application, no options available via Menus or ESC
6. Forcing Application to close by using ALT-F4

### Current behavior

1. Application used to start in windowed mode on previous version, after upgrade application only works on full screen mode, occupying the entire desktop, making it impossible to use windows taskbar features and windows start menu options. NOTE: Currently running plex under Windows 10 with 3 monitors, Plex launches directly and works only on Screen 3 in full screen mode.

### Expected behavior

1. Application starts in windowed mode. Thereby occupying only a fraction of the desktop and allowing user to freely move windowed Plex GUI across any of the monitors supported by Windows 10 system. User has the option to toggle between Full Screen and Windowed Mode any time desired.

**Comment by carbonbaseunit** [comment]
Same problem here.  I cannot get into windowed mode, no matter what I do.

**Comment by mseeley** [comment]
@jarlosc, @carbonbaseunit are you all still running into this after 2.19 split apart the fullscreen and layout controls?

**Comment by mseeley** [comment]
We've verified that fullscreen and layout controls are functioning correctly on Windows. If you folks still run into an error please let us know and we'll test using your steps to reproduce. Thanks!
