### ISSUE TITLE
Investigate `systemname` conf setting

### ISSUE THREAD

**Issue by mseeley** [plexinc/plex-media-player#762]
### Test environment
**PMP Version:** Latest
**Platform (Windows/OSX/Embedded):** All

### Steps to reproduce
1. Change the `systemname` setting in `plexmediaplayer.conf`
1. Restart PMP
1. View cast targets in Plex Web

### Current behavior
It sounds like the value is not respected: https://forums.plex.tv/t/for-the-love-of-god-can-you-please-let-me-change-name-of-pmp/278708/3

### Expected behavior
1. We should display the configured `systemname` value

**Comment by mseeley** [comment]
The `systemname` conf setting was indeed only used by `OESystemComponent.cpp`. To set the devices host name.

Later the `RemoteComponent##ResourceInformation()`, which returns the Plex Companion player name, returns the host name. So, on a non OE platform the host name would be the machine name.

Forwarding the `systemname` as the Plex Companion player name is straightforward:
```
diff --git a/src/remote/RemoteComponent.cpp b/src/remote/RemoteComponent.cpp
index c376dfa6..ffe5ba98 100644
--- a/src/remote/RemoteComponent.cpp
+++ b/src/remote/RemoteComponent.cpp
@@ -85,6 +85,10 @@ QVariantMap RemoteComponent::ResourceInformation()
   resourceInfo["platform"] = QSysInfo::productType();
   resourceInfo["platformVersion"] = QSysInfo::productVersion();
 
+  // Include the `systemname` setting as the `title` member allowing users to change the Plex Companion player name of
+  // of PMP on all platforms.
+  resourceInfo["title"] = SettingsComponent::Get().value(SETTINGS_SECTION_SYSTEM, "systemname").toString();
+
   return resourceInfo;
 };
 
```

Although that change would result in all users seeing the default value of `systemname` instead of an objectively more descriptive host name.

I think we'll have to compare `systemname` to its default value. When the `systemname` is the default value we continue to return the host name, otherwise we return the `systemname`.

**Comment by elan** [comment]
That sounds right, thanks for checking!

If you haven't already, can you reply on the forum thread?
