### ISSUE TITLE
gui: No way to customize shortcut keys or seek time

### ISSUE THREAD

**Issue by edwinbadillo** [plexinc/plex-media-player#764]
PMP Version: 2.13.0.877-6e1ea2cb
Platform: Windows

Currently there is no way to customize the shortcut keys for existing features.
You can't set custom seek times for "seekBackward" and "seekForward" either.

I had to look into the minified code to change the same for myself.
Seeing as the shortcut keys are in an array and the seek times are hardcoded variables this can be added as part of the player settings. (at the very least be set to load from a config file)

**Comment by mseeley** [comment]
Thanks for your feedback. We'll take this into consideration.
