### ISSUE TITLE
GUI: Server cannot be hidden

### ISSUE THREAD

**Issue by HazCod** [plexinc/plex-media-player#765]
### Test environment
**PMS Version:** 1.13.3.5223
**PMP Version:** 2.13.0.877-6e1ea2cb
**Platform (Windows/OSX/Embedded):** macOS 10.13.5

### Steps to reproduce
0. Start PMP in TV mode
1. Remove all but one server from account
2. Move server below "..." so it is not displayed on the main screen supposedly
3. Go back to Movies/Series view

### Current behavior
Server cannot be hidden from main screen.
This does not follow the guideline of the new iOS/Android apps. (server-agnostic content)

### Expected behavior
1. Server should stay below "..." line and be hidden from main screen.

Note: What is the use of showing this if we only have 1 server?
Note: Removed servers have no effect on PMP configuration unless I log out and log in again.

**Comment by purposelycryptic** [comment]
To add to this, it would be great if, when only connected to a single server, the name of the server would not automatically be appended to every Library name when displayed.

As an example, I have three 'TV Show' Libraries, "Anime", "TV Shows" and "Test"; currently in PMP (Version 2.16.0.885), in the 'Shows' tab, they appear like this:

![base](https://i.imgur.com/f6uOWr7.jpg)

which not only makes for an unattractive appearance, and uses up an unnecessary amount of screen space (as demonstrated by text being partially cut off), but is also just completely pointless and redundant, especially when the client and server are running on the same machine. 

When PMP is only connected to a single server, not labeling every Library with the server name would make for a much cleaner and attractive interface - see the mock-up below for comparison:

![mockup](https://i.imgur.com/VfPMjkA.jpg)

PMP traded the complex customization of PHT in favor of a single sleek, simple UI, and this would really help in continuing toward that goal - unnecessary repetitive server labels only serve to scare and confuse my less technically-inclined family members.

Thank you for your consideration.

**Comment by mseeley** [comment]
@Moussa I remember an issue moving a single library below the ellipsis. Does this sound like something you've addressed ~recently?

> When PMP is only connected to a single server, not labeling every Library with the server name would make for a much cleaner and attractive interface - see the mock-up below for comparison:

We'll consider this. Thanks :)

**Comment by Moussa** [comment]
@mseeley yea this sounds like a bug that was fixed in the last PMP release.

**Comment by mseeley** [comment]
Thanks for confirming. The three dots need to stay for a variety of reasons. 

Let's handle fatal checking for updates in a separate GHI.
