### ISSUE TITLE
Cast list shown in alphabetical order - iOS

### ISSUE THREAD

**Issue by Elliotblah** [plexinc/plex-media-player#768]
### Test environment
**PMS Version: 1.13.4.5271-200287a06**
**PMP Version: 5.1**
**Platform (Windows/OSX/Embedded): iOS**

### Steps to reproduce
1. Open any newly added movie.

### Current behavior

1. Cast list is shown in alphebetical order (the first three cast members are shown) for new movies. On Plex media server cast list is still shown in the correct order. If metadata is refreshed old movies will also display cast list in wrong order in the player.

### Expected behavior

1. Cast list should be shown in the correct order.
[PlexDebugInfo-epbesser-5.1-14317 (2018-07-26 19.56.35 +0700).zip](https://github.com/plexinc/plex-media-player/files/2232012/PlexDebugInfo-epbesser-5.1-14317.2018-07-26.19.56.35.%2B0700.zip)

**Comment by OttoKerner** [comment]
The Plex iOS app has nothing to do with Plex Media Palyer.

**Comment by mseeley** [comment]
I've filed an issue with our iOS team. Thanks for the heads up.
