### ISSUE TITLE
PMP Settings not available in 2.15.0.882 for Windows PC

### ISSUE THREAD

**Issue by nkellogg07** [plexinc/plex-media-player#769]
Upgrade PMP to 2.15.0.882 and the PMP Settings disapeared.  IE: you can no longer select the audio output device.  The only settings available now are for Web & Server.

Completely uninstalled and re-installed including removing the @appdata\local\Plex Media Server directory.  Same result.

No way to back rev to verify as the previous version is longer available for download on the website.

![image](https://user-images.githubusercontent.com/37935605/43377785-9665349e-9377-11e8-8211-76f5fbf273be.png)

**Comment by OttoKerner** [comment]
You have to put PMP into its full screen mode.
Go to the main page
then click on
![pmp_fullscreen](https://user-images.githubusercontent.com/10280992/43417770-36388cc2-943c-11e8-9158-ebb37a04eedc.png)

**Comment by nkellogg07** [comment]
It should be available in windowed mode. Doesn't work out to well wen you
have multiple monitors and want to change settings on the fly.

Thanks,

Nic
k

**Comment by mseeley** [comment]
Totally agreed. The split settings is mysterious and surprising. Thanks for filing.
