### ISSUE TITLE
gui: Clicking "on deck"-item does not jump to correct item in season for large seasons

### ISSUE THREAD

**Issue by martenjacobs** [plexinc/plex-media-player#770]
### Test environment
**PMS Version:** 1.13.0.5023
**PMP Version:** 2.15.0.882-8b488458
**Platform:** macOS

### Steps to reproduce
1. Make sure you have a TV show On Deck with an episode number that's higher than 50
2. Click it or select it and press the enter key

### Current behavior

1. The app jumps to the correct season
2. The first episode of the season is selected

### Expected behavior

1. The app jumps to the correct season
2. The episode that was shown in the 'On Deck'-section is selected

I expect this has something to do with the fact that PMP seems to load metadata for only the first 50 items of a series at first, only loading the next chunk when they've come into view.

**Comment by mseeley** [comment]
Hi @martenjacobs I've create an issue with our UI team to investigate. Thank you for your report!
