### ISSUE TITLE
gui: can't navigate to Settings

### ISSUE THREAD

**Issue by mhitchens** [plexinc/plex-media-player#771]
### Test environment
**PMS Version:** 1.13.5.5291
**PMP Version:** 2.16.0.dev-ddf690d3 build date: 2018-08-07
**Platform (Windows/OSX/Embedded):** Embedded

### Steps to reproduce
1. Navigate to the home screen.
2. Move the cursor over to the top right until the username menu is highlighted.
3. Select the username menu to display the dropdown menu, containing Settings, Media Server Status, Sign Out and Exit.
4. Attempt to move the cursor down.

### Current behavior

1. The cursor does not move to select the submenu items.

### Expected behavior

1. The cursor should move down to highlight Settings.

**Comment by mhitchens** [comment]
I was able to reach the Settings screen by hooking up a mouse, but I still can't seem to reach it via keyboard or iOS remote control. Also, when mousing over the word "Settings" in the submenu there was no cursor highlighting.

**Comment by markus101** [comment]
This is fixed in the latest commit.

**Comment by mhitchens** [comment]
Yep, just rebuilt master and the issue is gone. Thanks for the quick turnaround.
