### ISSUE TITLE
gui: Manually checking for new software version ends with a blank screen

### ISSUE THREAD

**Issue by OttoKerner** [plexinc/plex-media-player#773]
Forum thread https://forums.plex.tv/t/plex-media-player-opens-as-a-finder-window/294858/11

### Test environment
**PMS Version:** 1.13.6.5312
**PMP Version:** 2.16.0.885-f2338b5e
**Platform (Windows/OSX/Embedded):** Windows 10

### Steps to reproduce
1. use the PMP full screen mode
2. go to Settings - Main - Check for Update

### Current behavior
Screen gets blank, only the background blur remains

### Expected behavior
The usual dialog should come up where it either says 'Checking for Update' etc.

**Comment by dan-the-man-nz** [comment]
i can confirm same issue
[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2280550/PlexMediaPlayer.log)
![2018-08-12_09-07-47](https://user-images.githubusercontent.com/906806/43996079-4761d1fc-9e0f-11e8-9db6-f0094bcba5ba.gif)

**Comment by HazCod** [comment]
@mseeley seems like I'm late to the party

**Comment by pcalves** [comment]
Yeah, this is indeed related to the new settings UI. Each settings item can belong to one of several input types (options, checkbox, button and so on). This is how use used to handle buttons [in the v1 world](https://github.com/plexinc/plex-web-client/blob/18f2ab01f78cb798ffda4339eac2439dd914bb09/app/tv-old/common/js/views/components/system/SettingsGroupView.js#L130-L132):

```js
} else if (type === inputTypes.BUTTON) {
  dispatcher.trigger('settingsClick:' + key);
}
```

For v2, we made the assumption that these input types will always open up a v2 modal: https://github.com/plexinc/plex-web-client/blob/master/app/tv/common/js/views/v3/components/settings/lists/AppSettingsButtonCell.js#L18-L26

This is _mostly_ true, except for this one case, for which we have `KonvergoUpdater` listening for a `settingsClick:manualUpdateCheck` event. We could simply add an exception to the logic in `AppSettingsButtonCell` to let it trigger an event when the setting key doesn't match an existing modal.
