### ISSUE TITLE
player: Playback Error - vobsub not found

### ISSUE THREAD

**Issue by vtron21** [plexinc/plex-media-player#774]
### Test environment
PMS Version: 1.13.5.5291
PMP Version: 2.16.
Platform: PMP Windows 10 Desktop App, PMS Windows Server 2016

### Steps to reproduce
1. Adjust local, or remote, settings to anything less than Original (Make sure you will be transcoding)
2. Choose any MKV file with embedded subtitles and set sub titles
3. Play video with transcoding

### Current behavior
1. Video begins to play
2. Error appears over entire screen Playback eror <Video Title> Cannot convert this item. Implementation for subtitle encoder 'vobsub' not found

### Expected behavior
1. Video will play with chosen subtitles.

Issue was mentioned in this thread on the forums
[https://forums.plex.tv/t/implementation-for-subtitle-encoder-vobsub-not-found/281992](https://forums.plex.tv/t/implementation-for-subtitle-encoder-vobsub-not-found/281992 
)

The following is logged when an attempt to play a transcoded video with subtitles:
Aug 13, 2018 20:47:11.830 [3460] DEBUG - MDE: <Video Title>: selected media 0 / 25028
Aug 13, 2018 20:47:11.830 [3460] ERROR - Streaming Resource: Cannot make a decision because either the file is unplayable or the client provided bad data
Aug 13, 2018 20:47:11.830 [3460] DEBUG - Streaming Resource: Reached Decision id=25351 codes=(General=2000,Neither direct play nor conversion is available. Direct Play=3000,App cannot direct play this item. Direct play is disabled. Transcode=4007,Cannot convert this item. Implementation for subtitle encoder 'vobsub' not found.) media=(id=25028 part=(id=29668 decision=none container=mkv protocol=http streams=(Video=(id=23773 decision=copy width=1920 height=1080) Audio=(id=23774 decision=copy channels=6 rate=48000) Subtitle=(id=23775 decision=transcode bitrate=2147483647 encoder= languageCode=eng location=embedded))))

In my own testing I've tried using an older version of pmp, 2.7, as well as tried with 2.15 and 2.16.  I've not been able to roll back my pms.  I do have a friend that uses pms on a synology and when attempting to watch an mkv with subs from his server I get the same error.  As mentioned in the linked forum thread, playing the same files using plex for android, plex web play, plex windows store app do not have the same issue.

**Comment by pressRtowin** [comment]
This only happens with PGS subs for me. I don't recall other types of embedded subs causing the issue. Also, the video doesn't always even start playing. I get the error immediately. Happens in both fullscreen UI and web UI in PMP. As you stated, it only happens when transcoding. Video will play fine with the PGS subs when Driect Playing. Also worth mentioning that this issue (as far as I've tested) is EXCLUSIVE to PMP, on both windows and mac. The web client, android client, chromecast, and Win10 app work as expected when transcoding.

**Comment by vtron21** [comment]
Your welcome.

If you have a build that needs testing I'm available

**Comment by mseeley** [comment]
Tracked it down to an issue in the information provided to PMS. Our next version of PMS will include an update.

If you're feeling adventurous you can edit the `Konvergo.xml` if you'd like (notice `subtitleCodec`). The XML system profiles are kept within the PMS directory on Windows and within the `.app` file on macOS. Tread lightly and keep any edits light, this file will be replaced when PMS is upgraded.

```
diff --git a/Resources/Profiles/Konvergo.xml b/Resources/Profiles/Konvergo.xml
index ad53110a5..f5757e9ec 100644
--- a/Resources/Profiles/Konvergo.xml
+++ b/Resources/Profiles/Konvergo.xml
@@ -1,7 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <Client name="Konvergo">
   <TranscodeTargets>
-    <VideoProfile protocol="http" container="mkv" codec="h264" audioCodec="opus,vorbis,flac" subtitleCodec="ass,vobsub,*" context="streaming">
+    <VideoProfile protocol="http" container="mkv" codec="h264" audioCodec="opus,vorbis,flac" subtitleCodec="ass,pgs,vobsub,*" context="streaming">
       <Setting name="CopyMatroskaAttachments" value="true" />
     </VideoProfile>
     <MusicProfile container="mkv" codec="opus" />

```

After applying give PMS a restart for good-measure.

You can confirm the fix is working by disabling Direct Play. In the Desktop layout of PMP that's in Settings > Show Advanced > Debug. Afterwards be sure to re-enable Direct Play. :)

**Comment by jamescostian** [comment]
The patch you provided says `codec="h264"` - does that also affect .mkv files with H.265 encoded video streams?

**Comment by vtron21** [comment]
I'm Adventurous.  Made the change, rebooted the server and tried to play a video I was having issues with and it worked without issue.  

That particular video is in VC1 not h264, so it probably will work for your mkv files using h265 as well.

**Comment by mseeley** [comment]
Hi @jamescostian. The UI sends an augmentation at run-time to essentially change the `codec` value to `codec="h264,*"`. So, it should also work for VC1 as @vtron21 noted and HEVC.

**Comment by pressRtowin** [comment]
didn't see any mention of this in the latest update notes that came out today.

**Comment by mseeley** [comment]
Correct, `Konvergo.xml` is part of PMS. This fix will arrive with PMS 1.3.7 and greater. Current PMS version is 1.3.6.

**Comment by sbaier1** [comment]
@mseeley I am still experiencing this error.

Using the latest version of PMS on Raspbian with Live TV. It contains the patch you described on the PMS but i cannot play any Live TV streams using PMP, neither with Direct Play / Direct Stream nor with any or both of them disabled. I always get the `vobsub` error. Should i raise a separate issue?

**Comment by mseeley** [comment]
Hi @sbaier1 can you be more specific wrt the PMS version and repo where you got it?

**Comment by sbaier1** [comment]
> Hi @sbaier1 can you be more specific wrt the PMS version and repo where you got it?

The apt repo is `https://downloads.plex.tv/repo/deb/ public main` and the version i was testing was `1.16.6.1592`.

I worked around the issue by setting subtitle mode to "manually selected". That way i don't get the error and it does not transcode anymore.
