### ISSUE TITLE
player: OSD does not hide when next queued item starts playing via Play button press

### ISSUE THREAD

**Issue by enchained** [plexinc/plex-media-player#776]
### Test environment
**PMS Version:** 1.12.2.4929
**PMP Version:** 2.17.0
**Platform (Windows/OSX/Embedded):** Windows 10 64bit

### Steps to reproduce
1. Start playing a tv show.
2. After one episode ends, **press Play button** on countdown.
3. Do not press anything else.

### Current behavior
OSD stays on until you press something, like pause or just arrows to navigate OSD (I waited for a minute before trying that). After that it'll disappear within the usual 3ish seconds.

### Expected behavior
OSD should not appear on next episode start when pressing a Play button on countdown (or at least it shouldn't stay on).
But preferably the behaviour should be Identical to pressing the Enter/OK button on countdown and to waiting for the end of the countdown - no OSD on next episode in those cases.

**Comment by mseeley** [comment]
Thanks @enchained for the clear repro steps.
