### ISSUE TITLE
player: Volume extremely low since 2.1.3 on Mac playing to stereo speakers

### ISSUE THREAD

**Issue by atrus05** [plexinc/plex-media-player#777]
### Test environment
**PMS Version:** 1.13.5.5245
**PMP Version:** 2.1.3.724-d4bcc1ff and all versions after. However, builds made after with the _old interface_ still have normal volume.
**Platform (Windows/OSX/Embedded):** Mac Mini 2012 (quad i7). Mac OS X 10.13.4. Can't remember if I ever tested this in 10.12.X

### Steps to reproduce
1. Hook Mac straight up to a TV with an HDMI cable.
2. Download build 722, and build 724.
3. Start a video in 722, and a video in 724 and listen.

### Current behavior

1. Volume level in 722 and earlier is normal volume. Volume level in 724 and after is very very low.

### Expected behavior

1. Volume level should be comparable between those two versions.

**Comment by mseeley** [comment]
1000 thank you's for bisecting this for us @atrus05!

**Comment by atrus05** [comment]
No problem good Sir. I will close this out since the release notes for 2.1.3 hid the culprit. Since 2.1.3 it now respects the internal PMP volume level that is set by the + sign. A function I have never used knowingly. I hit the + sign a couple of times, and lo and behold... the volume was back to normal :)

Closing.
