### ISSUE TITLE
IR Remote not working well

### ISSUE THREAD

**Issue by JonathanFowlke** [plexinc/plex-media-player#78]
Running on Windows 7 x64 using an IR remote, may remote commands do not work, like: play, pause, stop, fast forward, rewind, exit, etc...

**Comment by LongChair** [comment]
We need to know a bit more a bout your setup ... which remote ? which IR receiver ?

**Comment by JonathanFowlke** [comment]
I'm using a universal logitech harmony remote with a inteset internal IR receiver.  It works just fine out of the box with Plex Home Theater.

**Comment by tru** [comment]
Does the log say anything when you press the buttons?

**Comment by nitrobass24** [comment]
I have this same problem too. Using the MCE remote.

**Comment by tru** [comment]
probably missing key maps. Watch the log when you press a button and it will show you what it receives.

**Comment by ghenry22** [comment]
I also just posted in the forums about this.  The standard windows Media Remote, works fine with PHT.  Most of the buttons do nothing in PMP.

back button does nothing
info button does nothing
stop button does not stop the playing video, does nothing

Basically aside from the directional d-pad and enter nothing works.

As this all worked in PHT it would be good if you could bring over a sensible mapping to PMP.  I can't use it on my media center until then as it's completely non functional when trying to use it solely with the remote.

**Comment by tru** [comment]
Help us develop that key map then. Press a button and check the log. What does it say?

**Comment by ghenry22** [comment]
Someone else has already done the hard work by the look of it, see issue #40 and potentially close one of these as a duplicate.

**Comment by LongChair** [comment]
should be fixed now.
