### ISSUE TITLE
Translation Error on Plex Web 3.69.1

### ISSUE THREAD

**Issue by TheMrJuco** [plexinc/plex-media-player#780]
Since the 3.69.1, the "Mark as played" string has been in english even if i'm in French.
If i use the 3.57.1 version (by accessing my PMP locally) the "Mark as played" string is correctly translated.
I think you know there's an issue because i found this line in the 3.69.1 post : 
"Fixed inconsistency with Mark as Played string naming"
But unfortunately this doesn't seems to work ?

**Comment by mseeley** [comment]
Hi @TheMrJuco, an upcoming release will contain these translations: `Marquer comme lu` and `Marquer comme non lu`. Thanks for the heads up. :)
