### ISSUE TITLE
player: Add option to disable controller input

### ISSUE THREAD

**Issue by rcdailey** [plexinc/plex-media-player#781]
### Test environment
**PMS Version:** N/A
**PMP Version:** 3.69.0
**Platform (Windows/OSX/Embedded):** Windows

Please add a simple option in player settings to disable controller input (PS4 Dual Shock, XBox, etc). When I have plex open behind a game, my controller input interferes with Plex Media Player. I only run PMP on my computer, and I prefer to only control it via mouse & keyboard. Controllers I plug in are only for games, not for media.

**Comment by OttoKerner** [comment]
https://forums.plex.tv/t/can-you-disable-xbox-360-controller-as-remote/160372

**Comment by rcdailey** [comment]
That's not a simple on/off option

**Comment by Gater** [comment]
Any news? Non of the reported "Workarounds" have fixed it for me.

**Comment by glass-ships** [comment]
+1 for any sort of solution to this issue, which has persisted for at least a couple years now.

**Comment by gilles007-** [comment]
it is a problem for me too

**Comment by insanemal** [comment]
This is a joke. Add a On/Off button.

**Comment by mseeley** [comment]
This has been addressed in Plex HTPC. We won't be making changes to Plex Media Player.

**Comment by glass-ships** [comment]
What about people who don't have a Home Theatre PC? 

People on a regular ass desktop? Do we just migrate to using Plex HTPC regardless? 

Please elaborate on your answer, as this has been an ongoing issue for **3 years**. 

We'd like a proper solution, or to at least fully understand the one you're suggesting.

**Comment by mseeley** [comment]
Plex HTPC can be used on a regular ass desktop for certain. It serves the same use case and users as Plex Media Player.

You can [read more about it here](https://forums.plex.tv/t/plex-htpc/703783). Linux support is unavailable but it's in the works.

**Comment by glass-ships** [comment]
Perfect, thanks! Minor confusion regarding Plex HTPC vs. PMP but this clears it up, I appreciate it!

**Comment by glass-ships** [comment]
Upon further investigation, I notice the Plex download page has two options: 

- Plex for Windows
- Plex Media Player for Windows Home Theater PCs. 

I'm confused as to whether `Plex HTPC = Plex Media Player for Windows Home Theater PCs`  since you said PMP will not be updated, and this option is: 
  A) Called Plex Media Player
  B) Older than the Plex for Windows option (by a year) 

Can someone perhaps shed light on this?

**Comment by mseeley** [comment]
Plex HTPC replaces Plex Media Player although we haven't made it easily discoverable/downloadable yet. That's in the works.

The download link on our website is still Plex Media Player. It will be replaced with a download link for Plex HTPC once HTPC graduates out of preview.

**Comment by insanemal** [comment]
How long will the delay for the linux version be?

**Comment by mseeley** [comment]
No estimate to share at this time.
