### ISSUE TITLE
GUI Translation: some fileds translated in Transifex are not taken into account anymore in v3.69+ of PMP

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#782]
### Test environment
**PMS Version:**  1.13.5.5332
**PMP Version:** 3.69.0 (Plex Media Player.app - Web ?) / 2.19.1.904-f679df4f (in TV Layout)
**Platform (Windows/OSX/Embedded):** OSX (10.13.6)

### Steps to reproduce 
Launch PMP and change the preferred user local for the GUI to something different than English (tests were done with r-the french translation)

### Current behavior

1. Some fileds for which the translation as been made in Transifex and for which translation was working as expected in previous version of PMP are no more displayed in user chosen locale. Problem was probably introduced after v3.57.1 of PMP

The issue as been verified and reproduced, at least, in the french translation of PMP.

Fields concerned by this issue:

- **_Mark as played_** / **_Mark as Unplayed:_**
![capture d ecran 2018-09-21 a 10 37 04](https://user-images.githubusercontent.com/2266264/45870112-6f956b80-bd8a-11e8-85cd-e074e5cdbe36.png)

- In Movies/TV Shows/Music/… if the sort Order is “Date Added” each film/tv show/music album… has underneath its title the date it was added to the library in english only (not translated). For example: **_10 hours ago_** or **_2 months ago_**
![capture d ecran 2018-09-21 a 10 26 46](https://user-images.githubusercontent.com/2266264/45870538-6c4eaf80-bd8b-11e8-8acc-d00a994130b8.png)

- when entering in the “TV Layout” version of PMP the string “**_Loading media types_**” is displayed in english in the “Menu bar”
![capture d ecran 2018-09-21 a 10 24 38](https://user-images.githubusercontent.com/2266264/45870599-8d170500-bd8b-11e8-8eca-2d877a2593be.png)

- always in the context of “TV Layout” in the menu Settings “**_Home Screen Media Types_**” is not translated and the sub-section of this menu also : “**_Show & Include_**”, “**_Hide & Don’t Include_**”

![capture d ecran 2018-09-21 a 10 24 57](https://user-images.githubusercontent.com/2266264/45870715-d5cebe00-bd8b-11e8-9b5e-5ed45185bc39.png)
![capture d ecran 2018-09-21 a 10 25 11](https://user-images.githubusercontent.com/2266264/45870716-d5cebe00-bd8b-11e8-8f0f-bd94071ff2bd.png)
![capture d ecran 2018-09-21 a 10 25 29](https://user-images.githubusercontent.com/2266264/45870718-d5cebe00-bd8b-11e8-82f2-2df36fc31be2.png)

### Expected behavior

1.Fields translated in Transiflex should be displayed in user's locale in  as in previous versions of PMP.

**Comment by mseeley** [comment]
Hi @Ribero thanks for opening this. Our translation updates are definitely behind at the moment. We've linked this to an internal issue that is working to resolve issues blocking translation updates.

**Comment by mseeley** [comment]
We're mostly good to go here:

```
"Mark as Played": "Marquer comme lu",
"Mark as Unplayed": "Marquer comme non lu",
"Home Screen Media Types": "Types de média de l'écran d'accueil",
"Show & Include": "Voir & Inclure",
```

I do still see `## days ago` and `# months ago` in English when viewing the app in French. I'll open up an internal issue to address this.

**Comment by Ribero** [comment]
Many thanks for the fix.

Can you please let the issue open until lates translation issues are solved ?

Tanks
