### ISSUE TITLE
player: weird black or white pixels appear in diagonal when playing 10-bit files, direct play online stream

### ISSUE THREAD

**Issue by NextFire** [plexinc/plex-media-player#791]
### Test environment
**PMS Version: 1.13.8.5395 (Raspbian, Raspberry Pi 3B)**
**PMP Version: 3.71.1**
**Platform (Windows/OSX/Embedded): Windows**

### Steps to reproduce
1. Play any 1080p 10-bit video of a distant server, in direct play

### Current behavior

1. Weird black or white pixels appear in diagonal
https://cdn.discordapp.com/attachments/229612779840077825/507138630737985536/unknown.png

### Expected behavior

1. No black or white pixels in diagonal

**Comment by mseeley** [comment]
Hi @NextFire 👋 . Couple questions:

- Just to confirm, you're using Plex Media Player on Windows to play from a remote Plex Media Server running on a Raspberry Pi 3B?
- You mention "any 1080p 10-bit video" but I'd like to confirm you really mean "every 1080p 10-bit video".
- Please include XML media information and, if possible, sample clips for some of the affected videos.

**Comment by mseeley** [comment]
Hi @NextFire please feel free re-open after you have a chance to include tighter reproduction steps. Thanks!
