### ISSUE TITLE
GUI: Artist bio not expandable

### ISSUE THREAD

**Issue by hawigit** [plexinc/plex-media-player#792]
### Test environment
**PMS Version:** 1.13.9.5439
**PMP Version:** 2.21.0.914-4839cbf2
**Platform (Windows/OSX/Embedded):** Windows 10

### Steps to reproduce
1. Open Plex Media Player, goto music, select an artist with bio information.

### Current behavior

1. You can't click on the bio with the mouse to expand it.
2. You can't navigate to the bio with the left/right/up/down keyboard keys.
3. You can't read the whole bio.

### Expected behavior

1. The opposite of what's written above. Same behaviour as the previous release. You can click on the bio, you can navigate to the bio, you can expand the bio.

**Comment by mseeley** [comment]
Thanks @hawigit this is a bug. We used to have the bio treated as a big button when it had more text than would fit in the spot. Although recently we moved away from that to display an extended info modal using an ℹ️ button to the left of the play button. It looks like this button made its way to the movie screens but not the artist screen.
