### ISSUE TITLE
Can't install on fedora 28

### ISSUE THREAD

**Issue by alsoGAMER** [plexinc/plex-media-player#793]
```
[alsogamer@alsoPC build]$ cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/usr/include/Qt -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
-- The CXX compiler identification is GNU 8.2.1
-- The C compiler identification is GNU 8.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:49 (set_policy)


-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Performing Test HAVE_FLAG_Wshorten_64_to_32
-- Performing Test HAVE_FLAG_Wshorten_64_to_32 - Failed
-- Performing Test HAVE_FLAG_fno_omit_frame_pointer
-- Performing Test HAVE_FLAG_fno_omit_frame_pointer - Success
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_/Oy_
-- Performing Test HAVE_FLAG_/Oy_ - Failed
-- Performing Test HAVE_FLAG_fvisibility_inlines_hidden
-- Performing Test HAVE_FLAG_fvisibility_inlines_hidden - Success
-- Performing Test HAVE_FLAG_/wd4244
-- Performing Test HAVE_FLAG_/wd4244 - Failed
-- Performing Test HAVE_FLAG_/wd4267
-- Performing Test HAVE_FLAG_/wd4267 - Failed
-- Performing Test HAVE_FLAG_flto
-- Performing Test HAVE_FLAG_flto - Success
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Success
-- Downloading https://artifacts.plex.tv/web-client-pmp/80-af3977f757f795/buildid.cmake to buildid-80-af3977f757f795.cmake...
-- set(TV-OLD_VERSION 3.13.3-5401c32)
-- Downloading https://artifacts.plex.tv/web-client-pmp/80-af3977f757f795/web-client-desktop-3.71.1-757f795.tar.xz.sha1 to web-client-desktop-3.71.1-757f795.tar.xz.sha1...
-- Clearing out old dependencies ...
-- Downloading web-client-desktop-3.71.1-757f795.tar.xz...
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- ...
-- [download 100% complete]
-- Checking checksum of file web-client-desktop-3.71.1-757f795.tar.xz
-- Unpacking web-client-desktop-3.71.1-757f795.tar.xz...
-- Downloading https://artifacts.plex.tv/web-client-pmp/80-af3977f757f795/web-client-tv-3.74.0-af3977f.tar.xz.sha1 to web-client-tv-3.74.0-af3977f.tar.xz.sha1...
-- Clearing out old dependencies ...
-- Downloading web-client-tv-3.74.0-af3977f.tar.xz...
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- ...
-- [download 100% complete]
-- Checking checksum of file web-client-tv-3.74.0-af3977f.tar.xz
-- Unpacking web-client-tv-3.74.0-af3977f.tar.xz...
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Not using bundled deps
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Qt root directory: /usr/include/Qt
CMake Error at CMakeModules/QtConfiguration.cmake:53 (find_package):
  By not providing "FindQt5WebChannel.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebChannel", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebChannel"
  (requested version 5.7.0) with any of the following names:

    Qt5WebChannelConfig.cmake
    qt5webchannel-config.cmake

  Add the installation prefix of "Qt5WebChannel" to CMAKE_PREFIX_PATH or set
  "Qt5WebChannel_DIR" to a directory containing one of the above files.  If
  "Qt5WebChannel" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:55 (include)


-- Configuring incomplete, errors occurred!
See also "/home/me/Desktop/pmp/plex-media-player/build/CMakeFiles/CMakeOutput.log".
See also "/home/me/Desktop/pmp/plex-media-player/build/CMakeFiles/CMakeError.log".
```

**Comment by comio** [comment]
Hi,

it seems that the precalculated sha1 checksum differs from the stored sha1 checksum. this is an issue on Plex side.

**Comment by jleroy** [comment]
This file is provided by the `qt5-qtwebchannel-devel` package.

**Comment by alsoGAMER** [comment]
i've installed it, but now show a new error

**Comment by alsoGAMER** [comment]
[alsogamer@alsoPC build]$ cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.9.5/5.9/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..
-- The CXX compiler identification is GNU 8.2.1
-- The C compiler identification is GNU 8.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Deprecation Warning at CMakeLists.txt:42 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:49 (set_policy)


-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Performing Test HAVE_FLAG_Wshorten_64_to_32
-- Performing Test HAVE_FLAG_Wshorten_64_to_32 - Failed
-- Performing Test HAVE_FLAG_fno_omit_frame_pointer
-- Performing Test HAVE_FLAG_fno_omit_frame_pointer - Success
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9
-- Performing Test HAVE_FLAG_mmacosx_version_min=10.9 - Failed
-- Performing Test HAVE_FLAG_/Oy_
-- Performing Test HAVE_FLAG_/Oy_ - Failed
-- Performing Test HAVE_FLAG_fvisibility_inlines_hidden
-- Performing Test HAVE_FLAG_fvisibility_inlines_hidden - Success
-- Performing Test HAVE_FLAG_/wd4244
-- Performing Test HAVE_FLAG_/wd4244 - Failed
-- Performing Test HAVE_FLAG_/wd4267
-- Performing Test HAVE_FLAG_/wd4267 - Failed
-- Performing Test HAVE_FLAG_flto
-- Performing Test HAVE_FLAG_flto - Success
-- Performing Test HAVE_FLAG_fuse_ld=gold
-- Performing Test HAVE_FLAG_fuse_ld=gold - Success
-- Downloading https://artifacts.plex.tv/web-client-pmp/85-88b3ac67015f76/buildid.cmake to buildid-85-88b3ac67015f76.cmake...
-- set(TV-OLD_VERSION 3.13.3-5401c32)
-- Downloading https://artifacts.plex.tv/web-client-pmp/85-88b3ac67015f76/web-client-desktop-3.77.2-7015f76.tar.xz.sha1 to web-client-desktop-3.77.2-7015f76.tar.xz.sha1...
-- Clearing out old dependencies ...
-- Downloading web-client-desktop-3.77.2-7015f76.tar.xz...
-- [download 0% complete]
. . .
-- [download 100% complete]
-- Checking checksum of file web-client-desktop-3.77.2-7015f76.tar.xz
-- Unpacking web-client-desktop-3.77.2-7015f76.tar.xz...
-- Downloading https://artifacts.plex.tv/web-client-pmp/85-88b3ac67015f76/web-client-tv-3.78.0-88b3ac6.tar.xz.sha1 to web-client-tv-3.78.0-88b3ac6.tar.xz.sha1...
-- Clearing out old dependencies ...
-- Downloading web-client-tv-3.78.0-88b3ac6.tar.xz...
-- [download 0% complete]
. . .
-- [download 100% complete]
-- Checking checksum of file web-client-tv-3.78.0-88b3ac6.tar.xz
-- Unpacking web-client-tv-3.78.0-88b3ac6.tar.xz...
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.4.2") 
-- Not using bundled deps
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/hash.txt to plexmediaplayer-qt-206-hash.txt...
-- Dependency hash is: 206d4d1
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt to konvergo-qt--release-206d4d1.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:59 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt:
  "HTTP response code said error"

    Trying 104.18.157.41...

  TCP_NODELAY set

  Connected to nightlies.plex.tv (104.18.157.41) port 443 (#0)

  ALPN, offering http/1.1

  ignoring certificate verify locations due to disabled peer verification

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [106 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [2484 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [300 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [37 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  [5 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  [5 bytes data]

  [5 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305

  ALPN, server accepted to use http/1.1

  Server certificate:

   subject: C=CH; ST=Nidwalden; L=Stans; O=Plex GmbH; CN=*.plex.tv
   start date: Feb 10 00:00:00 2017 GMT
   expire date: May 10 12:00:00 2020 GMT
   subjectAltName: host "nightlies.plex.tv" matched cert's "*.plex.tv"
   issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
   SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

  [5 bytes data]

  GET
  /directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt
  HTTP/1.1

  Host: nightlies.plex.tv

  User-Agent: curl/7.59.0

  Accept: */*

  

  [5 bytes data]

  The requested URL returned error: 404 Not Found

  stopped the pause stream!

  Closing connection 0

  [5 bytes data]

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

Call Stack (most recent call first):
  CMakeModules/FetchDependencies.cmake:144 (get_content_of_url)
  CMakeModules/QtConfiguration.cmake:9 (download_deps)
  CMakeLists.txt:55 (include)


-- Configuring incomplete, errors occurred!
See also "/home/me/Desktop/pmp/plex-media-player/build/CMakeFiles/CMakeOutput.log".
See also "/home/me/Desktop/pmp/plex-media-player/build/CMakeFiles/CMakeError.log".

**Comment by jleroy** [comment]
Have you downloaded the *latest* PMP release? 
FYI, I've made RPM packages for Fedora: https://forums.plex.tv/t/plex-media-player-rpm-packages-for-fedora-27/129620

Also please note that the Qt version shipped with Fedora 28 and 29 are not compatible with PMP because of a Qt bug.

**Comment by alsoGAMER** [comment]
Ok now is installed and working, thanks for your help.
I'll notify you if another issue came :D
