### ISSUE TITLE
player: control bar doesn't go away after resuming

### ISSUE THREAD

**Issue by anthonybilinski** [plexinc/plex-media-player#796]
### Test environment
**PMS Version:** 1.13.8.5395
**PMP Version:** 2.21.0.dev-4839cbf2
**Platform (Windows/OSX/Embedded):** Ubuntu 18.04
**Qt Version:** 5.9.5

### Steps to reproduce
1. Resume paused video playing on plex-media-player from app.

### Current behavior

1. Control bar at bottom of player resumes, but doesn't fade away. Stays present forever.

### Expected behavior

1. Control bar fades away after a couple seconds.

**Comment by mseeley** [comment]
@anthonybilinski are you using the TV or Desktop layout? When you resume paused video are you navigating with the mouse or using a keyboard shortcut?

We'll verify behavior on macOS and Windows. If the issue is limited to Linux we'll have to backlog this issue for a later fix.

**Comment by mseeley** [comment]
👍 thank you for your prompt feedback. Please feel free to reopen if the behavior regresses.
