### ISSUE TITLE
CEC support regression on Mojave

### ISSUE THREAD

**Issue by mseeley** [plexinc/plex-media-player#800]
Mojave broke Pulse-Eight CEC broke. It's since been fixed: https://github.com/Pulse-Eight/libcec/pull/434.

From: https://forums.plex.tv/t/pmp-cec-on-mojave/321060/4

We'll need to update our `libcec` dependency. User's can manually replace the libcec dylib although the replaced file will be overwritten on updates.

**Comment by opdenkamp** [comment]
linking this here since it applies to you guys too: see https://github.com/xbmc/xbmc/pull/15095#issuecomment-449369844
best wait for the next tagged version, or use the current master branch's HEAD

**Comment by mseeley** [comment]
HI @opdenkamp, right on, I appreciate you linking us up.

Let me see if/how our dependency configurations can pull from a tag instead of a branch. Linking to a 4.0.4 tag would be good by me. If you'd be more comfortable with us linking to a tag instead of the `release` branch please let me know. I'm not brave enough to link directly to `master`. ;) 

Take care and thank you!

**Comment by mseeley** [comment]
I've started the process of updating to https://github.com/Pulse-Eight/libcec/releases/tag/libcec-4.0.4 instead of `release`. Thanks for making that available @opdenkamp!

**Comment by mchlrv** [comment]
Any update when this will be release for Plex?

**Comment by mseeley** [comment]
Thanks for the bump @mchlrv I'll poke on this again.

**Comment by mchlrv** [comment]
Thanks @mseeley, any news on this? Still can't use my new Mac Mini as I could use my previous Mac Mini with Plex.

**Comment by basn** [comment]
I guess this is to hard for plex to fix?

**Comment by mchlrv** [comment]
@mseeley can you please give us an update on this? We - the first Plex users - would like to have this fixed as we're now stuck with an Mac running Plex but need multiple remotes to operate it. Feels a bit as if Plex lets their initial supporters down.

**Comment by mchlrv** [comment]
@tru are you able to give us an update on this long open standing issue?

**Comment by mseeley** [comment]
Hi @mchlrv, we've resolved this in the PMP v3 beta. No timeline yet for finalizing the v3 update.

**Comment by mchlrv** [comment]
@mseeley I tried PMP v3 beta and it is not working. I've send a PM to @tru about this.

**Comment by mchlrv** [comment]
Ok I found the solution in "~/Library/Application Support/Plex Media Player/plexmediaplayer.conf" at the "cec" set "hdmiport" to 1 instead of the default 0. This might be due to the fact that the new Mac Mini has an HDMI port of its own.

I'm happy that is finally working although it requires some small tweaking. If you want your Mac Mini to turn off when your TV goes into standby also set 'poweroffonstandby' to true.

**Comment by mseeley** [comment]
We're addressing this [in PMP v4](https://forums.plex.tv/t/plex-media-player-3-0-feedback/548889/131). Thanks @mchlrv for your investigation, sorry you had to go through it. 😓
