### ISSUE TITLE
player: Fling from a MacOS player to another MacOS player doesn’t work

### ISSUE THREAD

**Issue by miljank** [plexinc/plex-media-player#801]
### Test environment
**PMS Version:** 1.13.9.5456
**PMP Version:** 3.71.1
**Platform (Windows/OSX/Embedded):** OSX

### Steps to reproduce
1. Try to fling content.

### Current behavior

1. Fling button greyed out and can not be clicked.

### Expected behavior

1. Should be able to click on a button and get the list of players in the network to fling content on.

This doesn't work only from an OSX player to another OSX player. Flinging content from an iOS player to any of the two OSX players works just fine.

**Comment by mseeley** [comment]
Thanks @miljank we'll get this triaged. :)

**Comment by miljank** [comment]
The problem is still there with the latest PMP version - 3.77.2.

**Comment by DaveBinM** [comment]
@miljank Are you seeing the option greyed out, or do you just not see any selected players, or can you select a player, but it doesn't fling?

**Comment by miljank** [comment]
The option is completely greyed out. Even when i hover over it, the tooltip is not shown. For example, if I hover over Settings button, tooltip is shown (saying Settings).

Here is a screenshot: https://imgur.com/a/XmC21Df

**Comment by DaveBinM** [comment]
Hmmm, I'm unable to reproduce that. I see options for flinging to all my local players (although for some reason, flinging to another macOS player doesn't actually play).

<img width="373" alt="image" src="https://user-images.githubusercontent.com/19317607/49977155-54a55280-ff99-11e8-9db1-3d9e99a6e318.png">

**Comment by miljank** [comment]
I'd be happy to provide you with some additional debugging info if you tell me what would you need?

**Comment by DaveBinM** [comment]
@mseeley Anything in particular you can think of you might need?

@miljank PMP logs would be helpful. Close the app, reproduce the issue, then add the logs here 🙂

**Comment by miljank** [comment]
PMP log file: https://file.io/bvPr1z
PMP Helper log file: https://file.io/NNQDvq

**Comment by miljank** [comment]
Do you need any more information?

**Comment by mseeley** [comment]
Looking at the PMP log file I can see it's registered itself with plex.tv as a companion player.

```
2018-12-14 10:31:40 [ INFO  ] JS: %c[Companion] Registering player with plex.tv, clientID="a2h0v0ucybmx5s32yq77gb9p"
...
2018-12-14 10:31:41 [ INFO  ] JS: %c[Companion] Registered player with plex.tv, clientID="a2h0v0ucybmx5s32yq77gb9p"
...
2018-12-14 10:31:42 [ INFO  ] JS: %c[Companion] No companion found
```

I believe that last "No companion found" message is a red herring from some shared code.

I don't have two macOS systems available to test flinging from one to another. Although when attempting to fling from Chrome to PMP on the same system I run into problems. I'm able to see each "device" in the fling target drop down. After selecting PMP in the Chrome window a server error is recorded in Chrome and the app fails to connect.

Let's bring this issue into triage with the team and make sure that we're able to cast from web browser to a PMP player then work through PMP player to PMP player behavior.

**Comment by miljank** [comment]
I have some unused macOS systems laying around. Let me know if I can make those somehow useful to debug this.

**Comment by miljank** [comment]
I've managed to get a Windows PC to test PMP on it, and it is experiencing the same symptoms. It might be a problem with my network setup. Any ideas what could prevent this feature from working?

**Comment by robertschmid23** [comment]
I started having this problem after recent updates.  My server is version 1.15.3.858.  My players are version 3.83.2.  When I click on the Select Player button, no players appear.  My iPhone still works, thankfully or I wouldn't be able to control my main system from it.  

Everything is on the same local network.  The only other coincidence was a internet service upgrade that change my IP.  Could that have any impact?

**Comment by miljank** [comment]
@robertschmid23 That is a different issue. The issue I've opened was for the case when Select Player button is disabled and can not be clicked.

@DaveBinM @mseeley Any update on this issue? Is there a documentation that specifies requirements for this feature to work?

**Comment by duncanbeevers** [comment]
I dug around in here a bit today and consistently saw the cast button enabled when another player was present on the LAN.

I checked the code paths and the only way you can get a disabled Cast button in PMP is by having no companion server available.

@miljank 
I don't know what the underlying reason is for the companion server discovery being broken in this instance; it strikes me as something that might happen on a segmented LAN.

**Comment by miljank** [comment]
@duncanbeevers Thanks for checking this!

Network (mis)configuration is my guess as well at the moment. My hosts are on the same /24 subnet. The issue is there even when they connected the same dumb L2 switch. So, segmentation is not really a problem. But it's especially weird because iOS client, on a bridged WiFi network, works just fine.

How does PMP discover the companion server? Is it mDNS?

**Comment by miljank** [comment]
Ok, so if your definition of a private network matches the Wiki link you've pasted, we might have found a reason for the problem. My network is using a documentation/test subnet (192.0.2.0/24). [RFC5735](https://tools.ietf.org/html/rfc5735) says:

> This block is assigned as "TEST-NET-1" for use in documentation and example code.  It is often used in conjunction with domain names example.com or example.net in vendor and protocol documentation.  As described in [RFC5737], addresses within this block do not legitimately appear on the public Internet and can be used without any coordination with IANA or an Internet registry.

People usually use this block in home networks if they have problem with VPN route collisions. Any chance of adding this subnet to the list of private ipv4 subnets?

**Comment by duncanbeevers** [comment]
@miljank There's a bit of push-back from the server team on recognizing these subnets as local.

I've opened a PR to recognize these subnets; I'll capture some discussion there and if the team deems the behavior safe we'll roll it out.

Otherwise, you may have to use one of the sanctioned private subnets to use the Companion feature.

**Comment by miljank** [comment]
@duncanbeevers Thanks for checking. It's still quite weird because iOS client on the same subnet works just fine.

**Comment by duncanbeevers** [comment]
@miljank We had some discussion around this today, and we've decided to table recognizing these subnets as private.

> It's still quite weird because iOS client on the same subnet works just fine.

iOS is able to control companion players directly, while web needs to coordinate with a Plex Media Server on the same LAN to handle companion duties.

Thanks to today's discussion, we're looking into ways to support Plex Companion without requiring an intermediary Plex Media Server, so thanks for pushing on this, and working with me to figure out what was going on.
