### ISSUE TITLE
player: Playback controls not working with new version of Roku PMP app.

### ISSUE THREAD

**Issue by atoy3731** [plexinc/plex-media-player#805]
### Test environment
**PMS Version:** 1.14.0.5470
**PMP Version:** 6.1.1
**Platform (Windows/OSX/Embedded):** Ubuntu 16.04 Server

### Steps to reproduce
1. Attempt to pause playback of a movie by using: `curl http://<roku-ip>:8324/player/playback/pause`

### Current behavior

1. Movie playback no long pauses. Previous to the app update, it worked.

### Expected behavior

1. The movie should pause.

Not sure if anyone else is having this issue. The app updated on its own yesterday and broke my custom Alexa app.

**Comment by OttoKerner** [comment]
'Plex Media Player' is not an umnbrella term for all Plex Clients.
It is a separate software which only runs on PC hardware.
The Roku client is a totally different thing.

**Comment by mseeley** [comment]
Hi @atoy3731 I reached out and got some good news for you. Looks like the request's format changed slightly:

> It does work, but requires the `type` to be sent now. They can send `type=music|photo|video` or `type=all`. e.g. `curl http://<roku-ip>:8324/player/playback/pause?type={type}`
