### ISSUE TITLE
Playlists / Smart Playlists: Sync Playlists from iTunes is broken

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#809]
### Test environment
**PMS Version:** 1.14.0.5470
**PMP Version:** 3.77.2
**iTunes Version:** 12.6.5.3
**Platform (Windows/OSX/Embedded):** macOS 10.12.6

### Steps to reproduce

1. Delete all existing playlists in Plex
2. In Plex "Playlist" section select "Import from iTunes"
3. Select "overwrite existing playlists"
4. Wait for initial sync to finish 

### Current behavior

1. Sync starts and finishes without any visible error message
2. Only **9** playlists are imported (some static playlists and some smart playlists) out of **40** existing playlists in iTunes

### Expected behavior

1. All playlists (exactly **40** in my context, not 39 as stated in the log) including smart playlists (**36**) and static playlists (**4**) should have been imported

### Additional information

Extract of current existing playlist in iTunes:

![capture d ecran 2018-12-14 a 10 09 13](https://user-images.githubusercontent.com/2266264/49993997-911c8280-ff88-11e8-8d52-15a63d37dd7c.png)

Currently imported playlist in Plex:

<img width="1114" alt="capture d ecran 2018-12-14 a 10 11 38" src="https://user-images.githubusercontent.com/2266264/49994027-abeef700-ff88-11e8-93b7-250a74587b3c.png">

### Logs

- [Plex Media Server.log](https://github.com/plexinc/plex-media-player/files/2679388/Plex.Media.Server.log)
- [com.plexapp.system.log](https://github.com/plexinc/plex-media-player/files/2679389/com.plexapp.system.log)

**Comment by OttoKerner** [comment]
This is a server issue. 
It has nothing to do with Plex Media Player.

**Comment by Ribero** [comment]
Oups ! My bad. 
... And after having a quick look in GitHub, I'm not sure there is a repository dedicated to PMS where I can open this issuer (or I did not found it).

**Comment by OttoKerner** [comment]
All other repositories are private.
Please report any issues which have nothing to do with PMP in the Plex forums.

**Comment by cartayna** [comment]
I have the exact same problem, and my server is perfectly fine.
