### ISSUE TITLE
Update channels other than stable is hidden for PlexPass users.

### ISSUE THREAD

**Issue by tru** [plexinc/plex-media-player#81]
This works fine when you are in a employee role, why doesn't it with just the PlexPass role?

**Comment by pmwoodward3** [comment]
Do you have a link to the other channels? So I could download the 1.0.2 update for my RP2?

**Comment by tru** [comment]
Here is one method to get it going: https://forums.plex.tv/discussion/comment/1045743/#Comment_1045743

**Comment by tru** [comment]
@dogonwheels is this merged and fixed?

**Comment by dogonwheels** [comment]
Yes! Sorry - https://github.com/plexinc/plex-web-client/commit/bc099fa26ed9c9b72900ddb68afa21d7e3f5b69a

Will be fixed in the next web-client push.
