### ISSUE TITLE
PmP exits full screen when minimizing player

### ISSUE THREAD

**Issue by kicjow** [plexinc/plex-media-player#810]
### Test environment
**PMS Version:** 1.14.1.5487
**PMP Version:** 3.69.0
**Platform (Windows/OSX/Embedded):** MacOS Mojave

### Steps to reproduce
1. Put the PmP in full screen.
2. Open a video and play it in full screen.
3. Hit the minimize button to view the Plex server

### Current behavior

1. When hitting the minimize button it exits the PmP full screen as well as the player.

### Expected behavior

1. It should just minimize the player and not exit the PmP full screen.

Example: https://gyazo.com/1104e976a186d166c69b9f77317aed4f

**Comment by mseeley** [comment]
That's a curious case. Thanks for the report @kicjow.

PMP doesn't support playing the video in the bottom left corner. Regardless we shouldn't be exiting fullscreen, that doesn't seem right at all.  Demo:

![1104e976a186d166c69b9f77317aed4f](https://user-images.githubusercontent.com/30019/50321484-2a5e0400-0475-11e9-8895-dcb47111f8f5.gif)

**Comment by kicjow** [comment]
I know the bottom left is just a picture and not suppose to show the live video. I was just pointing out the bug of it exiting full screen.

**Comment by thriem** [comment]
Yes - also appears in other players (music, photos) as well.

**Comment by thriem** [comment]
In addition, PMP appears to be top-most again.

**Comment by kicjow** [comment]
@mseeley did you know if there has been any progress on this but I understand if this is on the bottom of the bug fixing pile.

**Comment by mseeley** [comment]
Hi @kicjow it did fall behind some other issues in line but it's on my list for next week. I'll do my best to sort it out. 👍

**Comment by kicjow** [comment]
@mseeley were you able to find the issue? Sorry for the bump.

**Comment by mseeley** [comment]
I haven't quite yet but I have found it's behavior shared with our app in Chrome. This is a good thing; points to application logic instead of a window handling implementation issue in PMP. I'm on it today.

**Comment by mseeley** [comment]
Okay fixed up. Thank you for your report.

Updates to the Desktop layout are released every few weeks by the team that builds the TV layout.

The Desktop layout with the fix will show a 3.89 or higher in the General settings where the arrow is pointing:

![image](https://user-images.githubusercontent.com/30019/52752970-e977fc80-2f98-11e9-8835-d2d54e5ff96f.png)
