### ISSUE TITLE
PMP: Remote control handler is buggy.

### ISSUE THREAD

**Issue by mseeley** [plexinc/plex-media-player#815]
The following was from an issue in a separate repo filed in Feb 2018. It hasn't been verified. The remaining take away may particularly be the desire to use the PMS companion proxy instead of the custom Konvergo one.

> I observed the following issues (while music was playing continuously), all calling: `/player/timeline/poll?wait=1&includeMetadata=1&commandID=X`:
>
> - Some requests didn't return for over 30 seconds, causing timeout in calling.
> - When timelines were returned, they lacked the metadata required by `includeMetadata=1`.
> - When sending `/player/playback/stop`, e.g. it would fail with "Ignored playback action due to missing type" in the log, even though the spec states `These playback commands take an optional “type” argument`.
> 
> The easiest way to fix this might honestly just be to use the web-based companion support instead of trying to provide a custom server. This will have the effect of requiring server proxy or pubsub...

**Comment by duncanbeevers** [comment]
@mseeley Let me know how you want to handle this (are we retiring the Konvergo proxy?) and if I should perform the cut-over to use the web companion proxy instead.

**Comment by mseeley** [comment]
There's a lot of desire to consolidate on the media server companion proxy but before we do that we should test behavior if we allow selection of a remote PMS when there isn't one on the local network. 

This way we don't remove companion capabilities from PMP for users streaming from a remote PMS, eg all those seedbox provider folks.
