### ISSUE TITLE
[feature request] Quit menu

### ISSUE THREAD

**Issue by ooii** [plexinc/plex-media-player#82]
Hi,

Could you add the quit menu, that allows to quit PMP, switch off the computer and/or enter it into standby mode?

Thanks.

**Comment by NedtheNerd** [comment]
Feature request should be posted in the forums.

Regards

**Comment by tru** [comment]
We are adding this soon. Thanks for the report, please keep github for technical issues.

**Comment by ooii** [comment]
Sorry for that.
