### ISSUE TITLE
Plugins still shows on all PMP installs

### ISSUE THREAD

**Issue by dan-the-man-nz** [plexinc/plex-media-player#822]
PMS Version: 1.14.1.5488
PMP Version: 2.24.0.933-e3a8e847 build date: 2018-12-19
Platform (Windows/OSX/Embedded): Windows 10

i just suprised to see achilles mention in slack this has been removed from PMP GUI.
it still shows for me, even tho there is no plugins inside.  (however in the past, there was,
but i deleted it from PMS 30+days ago once i heard they are been retired)

### Steps to reproduce
1.  Scroll down to the bottom of the discovery page in PMP

### Current behavior

1. Plugins shows under Online Content

### Expected behavior

1. Plugins should no longer show under Online Content apparently.

[PlexMediaPlayer.log](https://github.com/plexinc/plex-media-player/files/2701569/PlexMediaPlayer.log)

![2018-12-21_18-07-52](https://user-images.githubusercontent.com/906806/50325730-62d01180-054b-11e9-9e98-b0607447cefb.gif)

![image](https://user-images.githubusercontent.com/906806/50325756-87c48480-054b-11e9-868a-c65ea1664e75.png)

**Comment by markus101** [comment]
Plugins are still in the app at this time.
