### ISSUE TITLE
player: [DVR] Channels with “Unknown Airing” are not played

### ISSUE THREAD

**Issue by mpajer** [plexinc/plex-media-player#824]
### Test environment
**PMS Version:** 1.14.1.5488
**PMP Version:** 3.81.1
**Platform (Windows/OSX/Embedded):** Linux & Windows & probably all?

### Steps to reproduce
1. It is fully described [here](https://forums.plex.tv/t/bug-dvr-channels-with-unknown-airing-are-not-played/350286) on Plex Forums

### Current behavior

1. Error: 
`There was an unexpected error during playback. Please visit our forums if you continue to experience problems.`

### Expected behavior

1. Please fix it ASAP so we can watch our TV :(

**Comment by mseeley** [comment]
Please see https://forums.plex.tv/t/bug-dvr-channels-with-unknown-airing-are-not-played/350286/8?u=mattseeley
