### ISSUE TITLE
Studio custom filters not working as expected.

### ISSUE THREAD

**Issue by pummra** [plexinc/plex-media-player#828]
### Test environment

**PMS Version:** 1.14.1.5488
**PMP Version:** 3.81.1
**Platform:** PMS: UnRaid Docker PMP: Chrome

### Steps to reproduce
1. Go to movie library
2. Choose 'custom filter' from filter dropdown
3. Choose to filter by studio. 
4. Enter a filter based on 'contains'
5. Enter a filter based on 'is'

Example: 
https://media.giphy.com/media/42wasPac8K4Su7Ydrw/source.mp4

### Current behavior
1. When filtering by 'contains' and 'is' the results are not correct. Either no results are returned or incorrect results are returned. 

Example: 
https://media.giphy.com/media/42wasPac8K4Su7Ydrw/source.mp4

### Expected behavior
1. When filtering, for example, by studio that contains 'Disney' all movies with 'Disney' in the studio tag should be returned.

**Comment by OttoKerner** [comment]
This is probably an issue with the web app or the server itself.
So it doesn't belong in here. ('Plex Media Player' is **not** an umbrella term for all Plex clients)

I have copied the information to an internal repository.
Please leave the screen recordings up on Giphy.

**Comment by mseeley** [comment]
I think this is fine to keep here. It's a bug in the web app in PMP and in general.

Thanks a lot @pummra for filing. We'll get this looked at.

**Comment by chrishoage** [comment]
Dupe. Closing in favor of internal GHI https://github.com/plexinc/plex-web-client/issues/13255
