### ISSUE TITLE
[feature request] navigation in categories with letter

### ISSUE THREAD

**Issue by ooii** [plexinc/plex-media-player#83]
Hi,

Is it possible to put back the ability to jump from one section in the other, when the focus is on the navigation bar, using the first letter of that section (M for movies, T for TV Shows, etc)?
Thanks.

**Comment by NedtheNerd** [comment]
Feature request should go in the forum, not here.

**Comment by tru** [comment]
Ned is correct. Please file the feature requests in the forum and keep github for technical issues for now.

**Comment by ooii** [comment]
Sorry for that.
