### ISSUE TITLE
iOS - collection management

### ISSUE THREAD

**Issue by cmeyertons** [plexinc/plex-media-player#830]
This is a feature request to add capability to manage collections from iOS. 

I have my setup automated to the point that I can acquire new movies (with correct subtitles) all from my phone.

It would be great if when going through the app, we could add movies to collections as that is the one step at this point that requires going to desktop (iOS and Roku don’t support it)

**Comment by OttoKerner** [comment]
The iOS app has nothing to do with Plex Media Player.
Feature requests go here: https://forums.plex.tv/c/general/feature-suggestions
But search before adding a new one. Duplicates are closed.

**Comment by cmeyertons** [comment]
Thanks, sorry for inconvenience.  Closing.
