### ISSUE TITLE
Web client artifacts missing

### ISSUE THREAD

**Issue by Techjar** [plexinc/plex-media-player#833]
The web client artifacts are missing and I am unable to build Plex Media Player.

Getting a 404 for URL https://artifacts.plex.tv/web-client-pmp/98-0ff841fe41d5c5/buildid.cmake

**Comment by tru** [comment]
Public downloads where disabled Friday because of a config problem. We will fix it after the weekend.

**Comment by mseeley** [comment]
@tru thanks for commenting. Is this good to close?

**Comment by mseeley** [comment]
Actually, it's pretty clear that the URL is no longer 404'ing. 😅
