### ISSUE TITLE
Ubuntu 18.10 Build PMP Fails with dependencies url 404'ing

### ISSUE THREAD

**Issue by snugglej** [plexinc/plex-media-player#834]
I am building everything from the directions provided in the README for linux but when I got to build the final player I get 404 errors on the nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt

When this happens this means I can not continue to finish the build of the plex media player.

-----CMAKE ERROR -----
  GET  /directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt
  HTTP/1.1
  Host: nightlies.plex.tv
  User-Agent: curl/7.60.0
  Accept: */*
  [5 bytes data]
  The requested URL returned error: 404 Not Found
  stopped the pause stream!
  Closing connection 0
------------------------------------------------------

### Test environment

PMP Version: Trying to build from github pull.
Platform: Linux

### Steps to reproduce
1. Follow directions on github to build for linux
2. Finish all steps including running QT 5.9.5 installer from QT website
3. Try to use cmake (cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.9.5/5.9/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..)
4. Error

### Current behavior
1. Unable to finish building due to URL download error

### Expected behavior
1. Complete the build and not have URL errors when checking dependencies.

**Comment by gbooker** [comment]
There are no files at that site for any linux distro.  In the `QtConfiguration.cmake` file it has:
```
if(NOT IS_DIRECTORY ${QTROOT})
  download_deps(
		"plexmediaplayer-qt"
		DIRECTORY dir
		DEPHASH_VAR QT_DEPS_HASH
    BUILD_NUMBER 206
    ARTIFACTNAME konvergo-qt
    DYLIB_SCRIPT_PATH ${PROJECT_SOURCE_DIR}/scripts/fix-install-names.py
)
```
and it's inside the `download_deps` function that it hits that URL.  So, it only goes into there if the `QTROOT` is not a directory.  Check the argument you provided for `-DQTROOT` to ensure it is correct.

**Comment by gbooker** [comment]
This appears to be resolved, closing.
