### ISSUE TITLE
Top/Bottom UI Elements slide in when playing a video (and no mouse/keyboard activity)

### ISSUE THREAD

**Issue by Endda** [plexinc/plex-media-player#836]
### Test environment

PMS Version: 1.15.0.659
PMP Version: 3.83.1
Windows

### Steps to reproduce
1. Play any video
2. Put video in full screen
3. Watch video for 5-10 minutes

### Current behavior
1. The top/bottom UI elements slide in as if I had moved the mouse

### Expected behavior
1. The top/bottom UI elements are not supposed to slide in if I haven't moved the mouse

______________________________________

I have switched mice, and have even unplugged my wireless mouse receiver from the PC (as I had assumed it was the mouse that was causing the bug).

However, even with the computer having zero mice connected, the bug still happens. I'll be watching a video and then all of a sudden the top and bottom UI elements will slide in. Stay for a few seconds and then slide away.

**Comment by Endda** [comment]
Doing another test, I unplugged the keyboard just to make sure it wasn't causing the error.

Still get the same issue

**Comment by Endda** [comment]
I went ahead and uninstalled Plex Media Player and did a reinstall using a fresh download just as another troubleshooting step

Unplugged my keyboard for another test

The issue still persists.

I even noticed that the top/bottom UI elements will pop in for a second or two and then go away even when PMP isn't in full screen mode.

I have it as a regular (not even maximized) with the mouse outside of the PMP window. And those UI elements still pop in/out while something is playing

____________________________

FYI, this is in web mode of PMP. Will do some tests later today and see if it happens in the browser as well (but I'm doubtful as it seems isolated to PMP).

**Comment by Endda** [comment]
Even downgraded to an older version of PMP (before the bottom UI bar was changed) and it's still happening. I see the UI elements pop in and then go away about once every 1-5 minutes.

I haven't added anything to my computer. Like I said, I removed the keyboard and mouse for test purposes.

The only thing unique is, that I would consider, is that I have two GTX 1080 founder edition cards in SLI. But I've had this setup since those cards came out and never had this issue with PMP.

Videos play in direct play and I also just tested and am seeing it when watching a video in full-screen mode with the web browser (pointed directly to my server (http://192.168.86.150:32400/web/index.html)

**Comment by mseeley** [comment]
Hi @Endda. That's definitely some curious behavior. I downloaded the latest Windows Plex Media Player and been working on reproducing this. PMP is running on my desktop inside a Windows 10 virtual machine, no unusual top/bottom bar slide ins. Which version of Windows are you using?

I've asked some of our testers to also attempt to reproduce.

> Videos play in direct play and I also just tested and am seeing it when watching a video in full-screen mode with the web browser (pointed directly to my server (http://192.168.86.150:32400/web/index.html)

Do I understand correctly that you are able to reproduce the problem in a window of Plex Media Player _and_ in a full-screen web browser?

**Comment by Endda** [comment]
> Hi @Endda. That's definitely some curious behavior. I downloaded the latest Windows Plex Media Player and been working on reproducing this. PMP is running on my desktop inside a Windows 10 virtual machine, no unusual top/bottom bar slide ins. Which version of Windows are you using?
> 
> I've asked some of our testers to also attempt to reproduce.
> 
> > Videos play in direct play and I also just tested and am seeing it when watching a video in full-screen mode with the web browser (pointed directly to my server (http://192.168.86.150:32400/web/index.html)
> 
> Do I understand correctly that you are able to reproduce the problem in a window of Plex Media Player _and_ in a full-screen web browser?

Agreed, it is very unusual. As I mentioned, it's not just the latest version, I downloaded an older one (before bottom UI changes) and it happens there as well. And it happens in Chrome's Plex Web UI as well.

I got my girlfriend to do some testing but she doesn't have the issue.

Here are the version and hardware that I have on my machine

 - https://imgur.com/uWpdpxJ

And yes, I am able to reproduce the problem in a window of Plex Media Player _and_ in a full-screen web browser?

I'm running the latest Plex Media Server on an unRAID docker (linuxserver repo) if that has anything to do with it. I doubt it does, but I just want to give as much information as possible

**Comment by mseeley** [comment]
That is a beast of a rig. :)

The case that it happens in Chrome as well and doesn't happen for your GF and our testers really diminishes the possibility that we'll be able to reasonably address this.

PMP has a Chromium 56 web view within it. _Maybe_ there's an issue in Chrome/Chromium that is tickled by your setup. Does the same issue happen if you use our app in Edge or Firefox?

I'll leave this issue open until next week, maybe you'll strike pay dirt or, maybe one of our testers will see something similar. I'm not sure we're going to catch this 👻.

**Comment by Endda** [comment]
> That is a beast of a rig. :)
> 
> The case that it happens in Chrome as well and doesn't happen for your GF and our testers really diminishes the possibility that we'll be able to reasonably address this.
> 
> PMP has a Chromium 56 web view within it. _Maybe_ there's an issue in Chrome/Chromium that is tickled by your setup. Does the same issue happen if you use [our app](https://app.plex.tv/desktop) in Edge or Firefox?
> 
> I'll leave this issue open until next week, maybe you'll strike pay dirt or, maybe one of our testers will see something similar. I'm not sure we're going to catch this 👻.

lol, thank you for the compliment. it was my first custom water loop build (dual loops), so I went all out when putting it together.

It's late tonight, but I will try the plex.tv URL app in both Edge and Firefox tomorrow and reply to this open issue.

I guess I was just hoping there would be some kind of log file somewhere that could be pulled (from Plex or Windows) that would be able to single out the issue.

Will respond with additional test results tomorrow

**Comment by dan-the-man-nz** [comment]
i would also try killing every app possible running in the background / system tray / chrome extensions in windows, and retest.

**Comment by OttoKerner** [comment]
If there are any game controllers or joysticks connected, unplug them as well and re-test.

**Comment by Endda** [comment]
So using https://app.plex.tv/desktop in Chrome and Firefox, **but it didn't happen in Edge**. Watched a show for about 10 minutes straight and didn't see the UI elements pop in/out. It happened within a minute and then again in 3 minutes with both Chrome and Firefox

I don't have any Game Controllers connected to my computer

I will try killing apps/background processes and chrome + extensions with a PMP test. But I can't do that now as I'm using HD Sentinel to test an 8TB WD Easystore external drive before I shuck it for my unRAID NAS.

I will try that as soon as that test is completed though (or as soon as it shows if something is wrong with the disk)

**Comment by mseeley** [comment]
Hi @Endda, we can't reproduce this. If you find out the culprit please let us know!
