### ISSUE TITLE
Can't build 

### ISSUE THREAD

**Issue by D4rk4** [plexinc/plex-media-player#837]
### Test environment

**PMS Version:** GIT
**PMP Version:** GIT
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** RK3399 NanoPi M4

### Steps to reproduce
Can't build with:
 cmake -DCMAKE_INSTALL_PREFIX=/usr/  -DCMAKE_BUILD_TYPE=Debug ..

### Current behavior
```
  GET
  /directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt
  HTTP/1.1

  Host: nightlies.plex.tv

  User-Agent: curl/7.52.1

  Accept: */*



  [5 bytes data]

  The requested URL returned error: 404 Not Found
```

### Expected behavior
1.

**Comment by gbooker** [comment]
Duplicate #834
