### ISSUE TITLE
Screen locking when video is playing on manjaro with kde

### ISSUE THREAD

**Issue by marine1988** [plexinc/plex-media-player#838]
### Test environment

plex-media-player  2.28.0-1
manjaro 18 with kde 5.15

### Steps to reproduce
1. play some movie or tv show
### Current behavior
1. screen locks like nothing is playing

### Expected behavior
1.screen allways on

**Comment by mseeley** [comment]
Hi @marine1988 thanks for letting us know.

We don't directly support Linux desktop distributions. Without the requested logs there's very little we can do to help you.

If you have time/desire to file a more complete report we may be able to assist. Thanks.
