### ISSUE TITLE
PMP Bug: Playlists not showing for Guest account

### ISSUE THREAD

**Issue by clarenceb5** [plexinc/plex-media-player#84]
Windows 7 on Lenovo Laptop
PMP Build: 1.0.1.42

Current behavior: Playlists show for all users except the guest account.  I have other managed users and the playlists item is displayed.

Steps to reproduce:
1. enable the guest account in PMS
2. create a playlist for the guest account
3. open PMP and switch to the guest account
4. you should notice that Playlists is not in the library menu on the left

Logs are not included because when I try to drop the log file in this post I get an error saying "Unfortunately, we don't support that file type." So I try renaming the log file to a TXT file and drop it in and I get a new message saying "Attaching documents requires write permission to this repository".

![plexwebguest](https://cloud.githubusercontent.com/assets/5191732/10824062/217fde40-7e35-11e5-92f8-774e582cd6db.png)
![plexmediaplayerguest](https://cloud.githubusercontent.com/assets/5191732/10824066/25481f60-7e35-11e5-91fa-53b75e16edb1.png)

**Comment by dogonwheels** [comment]
We will only show the playlists button if there are playlists for that user in PMP. The web application shows this button/item in the sidebar, even if there are no playlists.

Playlists are per user as well - so I wouldn't expect other managed users to see each other's playlists. Let me know if that's not the case though.

**Comment by clarenceb5** [comment]
Item number 2. in my list of steps to reproduce says to create a playlist for the guest account, this implies I have a playlist for the guest account and it is still not displayed in PMP

**Comment by clarenceb5** [comment]
Including screen capture of guest account playlist
![plexmediaplayerguestplaylist](https://cloud.githubusercontent.com/assets/5191732/10824390/93a23b48-7e36-11e5-8405-debbaab947a8.png)

**Comment by clarenceb5** [comment]
Also I did say that I have other managed users who have playlists and when they are logged into PMP they can see their own playlists(not each others) just their own.

**Comment by dogonwheels** [comment]
Hehe. Sorry. Failed to read that correctly!

We'll look into this. Thanks for the report.

**Comment by clarenceb5** [comment]
why am I unable to attache the PMP log file here in GITHUB?

**Comment by dogonwheels** [comment]
Try and create a gist instead? https://gist.github.com/

**Comment by dogonwheels** [comment]
Oh, are these video playlists? PMP currently will only show audio playlists in the app.

**Comment by clarenceb5** [comment]
Oh right! Just like the app on the PS3 no love for the video playlist.  Will it be implemented in PMP?

**Comment by dogonwheels** [comment]
Yup. They'll get there for both platforms. As always, just a matter of juggling TODOs and priorities! Thanks, I'll close this one off then.
