### ISSUE TITLE
Plex App Companion Features not working as intended

### ISSUE THREAD

**Issue by docsnyder12345** [plexinc/plex-media-player#840]
### Test environment

**PMS Version: 1.15.1.710**
**PMP Version: 2.29.1.961-bb236059**
**Plex App Version: 7.12.0.9236 (3808a91c)**
**Platform: Windows 10 1803 Build 17134.619**

All Issues described here can be found in the Forum : https://forums.plex.tv/t/android-companion-almost-completely-broken-now/371854
I go more into Detail there as i would have to describe about 10 similar Issues here concerning Actions that follow the original Issue. For Example when the Playback is started regular and seems to work, i still cant change Playback Mode "on the fly" by selecting shuffle and expecting to see the Queue shuffled and behaving as such.
The very top Behaviour would of course be if one could go back from shuffled to regular Playback, meaning for TV-Shows that you start shuffled and when you de-shuffle at say S1E13 the Playback continues with S1E14, S1E15 and so on. I dont know if thats possible if you shuffle the Playlist itself and dont just keep an Order List on top of the selected Items like VLC Player where this Behaviour is noticable.
TL:DR: Those Issues are a Starting Point that i cant overcome, so i cant describe all additional Behaviour that falls in the "General" Category, such as skipping, nextElement, adding Items on the fly (like a Song from a different Artist via the Play as Next or add to Waiting Queue Actions), selecting another Item from the Queue, changing the Playlist Properties like Shuffle or Repeat and so on.

Attached are the Logs from PMP and PMS when i recreated the Issues described below.
[PMP_Logs.zip](https://github.com/plexinc/plex-media-player/files/2949335/PMP_Logs.zip)
[PMS_Logs.zip](https://github.com/plexinc/plex-media-player/files/2949336/PMS_Logs.zip)

Related Posts : 
https://github.com/plexinc/plex-media-player/issues/797
https://forums.plex.tv/t/plex-media-player-as-receiver-of-plex-companion-is-not-working-properly-anymore/302682
https://forums.plex.tv/t/android-companion-almost-completely-broken-now/371854

Let me know if you need more Details / Descriptions or other Test Cases etc. Im more than glad to help if that means i can use the App again.

**Issue 1 (TV-Shows)**
### Steps to reproduce
1. Start PMS, PMP (TV-Mode), Android App
2. Connect Android App to PMP Instance 
3. Select a TV-Show at Show Level and press the Shuffle Button in the App

### Current behavior
1. Random Season is chosen, played sequentially in itself (in the Log Files Family Guy was selected and Season 13 started playing and all Episodes in Season 13 in their regular Order)

### Expected behavior
1. Random Episode across all Seasons is chosen, played back and all following Items are in random Order

**Issue 2 (Music Playback)**
This Issue was once that random Playback would stop after the first random Element was completed, now its an View / GUI Issue, as the manual Selection doesnt update in the App, but in the Player.
### Steps to reproduce
1. Start PMS, PMP (TV-Mode), Android App
2. Connect Android App to PMP Instance 
3. Select an Artist (Music Collection) at Artist Level and press the Shuffle Button in the App

### Current behavior
1. Random Song is chosen and played back. Upon manual Selection from another Song from the Queue displayed in the App the Song starts playing in PMP but the previous (first) played back Song remains visible in the Android App

### Expected behavior
1. Manual Selection of an Item in the Queue updates not only PMP but the Android App too

**Issue 3 (Self defined Playlists)**
This Issue has changed from the Forum Post as that in previous Versions the Playback Queue was containing only the first Element. Not it contains all and looks correct but Playback still stops after the first Item.
### Steps to reproduce
1. Start PMS, PMP (TV-Mode), Android App
2. Connect Android App to PMP Instance 
3. Select a self defined Playlist press the Shuffle Button or the Playback Button in the App

### Current behavior
1. The Playback of the first Item (depending on shuffle or not) finishes and then the Playback stops and the Player returns to the previous View (Home or TV-Show or whatever was active before)

### Expected behavior
1. The Playback continues after the first Element

**Comment by mseeley** [comment]
@markus101 to triage.

**Comment by markus101** [comment]
I landed a fix for this today, it only affected casting to PMP running on Windows in production which made it much harder to pin down, it should be in the next release.

**Comment by docsnyder12345** [comment]
That sounds great!
Do the Side Effects described in 
https://forums.plex.tv/t/android-companion-almost-completely-broken-now/371854
correlate with your fixings so all of those are expected to be working again?
