### ISSUE TITLE
PMP accepts key inputs (from controller) while it's in the background -- it shouldn't

### ISSUE THREAD

**Issue by OnAnOpenField** [plexinc/plex-media-player#842]
### Test environment

**PMS Version:** 1.14.1.5488
**PMP Version:** 3.83.1
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows 10

### Steps to reproduce
1. Pressing the right trigger on a controller (which triggers PMP full screen mode), while PMP is in the background, triggers fullscreen mode. Pressing the right trigger will sometimes make PMP steal the foreground from other apps.

### Current behavior
1. PMP accepts the right trigger, as well as other controller buttons, as key strokes while it is in the background.

### Expected behavior
1. PMP should only accept key presses while it is in the foreground.

**Comment by mseeley** [comment]
Definitely annoying. We have an existing issue here tracking this behavior: #781.
