### ISSUE TITLE
Unauthenticated PMP in TV mode does not display libraries icon bar

### ISSUE THREAD

**Issue by bouscram** [plexinc/plex-media-player#843]
### Test environment

**PMS Version:** 1.15.1 (but was present before)
**PMP Version:** 2.29.1 but present since 2.19.1 where nothing was working under similar test conditions (issue #798)/ partly corrected in 2.24

**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS 10.13 and 10.14

### Steps to reproduce
Use PMS **unclaimed** and PMP **not authenticated**; start PMP in TV mode.
Same behaviour with both apps on the same machine or on the same LAN (with the proper authorisation)

### Current behavior
The top bar where the libraries icons are stays empty (except the "Home" icon), with a spinning wheel.
The rest of the interface is correctly displayed and works.

### Expected behavior
Libraries icons should show.

**Comment by mseeley** [comment]
@markus101 will you check this out briefly? Mostly to double check the behavior of the types in the header when there are troubles fetching remote types.

**Comment by markus101** [comment]
We made some changes in this area in the last few releases and I'm unable to reproduce in PMP 2.32 (though the fix likely came in 2.30 or 2.31).
