### ISSUE TITLE
PMP does not work unauthenticated in web mode when running on a different computer than PMS

### ISSUE THREAD

**Issue by bouscram** [plexinc/plex-media-player#844]
### Test environment

**PMS Version:** any
**PMP Version:** any I can remember
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS

### Steps to reproduce
1. Configure PMS to allow unauthenticated and unencrypted connections to your local LAN + local network discovery
2. Start PMP on another computer
3. Switch to web mode (if not already)

### Current behavior
PMP asks for authentication. If you switch to TV mode, PMP connects to PMS without problem (except issue #843).

### Expected behavior
PMP should find PMS and connect without authentication

**Comment by mseeley** [comment]
> Configure PMS to allow unauthenticated and unencrypted connections to your local LAN + local network discovery

Can you describe this a little bit? In particular I don't understand  "local network discovery".

Do you know how the TV layout is finding PMS running on a different machine on the local network? Have you configured the TV layout with manual connection information to the LAN PMS?

**Comment by bouscram** [comment]
Yes, I have configured the local server IP in the TV mode interface. 
Regarding the local network discovery, this is a setting  in the LAN config of the server, if I’m not mistaken. I always thought it was a discovery protocol used by clients on the same network to find the server.  Am I wrong?

**Comment by bouscram** [comment]
Nothing is changed in PMP 2.34. When using the Web UI, PMP can't find the server running on the same network (but not on the same machine, in which case it works).
When using the TV mode, if the server address has been entered manually, PMP can access it.

**Comment by mseeley** [comment]
Thanks @bouscram, this scenario isn't support in the Desktop layout.
