### ISSUE TITLE
Skip buttons often fail, sometime skipping forward instead of back

### ISSUE THREAD

**Issue by daltschu22** [plexinc/plex-media-player#847]
This bug has exhisted for years for me across numerous different makes of PC's and Android phones. 

### Current behavior
Often when im playing media, I will go to hit the "Skip back 10 seconds" button. This might work okay once or twice in a row but repeated attempts will often cause the media to skip forward, sometimes 30 seconds or even minutes ahead. Any attempts to hit the skip back button after that will continue to produce unexpected outcomes. This happens on a variety of different clients, including the phone client.

### Expected behavior
For the media to skip back 10 seconds on every button press.

### Steps to reproduce
Reproducibility is difficult as it seems to happen only occasionally. 
The fix ive found is to close the media, and reopen starting at the same timestamp. That generally gets the buttons working fine again.

Web Client: Version 3.93.1
Plex Media Server: Version 1.15.3.858 
Platform: Windows 10 - Chrome (Version 73.0.3683.86)

This also happens on the android app frequently, but I can open a separate issue for that if need be. 

XML of a piece of media that this happened on recently is attached. 

I will attempt to get logs of the issue happening, I dont have them currently as I did not have debug mode on. I will update this issue as soon as ive captured the issue.

[plex_xml.zip](https://github.com/plexinc/plex-media-player/files/3050895/plex_xml.zip)

**Comment by mseeley** [comment]
Thanks @daltschu22, this does sound troublesome. Without a clear repro we won't be able to fix this but we will keep our eyes open for it.

**Comment by daltschu22** [comment]
Hello, ive duplicated this error and logged in debug mode the issue.

I have attached the console output during the issue.

The skip back 10 seconds button was hit numerous times and many of those button presses resulted in the show skipping forward, often minutes ahead.

The episode in this case is titled `Watch Out`.


From what I can see, an example of the error is:
Jun 09, 2019 12:39:42.758 [0x7fc065ffb700] Error — [Transcoder] [mp4 @ 0x1377f40] Application provided duration: -16 / timestamp: 54917096 is out of range for mov/mp4 format


Please see attached file
[skipping_logs.txt](https://github.com/plexinc/plex-media-player/files/3269753/skipping_logs.txt)


Thanks!
