### ISSUE TITLE
subtitle options not available

### ISSUE THREAD

**Issue by dleghthikos** [plexinc/plex-media-player#848]
### Test environment

**PMS Version:** 1.15.3.876
**PMP Version:** 3.83.2
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows 10 64-bit

### Steps to reproduce
1.  movie is mpeg4 or x264, audio is ac3 mono or stereo unknown language, subtitle file for english language is .srt

### Current behavior
1.  Plex does not show subtitle options.

### Expected behavior
1.  Subtitle options should appear.

**Comment by mseeley** [comment]
Not enough information to approach triage. Please review the `Each filed issue must please:` section of the issue template displayed when creating a new issue.
