### ISSUE TITLE
High GPU usage when playing audio 

### ISSUE THREAD

**Issue by philbraun** [plexinc/plex-media-player#849]
Playing Music in Plex Media Player causes the GPU to spike, fans to start up, and battery to quickly drain, as long as the player is not maximised.
<img width="1668" alt="nothing-playing" src="https://user-images.githubusercontent.com/8843647/55683240-f2a09c80-593d-11e9-858a-5f6736e766a7.png">
<img width="1668" alt="plex-plays-audio" src="https://user-images.githubusercontent.com/8843647/55683241-f8967d80-593d-11e9-9424-b2afeaad2a55.png">
<img width="1667" alt="plex-plays-audio-maximised" src="https://user-images.githubusercontent.com/8843647/55683243-fc2a0480-593d-11e9-8a41-b3cb9995d609.png">
Looks like PMP is doing some wild behind-the-scenes calculations for the animated three little yellow dancing bars.

Macos 10.14.4, PMP 2.31.0.967, CPU and GPU usage by Activity Monitor -> Window -> GPU / CPU History (https://www.tekrevue.com/tip/view-gpu-usage-mac/)

**Comment by mseeley** [comment]
I'll see if I can get to the bottom of this.

**Comment by philbraun** [comment]
Just noticed this, maybe it's related: when the server is busy, PMP has a habit of using quite a bit of CPU,my guess is: for animating the little orange "busy" indicator.
Here's the Server doing a metadata resca - notice how PMP is using CPU cycles:
<img width="322" alt="Server busy - PMP visible" src="https://user-images.githubusercontent.com/8843647/57277615-cbf09580-70a4-11e9-8fad-afea67ac88a9.png">

Here's the server still busy with the same task, but PMP is minified to the dock:
<img width="319" alt="Server busy - PMP minified" src="https://user-images.githubusercontent.com/8843647/57277752-140fb800-70a5-11e9-95df-283b5f66fdb6.png">

**Comment by buphomet** [comment]
To me your report looks a lot like normal functioning from plex. 

> 
> " ...Playing Music in Plex Media Player causes the GPU to spike, fans to start up, and battery to quickly drain, as long as the player is not maximised...
> "

It is not clear what you mean by the when the player is not maximized as from your screenshots, the player is minimized in all the three cases.

Given Plex will draw icons and animate others when you start playing, it does make sense that the GPU and CPU usage spikes on use.

The same argument applied to the second scenario would mean that minimizing the application to the dock cuts on what is being drawn on the screen and hence reducing CPU and GPU use.

It is however not clear where this comes in 

> " ... Here's the Server doing a metadata rescan - notice how PMP is using CPU cycles
> 
> ...."

though.

**Comment by philbraun** [comment]
Sorry if "maximized" is not the technically correct term.
<img width="710" alt="Bildschirmfoto 2019-07-07 um 21 38 44" src="https://user-images.githubusercontent.com/8843647/60773093-6f3f4480-a100-11e9-8703-3411e2ef243d.png">
<img width="898" alt="Bildschirmfoto 2019-07-07 um 21 39 34" src="https://user-images.githubusercontent.com/8843647/60773096-749c8f00-a100-11e9-9a3e-80c73a0120a2.png">
Best to test yourself: play a song in PMP, look at CPU / GPU usage, click on the "up" arrow inside the small albub image at bottom left corner, see CPU and GPU usage drop significantly with nothing whatsoever changed besides the view in PMP.

**Comment by buphomet** [comment]
So, this is a server issue?

**Comment by philbraun** [comment]
Client, obviously.

**Comment by buphomet** [comment]
It honestly would not be surprising if a change in the view leads to a significant change in CPU and GPU usage.

This might be TMI, and this has not been tested by me but in games the radar/mini-map, which is usually a tiny part of the UI is known to be very CPU and even GPU intensive so, well, this might not be surprising.

At least not so surprising to me.

**Comment by mseeley** [comment]
The high GPU here is related to two things:

- The animated yellow equalizer displayed next to the playing track. It's a minor embellishment but it's constantly redrawing. That's the source for the major GPU usage delta between views.
- Position updates were sent from the host->client at 60Hz. This resulted in portion of the player controls re-rendering and sometimes trigging animations at the same frequency.

Our next release of Plex for Windows/Mac replaces the animated yellow equalizer with a static icon. The position update frequency was also decreased to 30Hz. There are no plans to introduce the changes back into Plex Media Player.
