### ISSUE TITLE
Cannot launch on Sway (Wayland based)

### ISSUE THREAD

**Issue by Jpfonseca** [plexinc/plex-media-player#852]
Cannot launch on Sway (Wayland based) on version `2.32.0.dev-62b2e27f` of pmp.

 Xwayland is enabled.

_Originally posted by @Jpfonseca in https://github.com/plexinc/plex-media-player/issues/802#issuecomment-483705112_ for the previous version.

**Comment by Jpfonseca** [comment]
`
[plexmediaplayer.log](https://github.com/plexinc/plex-media-player/files/3103297/plexmediaplayer.log)
[pmphelper.log](https://github.com/plexinc/plex-media-player/files/3103295/pmphelper.log)
[Uploading plexmediaplayer.log…]()
[pmphelper.log](https://github.com/plexinc/plex-media-player/files/3103298/pmphelper.log)

`

**Comment by Jpfonseca** [comment]
[plexmediaplayer.log](https://github.com/plexinc/plex-media-player/files/3103300/plexmediaplayer.log)
[pmphelper.log](https://github.com/plexinc/plex-media-player/files/3103301/pmphelper.log)

**Comment by mseeley** [comment]
Hi @Jpfonseca thanks for the issue. We don't offer build support for Linux platforms. Sorry we don't have an answer to your query.

**Comment by Jpfonseca** [comment]
@mseeley  i am not asking for build support. I can run the PMPlayer on i3 (xorg based). I was only trying to raise awareness to the fact that Graphical environments like KDE are already making a switch from Xorg to Wayland. They are building Xwayland apps which are normal xorg apps that are built on top of a wayland compositor.
More info on [xwayland](https://wayland.freedesktop.org/xserver.html)

**Comment by Jpfonseca** [comment]
@mseeley just to add that GNOME will start to avoid using X and migrate to Wayland.
