### ISSUE TITLE
Update Ubuntu Build Tutorial

### ISSUE THREAD

**Issue by Massaguana** [plexinc/plex-media-player#853]
Please Update the Tutorial tu build PMP on Ubuntu systems... 18.04 or 19.04. wood be nice

Thanks

**Comment by mseeley** [comment]
Hi @Massaguana we'll accept a PR to update the Linux build instructions. If anyone finds this issue in the future please feel free to submit.

**Comment by Mitzsch01** [comment]
Only some minimal adjustments need to be made and the build instructions are working again.
I´ve made a PR, where the changes are included.

**Comment by Massaguana** [comment]
What is meant by PR?

**Comment by Mitzsch01** [comment]
Pull Request ;)

**Comment by Massaguana** [comment]
I have test this new Readme.md

Works up to the step
`cmake -DCMAKE_BUILD_TYPE=Debug -DQTROOT=/opt/Qt5.9.5/5.9/gcc_64/ -DCMAKE_INSTALL_PREFIX=/usr/local/ ..`

No make file were created

**Comment by Mitzsch01** [comment]
You have to adjust the path to your Qt installation. ;) 
`-DQTROOT=/where your Qt installation lives/Qt/5.9/gcc_64/`
On my Ubuntu setup it is `-DQTROOT=/usr/home/Qt/5.9/gcc_64/`

**Comment by Massaguana** [comment]
Here not... how i can find the path with my Ubuntu?

**Comment by Mitzsch01** [comment]
It´s specified by the Qt installer. 
-> https://www.qt.io/download-thank-you?os=linux&hsLang=en

**Comment by Massaguana** [comment]
Okay, building PMP are done... but after startup and login/config and restart PMP stop working... I see just an loading picture... no responding...

**Comment by Mitzsch01** [comment]
Same here. But only the TV layout is affected. If you run `plexmediaplayer --desktop` everything works. 
So it´s not related to the building process.

**Comment by Massaguana** [comment]
yes, same here... desktop mode is working

**Comment by Mitzsch01** [comment]
It´s also not building v2.33.1. Only v2.33.0.

**Comment by Mitzsch01** [comment]
Well,.....
You can download the latest release (v2.33.1.979-c4087ea7, here in the "release" section), unzip it and build it with the given instructions... This will work. ;)
