### ISSUE TITLE
No Picture @TV... Wrong refreshrate

### ISSUE THREAD

**Issue by Massaguana** [plexinc/plex-media-player#854]
### Test environment

**PMS Version:** 1.14.1.5488
**PMP Version:**2.31.0.974
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Embedded Intel
**Hardware:** Asus ChromeBox CN60 "Panther" with UEFI Bios

I Use an TV connected with HDMI to an Denon AVR. The ChromeBox are also connected with HDMI to this AVR. Der AVR is the Focus in my Setup.

Issue, PMP Setup 1920x1080 @ 59,95 Hz, my TV need 50Hz

The AVR can handle 59,95Hz, but the TV not. I Think there is an mistake with the identification. PMP looks what the AVR can do, nit what the TV can do...
With Kodi, OpenPHT etc. it it possible to Change manual to 50Hz, with PMP it is not possible.

See #208 

Regards

Massaguana

**Comment by Mitzsch01** [comment]
This is more likely a Linux thing related to the Libreelec/Openelec version used by the embedded build. (it´s quite old) Nothing really to be solved in this repo.
But... You can get around this by using the latest LibreElec combined with the PlexForKodi Plugin. This should work... :)

**Comment by Massaguana** [comment]
With the last LibeELEC and Kodi they are the same issue... but with Kodi it is no problem to Change to 50Hz

**Comment by Mitzsch01** [comment]
Do you see a picture on your TV or is it just blank with LibreElec?

**Comment by Massaguana** [comment]
just black, i have to connect an Computer Display to see anything and Setup 50Hz... After That i put the Box back to my TV and "tadaaaa" there is an Picture

**Comment by Mitzsch01** [comment]
Ah okay. Well, then it works? Even after rebooting the chromebox?

**Comment by Massaguana** [comment]
Normally this only has to be done 1 time. An Reboot are no Problem, unless the detection is restarted...

**Comment by Mitzsch01** [comment]
Is this a suitable solution for you? Kodi + Plex Plugin?

detection is restarted? What do you mean by that?

**Comment by Massaguana** [comment]
I don´t like Kodi, the operation is odd, unlike Plex usual... example Press ESC don´t stop Playback.

I don´t know what sometimes happens exactly. After Restart or back from hibernate the system jumps back to 59,95 Hz... No picture. I need an Computer Display to fix that.

With OpenPHT embedded they are no problems with this, 1 time setup 50HZ and it works... but OpenPHT don´t work with UEFI and is not in development... I'd rather use OpenPHT... it has Skin Support.

**Comment by Mitzsch01** [comment]
Mh, Have you tried using Kodi together with the Plex Plugin? There you can set to launch the Plex Plugin after boot. No Kodi Ui anymore...

**Comment by mseeley** [comment]
I've added this to our backlog to review when investigating other AV integration issues.

**Comment by Massaguana** [comment]
I have test to use Ubuntu and PMP self build PMP... This Works fine...
