### ISSUE TITLE
How to open in Qt creator?

### ISSUE THREAD

**Issue by Mitzsch01** [plexinc/plex-media-player#856]
### Test environment

**PMS Version:** 1.15.5.994
**PMP Version:** v2.32.0
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** independent 

Is it possible to open this Repository or better the PMP Qt framework in Qt Creator? 
If yes, how? :D

**Comment by mseeley** [comment]
That's a good question @Mitzsch01. In my experience Qt Creator is rudimentary at best. I don't know anyone using it for development.
