### ISSUE TITLE
RPi - not visible debug overlay on 1080p 24p resolution

### ISSUE THREAD

**Issue by purger500** [plexinc/plex-media-player#86]
Device: RPi 2
 OS: Embeded RPi 2
 Build: 1.0.1.42-56cc6ef9

Current behavior: PMP does not open debug overlay on 1080 24p resolution. When "allow display mode switching" is uncheked, media plays on 1080p 60FPS and debug overlay works 

Steps to reproduce:
1. check "allow display mode switching"
2. play media in 1080 and 23,976FPS

On my NUC (PMP embeded generic) debug overlay works on 1080 24p

EDIT 31.10.2015.

Possible solution:
When I set RPi on 1080 24P resolution (in config.txt) debug overlay is visible. I will do more testing with this setting today.

**Comment by ac4lt** [comment]
I see this happen also. And for 30p as well as 24p.
