### ISSUE TITLE
TV Mode not loading [Ubuntu 18.04 ARM64]

### ISSUE THREAD

**Issue by GayDingo** [plexinc/plex-media-player#860]
### Test environment

**PMS Version: 1.15.4.994(macOS)**
**PMP Version: 2.33.0.dev-36e9306d**
**Platform: Ubuntu 18.04 _ARM64_ (Nintendo Switch)**

### Steps to reproduce
1. Select TV Mode

### Current behavior
1. Loads infinitely. Shows nothing. **Picture of issue down bellow.**

### Expected behavior
1. Actually load content. Everything else functions in non-tv mode.

![Screenshot from 2019-05-14 17-54-42](https://user-images.githubusercontent.com/50568332/57741442-aef22e80-7671-11e9-9318-5ff8a2036d9e.png)

**Comment by mseeley** [comment]
We [spotted your tweet](https://twitter.com/DingoTech/status/1128228220803829760) as well. Nice work!

Will you share some tight logs that just track startup until the DOA tv mode screen displays? I'm hoping there's evidence of a UI error we can poke. I don't know precisely where the logs are stored in Ubuntu but perhaps our [existing docs](https://support.plex.tv/articles/207338748-plex-media-player-logs/) are good hints.

**Comment by GayDingo** [comment]
Here are the logs!

[logs.zip](https://github.com/plexinc/plex-media-player/files/3186713/logs.zip)

There's a secondary issue, but I believe its because of Qt rather PMP. Touch input is detected as two inputs in succession, making it practically useless for anything other than scrolling. I know qt has a few issues with touchscreens, so I'll let that be for now.

**Comment by mseeley** [comment]
Thanks @GayDingo. Your logs show that the app is unable to save `plexmediaplayer.config` and `storage.json`. There's a reasonable chance that the failure is causing downstream troubles later attempting to load content from either file.

The touch support is definitely further out there. The scrolling in TV mode and Desktop mode are handled differently. As you noticed only Desktop mode is done in a way that touch friendly. TV requires arrow key input.

**Comment by mseeley** [comment]
Closing with a tear. Good luck!

**Comment by mattgorski** [comment]
What Qt version did you use to build?  I am having issues atm on jetson tx1 building pmp, ive tried 5.9.5 / 5.10.0 / 5.11.0
