### ISSUE TITLE
PMP in web UI (signed in) doesn't not find unclaimed server on local LAN, while it does in TV UI

### ISSUE THREAD

**Issue by bouscram** [plexinc/plex-media-player#861]
### Test environment

**PMS Version:** 
**PMP Version:** 2.34 but existed before
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS

### Steps to reproduce
1. Have PMS running unclaimed
2. Start PMP on another machine on the same LAN and authenticate

### Current behavior
1. PMP can't find server

### Expected behavior
1. PMP should find the server

Additional notes : 

- PMP opens a TCP connections to the PMS IP address, on different ports (I have seen 55177, 1031, 5824, 6963, ...
- if you start with PMS claimed, PMP finds it. If you unclaim it, PMP instantaneously loses the connection.

**This does not happen in TV mode**
Combined with #844, it means that I can't use PMP in web mode on a different computer than the one with PMS on my local network.

**Comment by mseeley** [comment]
Hi @bouscram. In TV mode we supported configuring a manual connection for a server to support unclaimed server access. We don't have plans to support manual connection configuration in the Desktop layout.

**Comment by bouscram** [comment]
@mseeley : well I think you should. This is clearly not a technical difficulty, so why not doing it? 
I may be looking paranoid, but if you use Plex only on a LAN with no intend to access remotely, there is absolutely no reason to log in to Plex, inc - please correct me if I'm wrong, but I have not seen any more detailed explanation than "it is more secure".
If you want to force users to connect because of some **evil** reasons (I hope not), why not be honest and completely forbid unauthenticated mode? I would immediately look for another solution, but that's another story.
Otherwise, you should add a simple way to use PMS / PMC completely disconnected. And keep the original spirit of Plex.
