### ISSUE TITLE
PMP Instance not syncing Playback with Companion

### ISSUE THREAD

**Issue by docsnyder12345** [plexinc/plex-media-player#864]
### Test environment

**PMS Version:** 1.15.6.1079
**PMP Version:** 2.34.0.983-edb7fbf7
**Plex App Version:** 7.16.0.10517 (2e560940)
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows 10, Android 8

### Steps to reproduce
1. Connect Plex App with PMP Instance
2. Start Playback of a Set of Items
3. Wait for the first Item to be played completely and the 2nd starting to play

### Current behavior
1. In the Companion App the Timeline is accurate, but the Title and Element to control remains the first Item played, not the current one.

### Expected behavior
1. The Companion App displays the current Item being played, not the first at the Start of the Playback

### Steps to reproduce
1. Start Playback of a Set of Items
2. Connect Plex App to PMP Instance

### Current behavior
1. No currently playing Item is displayed in the Companion App

### Expected behavior
1. The Companion App displays the current Item being played and offers the Option to control this Item

**Comment by mseeley** [comment]
Hi @docsnyder12345, couple questions:

- What do you mean by "Set of Items"?
- Do you see the same behavior if you play the "Set of Items" via Companion, using https://app.plex.tv/desktop instead of PMP?

**Comment by docsnyder12345** [comment]
Hey,

+ By Set of Items i mean for Example a TV-Series, or a self defined Playlist, doesnt matter as far as i could see.
+ Didnt test that before, because i use the PMP, but as i tested it now, it seems to behave the same Way
+ I use the TV Layout of PMP because of the Fullscreen Behaviour which suits my Needs more than the Desktop Layout (no Title Bar etc.)

Hope that helps

**Comment by mseeley** [comment]
Thnks @docsnyder12345, we'll take a look.

**Comment by markus101** [comment]
I've been able to reproduce this on Android, but not on iOS and have filed an issue for the Android team to investigate.

Closing as this is not something on the PMP side.
