### ISSUE TITLE
When playing TV media generally

### ISSUE THREAD

**Issue by nzflex** [plexinc/plex-media-player#865]
**PMS Version:** Version 1.15.6.1079
**PMP Version:** Version 3.100.1
**Platform :MacOS **

### Steps to reproduce
1. From a recently addedTV, select an episode to view
2. A Playback error occurs with the following message:
There was an unexpected error during playback. Please visit our forums if you continue to experience problems.

### Current behavior
1. Playback error occurs

### Expected behavior
1. The media to start playing

### ERROR LOG FROM DEBUG
  "type": "log:message",
    "level": 0,
    "message": "TypeError: Cannot read property 'features' of undefined\n    at Xie (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:1360149)\n    at http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:1361764\n    at Array.reduce (<anonymous>)\n    at sre (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:1361631)\n    at http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:1361921\n    at http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:1:19222\n    at http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:1:18672\n    at c (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:1:19427)\n    at http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:1:19386\n    at Array.map (<anonymous>)\n    at Function.c [as mapToProps] (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:1:19361)\n    at i (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:557586)\n    at Function.i.mapToProps (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:557802)\n    at i (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:557586)\n    at http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:559152\n    at Object.run (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:555109)\n    at a.initSelector (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:555290)\n    at new a (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:553681)\n    at Ea (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:64260)\n    at lo (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:76542)\n    at co (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:76849)\n    at Qo (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:80423)\n    at Ho (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:79894)\n    at Fo (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:79720)\n    at Uo (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:79093)\n    at fo (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:78340)\n    at Object.enqueueSetState (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:53923)\n    at a.S.setState (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:116:1281)\n    at a.onStateChange (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:555730)\n    at Object.notify (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:551501)\n    at e.notifyNestedSubs (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:551127)\n    at a.onStateChange (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:555749)\n    at n.<anonymous> (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:2806573)\n    at v (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:63:4550)\n    at m (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:63:4224)\n    at d (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:63:2146)\n    at n.c.trigger (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:63:4117)\n    at n.updateState (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:39:92892)\n    at g (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:50:4431)\n    at i (http://127.0.0.1:32400/web/js/chunk-2-4a32fe3f94e5216b5ceb-plex-3.95.2-25e2ffd.js:124:239700)",
    "time": "2019-06-02T05:42:21.783Z"
  },

**Comment by matz96** [comment]
I have the same issue but on windows.
Although it does work on the web player.

**Comment by mseeley** [comment]
Thanks; I can reproduce. Examining.
