### ISSUE TITLE
Version 3.102.0 Can not access Custom Filter in libraries.

### ISSUE THREAD

**Issue by kmoodysoh** [plexinc/plex-media-player#866]
### Test environment

PMS Version: 1.15.6.1079
PMP Version: 3.102.0
Windows 10 Pro Version 1903
Same result in all browsers.

### Steps to reproduce
In the new Plex experience, go into a library (IE. Movies) and click on All to pick a filter. At the very bottom is Custom filter.

### Current behavior
1. The first click on Custom Filter refreshes the page and clears any existing filter. Any click on Custom Filter after this doesn't do anything.

### Expected behavior
1. Expected to be able to pick a filter with the option to include or exclude criteria.

[plex-web.log](https://github.com/plexinc/plex-media-player/files/3262103/plex-web.log)

**Comment by mseeley** [comment]
Thanks @kmoodysoh. I believe we've fixed this elsewhere. I'll track it down.

**Comment by mseeley** [comment]
I'm not understanding the issue at hand.

- Clicking on Custom Filter clearing an existing custom filter is strange. I don't think it should do that.
- But, once a Custom Filter is selected then the controls within it are working correctly.

![Recording](https://user-images.githubusercontent.com/30019/70101101-0210dc00-15d8-11ea-9d7c-cee5ec9c2119.gif)

I'll file an internal issue to prevent clicks to Custom Filter from sometimes clearing the existing filter. Instead there's a nice prominent Cancel and `X` buttons.

If you're seeing a different error please do leave a follow-up comment.

**Comment by kmoodysoh** [comment]
I apologize for leaving this open. The problem I was having seemed to resolve itself with the next Plex build I installed. Everything is currently working as intended.
