### ISSUE TITLE
[Request] Display Stretch Modes

### ISSUE THREAD

**Issue by Zertop** [plexinc/plex-media-player#87]
Hi There!

Great stuff here, keep it up! :)

More of a feature request than a bug, but is there any chance of keeping the (Stretch by 20%) mode from Plex Home Theatre in Media Player? Also, stretching 4x3 content to 16x9?

I know it looks horrible most of the time, but some 4x3 content really does look nice (even stretched), and therefore it'd be nice to have as an option.

Thanks!

**Comment by tru** [comment]
Hey, this is definitely something we want to do! But please keep feature requests to the forum and let GitHub handle technical issues for now at least. See if there is a feature request in the forum otherwise post one there. Thanks!
