### ISSUE TITLE
Jump forward/backward 10 minutes control not updating elapsed time of video

### ISSUE THREAD

**Issue by Sada-Mio** [plexinc/plex-media-player#870]
### Test environment

**PMS Version:** 1.16.0.1226
**PMP Version:** 2.36.0.988
**Platform:** Windows 10

### Steps to reproduce
1. Press up/down to jump 10 minutes of video playerback

### Current behavior
1. Video jumps, but elapsed time doesn't update in playback control UI until it fades out

### Expected behavior
1. elapsed time changes after each 10minute jump without waiting for UI to fade out.

**Comment by mseeley** [comment]
Thanks @Sada-Mio we'll check it out.

**Comment by radley** [comment]
The bug was also introduced in 2.36 for Mac. 2.35 is fine.

**Comment by mseeley** [comment]
@markus101, @WillsonHaw checking in.

**Comment by markus101** [comment]
This should be fixed in the next release.
