### ISSUE TITLE
Xbox 360 controller Full Screen toggle no longer on Start button

### ISSUE THREAD

**Issue by jorubyp** [plexinc/plex-media-player#871]
Hi,

PMP no longer goes into full screen when pressing the Start button on my Xbox 360 controller as it used to.

I couldn't see such a change mentioned in the change logs, so I assume it's a bug.

### Test environment

**PMS Version:** 1.15.4.994-107756f7e
**PMP Version:** 2.36.0.988-0150ae52
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows 10

### Steps to reproduce
1. Press start on an Xbox 360 Controller when in TV Layout

### Current behavior
1. Nothing happens

### Expected behavior
1. For Plex Media Player to enter Full Screen.

**Comment by mseeley** [comment]
Hi @jorubyp couple questions. Do you remember when this last worked?

**Comment by jorubyp** [comment]
I’m afraid I can’t be sure, I don’t always update right away.

I think it could have been working as recently as the previous version though.

**Comment by jorubyp** [comment]
Oh, it’s working now.

I did try to make sure not to report an issue for a few days to try and rule other causes.

If it happens again I’ll be back, but sorry if it turns out this wasn’t PMP.
