### ISSUE TITLE
Kernel Drivers missing to get DTS-HD and TrueHD passthrough working on Intel NUC6CAYH

### ISSUE THREAD

**Issue by megapearl** [plexinc/plex-media-player#876]
**PMS Version:** 1.16.2.1297
**PMP Version:** 2.37.2.994-5717f996
**Platform:** Embedded Intel NUC6CAYH

### Steps to reproduce
1. Install https://nightlies.plex.tv/public-test/plexmediaplayer/embedded-testing/latest-full/PlexMediaPlayer-2.37.2.994-5717f996.Generic-x86_64.img.gz on Intel NUC6CAYH
Configure it to let audio all passthrough.

### Current behavior
1. No Dolby TrueHD playback and no DTS-HD playback (no audio, silence)

### Expected behavior
1. TrueHD and DTS-HD playback

I installed Windows 10 on this same NUC with PlexMediaPlayer on it, and DTS-HD and TrueHD passthrough is working as expected.
Also Ubuntu Linux with PlexMediaPlayer on that same NUC is doing DTS-HD and TrueHD passthrough fine.

See:
https://forums.plex.tv/t/not-able-to-do-truehd-and-dts-hd-passthrough-bitstreaming-on-nuc6cayh/383821

There are 2 firmware drivers missing to get it working on the embedded intel image:

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915/bxt_guc_ver8_7.bin

and

https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915/kbl_guc_ver9_14.bin

I tried to put them on the sdcard in ~/.config/firmware/i915 but they won't get loaded at boot.

What to do?
How can I get the firmware loaded so TrueHD and DTS-HD passthrough are working?

Hope anyone can help me out.

Best Regards,
Donald.

**Comment by mseeley** [comment]
@gbooker, @rcombs do you guys have any suggestions?

**Comment by gbooker** [comment]
- Supporting that NUC requires a newer version of LE (9)
- That version of LE using a newer version of libva which isn’t API compatible
- Building on that newer LE at the least requires updating the MPV version in PMP

**Comment by megapearl** [comment]
Are there any plans to build it with LE9?
Is there anything I can do to in the meantime?

**Comment by mseeley** [comment]
Hi @megapearl. No, no plans currently. I don't believe there is a workaround aside from the steps mentioned above.

**Comment by megapearl** [comment]
I have plex media player running with audio passthrough and video hardware acceleration on Ubuntu Linux now.
