### ISSUE TITLE
Can't connect to Chromecast from Android app

### ISSUE THREAD

**Issue by philwild** [plexinc/plex-media-player#879]
Trying to play offline synced content from the Plex Android app does not work. Clicking on the cast icon will not connect to the Chromecast.

Rebooting chromecast and tablet does not resolve the issue. I can cast to the chromecast from youtube with no issues. An IOS device can cast to the chromecast from Plex without issue.

Rant: Plex reliability really does suck nowadays. No matter how much testing I do before going on holidays the chances of reliably playing synced media to a tv would have to be under 50% in my experience. I brought a roku and a chromecast and both are failing to act as a streaming device.

Log from client below.

07-16 22:01:01.069  i: ------------------------------
07-16 22:01:01.069  i: Hello, Plex for Android world (debug: false)!
07-16 22:01:01.070  i: App version: 7.18.1.11300 (723698241)
07-16 22:01:01.070  i: Nano server version: 1.16.3.1277-4309f52b9
07-16 22:01:01.071  i: Manufacturer: samsung  Device: gts3lwifi  Model: SM-T820  Product: gts3lwifixx  Version: 8.0.0
07-16 22:01:01.075  i: Screen size: XLarge Screen density: Unknown Resolution: 2048x1536 DPI: 280 Touchscreen: true  Marketplace: com.android.vending  Architecture: arm64-v8a
07-16 22:01:01.076  i: Showing toast: Network logging has started
07-16 22:02:15.748  i: [pms] /192.168.1.13:60663 - GET /logging
07-16 22:02:18.800  i: [pms] /192.168.1.13:60664 - GET /favicon.ico
07-16 22:02:58.385  i: Resuming HomeActivity.
07-16 22:02:58.389  i: [TypeFirstBrain] Requesting type hubs for DataSource: (UrlDataSource{path='/hubs/sections/5?count=50&includeEmpty=1&includeExternalMetadata=1&includeLibraryPlaylists=1&includeStations=1&includeTrailers=1&includeTypeFirst=1&libraryHubsOnly=1&onlyTransient=1'})
07-16 22:02:58.390  i: [InitializationMonitor]        ReadyToRequestData		(+305.34s,	+284675.72s)
07-16 22:02:58.392  i: Fetching [method:GET] https://115-70-123-56.5a8ac1b9ed6f46fba3f6385f3d9e364b.plex.direct:25309/hubs/sections/5?count=50&includeEmpty=1&includeExternalMetadata=1&includeLibraryPlaylists=1&includeStations=1&includeTrailers=1&includeTypeFirst=1&libraryHubsOnly=1&onlyTransient=1&X-Plex-Token=...DPLT&X-Plex-Container-Start=0&X-Plex-Container-Size=50
07-16 22:02:59.943  i: [Cast] Starting aggressive device scanning.
07-16 22:03:01.823  i: [PlayerManager] Setting selected player: Away TV
07-16 22:03:01.824  i: [device] Setting selected server to com.plexapp.plex.net.remote.b@2dd12822
07-16 22:03:01.832  i: [Cast] - Connecting to CastDeviceController.
07-16 22:03:01.890  i: [Player][RemotePlayer] onPlayerSelected
07-16 22:03:01.892  i: [Cast] Stopping aggressive device scanning.
07-16 22:03:17.215  i: [Cast] Connection failed (error 7).
07-16 22:03:17.216  i: [PlayerManager] Setting selected player: null
07-16 22:03:17.219  i: [device] Setting selected server to null
07-16 22:03:17.219  i: [Cast] Attempting to disconnect device: com.google.android.gms/.cast.media.CastMediaRouteProviderService:76c75a862cc965731f32015c208a215a
07-16 22:03:17.224  i: [Remote Notification] - Cancelling notifications for Away TV
07-16 22:03:17.224  i: [Remote Notification] - Cancelling notification for com.google.android.gms/.cast.media.CastMediaRouteProviderService:76c75a862cc965731f32015c208a215a, type video
07-16 22:03:17.225  i: [Remote Notification] - Cancelling notification for com.google.android.gms/.cast.media.CastMediaRouteProviderService:76c75a862cc965731f32015c208a215a, type music
07-16 22:03:17.225  i: [Remote Notification] - Cancelling notification for com.google.android.gms/.cast.media.CastMediaRouteProviderService:76c75a862cc965731f32015c208a215a, type photo
07-16 22:03:17.226  i: [Remote Control Manager] Cancelling
07-16 22:03:17.228  i: Showing toast: Unable to connect to Away TV
07-16 22:03:17.242  i: [Player][RemotePlayer] onPlayerSelected
07-16 22:03:17.243  i: [Player][RemotePlayer] Prompting to see if we should resume locally
07-16 22:03:22.996  i: [FocusService] App focus lost.
07-16 22:03:22.997  i: [EventSource] Application unfocused, disconnecting...
07-16 22:03:23.004  i: [EventSource] Application unfocused, disconnecting...
07-16 22:03:23.004  i: [MetricsSessionApplicationBehaviour] Attaching listener for play queue events.
07-16 22:03:23.004  i: [EventSource] Disconnected from http://127.0.0.1:48917/:/eventsource/notifications?X-Plex-Token=...DPLT (reconnect: false)
07-16 22:03:23.007  i: [EventSource] Disconnected from https://pubsub.plex.tv/sub/eventsource/126101/6735b349884b9660-com-plexapp-android?X-Plex-Token=...DPLT (reconnect: false)
07-16 22:03:23.025  i: [Cast] Application unfocused, stopping active scan.
07-16 22:03:27.084  i: [pms] /192.168.1.13:60684 - GET /logging

**Comment by OttoKerner** [comment]
This repository is for Plex Media Player. 
"Plex Media Player" is **not** an umbrella term for every type of Plex client.

**Comment by philwild** [comment]
Where would you suggest i file this bug then?
