### ISSUE TITLE
ATL content not available in desktop mode

### ISSUE THREAD

**Issue by jsclayton** [plexinc/plex-media-player#880]
### Test environment

**PMS Version:** 1.16.3.1402
**PMP Version:** 3.104.1-99cd699
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS

### Steps to reproduce
1. Have a music library with content you've added from TIDAL
1. Open PMP in desktop mode
1. Browse to the content (or where it should be)

### Current behavior
1. Content! 😃 

### Expected behavior
1. No content 😢

**Comment by dogonwheels** [comment]
The feature flag was limited to 3.105. Moved back down to 3.104 so works in desktop (was added in 3.95.2), but not TV (which only supports it in 3.105).
