### ISSUE TITLE
All libraries available to home user if I do not share any libraries with the user

### ISSUE THREAD

**Issue by master-kenobi** [plexinc/plex-media-player#884]
I want to temporary deny a user access to all of my libraries without removing him from Home. So I untick all libraries under share for that user. Instead of seeing no libraries when he login, he can access all libraries.

### Test environment

**PMS Version:** 1.15.3.876
**PMP Version:** N/A
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** all platforms

### Steps to reproduce
1. Edit home user.
2. Untick all libraries under Share.
3. Login to the user account.

### Current behavior
1. All libraries become available

### Expected behavior
1. No library should be in the user account.

**Comment by mseeley** [comment]
This repository is for Plex Media Player only.
