### ISSUE TITLE
HTTP response code said error, while trying to pull dependencies

### ISSUE THREAD

**Issue by requiem240sx** [plexinc/plex-media-player#886]
Disclaimer, I'm very new to building and compiling code.  Its possible I may be doing something incorrectly, i'm also doing this on some very new software/hardware, which also may be some of my issues. 

While trying to build PMP on raspberry pi4, i'm getting an error that it can't reach a dependency URL? 

`-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PythonInterp: /usr/bin/python (found version "2.7.16")
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/hash.txt to plexmediaplayer-qt-206-hash.txt...
-- Dependency hash is: 206d4d1
-- Downloading https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt to konvergo-qt--release-206d4d1.tbz2.sha.txt...
CMake Error at CMakeModules/FetchDependencies.cmake:59 (message):
  Failed to download
  https://nightlies.plex.tv/directdl/plex-dependencies/plexmediaplayer-qt/206/konvergo-qt--release-206d4d1.tbz2.sha.txt:
  "HTTP response code said error"`

### Test environment

**PMS Version:**  1.16.3.1433
**PMP Version:**   2.39.0
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**

### Steps to reproduce
1.  Install Raspian Buster on Raspberry Pi 4
2. Manually install QT5.9.5
3. Manually install ffmpeg and mpv
4. Try to build pmp

### Current behavior
1. When building, I'm getting an error. It appears like its happening while trying to view a web page that doesn't exist? 

### Expected behavior
1. Continue the build, or have an option to point to a different file or ignore the file.

**Comment by mseeley** [comment]
Please try `-DQT_ROOT` to load your local Qt.
