### ISSUE TITLE
UNO Cannot Reset customizations when account only has one server

### ISSUE THREAD

**Issue by BigWheel88** [plexinc/plex-media-player#887]
### Test environment

**PMS Version:** 1.15.x ( pretty sure user had current 1.16 though)
**PMP Version:** 3.104.1-99cd699
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**

### Steps to reproduce
1. log into PMP with an account that only has one server
2. go to user menu and select "reset customizations"

### Current behavior
1. goes directly to home screen with zero libraries pinned to home screen

<img width="365" alt="Screen Shot 2019-08-04 at 5 24 07 AM" src="https://user-images.githubusercontent.com/4098091/62423661-208db780-b678-11e9-91af-19fc84544da4.png">

### Expected behavior
1. skips Preferred Server selection because there it only one
2. goes to library selections to be pinned.
3. goes to home screen with those libraries pinned.

I'm worried this might affect TV apps like LG,Samsung  as well but I don't have one of those to test.

### Workaround
so there is a work around for PMP but IMO is is very janky and we can't expect folks to remember these steps.

In desktop view general settings
1. check preview new experience
2. save
3. show advanced button
4. Reset Customizations button
5. choose libraries
6. switch to tv mode (edited)

**Comment by pcalves** [comment]
Initially I wan't having any luck reproducing this issue. Turns out it only happens if the user has a single server _and_ has disabled every online media source. Will look into it. 👍
