### ISSUE TITLE
PMP UI not scaling properly at 150% UI scaling in Windows

### ISSUE THREAD

**Issue by kieronam** [plexinc/plex-media-player#889]
Server Version#: 1.16.3.1402 (latest)
Player Version#: 2.39.0.1005-1b0839a8 (latest)
Windows 10 1903

On a laptop with 1080p resolution (16:9 aspect ratio) and UI scaling at 150%, PMP displays everything far too big. It looks like it’s scaling at 200% instead of 150%. The web player in Firefox looks fine, however - everything at the right size.
![plex media player - 1080p laptop monitor- 1 5x display zoom (UI unusably large)](https://user-images.githubusercontent.com/33033550/62653542-adc15c80-b955-11e9-9e98-ec2d831cb789.jpg)
![plex web player in firefox - 1080p laptop monitor - 1 5x display zoom (looks as expected)](https://user-images.githubusercontent.com/33033550/62653545-af8b2000-b955-11e9-994c-fff06885fd87.jpg)

As an additional problem, when PMP opens, the window is positioned off the top and left edges of the screen. (Since PMP doesn’t remember window position, it starts like this every time.) 
![plex media player - 1080p laptop monitor - 1 5x UI scaling (window opens off edge of screen)](https://user-images.githubusercontent.com/33033550/62653557-b4e86a80-b955-11e9-949e-037a6ce16464.jpg)

Changing the UI scaling on this machine to 100% resolves the issue. PMP is now scaling at the same size as the web player in Firefox.
![plex media player - 1080p laptop monitor - UI scaling reduced to 1x (looks as expected)](https://user-images.githubusercontent.com/33033550/62653589-bca80f00-b955-11e9-9f4b-fd2b55f0c5e3.jpg)
![plex web player in firefox - 1080p laptop monitor - UI scaling reduced to 1x (looks as expected)](https://user-images.githubusercontent.com/33033550/62653594-be71d280-b955-11e9-8a7a-af63d832f202.jpg)

On another machine (also Windows 10 1903), at 4k resolution and UI scaling at 200%, PMP's scaling is also fine here. The web player in Firefox and PMP are both showing the UI at the same size.
![plex media player - 4k monitor - 2x display zoom (looks as expected)](https://user-images.githubusercontent.com/33033550/62653616-c893d100-b955-11e9-942d-756be174454a.jpg)
![plex web player in firefox - 4k monitor - 2x display zoom (looks as expected)](https://user-images.githubusercontent.com/33033550/62653618-ca5d9480-b955-11e9-8daa-6870a0f52575.jpg)

The issue here seems to be with 150% scaling?

**Comment by mseeley** [comment]
It's an issue with any non integer zoom level. The framework rendering the app rounds the zoom level to an integer. So, `150%` is provided to the framework as `1.5` which is then rounded to `2`. You can verify this behavior by setting the zoom level to `125%`. Following the logic above it'll round down to a zoom level of `1` before reaching our application.

You can _try_ setting a user environment variable `QT_SCALE_FACTOR=1.5` before launching the app.

**Comment by kieronam** [comment]
Is there a reason for that rounding or is it just an oversight? (If it were intentional behaviour surely it ought to always round down, rather than bringing up windows off the edges of the screen)

Where would I set the user environment variable?

**Comment by mseeley** [comment]
> Is there a reason for that rounding or is it just an oversight? (If it were intentional behaviour surely it ought to always round down, rather than bringing up windows off the edges of the screen)

The rounding is intentional to avoid issues in areas of the framework that we don't use. Unfortunately we can't opt out of it.

Please ask Google how to set the variable.

**Comment by kieronam** [comment]
Thanks... Setting QT_SCALE_FACTOR=1.5 exacerbated the problem - made it even bigger.

However setting it to QT_SCALE_FACTOR=0.75 seems to have rsolved the issue - PMP is now at the correct ratio.

**Comment by mseeley** [comment]
Ah interesting. Maybe it was being handled as 1.5 more on top of an existing 1.5. I'm glad you found a workaround.

I found that we also have a `--scalefactor` argument available: https://github.com/plexinc/plex-media-player/blob/6e1ea2cbf289a1f101de98513a91eed1a44733f9/release-notes/1.2.1.txt. I think the env variable is still a cleaner workaround since you don't need to edit/create shortcuts with the argument.

Since you've got a cozy scale factor I'm going to close this out. It's imperfect but it's not our code doing the rounding.

**Comment by kieronam** [comment]
Can confirm adding the command-line argument to the Windows shortcut also works. Might be better as presumably it won't affect any other QT apps on the system.

However I fear a lot of PMP users on 1080p laptops won't bother and will just uninstall.
