### ISSUE TITLE
1024x768 unusable due to interface jitters

### ISSUE THREAD

**Issue by oucil** [plexinc/plex-media-player#89]
I'm no longer able to use the native resolution of my projector, 1024x768 (please don't laugh).  

The moment I start the app, the logo splash screen becomes jittery with the wordmark jumping back and forth, and then this gets much much worse when it's fully loaded and sitting at the menu screen.  

The interface is completely unusable because of the jitters.  It doesn't actually appear like anything is moving around relative to each other (i.e. like a webpage if css were loaded progressively), it's the entire screen that continually jumps around. I can't even get to the exit menu as the focus point keeps resetting it seems, I have to hit the windows key and manually close the app from the task bar.

I should add, I've never had an issue with Plex Home Theatre, it works perfectly.

Windows 10, Atom CPU with ION, generic HTPC

Kevin.

**Comment by oucil** [comment]
I should add, I've never had an issue with Plex Home Theatre, it works perfectly.

**Comment by tru** [comment]
PMP currently only supports 16:9 layout, so I am not surprised it behaves strangely on 4:3. I don't see us adding 4:3 aspect support though, there can't be many people that needs that anymore. Sorry.

**Comment by wm4** [comment]
The technical reason might be that the code to "letterbox" the UI into 16:9 behaves stupidly and causes this "jumping around".

**Comment by tru** [comment]
also the scaling in the web client assumes 720p, so I bet there are things with the scale factor that would have to change as well.

**Comment by oucil** [comment]
@tru Are you kidding me, you're tossing support for a ton of projectors by chosing not to support it, and this is supposed to be your HTPC platform.  You're going to make that call without even researching how many people might be using that resolution???

**Comment by oucil** [comment]
@tru After just a VERY quick search, ALL affordable projectors are still using 800x600, 1024x768.  I can't understand how you could arbitrarily choose not to support this aspect when a very likely large portion of your home theatre users on smaller budgets are using it.

**Comment by tru** [comment]
Sorry I understand my message could be read like I did a gut reaction type of call. It was not, we looked at resolutions for PHT and 16:9 was by far the most used one so we prioritized that. We are also gathering stats for users that start PMP so we can change direction later. 

I am sorry you are part of that group that needs 4:3, but currently we don't have the resources to add support for that. Later on we might be able to support letterboxed 16:9 UI on 4:3 but I don't want to promise anything now. 

For now your best bet is to continue to use PHT.

**Comment by oucil** [comment]
Being a dev myself, I completely understand resource allocation, but this seems very premature for that level of deprecation, considering the audience and your intention to drop PHT.  You've already hidden for all intents PHT (other than a tiny "looking for" link) on the website download page.  

I'll bring it up in the forums and maybe you're right and nobody will care, but it's worth checking with your users.

**Comment by miketweaver** [comment]
I'd like to mention that the 4:3 ratio is important to me as well. I love that PMP can be windowed, and when I'm watching my 4:3 videos, I do not want the extra space on my screen. So I resize the window to be 4:3 and only show what is needed.

<hr>
Because of this, I have weird interface errors as well:
<img src="http://i.imgur.com/2ErgVjh.jpg" alt="weird interface" width="75%" height="75%">
<img src="http://i.imgur.com/EuCaV0L.png" alt="weird interface - two" width="75%" height="75%">
<hr>
Now, I don't mind an interface that has black bars. It's not the best, but it's OK:
<img src="http://i.imgur.com/sFfqHXX.png" alt="weird interface - two" width="75%" height="75%">
<hr>
I would suggest taking a look at doing a *few* things to make the 4:3 ratio workable.
