### ISSUE TITLE
PMP Poster art not displaying

### ISSUE THREAD

**Issue by terwalsh** [plexinc/plex-media-player#890]
**PMS Version:1.16.3.1402 
**PMP Version:2.39.0.1005-1b0839a8
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):MacOS

### Steps to reproduce
1. Open PMP

### Current behavior
1. Many recently played TV shows have lost their poster art.  The poster art is visible within the web client of PMS using the same login, just not PMP.

### Expected behavior
1. All poster art is displayed in PMP, just like web client in PMS

**Comment by mseeley** [comment]
Please provide logs.
