### ISSUE TITLE
Future of This Repository?

### ISSUE THREAD

**Issue by SlvrEagle23** [plexinc/plex-media-player#892]
Recent comments from Plex Inc. have indicated that their overall strategy is to get everyone away from both Plex Media Player and the Plex Windows Store app, instead shifting over to the new vaguely-named "Plex for Windows" app.

It appears that this repository is the open-source code behind the now-"soon-to-be-retired" Plex Media Player, which was far more full-featured and stable on Windows, and included HiDPI support and TV mode, both of which seem to be absent from the new version.

I've noticed that even today, when you go to download clients from Plex's web site, Plex Media Player is no longer present in favor of the new Plex for Windows.

Does this mean that this repository will in turn be archived as well?

If so, choosing to replace a stable, powerful **open-source** application with a closed-source one seems like an immense step backwards.

**Comment by mhitchens** [comment]
I've forked it. I'd encourage others to as well. The attitude of the mods has been relatively hostile to Linux users, so the safe assumption is that this is going away.

**Comment by Mitzsch01** [comment]
Yeah, I think that´s the best thing we can to right now...
I´ve forked it as well ;)

**Comment by ericmatthys** [comment]
We will not be taking down this repository, but we will likely update the README and hide the Issues tab in GitHub after the app is no longer officially supported by the team.

**Comment by mhitchens** [comment]
That’s unfortunate, as the issues, even the resolved ones, serve an important need for documenting changes.

It’s not too late to reconsider the choice to close the source for the app. Confidence in PMP has come partially from our ability to answer our own questions about functionality. You might find yourselves in a more defensive posture with your paying customers (like myself) if you decide to close off more access to the product.

Can you pass this on to your team and management? We’re all a bit baffled at the direction here.

**Comment by ericmatthys** [comment]
We wouldn't be making PMP closed source. We'd be leaving the source where it is. Without an active maintainer or official support from Plex, I think the Issues tab is a false promise. That said, I get that there is some important information tucked away in those issues, so perhaps a README update is sufficient.

**Comment by mhitchens** [comment]
Ah, I should have been more clear. I was referring to the decision to keep the source private for the new Plex app announced last week. Naturally, PMP is already public.

**Comment by Maxou44** [comment]
@ericmatthys 

To make the transition as smooth as possible, would it be possible for you to make the web bundle of the TV part open source? If we update the PMP to remove the "desktop" web app (bundled on your side) and if the "tv" part became open source we could continue to improve it, without any support on your side.

People who want to use the web version will use your new App and people who love this TV version could continue to support and improve this TV mode

I love this idea and it could be a good move for people who loves this app 😉

**Comment by ericmatthys** [comment]
I will raise it with the team, but it's not quite as simple as removing desktop and open sourcing the TV UI for a couple reasons. The base TV UI is used on a handful of other platforms (LG, Samsung Tizen, PS4, Xbox One, etc) and I'm not sure we'd open source everything. Also, all of the web-based UIs, including the desktop UI, are closely related and live in the same repository right now.

I do understand that leaving only the Qt and player integrations open source greatly restricts what can be done by the community though. Input maps, player features, etc can be maintained, but without swapping in a different UI, there is only so much that can be done.

**Comment by Maxou44** [comment]
@ericmatthys

If the TV mode is maintained on your side (for other apps) can you bundle it into the web client for new Plex app ?

If you merge it we will have a unique Plex app with tv mode and desktop mode (And the web app can also support the tv mode)

**Comment by mhitchens** [comment]
@ericmatthys 

> I do understand that leaving only the Qt and player integrations open source greatly restricts what can be done by the community though.

I hope you wouldn't use this as a reason to keep these layers private for the new Plex app, though. A Linux user or package maintainer could build and use the product if the UI were developed as a proprietary layer and shipped separately, just as it is done today, and you'd still gain the benefit from community improvements and feedback for the shell and player.

There are a lot of folks here that love and pay for the product, but it should be clear by now that we're losing confidence that our participation will be possible after January, and keeping the Qt shell and mpv integrations open is a reasonable layer to leave open. For me, it's important to know that this is really being considered, or if the decision to privatize all source for the new Plex app has already been made.

At any rate, thanks for engaging on this. I look forward to hearing your thoughts.

**Comment by Maxou44** [comment]
After technical analyse, I'm sure the new app is not open source because the new player app is bundled with a light Plex Media Server inside to support download / sync feature.

When the player started, you can check on 32700 port, you'll see a PMS api with the same urls. This light PMS is based on a 1.16.6-x release.

**Comment by ericmatthys** [comment]
We've updated our stance on PMP in the forums. Please take a look at https://forums.plex.tv/t/killing-pmp/446526/826.

> I hope you wouldn't use this as a reason to keep these layers private for the new Plex app, though. A Linux user or package maintainer could build and use the product if the UI were developed as a proprietary layer and shipped separately, just as it is done today, and you'd still gain the benefit from community improvements and feedback for the shell and player.

We've talked about doing this with the new macOS and Windows app for this reason. There are some challenges to actually letting people build the app without our internal build tools, but it's certainly not impossible. The media server bundled with the new desktop app wouldn't be open source if we were to do this, similar to the UI.

**Comment by a351must2** [comment]
Is there a reason these players keep getting abandoned?  I (and others I know) were originall attracted to Plex because of Plex Home Theater.  We all eventually (and reluctantly) switched to Plex Media Player once it PHT stopped reliably working with an updated media server.  Once PMP is abandoned, the server will eventially get updated to a point that PMP will no longer work reliably, and there currently are (IMHO) no other players worth dealing with on PC.

**Comment by Kage-Yami** [comment]
I'm still a bit confused on that the stance is, especially when it comes to Linux; can I expect to continue to be able to use PMP on Linux (same system as PMS; my daily driver desktop, so not HTPC)? And if so, will there continue to be fixes? (For example, sounds like Qt5.14 has busted the video player, leaving behind ghost UI elements.)

I notice that Linux is missing entirely from the download page: https://www.plex.tv/en-au/media-server-downloads/#plex-app

**Comment by ericmatthys** [comment]
> Is there a reason these players keep getting abandoned?

PHT was built on XBMC and was not easy to support as just one of many apps our teams support. PMP was able to use the same core TV UI that the rest of our web-based TV apps use, which made it easier to support than PHT. As for PMP, I think the blog post and forums thread already details it.

> I'm still a bit confused on that the stance is, especially when it comes to Linux; can I expect to continue to be able to use PMP on Linux (same system as PMS; my daily driver desktop, so not HTPC)? And if so, will there continue to be fixes?

We haven't released updated embedded builds for PMP aside from unofficial previews for a couple years. We're still interested in adding official Linux support to the new desktop app, but nothing to share on that quite yet.

I'm closing this issue since for now nothing is changing.
