### ISSUE TITLE
macOS: PMP does not start in Fullscreen

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#894]
### Test environment

**PMS Version:** 1.16.5.1488
**PMP Version:** Version 1.1.0.831-e1ae73b1
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS 10.13.6

### Steps to reproduce
1. Start PMP
2. Put PMP in fullscreen (macOS green button)
3. Quit PMP
4. Start PMP : the application starts in windowed mode instead of fullscreen

### Current behavior
1. PMP "forgets" fullscreen mode status when quitting or fail to start in fullscreen mode

### Expected behavior
1. PMP should remember when user has switched the app in fullscreen mode (green button) and should keep this setting upon restarting as all standard macOS application do. It should start in fullscreen mode not in windowed mode.
2. A user selectable setting in Player -> Settings -> General to allow "always start in Fullscreen" would certainly be very welcomed.

**Comment by mseeley** [comment]
Thanks for the heads up here too. This isn't the appropriate repo for Plex for Mac issues.
