### ISSUE TITLE
macOS: mouse cursor always visible when playing fullscreen mode

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#895]
### Test environment

**PMS Version:** 1.16.5.1488
**PMP Version:** Version 1.1.0.831-e1ae73b1
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS 10.13.6

May be duplicate of #503 but issue seems to occurs only when in full screen mode.
May be linked with issue #896 and #894 

### Steps to reproduce
1. Start PMP
2. Switch to fullscreen mode (macOS green arrow)
3. Play a movie -> the mouse cursor stays visible during playback and does not hide

### Current behavior
1. Mouse Cursor does not disappear after few seconds during playback of a movie

### Expected behavior
1. Mouse cursor should disappear after few second like it does when playing in windows mode

**Comment by mseeley** [comment]
Thanks for the heads up. This isn't the appropriate repo for a Plex for Mac issue.
