### ISSUE TITLE
macOS: Fullscreen mode seems to be broken

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#896]
### Test environment

**PMS Version:** 1.16.5.1488
**PMP Version:** Version 1.1.0.831-e1ae73b1
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** macOS 10.13.6

### Steps to reproduce
1. Start PMP
2. Switch to fullscreen (macOS green button)
3. Start to play a movie -> a gray band on top of the picture is present (it seems to have the height of the application window title bar in windows mode)
4. All player control button are inactive: user cannot click on them. To activate a button user has to click above the real button position

### Current behavior
1. Fullscreen generates a gray ban that should not be present
2. Player control buttons are shifted

### Expected behavior
1. No gray band display, image should be centered (between top and bottom of the screen)
2. Player control buttons should work when click on them not when clicking above the real position.
<img width="1680" alt="Capture d’écran 2019-08-23 à 15 21 38" src="https://user-images.githubusercontent.com/2266264/63596319-3fb69f80-c5bb-11e9-83c2-d8852e69810f.png">
<img width="1027" alt="Capture d’écran 2019-08-23 à 15 23 38" src="https://user-images.githubusercontent.com/2266264/63596342-50ffac00-c5bb-11e9-9f7b-a7a8fdbbf777.png">

**Comment by OttoKerner** [comment]
Wrong app.

**Comment by Ribero** [comment]
Ok I see. No comment.
