### ISSUE TITLE
Cannot search media for '-' or '+' (overrides to volume control)

### ISSUE THREAD

**Issue by owenrenn** [plexinc/plex-media-player#897]
### Test environment

**PMS Version:**  1.16.5.1554 
**PMP Version:** 2.4 
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Mac mini (2018) Mac OS 10.14.5

### Steps to reproduce
1. Click search icon
2. Type 123-456

### Current behavior
1. Volume will decrease when you type -

### Expected behavior
1. literal "-" should be entered into the search bar as included search criteria

Note, you cannot workaround this through the UI as no symbols are available in the search keyboard that appears
![Search Keyboard](https://user-images.githubusercontent.com/1229845/63694950-8be52800-c7e5-11e9-8e75-18e18cae33de.png)

**Comment by mseeley** [comment]
Agreed, thanks for filing this issue. 👍
