### ISSUE TITLE
Full screen mode overflows the screen resolution

### ISSUE THREAD

**Issue by alekdavis** [plexinc/plex-media-player#899]
### Test environment
**PMS Version: 1.16.6.1592**
**PMP Version: 1.2.0.875-b7362913**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): Windows 10 (x64) Version	10.0.18362 Build 18362**

When I launch a video in the full screen mode the screen size become bigger than the monitor (so top, bottom, left, and right sides are cropped). I cannot get to the navigation buttons or whatever is supposed to be at the top right side. This is only the problem of Plex Media Player desktop app. The web-based player and the Plex Player Metro app work fine. I'm running Plex server and client on the same NUC6i7KYK server connected to a Samsung TV via HDMI cable. The display resolution is set to 1600 x 900 (it's using an Intel Graphics card). 

### Steps to reproduce
1. Start video.
2. Click button to maximize.

### Current behavior
1. Screen overflows the monitor.
2. It does not respond to ESC or ALT+F4 keys.

### Expected behavior
1. Screen should not overflow the monitor.

**Comment by OttoKerner** [comment]
This error report is not about Plex Media Player.

**Comment by alekdavis** [comment]
I'm confused. What is it about?

**Comment by OttoKerner** [comment]
It is about "Plex for Windows" / "Plex for Mac"
which are not "Plex Media Player".

**Comment by alekdavis** [comment]
Oh, didn't realize that. The Plex for Windows app doesn't even say what it's called. The binary is called Plex. It looks like the Plex admin tool (since it shows all the server settings and such), and the version doesn't say which version it is. I had to open the Plex online app to make sure the Plex server version is not the same. Very frustrating. Anyway, any easy way to move this to a different subgroup? Or do I need to open a new one?

**Comment by OttoKerner** [comment]
Support and error reporting is through the forums, like all other Plex software.
Section Players > Desktop Player - tags: `player-windows` & `player-mac`

**Comment by alekdavis** [comment]
Okay, submitted to the forum.
