### ISSUE TITLE
Mac client: blank screen if eGPU connected

### ISSUE THREAD

**Issue by ScreamingPict** [plexinc/plex-media-player#900]
### Test environment

**PMS Version:1.16.5.1554**
**PMP Version:1.2.0.875-b7362913**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): MacOS 10.14.6 with HP Omen Accelerator eGPU and AMD RX580 graphics card**

### Steps to reproduce
1.Load Mac Plex app with eGPU already connected and "prefer external GPU" *not* enabled in the settings for the app.

### Current behavior
1. App loads, shows the Plex logo, goes black and then nothing more happens.

### Expected behavior
1. App loads and shows Plex media.

**Comment by mseeley** [comment]
Where is the `prefer external GPU` setting?

This is a problem with the Plex for Mac app, Plex Media Player is a different application.

Our 1.3 release will include the macOS Open GL fix previewed here: https://forums.plex.tv/t/plex-for-windows-and-plex-for-mac-forum-preview-releases/453210/3. It should handle your situation.

**Comment by ScreamingPict** [comment]
Matt,

Ah- Apologies- I just saw something saying I should raise issues on Github and didn’t realised PMP didn’t include the new Mac App. Thanks for closing it. Am hoping that by replying I don’t re-open the case.

Because you asedk- if you have an eGPU and you select the application and select ‘Get Info’ you will get an extra option titled "Prefer external GPU” that will ensure that the application uses the eGPU for its graphics even if it is running on a screen not directly connected to the output of the eGPU (e.g. a laptop screen).

Thanks.
-- 
Niall
