### ISSUE TITLE
Choppy Direct Play and No Full screen on Win 10 player

### ISSUE THREAD

**Issue by michaelpalmer7** [plexinc/plex-media-player#901]
On the latest version of Plex Media Player on Win 10 running on an MS surface Pro I have 3 issues:

1) When Direct streaming 4K the video is choppy, when transcoding to 1080P High it's fine and 4K is fine on other devices.

2) Full screen doesn't work the windows toolbar remains at the bottom of the screen.

3) The MS Surface pen stylus doesn't work for selecting menu options etc. weirdly. I haven't had this issue on any other apps.

**Comment by mseeley** [comment]
Thank you for the report. We're aware of full screen and touch (pen) input shortcoming in the new Plex for Windows app. Our next Plex for Windows release will have improved caching and rendering that should improve playback.

Please, when filing issues we really appreciate folks taking the time to fill out the issue template.

**Comment by michaelpalmer7** [comment]
Thank you
