### ISSUE TITLE
TV Mode button missing

### ISSUE THREAD

**Issue by nfazio49** [plexinc/plex-media-player#903]
The latest version of PMP doesn't have the "TV Mode" button at the top.

PMP Version: Version 1.3.0.910-77ef46d6
Platform Windows:

### Steps to reproduce
1.  Open the application

### Current behavior
1.  Button isn't present

### Expected behavior
1.  Button should be present and clickable

**Comment by mseeley** [comment]
You're referencing the latest Plex for Windows and Plex for Mac release number. These products do not have a TV mode. Plex Media Player is a separate product.

We'll be bringing back the PMP downloads as soon as some internal infrastructure work is done.
