### ISSUE TITLE
Videos open in uncloseable child window (after context switch?) 

### ISSUE THREAD

**Issue by bryanhunwardsen** [plexinc/plex-media-player#904]
## Test environment
**PMS Version: Version Synology-1.16.5.1552 (Synology - has not published updated server version yet)
**PMP Version:1.3.1.916-1cb2c34d
**Platform Win 10 x64 1903

### Steps to reproduce
1. Open Windows App
2. Play Video
3. Do Something, maybe nothing - mouse around on main window, context swtich (?)

### Current behavior
Video moves from main windows to restricted child window
 All subsequent playback uses child window(has no media controls)
Main Windows behaves with hover over controls appear and view home, but video plays only in unwanted separate window

### Expected behavior
1. Video stays in main windows
![Annotation 2019-09-28 134949](https://user-images.githubusercontent.com/3408302/65822330-e6174580-e1f6-11e9-81ce-887872099660.jpg)
![Annotation 2019-09-28 134909](https://user-images.githubusercontent.com/3408302/65822331-e8799f80-e1f6-11e9-9719-a1268cc605c8.jpg)

**Comment by Mitzsch01** [comment]
This repository is not about the new "Plex App". 
It´s about the (old) "PlexMediaPlayer"

**Comment by mseeley** [comment]
Hi @bryanhunwardsen will you please provide really tight steps to reproduce? Or perhaps you can share a screen recording of the app with correct playback devolving into the two window screenshots above?

**Comment by mseeley** [comment]
@bryanhunwardsen, also, does this happens with all videos or only select videos? If the latter will you please share one of these videos with us for testing?
