### ISSUE TITLE
Home screen full page refresh every few seconds

### ISSUE THREAD

**Issue by vanhecke** [plexinc/plex-media-player#905]
# Test environment

**PMS Version:**  Version 4.8.1 
**PMP Version:** 1.3.1.916-1cb2c34d
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Windows

### Steps to reproduce
1. Open Plex

### Current behavior
1. The plex "Home" screen refreshes every few seconds.
About every 15 seconds it does a full "page refresh" where I only see the loading symbol for about 5 seconds and then it shows Home again.

### Expected behavior
1. It used to dynamically add newly discovered content, not do full screen refresh every x seconds.
If I go to a different screen (Like "TV Shows > Recommended") it doesn't happen. only seems to happen on Home.

**Comment by Mitzsch01** [comment]
You are referring to the new "Plex App" but this repository is about a different piece of software (PlexMediaPlayer) :)

**Comment by mseeley** [comment]
Thanks for the report. We'll include this fix in v1.5.
