### ISSUE TITLE
Match is Missing Some Metadata Information

### ISSUE THREAD

**Issue by VxMxPx** [plexinc/plex-media-player#908]
When match dialog is displayed, the desktop version of client does not show metadata details as we can see on web version.

The screenshot of expected (top/web) and current (bottom/application) behavior: https://imgur.com/a/v8zB3wr

### Test environment

**PMS Version:** 1.18.0.1944
**PMP Version:** web(4.8.4) desktop(Version 3.104.1)
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Linux

### Steps to reproduce
1. Open any music file
2. Click Match... (or Fix Match...)
3. Observer results in dialog are missing additional metadata information

### Current behavior
1. Match dialog shows only author/album

### Expected behavior
1. Match dialog would show additional metadata (like author's location).

**Comment by mseeley** [comment]
Hi there. The Desktop layout in PMP is an older version. We do not currently have plans to update to a newer build with a fix for this behavior.
