### ISSUE TITLE
Bug: Wrong default audio language despite correct profile setting

### ISSUE THREAD

**Issue by Qhitewolf** [plexinc/plex-media-player#909]
Audio Language is set in profile to German.

Languages of Movies/shows are correctly identified as german and english.

In all Apps (mac, ios, fire tv...) and in the web 
player the default audio language for every movie and every show is set to english despite the german setting in the profile.

resetting the settings and even making a new plex account doesnt change the wrong default audio language.

More Info with several people having this exact bug can be found in this forum thread:

https://forums.plex.tv/t/bug-wrong-default-audio-language-despite-correct-profile-setting-web-player-all-apps/480319/6

**Comment by mseeley** [comment]
I'll pass this along to our server team.
