### ISSUE TITLE
64 bit windows install error

### ISSUE THREAD

**Issue by willydoit** [plexinc/plex-media-player#91]
When attempting to install windows 64 bit v 1.0.1.42-56cc6ef9 , as soon as I double click the install link I get the error "The ordinal 4369 could not be located in the dynamic link library LIBEAY32.dll" It seems as though the program still installs but do not know if issue could cause issues in use.

**Comment by tru** [comment]
You probably have a LIBEAY32.DLL in the path somewhere, maybe you have PHP installed?

**Comment by willydoit** [comment]
Thanks, as no-onbe seems to have had the issue it looks as though it is local.

**Comment by sa2000a** [comment]
Just reading through the issues - is this not fixed now in PMP 1.0.2.70

http://forums.plex.tv/discussion/comment/1058318/#Comment_1058318

looks similar to issue we had on PMS here https://forums.plex.tv/discussion/105322/error-on-launching-pms-9-9-9/p1#entry623194 - to do with MSI and version numbers of OpenSSL

**Comment by tru** [comment]
Yeah this should be fixed in 1.0.2, please try launch the installer again.
