### ISSUE TITLE
New version of PMP tags music albums with various artists tags "Album Artist" as the same one.

### ISSUE THREAD

**Issue by jlmitch5** [plexinc/plex-media-player#911]
I have 5 records that are compilations in my plex media server.  When I use the album view, it orders them all on the same "Album Artist"

![Screen Shot 2019-10-30 at 9 21 16 AM](https://user-images.githubusercontent.com/1342624/67861466-a8a81f80-faf6-11e9-80e7-761f3542699f.png)

When I select all to edit and change the "Artist" to "Various Artists":

![Screen Shot 2019-10-30 at 9 22 43 AM](https://user-images.githubusercontent.com/1342624/67861607-ee64e800-faf6-11e9-9dc3-d947f8500759.png)

They briefly change to be ordered by "Various Artists" in the grid, and then a few seconds later, go back to being ordered by "Bardo Pond | Yo La Tengo" in the album view.

If I go to edit an individual track, I see both the "Album Artist" (as "Bardo Pond | Yo La Tengo", not "Various Artists" as I wanted to change it to), as well as "Artist" (which is the artist for the individual track...and is correct)

![Screen Shot 2019-10-30 at 9 25 46 AM](https://user-images.githubusercontent.com/1342624/67861864-6df2b700-faf7-11e9-9ea2-839438aa72c1.png)

My request is that the edit-multiple-albums dialog allows you to change **Album Artist**.

Versions:
**PMS: 1.18.1.1973**
**PMP: 1.3.1.916-1cb2c34d**
**macOS**

**Comment by mseeley** [comment]
Hi there. Can you reproduce this issue in the hosted application at https://app.plex.tv/desktop?

**Comment by mseeley** [comment]
I was able to change Artist to Various Artists for multiple albums simultaneously in our 1.4 build. Please let us know if this is still an issue for you.

![image](https://user-images.githubusercontent.com/30019/70566332-f2454a80-1b37-11ea-9af2-3de264b2c62b.png)
