### ISSUE TITLE
Completed TV Shows are not being marked as watched

### ISSUE THREAD

**Issue by distributorofpain** [plexinc/plex-media-player#913]
### Test environment

**PMS Version: Version 1.17.0.1709
**PMP Version: 2.44.0.1018-8f77cbb9
**Platform:  Windows 10 1903 (client and Server )

### Steps to reproduce
1.  Play any on deck TV show

### Current behavior
1.  When a TV show is played to completion ( meaning the timer runs out ) and the PMP goes back to the TV show series screen, the video playback tracker rolls back 2-3 minutes and thus the video is marked as a candidate for the "Continue Watching" area.  If i go back to the on deck screen, the video is still marked as not completed with yellow bar indicating almost full playback with 2-3 minutes left.  I have to then click the 3 dots to then set the video as played.  Its happening with every TV show played.

### Expected behavior
1.  TV Show or Movie is marked as "Played" , the yellow/orange bar is gone and its no longer showing the "continue watching" area.

**Comment by mseeley** [comment]
Are you in the TV or Desktop layout?

**Comment by distributorofpain** [comment]
TV layout.  

If i open the web client on a different PC after this happens, it does show the episode in the "Continue Watching" area.

I should note that i recently rebooted the server and upgraded to Version 1.18.1.1973 this past weekend.  The issue remains even with the 1.18.1.1973 version.

**Comment by mseeley** [comment]
We weren't able to reproduce this on 2.47. Please let us know if this issue is still reproducible for you.

**Comment by distributorofpain** [comment]
Quick follow-up ( was on vacation out of the country when you commented ).  I upgraded to plex server 1.18.2.2058 ( windows ).  I havent had the issue since upgrading to this.  The PMP client upgraded Saturday when i got back.  I used it all Saturday and Sunday, the issue did not reappear.
