### ISSUE TITLE
When selecting an on deck episode, the season screen does not advance to that episode for long TV shows with over 50 episodes

### ISSUE THREAD

**Issue by distributorofpain** [plexinc/plex-media-player#914]
### Test environment

**PMS Version: Version 1.17.0.1709
**PMP Version: 2.44.0.1018-8f77cbb9
**Platform:  Windows 10 1903 (client and Server )

### Steps to reproduce
1.  Select an on deck episode for a TV show with more than 50 episodes in that season ( it seems only anime does this ):  One Piece, Black Clover, Baruto are examples of shows with over 50 episodes in the season.

### Current behavior
1.  When selecting an on deck TV show for playback and the there are more than 50 episodes in the current season, the PMP when going to the season show listing, will load the show but stay on the 1st episode rather than automatically selecting the latest episode.

### Expected behavior
1.  Just like shows with fewer than 50 episodes, the player should automatically select the latest episode for playback rather than requiring the user to scroll through 50+ episodes using the right arrow on the keyboard.

**Comment by distributorofpain** [comment]
I should note that this is not a new bug, i have posted on the forums about it before.  its not a show stopper but when you have 120+ episodes in a season, its a pain to scroll over.  BTW: If you hold the right arrow too long, it will scroll over to the last episode, then refresh the list and place the selection BACK on the first episode, thus forcing you to then scroll over again.

**Comment by mseeley** [comment]
> I should note that this is not a new bug, i have posted on the forums about it before. its not a show stopper but when you have 120+ episodes in a season, its a pain to scroll over.

You're right on all of this. I've added a link to this issue in our tracking issue for On Deck improvements for large shows. We'll update this issue if/when we have a good fix for this.

> BTW: If you hold the right arrow too long, it will scroll over to the last episode, then refresh the list and place the selection BACK on the first episode, thus forcing you to then scroll over again.

That's strange behavior and definitely doesn't sound right. We're working on some bigger changes to these screens and will make sure this issue doesn't persist.

**Comment by distributorofpain** [comment]
I know you guys closed this pending updates, but my irritation with the problem is growing rapidly.   Baruto is up to 136 episodes now and if i try to scroll over by holding down the right arrow key, when the highlighted episode hits the last episode in the list ( after scrolling for 10-15 seconds ), it will be bounce all the way back to episode one.  I feel like i am rolling the dice each time to get it so it snaps to the last episode.  Its very frustrating when this process has to be repeated 5-6 times to get to the last episode without being snapped back to episode one.

Would be nice if the end button could be used as a quick work around to get to the last episode.

**Comment by distributorofpain** [comment]
This is still occurring.  How about a play most recent unplayed episode button?  This is painful.

No, i dont want to use my plex server to encode everything being watched.  I still dont like the fire stick client or the web client for playing things as neither can properly page forward through video files to skip intros.

**Comment by mseeley** [comment]
Heard your comments. This definitely an old bug that is frustrating for users watching series with many episodes. We're aware of the issue and are actively discussing.

**Comment by distributorofpain** [comment]
I found a work around for now while i was changing my library agent setups from TVDB to TMDB due to the upcoming change at TVDB.  There is an episode ordering selection under each library that is of the TV variety, i was able to change the default library sorting to newest episode first.  Now the last episode is the first one in the list and i can just click it. 

Its set for the entire anime library, so hopefully those who do this can live with it.
