### ISSUE TITLE
Can I use an external shader with PMP?

### ISSUE THREAD

**Issue by rosystain** [plexinc/plex-media-player#917]
I created the mpv.conf with the option blow.
`glsl-shaders="~~/shaders/Anime4K_Adaptive.glsl"`
It works with mpv.

BUT when I do the same thing to PMP, nothing changed.
`2019-11-06 11:46:19 [ ERROR ] PlayerComponent.cpp @ 600 - cplayer: Error parsing option glsl-shaders (option not found) `
`2019-11-06 11:46:19 [ ERROR ] PlayerComponent.cpp @ 600 - cplayer: C:/Users/chock/AppData/Local/PlexMediaPlayer/mpv.conf:7: setting option glsl-shaders='~~/shaders/Anime4K_Adaptive.glsl' failed. `

**Comment by gbooker** [comment]
The libmpv is too older to support that option.  You can try the [forum preview](https://forums.plex.tv/t/plex-media-player-3-0-windows-and-mac-forum-preview/476401) which uses a newer version to see if that accomplishes what you want.

**Comment by mseeley** [comment]
Also, watch out for the double tilde. If it isn't an MPV ism it should be a single tilde.
