### ISSUE TITLE
[BUG] When screen in defined in plex.ini is not present plex window doesn't appear and task bar shows it as white window

### ISSUE THREAD

**Issue by SpacePotatoBear** [plexinc/plex-media-player#918]
### Test environment

**PMS Version: 1.18.1.2019 
**PMP Version: 1.3.1.916-1cb2c34d

**Platform (Windows):**

### Steps to reproduce
1. Have 2 or more monitors
2. put plex on auxiliary monitor maximized
3. check plex.ini that said monitor is the one in ui.screen
4. disconnect said monitor.
5. restart plex media player

### Current behavior
1. Plex launches but no window appears
2. previewing it from win-tab or task bar shows blank/white window
3. unable to bring window to front to

### Expected behavior
1. plex would launch and default to primary display

### Work around
1. remove screen= from plex.ini

[Logs.zip](https://github.com/plexinc/plex-media-player/files/3846773/Logs.zip)

**Comment by mseeley** [comment]
Thank for filing @SpacePotatoBear. We're aware of the issue and will address.
