### ISSUE TITLE
XBox 360 no longer plays video after server version 1.18.1.1944

### ISSUE THREAD

**Issue by rtaft** [plexinc/plex-media-player#919]
### Steps to reproduce
1. Upgrade to any version of plex media server after 1.18.1.1944
2. Attempt to play movies on XBox 360

### Current behavior
1. After selecting video to play, it spins for a few seconds, then displays that it cannot communicate with the server.

### Expected behavior
1. That is plays normally.

The advice in the forums is to downgrade to 1.18.1.1944 to get it working again.

https://forums.plex.tv/t/xbox-360-app-cannot-communicate-with-server/486236/4
https://forums.plex.tv/t/an-xbox-360-problem/489685

**Comment by mseeley** [comment]
Will you please link to the forum advice you referenced?

**Comment by rtaft** [comment]
@mseeley updated

**Comment by mseeley** [comment]
Thanks for the update. Upgrading to a more recent device is the best path forward.

From: https://forums.plex.tv/t/plex-for-xbox-360-status-update/210836
> The current Xbox 360 app is provided “as-is”
> There will be no future app updates
> It is not possible to add features or fix issues with the app
