### ISSUE TITLE
Plex for Mac have issues with Plex Pass

### ISSUE THREAD

**Issue by aavanian** [plexinc/plex-media-player#920]
PMP for Mac doesn't enable the sharing functionalities although the Plex Pass is recognised (in the account section of settings).
PMP for Windows and PMP for Web behave normally.

All observations made with the same Plex account.
Clearing the Plex preferences and cache from the client computer didn't help.
Log out / Log in again didn't help.
Restarting Client or Server (both the Plex apps and the systems) didn't help.

### Test environment

**PMS Version:** 1.16.5.1552
**PMP Version:** 1.4.0.924-60046db9
**Platform:** OS X Catalina 10.15.1

### Steps to reproduce
1. Log-in to PMP Mac
2. Settings -> Account shows Lifetime Plex Pass
3. Settings -> Users & Sharing shows `Adding additional users to your home requires a Plex Pass. Learn More`
4. Edit a media item and going to Sharing tab shows the same

on Windows and Web, item 3. and 4. behave as expected (allow adding users and editing the Sharing tab of media items)

### Current behavior
1. Plex Pass is not enabling relevant functionalities although the Player 'sees' the Plex Pass

### Expected behavior
1. All Pass functionalities enabled

**Comment by TehRiehlDeal** [comment]
Same issue happening on Windows PMP. Not present on web version of player.

**Comment by mseeley** [comment]
Hi @aavanian, @TehRiehlDeal. Thanks for your messages.

I just fixed the issue and will patch up our Desktop app later this week. A workaround is to enable the Automatically Sign In setting.

It won't be suitable to all situations but, at a minimum, it does retain the expected Plex Pass features at startup. Switching users will again lose the features.

Apologies again, we'll get the fix out.

**Comment by mseeley** [comment]
Fix is available in 1.4.1.
