### ISSUE TITLE
GUI Translation : Missing translations

### ISSUE THREAD

**Issue by Ribero** [plexinc/plex-media-player#922]
## Test environment

**PMS Version:** Version 1.18.2.2058
**PMP Version:** 2.45.0.1028-45edbf41
**Platform:** macOS 10.14.6

There are fields that are not translated (but available in Transifex) for the french localization (and probably other languages).
Majority of missing translations are visible in the "TV Layout" but some are also present in the "New Plex Experience Layout": 

## TV Layout 

Missing translation are presented in "English" -> "existing french translation in Transifex" or proposed translation if the original english field is missing in Transifex:

```
English                -> French
```
_the text translations proposed above take precedence over the one presented in the screenshots._

### Main menu: Movie, Music, TV Shows, Video..._
```
Recommended            -> Recommandé
Library                -> Bibliothèque
Collections            -> Sagas
```

<img width="1670" alt="Capture d’écran 2019-11-25 à 10 39 27" src="https://user-images.githubusercontent.com/2266264/69534823-d6a84480-0f7a-11ea-9a28-a4d165a9a434.png">

### Filter value for Library for Music, Movies... in "Library" sub-menu 
```
Unmatched              -> Orphelins
Collection             -> Saga
```

<img width="497" alt="Capture d’écran 2019-11-25 à 10 40 02" src="https://user-images.githubusercontent.com/2266264/69534842-e031ac80-0f7a-11ea-87a3-9664d1fe703f.png">

```
Folders                -> Dossiers
```

<img width="1058" alt="Capture d’écran 2019-11-25 à 10 41 54" src="https://user-images.githubusercontent.com/2266264/69534856-e58ef700-0f7a-11ea-96ab-bc6139545495.png">

### Details of a movie:
```
Select Audio Track     -> Sélectionner une piste audio
Select Subtitles Track -> Sélectionner les sous-titres
```
<img width="1155" alt="Capture d’écran 2019-11-25 à 10 40 40" src="https://user-images.githubusercontent.com/2266264/69534874-ede73200-0f7a-11ea-9419-fcff45e224e8.png">

### Home Screen configuration
```
Edit Home Screen        -> Organiser l’écran d’Accueil
Reset All Customization -> Réinitialiser aux valeurs par défaut
Manage Home Screen      -> Configuration de l'écran d'accueil
```

![Capture d’écran 2019-12-05 à 15 07 46](https://user-images.githubusercontent.com/2266264/70243025-230d3480-1772-11ea-8b5c-7128caf5a791.png)

```
Edit Home Screen        -> Organiser l’écran d’Accueil
Reset All Customization -> Réinitialiser aux valeurs par défaut
Manage Home Screen      -> Configuration de l'écran d'accueil
1                       -> Configurer l'écran d'accueil
2                       -> Actuellement Plex gère automatiquement votre écran d'accueil.

                           Plex utilise les sources épinglées et d'autres informations pour constituer un
                           contenu personnalisé de votre écran d'accueil. Si vous désactivez ce réglage,
                           Plex ne sera plus en mesure de vous suggérer automatiquement le contenu de
                           votre écran d'accueil.
3                       -> Conserver (personnalisation automatique)
4                       -> Désactiver (personnalisation manuelle)
```

![Capture d’écran 2019-12-05 à 15 07 54](https://user-images.githubusercontent.com/2266264/70244818-6917c780-1775-11ea-91b9-1089017dc1a2.png)

## New Plex Experience Layout (Not TV Layout)

###Filter value for Movies, Music, Videos, TV SHows... in the "Library" sub-menu: 
```
Unmatched              -> Orphelins
```
<img width="891" alt="Capture d’écran 2019-11-25 à 11 55 21" src="https://user-images.githubusercontent.com/2266264/69534888-f5a6d680-0f7a-11ea-816e-972a5562b1a0.png">

**Comment by mseeley** [comment]
Hi there @Ribero. The translations are all provided by community members. If you're feeling adventurous you can submit translations for Plex Media Player / Plex Web here: https://forums.plex.tv/t/want-to-help-translate-localize-the-plex-client-apps/155618.

We'll be updating the Desktop layout over the coming weeks. At that time I'm hoping that some of the issues above are addressed.

**Comment by Ribero** [comment]
Hi @mseeley,

1/ I'm already registered in transifex and I have done my job there
2/ Most of the fields that are missing a correct translation are already translated in transifex and already taken into account in the webplayer... 

So, the legacy player is missing some code to take into account the already translated fields... I do not think I can do more in Transifex

May be you can reopen this issue while not solved ?

**Comment by mseeley** [comment]
Thanks a lot for participating in Transifex, much appreciated. 😄 

I'll leave the issue closed because there are no code changes to apply. The issues will be resolved as update translations before our releases. The release within PMP's Desktop layout is quite old. One of the ways that manifests is through its translations.

**Comment by Ribero** [comment]
@mseeley 

Ok 

But to be honest I'm not sure to really understand the release process. The translation problem in TV Layout is prensent since few release and I do not see what is going to change soon on this point if no one advertise it. 

I understand that for english only speaking users it's not a big deal to have non translated or partially translated product. But for people that are not native english speaker, and especially for older (senior) basic users, this can be a real issue.
The other point is that translation done in transifex sometimes stays unused during many release even if it has required an important amount of work to translate it correctly. It can be perceived as a bit demotivating. 

Don't misunderstand my intention. It is not a criticism but just a friendly reminder that having software properly translated is not just a futile option but an essential point in user's perception of the quality and ergonomics of a product. 
As a Plex Pass customer I am happy to support the project and to participate in its translation. I am even more pleased when I see that the hard work of translators is taken into account quite quickly. At the end, All this in order to provide everyone (english and non english users) with the best possible user experience.

**Comment by mseeley** [comment]
Strings for all the images below are controlled by Plex Media Server. I'll look into why these are not translated by PMS:

![image](https://user-images.githubusercontent.com/30019/76254666-f80f0280-61f0-11ea-8951-a8a12a1451f8.png)
![image](https://user-images.githubusercontent.com/30019/76254720-0a893c00-61f1-11ea-8de9-0b00cb96e1af.png)
![image](https://user-images.githubusercontent.com/30019/76254760-1b39b200-61f1-11ea-8274-95ebed122cb5.png)
![image](https://user-images.githubusercontent.com/30019/76255630-9485d480-61f2-11ea-959b-6fa426246c65.png)

---
---
---

We're expecting a parametrizable translation where we can supply a `Select {trackType} Track...`

![image](https://user-images.githubusercontent.com/30019/76254785-242a8380-61f1-11ea-9a3f-d21c115f5516.png)

Regardless the component displaying the translation itself is buggy resulting in `Audio` and `Subtitles` to display regardless of language. I've filed a bug to fix this.

![image](https://user-images.githubusercontent.com/30019/76255460-47a1fe00-61f2-11ea-8b19-d012b459399c.png)

---
---
---

![image](https://user-images.githubusercontent.com/30019/76255614-8b950300-61f2-11ea-8692-37738f486a51.png)
![image](https://user-images.githubusercontent.com/30019/76255770-dadb3380-61f2-11ea-8269-9498d44579af.png)

Automatically updated:

![image](https://user-images.githubusercontent.com/30019/76255662-a8c9d180-61f2-11ea-9096-df7bd48a2bec.png)
![image](https://user-images.githubusercontent.com/30019/76255700-b8491a80-61f2-11ea-8418-3e8d0d564395.png)

**Comment by mseeley** [comment]
I've filed follow-up work for:

- `Select Audio Track...`, `Select Subtitles Track...`, 
- the `Library`, `Recommended`, and `Collection` headers
- the `Unmatched` and `In Progress` filters

**Comment by Ribero** [comment]
Thanks for the detailed review !
