### ISSUE TITLE
Avoid PMP+CEC turn on TV

### ISSUE THREAD

**Issue by Nyaran** [plexinc/plex-media-player#923]
Hi,

I recently installed plex-media-player on Fedora 31 and I have Pulse-Eight CEC-USB to be able to use my TV remote to contol Plex.

The part to control Plex is working fine, but any time I restart the PC, the TV is turned on, and if is on, the channel is changed to PC, but I don't always want this.

Is there any hidden config to avoid ths? On Raspbian, just needed to add hdmi_ignore_cec_init to config.txt, but I don't found anything like this with Fedora.

Thanks,

Regards

### Test environment

**PMS Version:** 4.8.4
**PMP Version:** 2.44 (rpmfusion)
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Fedora 31

### Steps to reproduce
1. Restart the PC with plex-media-player start at boot (via systemctl)

### Current behavior
1. TV is turned on when Plex starts

### Expected behavior
1. Have an option to disable TV boot/change when PMP starts.

**Comment by mseeley** [comment]
> Is there any hidden config to avoid ths? On Raspbian, just needed to add hdmi_ignore_cec_init to config.txt, but I don't found anything like this with Fedora.

Hi @Nyaran, no, I'm unsure if there is a way to accomplish this in Fedora.

**Comment by Nyaran** [comment]
Sorry to write on closed post, but I finally found the way.

Is not a Fedora only solutión, can be applied to any Linux version (I guess)

1. Locate plex-media-player config folder (`/var/lib/plex-media-player/.local/share/plexmediaplayer`)
2. Open, with vi, nano, or whatelse the file `plexmediaplayer.conf`.
3. Locate section `cec`, and modify the property `activatesource` to `false`.
4. Restart.

Now when I restart the system, the TV do not change to the PC HDMI port and is not turned on.

I think the GUI should have an option to allow this, or at least add it to the Wiki.
