### ISSUE TITLE
Plex Player (new format) - Playback error - Not enough bandwidth

### ISSUE THREAD

**Issue by brodyriver** [plexinc/plex-media-player#924]
When I play my music using the new Plex Windows Client I occasionally get the error "Playback Error" "Not enough bandwidth for any playback of this item.  cannot convert to below minimum bandwidth of 101 kbs."

I can successfully play the identical song from the same PC in the same environment from the same Plex server at the same time using the old Plex Media Player.

Both have identical client quality setting 
![2019-12-06 13_06_57-Clipboard](https://user-images.githubusercontent.com/45320579/70289585-519a1680-1829-11ea-9697-e0cb5cc25c0e.png)

**Comment by mseeley** [comment]
Thanks for filing. I'm sorry you're running into issues. Without logs or steps to reproduce we aren't able to look into your issue report.
