### ISSUE TITLE
Playlist Sorting

### ISSUE THREAD

**Issue by vimeso** [plexinc/plex-media-player#925]
Just an easy one. Playlists are not sorted on new Plex for Windows. And there is no way to set it. Would be nice to correct this. Thank you.

![plex-scr-191208_01](https://user-images.githubusercontent.com/47522663/70389865-7925e600-19c5-11ea-967e-26e71bca0c07.png)

btw: And it also would be nice to have the possibiltiy to change the background. It's a matter of taste, but as a photographer and image designer I should have a certain significance, the current background is very ugly.

**Comment by mseeley** [comment]
The smart playlists and regular playlists are each sorted alphabetically. I'll discuss this internally to see if there are intentions to sort smart and regular playlists in a single combined list.

Thanks for raising.

**Comment by vimeso** [comment]
Thanks for your answer and the readiness to discuss ist.

Freundliche Grüsse
Markus Hiltbrunner

VIMESO gmbh<http://www.vimeso.ch/>
www.vimeso.ch<http://www.vimeso.ch/> | 031 351 53 30

In unserem Internet-Blog<http://www.vimeso.ch/blog-11.html> finden Sie
aktuelle und spannende Informationen.

Von: Matt Seeley <notifications@github.com>
Gesendet: Dienstag, 10. Dezember 2019 21:33
An: plexinc/plex-media-player <plex-media-player@noreply.github.com>
Cc: Markus Hiltbrunner <him@vimeso.ch>; Author <author@noreply.github.com>
Betreff: Re: [plexinc/plex-media-player] Playlist Sorting (#925)


Closed #925<https://github.com/plexinc/plex-media-player/issues/925>.
