### ISSUE TITLE
version 2.47.0 does not compile against QT 5.14

### ISSUE THREAD

**Issue by boennhoff** [plexinc/plex-media-player#931]
### Test environment

**PMP Version:** 2.47.0
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Arch Linux

### Steps to reproduce
try to install package `aur/plex-media-player`. have a look on [the package page](https://aur.archlinux.org/packages/plex-media-player) for more details and background.

### Current behavior
compilation/installation fails, even if compilation issue is fixed manually, the player does not properly playback files anymore:
* UI parts are frozen
* white screen
* temporarily fixed by switching to fullscreen and back

### Expected behavior
compilation against QT 5.14 does work and does not introduce regressions

**Comment by boennhoff** [comment]
![image](https://user-images.githubusercontent.com/6317864/71646907-61a0fb00-2cee-11ea-96f2-339bdd6374ea.png)

![image](https://user-images.githubusercontent.com/6317864/71646931-c3616500-2cee-11ea-8caf-e225b474bec3.png)

**Comment by boennhoff** [comment]
Compiling and running against QT 5.13.2 works flawlessly.

**Comment by mseeley** [comment]
From our Linux build instructions:

> Plex Media Player officially requires Qt 5.9.5. Our users have indicated that Qt 5.10 and Qt 5.11 also builds correctly. However, Qt 5.11.0 and 5.11.1 versions are incompatible and should be avoided. Qt 5.12 may work for you. Please consider building PMP within a dedicated VM or Docker container if your system has a Qt version installed newer than 5.9.5. Downgrading a system Qt will cause issues in other applications depending on a newer Qt version.

With this in mind I'm closing this issue due to an unsupported Qt version.

I definitely understand how this can be frustrating. Although we are considering updating our dependencies any changes will be made separately of this issue.
