### ISSUE TITLE
Subtitles does not working on Downloaded Media to Watch offline

### ISSUE THREAD

**Issue by plvsouza** [plexinc/plex-media-player#932]
I downloaded some medias to play offline and even selecting MOV_TEXT or External SRT subtitles aren't showing.

### Test environment

**PMS Version:1.18.3.2156-349e9837e**
**PMP Version:1.4.1.940-574c2fa7**
**Platform (Windows/macOS):**

### Steps to reproduce
1. Select a Movie or TV Show from Library and Download to use offline

### Current behavior
1. Selecting Subtitle MOV_TEXT or External SRT are not showing when playing offline

### Expected behavior
1. When selecting subtitles, should be displayed just like when I'm using online

**Comment by mseeley** [comment]
Our 1.5 release addressed issues selecting subtitles. I've verified playback of a downloaded video with external (and embedded) subs works correctly in 1.5.

You can install it early from: https://forums.plex.tv/t/plex-for-windows-and-plex-for-mac-forum-preview-releases/453210/9

Or, hang tight. It's public release is coming soon.
