### ISSUE TITLE
Sorting order and accented letters

### ISSUE THREAD

**Issue by cortig** [plexinc/plex-media-player#936]
The Plex player (at least on mac OS X) has an issue with the sorting order.
Accented first letters (À É, Ô…) are at the end of the alphabet. Instead the accent should simply be ignored and the files should be sorted as if the letters were not accented. 

### Test environment

**PMS Version:**
PMP Version: 2.48.0.1038-11b21f57
Platform macOS: 10.15.2

### Steps to reproduce
1. add movies that have an accented letter at the beginning of the file name

### Current behavior
1. the movies are sorted last (e.g.”À fond”)

### Expected behavior
1. the accent should be ignored and the movie should be sorted as if the name didn’t have an accent on the first letter. ((e.g. "À fond" should be sorted as "A fond")

**Comment by OttoKerner** [comment]
Are you saying that this is different in other Plex clients?
Because only then this is a client issue. 

If however this sorting behaviour is the same in all types of clients, then it is a Plex server issue.

**Comment by cortig** [comment]
OttoKerner you are absolutely right… I (stupidly) didn’t think about that possibility and the issue is also there on my web browser. Obviously a Plex server issue that I’ll need to repost in the appropriate section.
