### ISSUE TITLE
Plex Media Player - Windows 10 causing errors to be logged on PMS

### ISSUE THREAD

**Issue by sykogee** [plexinc/plex-media-player#937]
PMP (Version 1.5.0.951-eb39ca04) on Windows 10 (1909) - Have been noticing a huge number of errors in the PMS log every 2 minutes:

Jan 19, 2020 21:29:25.328 [0x7fea937fe700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone

The device is blank - so PMS cannot load a profile.xml for it

Add device to PMP to be recognised by PMS

**Comment by mseeley** [comment]
@sykogee can you share a snippet of logs where this is happening?

**Comment by sykogee** [comment]
Hi

It appears it only occurs when using the PMP for Windows 10 – the other PMP doesn’t cause the errors

Running the PMP for Windows 10 ( 1.6.5.1097-3bb9dc68
I see the following in the logs

Apr 07, 2020 09:37:33.117 [0x7f64737fe700] ERROR - Unknown metadata type: folder
#265
Apr 07, 2020 09:37:39.573 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#266
Apr 07, 2020 09:37:49.849 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#267
Apr 07, 2020 09:37:59.849 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#268
Apr 07, 2020 09:38:09.850 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#269
Apr 07, 2020 09:38:19.850 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#270
Apr 07, 2020 09:38:29.848 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#271
Apr 07, 2020 09:38:39.847 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#272
Apr 07, 2020 09:38:49.852 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#273
Apr 07, 2020 09:38:59.849 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#274
Apr 07, 2020 09:39:09.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#275
Apr 07, 2020 09:39:19.852 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#276
Apr 07, 2020 09:39:29.851 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#277
Apr 07, 2020 09:39:39.851 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#278
Apr 07, 2020 09:39:49.849 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#279
Apr 07, 2020 09:39:59.848 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#280
Apr 07, 2020 09:40:09.849 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#281
Apr 07, 2020 09:40:19.866 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#282
Apr 07, 2020 09:40:29.847 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#283
Apr 07, 2020 09:40:39.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#284
Apr 07, 2020 09:40:49.858 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#285
Apr 07, 2020 09:40:59.848 [0x7f6478910700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#286
Apr 07, 2020 09:41:09.852 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#287
Apr 07, 2020 09:41:19.850 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#288
Apr 07, 2020 09:41:29.850 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#289
Apr 07, 2020 09:41:39.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#290
Apr 07, 2020 09:41:49.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#291
Apr 07, 2020 09:41:59.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#292
Apr 07, 2020 09:42:09.855 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#293
Apr 07, 2020 09:42:19.858 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#294
Apr 07, 2020 09:42:29.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#295
Apr 07, 2020 09:42:39.852 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#296
Apr 07, 2020 09:42:49.848 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#297
Apr 07, 2020 09:42:59.854 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#298
Apr 07, 2020 09:43:09.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#299
Apr 07, 2020 09:43:19.851 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#300
Apr 07, 2020 09:43:29.849 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#301
Apr 07, 2020 09:43:39.848 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#302
Apr 07, 2020 09:43:49.849 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#303
Apr 07, 2020 09:43:59.859 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone
#304
Apr 07, 2020 09:44:09.854 [0x7f6433fff700] ERROR - Unable to find client profile for device; platform=windows, platformVersion=10, device=, model=standalone


Running PMP 4.29.2 – no errors occur

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mseeley** [comment]
I couldn't find the exact case that lead to the floody error logging above. Though I correct a bit of code that lead PMS to log that message. The fix should be in our 1.13 release.

**Comment by sykogee** [comment]
Thanks Matt

Yes I had started using Plex for Windows 1.12, had some problems with video stuttering (another issue) but the logs of the PMS filling up with the error message every 10 seconds, while Plex for Windows was running.
I have gone back to using PMP 2.58 in the mean time.
I will wait for 1.13 version to be released and I’ll do some testing

Thanks

Andy

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mseeley** [comment]
Closing this out as addressed in 1.13.0.
