### ISSUE TITLE
Scanning metadata on TV never stops.

### ISSUE THREAD

**Issue by dadrepus** [plexinc/plex-media-player#938]
<!--

### Test environment

**PMS Version:**3.104.2
**PMP Version:**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**mac (2011) Intel 10.11.6

### Steps to reproduce
1. After install and reboot application, the spinning indicating scanning in the tv category never completes.

### Current behavior= scanning never completes, only in tv category.
1.

### Expected behavior =expect all scanning to stop eventually.
1.

**Comment by dadrepus** [comment]
also settings not available, just get the spinning wheel of death.

**Comment by mseeley** [comment]
> Each filed issue must please:
>
>  - include a concise description of the issue and steps to reproduce.
>  - include a sample media file or media file information when applicable.
>    - Generating samples: https://support.plex.tv/articles/201035968-generating-sample-files-from-media/.
>    - Retrieving XML media information: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/. Please attach within zip.
>  - be accompanied by _clean_ logs.
>    - PMP logs can be found here: https://support.plex.tv/articles/207338748-plex-media-player-logs/
>    - Clean log instructions: Clear your logs; reproduce the issue; attach logs in a .zip file.
