### ISSUE TITLE
Media Center and PMP

### ISSUE THREAD

**Issue by jwaltrip4** [plexinc/plex-media-player#94]
Windows 8.1
Windows Media center
PMP (latest)

PMP Stops launching from MC after a few tries.

1.I have created a link in Media Center to load PMP
2.Select link, and PMP starts
3.Exit PMP and it drops to desktop, and then MC starts back up (this is a bit disconcerting, as PHT does not do that)
4.Start PMP
5.Rinse, repeat about 3-4 times

Issue: After about the 3rd or 4th time, PMP no longer starts. Desktop flashes by, and then MC comes back.

Exit MC
 Exit PMS (running on same machine)
 Kill PMPhelper.exe
 Now can start PMP from MC

**Comment by nitrobass24** [comment]
Same Issue here. Would be nice if there was builtin-in WMC integration options like we had with PHT. I can only guess that I have not made the correct settings in my custom menu/entry for WMC. 

Windows 7
Windows Media Center
PMP 1.03
