### ISSUE TITLE
Plex Player for Mac OS Version 1.18.7.2434

### ISSUE THREAD

**Issue by dkuntz01** [plexinc/plex-media-player#941]
### Mac OS Mojave

Plex Player Mac OS Version 1.18.7.2434

### Steps to reproduce
1. The Activity Dashboard under play history the dates are out of order. See screen shots.
![Screenshot 2020-02-19 06 46 36](https://user-images.githubusercontent.com/45402864/74832396-334e9d80-52e5-11ea-8e2c-0462f4b0706b.jpg)
![Screenshot 2020-02-19 06 46 17](https://user-images.githubusercontent.com/45402864/74832397-334e9d80-52e5-11ea-966a-9e2d017add0c.jpg)

### Current behavior
1.

### Expected behavior
1.

**Comment by mseeley** [comment]
Issue template was disregarded. Issue description is unclear (1.18.x is a PMS version).
