### ISSUE TITLE
Movies & TV not listed in Online Media Sources

### ISSUE THREAD

**Issue by hcrray** [plexinc/plex-media-player#942]
In Plex Media Player (Version 1.6.3.1009-57cf57c8) for Mac the "Movies & TV" is not listed in the "Online Media Sources" - however, it does appear in the Plex Media Server for Mac  "Online Media Sources".

Anyone have a suggestion as to why it might be missing?

Thank you.

**Comment by mseeley** [comment]
Hi there @hcrray. Movies & TV aren't yet supported by Plex Media Player or Plex for Windows|Mac.
