### ISSUE TITLE
PMP  "Playback error" on everything

### ISSUE THREAD

**Issue by scrollop** [plexinc/plex-media-player#946]
I upgraded PMP to the latest V3 (from 5d ago), which has a filename including 3.0.0.32 (though weirdly the version stated in the program is 4.24.1).

Now, on attempting to play any video:

Playback error; An error occurred trying to play "____".

### Test environment

**PMS Version:** 1.18.7.2457
**PMP Version:**.24.1
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**

### Steps to reproduce
1. Try and play anything

### Current behavior
1. Playback error; An error occurred trying to play "____".

### Expected behavior
1. To play the file as it was prior to the update.

**Comment by mseeley** [comment]
```
Each filed issue must please:

  - include a sample media file or media file information when applicable.
    - Generating samples: https://support.plex.tv/articles/201035968-generating-sample-files-from-media/.
    - Retrieving XML media information: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/. Please attach within zip.
  - be accompanied by _clean_ logs.
    - PMP logs can be found here: https://support.plex.tv/articles/207338748-plex-media-player-logs/
    - Clean log instructions: Clear your logs; reproduce the issue; attach logs in a .zip file.
```

**Comment by mseeley** [comment]
Please include requested information when opening an issue.
