### ISSUE TITLE
Advertise as player

### ISSUE THREAD

**Issue by etiennedemoulin** [plexinc/plex-media-player#949]
### Test environment

**PMS Version: *1.18.8.2527*
**PMP Version:*1.6.2.994-e05b79d6*
**Platform : macOS

### Steps to reproduce
0. 2 macintosh connected on the same Wi-Fi network.
1. Mark advertise as player on Plex Media Player n°1
2. Click on Shared Player on Plex Media Player n°2

### Current behavior
1. No other media player found

### Expected behavior
1. See Plex Media Player n°1

**Comment by mseeley** [comment]
The version number you shared was for Plex for Windows and Plex for Mac yet you mention Plex Media Player. These are different applications.

Plex for Windows/Mac require a LAN pms for receiving or sending commands. Do you have a local PMS setup?

**Comment by mseeley** [comment]
Close due to lack of feedback.
