### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [plexinc/plex-media-player#95]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [appendCommandLineArguments](https://github.com/plexinc/plex-media-player/blob/3917405e4f809a3afeabada805fa43f92a8fce8b/src/main.cpp#L137)
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [main](https://github.com/plexinc/plex-media-player/blob/53192cb022f478a438c4dfaf451c58981995ba17/external/qhttpserver/http-parser/contrib/parsertrace.c#L117)

**Comment by tru** [comment]
Yeah we would be happy to accept patches for both those cases.

**Comment by tru** [comment]
Actually that malloc should probably be replaced with new that should throw on allocation errors.

**Comment by wm4** [comment]
The whole ``appendCommandLineArguments`` could use a clean up. Currently, PMP will exhibit undefined behavior if you pass more than 15 args to it.

The fseek one is in an unused part of imported 3rd party code (looks like some sort of test program), so it's not important for us.
