### ISSUE TITLE
PMP - Windows 10 - Always stuck in full screen view

### ISSUE THREAD

**Issue by ClairelyClaire** [plexinc/plex-media-player#951]
### Test environment

**PMS Version:** 1.18.9.2571
**PMP Version:** 1.6.3.1009-57cf57c8
**Platform:** Windows 10

### Steps to reproduce
1. Launch PMP
2. Try to exit full screen view (F11 or Alt+Enter)
3. PMP will not exit full screen. The window flashes for a moment as if it tried to restore to windowed, but then jumps back to full screen.

### Current behavior
1. Always maximized

### Expected behavior
1. PMP should exit full screen.

Addendum:
I can't find the Plex config file mentioned in [this 2017 forum thread](https://forums.plex.tv/t/maximized-plex-media-player-app-is-stuck-maximized-and-cant-be-minimized-resized-or-moved/204775). There's also [this 2018 forum thread](https://forums.plex.tv/t/stuck-in-full-screen-mode-exit-full-screen-effectively-does-nothing/235789), so it sounds like this bug has been around for awhile.

**Comment by mseeley** [comment]
Hi @ClairelyClaire is this on an integrated or external monitor? I'll test both ways regardless.

Am I correct that the app was exited when fullscreen, then restored fullscreen at next launch, and now refuses to exit fullscreen?

**Comment by ClairelyClaire** [comment]
Yes - exiting and relaunching still ends up stuck in full screen.

This is on a desktop with external monitors.

**Comment by mseeley** [comment]
@ClairelyClaire, a fix for this will be released in 1.9.0. Thanks for reporting. :)

**Comment by ClairelyClaire** [comment]
Still broken in 1.9.0.1188-c009e512.

That said it seems the desktop version of the UWP is working again, so at least I have Plex without forced full screen.

**Comment by mseeley** [comment]
Curious, thansk for mentioning. What are the values of the `[ui]` section of your `plex.ini` (`%LOCALAPPDATA%\Plex\plex.ini`)?

Pre 1.9 we would save the window's dimensions when maximizing or entering fullscreen. Now we will only save window dimensions when not in either of those states.

Exiting and relaunching while in fullscreen should relaunch the app in fullscreen. Although now you should be able to exit fullscreen. The window should take the size of the last windowed size. If that last size was recorded when maximized/fullscreen in 1.8 then that'll still be the size we use. Nothing stops a user from having a !maximized window that is the size of the screen.
