### ISSUE TITLE
Slow playback startup due to codec downloading attempts

### ISSUE THREAD

**Issue by chainikdn** [plexinc/plex-media-player#954]
This line is the cause: https://github.com/plexinc/plex-media-player/blob/9949398a34d2138040cf38662fb4fddf4f34d93e/src/player/PlayerComponent.cpp#L1297

Newer mpv doesn't contain 'family' field anymore (see https://github.com/mpv-player/mpv/commit/8b3306924d1b80ed85907449ffa2549946e8b137) => the comparison is always true => Plex thinks there're no acceptable codecs and tries to load external decoders from https://plex.tv/api/codecs

**Comment by mseeley** [comment]
Paging Dr @rcombs.

**Comment by mseeley** [comment]
@chainikdn are you using a different MPV version in your build? If so, which?
