### ISSUE TITLE
Touchscreen not working

### ISSUE THREAD

**Issue by MatthK** [plexinc/plex-media-player#956]
PMS Version: 1.18.5.2309
Plex for Windows Version: 1.8.2.1192-89432618
Plex Web Version: 4.31.2
Windows 10 using a touchscreen (independent of tablet mode on or off)
Firefox Version 74.0.1 (64-bit)

Steps to reproduce
1. Use the touchscreen instead of a mouse
2. Open PMP or use Plex Web
3. Select a show/movie
4. Try to select a subtitle
5. The windows opens and closes immediately making it impossible to make a selection
6. Alternatively, when you want to continue a show, you can't play it, as the windows asking if you want to continue from XX:XX or start from the beginning closes immediately

Current behavior
1. see above

Expected behavior
1. When making a selection, the window should stay open until you actually make a selection

**Comment by ssamulski** [comment]
I have downloaded the 3.104.2 Beta and the download buttons show properly on the version.

**Comment by mseeley** [comment]
Hi @MatthK I've added this issue to another tracking issue for touchscreen bug fixes/improvements.
