### ISSUE TITLE
PMP3 video not visible on Windows 10

### ISSUE THREAD

**Issue by fluffypony** [plexinc/plex-media-player#959]
### Test environment

**PMS Version: 1.19.2.2702**
**PMP Version: 3.0.0.32-d310c89b6**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): Windows 10 64-bit**

### Steps to reproduce
1. Play a video

### Current behavior
1. Can hear audio, but can't see video. Previous version of PMP3 (3.0.0.24?) worked fine.

### Expected behavior
1. That I can see the video, obvs

Attached [fresh logs](https://github.com/plexinc/plex-media-player/files/4532551/PlexMediaPlayer.txt) of starting PMP -> resuming a video -> exiting. I've tried various video settings (disabling GPU acceleration etc.) to no avail. Per the release notes on the forum, the only major change that I can spot that might affect this is the switch to Qt 5.14.1?

**Comment by fluffypony** [comment]
Bump

**Comment by fluffypony** [comment]
Bump

**Comment by mseeley** [comment]
It's been triaged internally but those changes won't display publicly.

We're hoping to be able to reproduce this before updating the PMP v3 beta.
