### ISSUE TITLE
PMP won't direct play .AVI files

### ISSUE THREAD

**Issue by jamespower1990** [plexinc/plex-media-player#96]
Previously I had no issues with PHT direct playing .AVI files as my media server is running off of a low power Synology NAS, however when attempting to migrate to PMP it shows an error screen when attempting to play any .AVI file, stating that the server isnt powerful enough to covert the video.

**Comment by NedtheNerd** [comment]
@jamespower1990 Which client?

**Comment by NedtheNerd** [comment]
Can confirm RPi embedded client direct plays .avi files OK.

**Comment by atrus05** [comment]
Confirmed working in PMP for Mac as well. So we need more info than just the container (avi), and we also need a log that shows what is happening when you play your avi files.

**Comment by jamespower1990** [comment]
Hi guys, first let me apologies, I'm extremely novice with this sort of thing - whats the easiest way of me showing you the logs?

**Comment by NedtheNerd** [comment]
Pop the on Dropbox or similar and post the share link in here.

Can you also verify which client version and platform.

**Comment by jamespower1990** [comment]
Sorry for the delay.

I've included each log in this folder.

https://drive.google.com/folderview?id=0Bx1mYJppdIkGcTgweWswRV9Xak0&usp=sharing

**Comment by jamespower1990** [comment]
The Client is Plex Media Server Version 0.9.12.18 on a Synology DS413 PowerPC NAS.

**Comment by wm4** [comment]
What error does it show? I looked at the PMP log, and I see no playback attempt.

**Comment by jamespower1990** [comment]
![image](https://cloud.githubusercontent.com/assets/11541553/10945130/63c04054-8314-11e5-8e03-b8f0c19becbb.png)

**Comment by tru** [comment]
What is your local and remote quality set to? It seems like it request a transcode but that should not be needed.

**Comment by mseeley** [comment]
> What error does it show? I looked at the PMP log, and I see no playback attempt.

Right. This error gets displayed when the video travels through the UI media decision engine (MDE), is flagged as requiring transcoding, yet the server is incapable of transcoding.

The media analysis for that video is bad. The UI's media decision engine is presented empty `container` information. We always require transcoding when there is no container information. From `PlexMediaPlayer.log`

```
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Starting analysis of undefined 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Analyzing direct play 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Direct play failed; unsupported container: undefined 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Analyzing video direct stream 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Analyzing audio direct stream 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Analyzing subtitles 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Subtitle codec: srt 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Burn level: never 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Analyzing playability 
2015-11-01 22:03:41 [ INFO  ] JS: MDE: Unable to play; server unable to transcode video 
2015-11-01 22:03:41 [ INFO  ] JS: canPlay: false 
2015-11-01 22:03:41 [ INFO  ] JS: canDirectPlay: false 
2015-11-01 22:03:41 [ INFO  ] JS: useSoftSubtitles: true 
2015-11-01 22:03:41 [ INFO  ] JS: videoResolution: 360 
2015-11-01 22:03:41 [ INFO  ] JS: PDE: Unable to play item; This server is not powerful enough to convert video. 
2015-11-01 22:03:41 [ INFO  ] JS: This server is not powerful enough to convert video. 
```

We had similar issues recently with channel music without container information requiring transcoding. We could look to change MDE behavior to optimistically choose direct play when the container isn't present. Although we could be trading bugs if MPV is somehow also unable to determine how to decode the file.

The XML media info will help us understand what's happening.

@jamespower1990 please post the [XML media information](https://support.plex.tv/hc/en-us/articles/201998867-Investigate-Media-Information-and-Formats) for that video. I like [making a new gist](https://gist.github.com/) then dropping the URL into an issue. Thanks!

**Comment by mseeley** [comment]
I wonder if this is related: https://github.com/plexinc/plex-media-server-issues/issues/406#issuecomment-137558100.

AVI :heavy_check_mark:
wonky media analysis: :heavy_check_mark:
Synology NAS :heavy_check_mark:.

**Comment by mikedm139** [comment]
I have run now run into the failure to play AVI files as well. Except rather than display an error message, PMP reboots to the splash screen. This is with PMP-OE 1.0.2.72 running on an Intel NUC 2820. PMS 
[Gist with log of attempted playback.](https://gist.github.com/anonymous/148c652d54e296b7bfc2)
This is the XML of the item.
```XML
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="4" librarySectionTitle="TV" librarySectionUUID="5671d1ed3337a9cc5c407d5aa247337458e7d31e" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1444346776">
<Video ratingKey="139883" key="/library/metadata/139883" parentRatingKey="139881" grandparentRatingKey="139880" guid="com.plexapp.agents.thetvdb://77996/1/2?lang=en" type="episode" title="The Invitation" titleSort="Invitation" grandparentKey="/library/metadata/139880" parentKey="/library/metadata/139881" grandparentTitle="Daria" contentRating="TV-PG" summary="After Daria helps dimwitted cheerleader Brittany in art class, Brittany invites her to her party. Daria doesn't want to go at first, but then decides to after seeing it as a good chance to embarrass Quinn, who is also attending." index="2" parentIndex="1" rating="7.0" year="1997" thumb="/library/metadata/139883/thumb/1441606056" art="/library/metadata/139880/art/1441606060" parentThumb="/library/metadata/139881/thumb/1441606059" grandparentThumb="/library/metadata/139880/thumb/1441606060" grandparentArt="/library/metadata/139880/art/1441606060" grandparentTheme="/library/metadata/139880/theme/1441606060" duration="1328828" originallyAvailableAt="1997-03-03" addedAt="1441594117" updatedAt="1441606056" chapterSource="">
<Media videoResolution="sd" id="186117" duration="1328828" bitrate="1104" width="512" height="384" aspectRatio="1.33" audioChannels="2" audioCodec="mp3" videoCodec="mpeg4" container="avi" videoFrameRate="24p" videoProfile="advanced simple" title="Original">
<Part accessible="1" exists="1" id="227220" key="/library/parts/227220/file.avi" duration="1328828" file="/Media/Video/TV/Daria/Season 01/Daria - S01E02 - The Invitation.avi" size="183332864" container="avi" indexes="sd" videoProfile="advanced simple">
<Stream id="695861" streamType="1" codec="mpeg4" index="0" bitrate="952" bitDepth="8" bvop="1" chromaSubsampling="4:2:0" codecID="XVID" duration="1328828" frameRate="23.976" gmc="0" height="384" level="5" pixelFormat="yuv420p" profile="asp" qpel="0" scanType="progressive" width="512"/>
<Stream id="695862" streamType="2" selected="1" codec="mp3" index="1" channels="2" bitrate="139" audioChannelLayout="stereo" bitrateMode="vbr" codecID="55" duration="1328808" samplingRate="48000" streamIdentifier="1"/>
<Stream id="695863" key="/library/streams/695863" streamType="3" codec="srt" language="English" languageCode="eng" format=""/>
</Part>
</Media>
<Extras size="0"></Extras>
</Video>
</MediaContainer>
```

This is the [XML of another item AVI file](https://gist.github.com/mikedm139/28d2c02cb8110d418a84) which caused the same behaviour when attempted to playback remotely from a friend's server.

Both servers are more than capable of transcoding when necessary. My PMS is running on Ubuntu 14.04 with a quadcore Xeon processor.

**Comment by wm4** [comment]
Maybe the player crashes. Reason yet unknown.

**Comment by jamespower1990** [comment]
This is the XML for the file requested, thats bare in mind, I have a two year old son.

`<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="2" librarySectionTitle="TV Shows" librarySectionUUID="4d3c23ca-fd63-457e-ba12-f4c2237cd5d8" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1446845086">
<Video ratingKey="30372" key="/library/metadata/30372" parentRatingKey="30371" grandparentRatingKey="30268" guid="com.plexapp.agents.thetvdb://78949/1/1?lang=en" type="episode" title="Thomas & Gordon" grandparentKey="/library/metadata/30268" parentKey="/library/metadata/30371" grandparentTitle="Thomas The Tank Engine & Friends" contentRating="TV-Y" summary="Thomas the Tank Engine works at the Big Station, fetching coaches for the bigger engines. He keeps teasing Gordon the Big Engine, making him very cross. When the Shunter later accidentally forgets to uncouple Thomas from Gordon's coaches, Gordon decides to be really fast to tire Thomas out." index="1" parentIndex="1" rating="6.7" year="1984" thumb="/library/metadata/30372/thumb/1437123644" art="/library/metadata/30268/art/1437123852" parentThumb="/library/metadata/30371/thumb/1437123841" grandparentThumb="/library/metadata/30268/thumb/1437123852" grandparentArt="/library/metadata/30268/art/1437123852" grandparentTheme="/library/metadata/30268/theme/1437123852" originallyAvailableAt="1984-10-09" addedAt="1437122738" updatedAt="1437123644">
<Media id="46247">
<Part accessible="1" exists="1" id="46698" key="/library/parts/46698/file.avi" file="/volume1/music/TV Shows/Thomas And Friends/THOMAS THE TANK ENGINE & FRIENDS SERIES 01/Thomas The Tank Engine & Friends - S01E01 - 001 - Thomas & Gordon.avi" size="52439040">
<Stream id="95064" key="/library/streams/95064" streamType="3" selected="1" codec="srt" language="English" languageCode="eng" format=""/>
</Part>
</Media>
<Writer id="35994" tag="Rev. W. Awdry"/>
<Director id="35995" tag="David Mitton"/>
<Extras size="0"></Extras>
</Video>
</MediaContainer>`

**Comment by mikedm139** [comment]
Testing the same file today with build 1.0.2.92 works as expected.
