### ISSUE TITLE
Fake duplicate files

### ISSUE THREAD

**Issue by r0747249** [plexinc/plex-media-player#961]
**PMS Version: 1.19.1.2645**
**PMP Version: 1.9.0.1203-00f2b4d9**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**

### Steps to reproduce
1. Enable Scan my library automatically in Settings>Library
2. Add media to TV shows folder
3. Send message to API when library is detecting a change

### Current behavior
I use an application (Sonarr) that automatically uploads my series to my hard drive and sends a message to plex that there is new media available. The problem with that is that when I enable Scan my library automatically, plex will sometimes detect a change in my library and sometimes not. That's why I enabled an option in Sonarr that sends messages to the server and informs him of new files on my hard drive. This can lead to fake duplicates (see picture).
![Screenshot_2](https://user-images.githubusercontent.com/43750381/80605720-baca3280-8a33-11ea-95eb-644c2158d045.png)

### Expected behavior
It would be nice if Plex doesn't import new files with automatic scan if he already got a message from the API OR when he already detected a change and he is importing the files that he should ignore the message send by the API (OR before showing 2 files as duplicates you could check if they aren't the same file)

It's difficult to add clean logs because it happens randomly

**Comment by OttoKerner** [comment]
That's a server issue and has nothing to do with the player.
