### ISSUE TITLE
Please keep desktop mode 🙏🏼

### ISSUE THREAD

**Issue by dmp1ce** [plexinc/plex-media-player#963]
I am making a request to keep desktop mode because I see a notification saying that only TV mode will be supported.

The reasons I use desktop mode are:

1. the TV mode doesn't allow me to rank music
2. when I play flac music on Firefox, my sound will often crash and I have to restart the song

I was using Plex on Firefox for Arch Linux before finding this great project.

**Comment by mseeley** [comment]
Thanks for your feedback. We'll tread carefully and thoughtfully.
