### ISSUE TITLE
Libraries on PMP do not retain display order

### ISSUE THREAD

**Issue by ebernet** [plexinc/plex-media-player#965]
The desktop client does not retain display format and sorting uniquely for each share, unlike the smart TV versions I've tried. What I mean is that if I change a music video folder that I want to display in list view for viewstyle (rather than grid) and display as folders (rather than movies), and then switch back to the movies library, my movies library is now displayed in list view rather than grid view. I do not see this issue on the AppleTV. These settings should be saved uniquely for each share as they are on smart TV platforms.

### Test environment
iMac 5k 2017 Catalina 10.15.4 (19E287)
**PMS Version:**
1.19.3.2764-ef515a800
**PMP Version:**
1.10.0.1208-daa6b641
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**
macOS

### Steps to reproduce
1. Add music video shares that you want to display as folders in list view. Make sure you have a movies share as well. (Note the music video shares are NOT movies, they are the "Other Videos" category where I have concert videos sorted into a variety of folders, say by band name, or by year - these files are NOT tagged nor do they have metadata, so they are sorted by their names in list view)
2. Click on movies share and ensure you are displaying as movies in grid view.
3. Switch to a music video share, change the display mode to Folders (note that the options are Movies/Folders)
3. Click the grid/list icon and choose List View
4. switch back to Movies share

### Current behavior
1. The movies share is now displayed by list view rather than grid view

### Expected behavior
1. The Movies share should retain the display mode you chose, movies by grid, rather than switch to list view. Each share should retain its own display settings.

**Comment by duncanbeevers** [comment]
Currently that's intended behavior. We'll consider per-share view settings persistence in upcoming work.

**Comment by ebernet** [comment]
That's a shame. I hope you do address this in the future. Thanks for quick response.
