### ISSUE TITLE
add equal functionality to the desktop client

### ISSUE THREAD

**Issue by codeman101** [plexinc/plex-media-player#966]
I wanted to request that the plex player desktop client have the same functionality as the web client. For example I noticed that I can't right click on a media category and tell it to scan the directory to add more to my library like I can with the web client.

**Comment by mseeley** [comment]
Please provide more information. What is plex player desktop client?

**Comment by mseeley** [comment]
Too, please help me understand where you're right-clicking. Thanks.

**Comment by codeman101** [comment]
Sorry I meant when you left click on the three of say the movies category in the web client. The desktop client repo. On my arch based OS this installed it as a desktop app. https://aur.archlinux.org/packages/plex-media-player-git/

**Comment by mseeley** [comment]
I see. Here's the dots/action in the latest Plex Media Player download from our website (2.57.0.1074-f7d709d1):

![image](https://user-images.githubusercontent.com/30019/82249375-5fc68580-98e5-11ea-9570-fd4f29336cd8.png)

![image](https://user-images.githubusercontent.com/30019/82249405-694fed80-98e5-11ea-91cc-cb34cf786a6c.png)

Please follow-up with the Arch package maintainer directly. Our app includes the mentioned functionality. Perhaps their version from March does not.
