### ISSUE TITLE
PmP loading page requiring login

### ISSUE THREAD

**Issue by ProNoob333** [plexinc/plex-media-player#968]
Is this a feature of PMP now requiring login?  

My only options are to 

1. "sign in"
2. "sing up"
3. exit full screen 
     3a. exiting full screen> only option is to sing in.

On same network can fully acces my plex server through web browser sans singing in.
windows 10 client (PmP)
i am not sure of version number

**Comment by mseeley** [comment]
No recent changes to authentication approach.

This is a better question for our forums.
