### ISSUE TITLE
Feature: Multi-Factor Authentication integration

### ISSUE THREAD

**Issue by MrPickles2009** [plexinc/plex-media-player#972]
### Feature request
I think integrating MFA into plex would be a great way to secure accounts without adding too much inconvenience.
 - Text/Email auth
 - Authenticator apps

**Comment by mseeley** [comment]
Agreed.

This is referring to a change to all Plex clients. It's the right idea for securing accounts but not appropriate for this repositories issue tracker.

**Comment by MrPickles2009** [comment]
@mseeley where would be a good place to suggest this?

**Comment by mseeley** [comment]
Hi @MrPickles2009. Our forums and Reddit are the best places to raise an army. There are topics on each concerned with 2FA/MFA support. We're aware of the discussions and don't have any further plans ready to share.
