### ISSUE TITLE
Live TV & DVR - Guide section not available

### ISSUE THREAD

**Issue by nhorvath** [plexinc/plex-media-player#975]
### Test environment

**PMS Version:**
4.38.2
**PMP Version:**
v2.58.0.1076-38e019da
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**
Ubuntu 18.04.4 LTS

### Steps to reproduce
1. Connect to a Plex Media Server with Live TV & DVR available
2. Go to Live TV & DVR

### Current behavior
1. Only the What's On, DVR and Browse sections are available.

### Expected behavior
1. The Guide section is available in addition to the other 3.

**Comment by markus101** [comment]
The Desktop app is behind the hosted version (https://app.plex.tv/desktop) and will not be updated now that Plex for Windows/Plex for Mac are available. We hope to launch a Linux version in the future.
