### ISSUE TITLE
Started out no Sound in Windows Desktop now it just cashes

### ISSUE THREAD

**Issue by Userinmd** [plexinc/plex-media-player#976]
This morning I was trying to use the Desktop install of Plex but was not getting any sound.  Rebooted the computer and still no sound.  There were some updates to install so i installed them now running Version 1.15.0.1354-d31489f0 but get a playback error when viewing any media including online new and other online links..  I can watch and hear everything if i use the Plex url in a browser. 
Error:
There was an unexpected error during playback. Please visit our forums if you continue to experience problems.

    - Generating samples: https://support.plex.tv/articles/201035968-generating-sample-files-from-media/.
    - Retrieving XML media information: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/. Please attach within zip.
  - be accompanied by _clean_ logs.
    - PMP logs can be found here: https://support.plex.tv/articles/207338748-plex-media-player-logs/
    - Clean log instructions: Clear your logs; reproduce the issue; attach logs in a .zip file.

### Test environment

**PMS Version:** Version 1.19.5.3112-k23ab3896
**PMP Version:** Version 1.15.0.1354-d31489f0 
**Platform Windows 10

### Steps to reproduce
1. run - "C:\Program Files\Plex\Plex"  try to play anything and error shows up.

### Current behavior
1. will not play any media or online content

### Expected behavior
1.run "C:\Program Files\Plex\Plex" and what recorded TV, Play MP3s see online content

**Comment by OttoKerner** [comment]
Update to version 1.15.1

**Comment by mseeley** [comment]
Otto's correct. You can download 1.5.1 from https://www.plex.tv/media-server-downloads/?lang=#plex-app. Restarting the app after it's been running for a few minutes should also prompt to install the 1.5.1 update automatically.
