### ISSUE TITLE
Question - HDMI-CEC - Raspberry Pi 4 - Plex Media Player

### ISSUE THREAD

**Issue by WanaGo** [plexinc/plex-media-player#981]
# Test environment

Raspberry Pi 4, Running Latest Rasbian Buster Desktop release, then with Plex Media Player installed from git://github.com/plexinc/plex-media-player, using instructions linked at the bottom of this post.

### Current behavior
1. HDMI-CEC from Sony TV does not seem to register at all on Plex Media Player. I am trying to establish whether it should work out of the box, or if there is something more which needs to be installed.
I have been using RasPlex for years on Pi1, Pi2 and Pi3, yet since it has not been updated in some time now I have not been able to use it on Pi3B+ or Pi4. I just attempted to install this Plex Media Player on a Pi4 Rasbian distribution, and its working correctly except that the HDMI-CEC is not doing anything. The exact same TV was used on Rasplex and HDMI-CEC is working, meaning I do not need to use a Keyboard at all, the TV remote passes through the HDMI to the Pi and I can navigate the menus. One would assume then I am just missing a setting or something to be installed to allow HDMI-CEC to work on this.

1) Is HDMI-CEC supported?
2) How do I get HDMI-CEC working in this setup?

This is how I installed Plex Media Player:
https://forums.plex.tv/t/instructions-how-to-build-plex-media-player-on-raspberry-pi-4-b-under-raspbian/562633

Thank you.

**Comment by mseeley** [comment]
I'm unsure what the expectations are; we haven't tested on the Pi 4. Please work with the guide's author.

**Comment by WanaGo** [comment]
The guides Author doesnt know. This should not be specific to the Pi4. As mentioned, the TV talks with HDMI-CEC to any of my previous Pi's when using Rasplex, but not with Plex Media Player. No external dongles or anything required.
I can see HDMI-CEC should work with Plex Media Player, I just cant see what is stopping it working in this situation...

**Comment by WanaGo** [comment]
On Rasplex, when it boots up, in the bottom right corner it says "Pulse-Eight CEC Adapter - Connected: TV", and just works out of the box. I have found this: https://github.com/Pulse-Eight/libcec/blob/master/docs/README.raspberrypi.md
and following the instructions and build/installed the Pulse-Eight, but I have no idea how to get this to work with PMP.
It works with Rasplex, so you would think PMP would also just work.
Does anyone how how to marry them together to make HDMI-CEC work on the Pi4 running PMP?
