### ISSUE TITLE
Dolby Vision support added to ExoPlayer

### ISSUE THREAD

**Issue by cannikin** [plexinc/plex-media-player#982]
Rumor is you guys use some parts of ExoPlayer, and they just merged Dolby Vision support into `master`: https://github.com/google/ExoPlayer/pull/7667#issuecomment-680168520 There [are](https://makemkv.com/forum/viewtopic.php?f=12&t=21937) [several](https://makemkv.com/forum/viewtopic.php?f=12&t=22513) [threads](https://makemkv.com/forum/viewtopic.php?f=12&t=18602) on makemkv.com where we're eagerly awaiting official Plex support!

**Comment by gbooker** [comment]
This is a repo about Plex Media Player which doesn't use ExoPlayer even in the slightest; it uses MPV/FFmpeg.
