### ISSUE TITLE
The web-client version is extremely out of date

### ISSUE THREAD

**Issue by TheFeelTrain** [plexinc/plex-media-player#985]
**PMP Version:** 2.58.0

Plex For Windows/Mac version of web-client: 4.41.1. 
Plex Media Player's version of web-client: 4.29.2

Plex Media Player is falling further and further behind. It's been months since a version bump. We are missing out on bug fixes and design improvements, along with important features like the Skip Intro button.

**Comment by mseeley** [comment]
PMP currently has two different layouts (TV and desktop). The desktop layout has been replaced by the Plex for Windows / Mac app and PMP will not be updating its desktop layout any further. We encourage all desktop users to switch to the new app and eventually we'll remove this layout from PMP. Let us know if there is something preventing that switch for you.

As for the TV layout, that is shared with our smart TV and console apps and it recently went through a major overhaul. We're currently rolling out the new experience to our supported smart TVs and consoles first and have been focused on that transition. After that is complete, we'll be evaluating how PMP fits into this new experience.

**Comment by TheFeelTrain** [comment]
Except it hasn't been replaced by Plex For Windows/Mac. I am on Linux and there is no new client to switch to 😐

**Comment by foss-** [comment]
How would Plex on macOS be controlled using the keyboard from the couch? Using the arrow keys does nothing.
> As for the TV layout, that is shared with our smart TV and console apps and it recently went through a major overhaul.

Sounds great, but how is the TV layout activated in Plex? Or maybe I understood what is being said. Where is a UI I can use if PMP is discontinued? 2.x crashes on macOS 10.15 Catalina and v3 has not seen an update since march 2020 and displayes an empty window for me.

**Comment by mseeley** [comment]
> Except it hasn't been replaced by Plex For Windows/Mac. I am on Linux and there is no new client to switch to 😐

The lack of a Plex for Linux (a player, not media server) is one of the reasons we haven't entirely removed the desktop layout from PMP. Although there's hope for a Plex for Linux player we don't have any more information to share.

> How would Plex on macOS be controlled using the keyboard from the couch? Using the arrow keys does nothing.

The desktop layout in Plex for Mac/Windows is intended for Desktop usage. It's not the kind of experience appropriate for a 10 foot user interface.

> Sounds great, but how is the TV layout activated in Plex? Or maybe I understood what is being said. What UI can I use if PMP is discontinued?

Plex for Mac/Windows only provides a desktop layout. I'd like to avoid discussing hypothetical situations.

Thanks for both of your feedback.
