### ISSUE TITLE
no  EPG in Live TV

### ISSUE THREAD

**Issue by kaiontour** [plexinc/plex-media-player#987]
I was  able to compile the Media Player for the pie
eveytthing is wworking wel so  far

in the live tv section I cannotssee the epg. I only see whats  on and recordings

how can I change it to see also the epg?

### Test environment

**PMS Version:  1.20.1.3252
**PMP Version: Compile from git
**Platform (Windows/macOS/Embedded RPi/Embedded Intel): Pi4

### Steps to reproduce
Use Plex Media Player, I first use Pi4, but I found ttdhe same on Windows). Open Live Tv PVR

### Current behavior
1. I see sektions: PlayNow and Recording, I do not see section EPG

### Expected behavior
1. I want to see section EPG

As I said, this seems to be a generel Plex Media Player Problem. Whean I open the Player on Windows, I do not have the EPG section either

**Comment by mseeley** [comment]
The UI bundled with PMP does not support the EPG. There are no plans to update the UI at this time.
