### ISSUE TITLE
PMP Windows: When watching live TV, positioning controls (forward, back, progress bar) no longer work since v. 1.18

### ISSUE THREAD

**Issue by DaLoon** [plexinc/plex-media-player#989]
### Test environment

**PMS Version:**
**PMP Version:**
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):**

### Steps to reproduce
1.

### Current behavior
1.

### Expected behavior
1.

**Comment by mseeley** [comment]
Close because the issue doesn't follow our issue guidelines.

But, we've verified this is an issue and are investigating. Agreed, too, appears to be a 1.19 regression.

**Comment by DaLoon** [comment]
Sorry for the breach in protocol. I'm new to Github and didn't have any guide for how to open an issue. I'm glad you recognize it is an issue and are looking into it
