### ISSUE TITLE
Taskbar icon is shown but no window is created

### ISSUE THREAD

**Issue by Idearum** [plexinc/plex-media-player#99]
Plex Media Player version: 1.0.1.42-56cc6ef9
Laptop: ASUS G73jh
OS: Windows 10 Pro x64
CPU: Intel Core i7 Q740
GPU: AMD Mobility Radeon HD 5800 Series

I have a really weird issue where Plex Media Player seems to start, yet no window is created and only a taskbar icon is shown. This is with a laptop I use as a HTPC that is hooked up to my TV through my Receiver. I've even tried with the DirectX option as well as the "PlexMediaPlayer-NoChromiumGPU.bat" with no difference.

Taskbar icon screenshot:
![7itz19n](https://cloud.githubusercontent.com/assets/10578344/10851423/4d41cfd8-7f2b-11e5-9617-b64bb8c641e5.png)

Log files:
PlexMediaPlayer.log - http://pastebin.com/bPuuGHWS
pmphelper.log - http://pastebin.com/FcdY1CMf

Related forum thread: https://forums.plex.tv/discussion/190826/plex-is-shown-in-taskbar-but-no-window-is-created

I am unsure if this is related to the issue described in https://github.com/plexinc/plex-media-player/issues/9. The difference is that I'm not experiencing a crash and I don't have switchable graphic cards on my laptop.

**Comment by wm4** [comment]
Looking at the log, it could be something very simple and stupid: the window somehow immediately loses focus, and we react to this by minimizing.

You could try editing the plex media player config file, and set ``fullscreen`` to ``false``. It's possible that it works if my suspicion is true.

I don't know why it happens, or what to do against it. (Yet.)

Minimizing when we lose focus and the window is in fullscreen mode was done to fix other problems with OpenGL fullscreen mode. The "Unable to locate current display. " are harmless at this point.

**Comment by Idearum** [comment]
I tried it and this happened: 
![2wtqw6k](https://cloud.githubusercontent.com/assets/10578344/10851701/dae1d954-7f2c-11e5-953b-dd9d749da937.png)

**Comment by Idearum** [comment]
Plex Media Player (DirectX) causes the window to be rendered with a black background instead of white.

![ikbgdb0](https://cloud.githubusercontent.com/assets/10578344/10851778/4aa21d58-7f2d-11e5-98a4-2f6200874f8e.png)

**Comment by wm4** [comment]
That's all kinds of odd.

**Comment by Idearum** [comment]
Okay, I troubleshooted a bit more and the issue is *only* happening when the lid of my laptop is closed so that only the TV is detected and used as a monitor.

PMP works as it should when I:
* have the lid open and both monitors (laptop screen + TV) configured as duplicate or extended desktop modes
* only use the laptop screen and have disconnected the HDMI cable completely

The workaround is basically to have the laptop lid open so that the picture gets duplicated on both it and the TV.  :confused:

**Comment by Idearum** [comment]
I experience the same issue when the laptop lid is open but Windows is configured to "Show only on 2" (meaning the TV). Basically, for whatever reason the laptop screen must be in use by Windows for PMP to work correctly.
