### ISSUE TITLE
Fedora PMP Linux Client 2.55 and 2.58 Freezes and Fix

### ISSUE THREAD

**Issue by dagunny** [plexinc/plex-media-player#993]
A recent update to Fedora 32 made the PMP client freeze with a really weird out of focus graphic yet let the audio come thru. Versions tested were 2.55.0.1069-fc32_x64-86 (Fedora repo) and 2.58.0.1076-1.fc32.x86_64 (negativo17 repo).  The QT5 is the offending problem. I downgraded qt5* to qt5-5.13.2-2.fc32 using DNF and the problem were away.  I tested on 2 Plex servers and 3 clients running Fedora Cinnamon 32.  Same result.  An additional problem was not enough CPU.  This was also cured with the downgrade.  Both servers were running Fedora Cinnamon 32 - one on a Supermicro 8-core Xeon and the other an HP i7-4th gen - both with 24GB RAM.  Clients were i5 and i7 laptops with 8 and 16GB RAM. Files tested were mp4, mpv, mkv, and avi.  A side effect was the TV app (LG TV) was really stuttering/buffering every 5 seconds. After the downgrade on the server this went away as well.  It was a long night. So both PMP and PMS were affected by QT5.

**Comment by mseeley** [comment]
Which version of Qt was installed on Fedora before downgrade?

**Comment by dagunny** [comment]
I had QT5-5.14.2-1 which was the current dnf update.  Drove me nuts - I uninstalled the PMS, restored from a backup, etc but nothing would change the rendering to the clients. Finally starting playing with QT5 and got it working.

**Comment by mseeley** [comment]
Thanks for the follow-up. We've run into Qt sensitivity before. Pulled this from our building on linux instructions:

>Plex Media Player officially requires Qt 5.9.5. Our users have indicated that Qt 5.10 and Qt 5.11 also builds correctly. However, Qt 5.11.0 and 5.11.1 versions are incompatible and should be avoided. Qt 5.12 may work for you.

I couldn't locate the Fedora RPM you mentioned but did find the negativo one: https://negativo17.org/repos/multimedia/fedora-32/x86_64/plex-media-player-2.58.0.1076-1.fc32.x86_64.rpm

At only 15MB, I'm guessing these packages don't include Qt. If so, that's a troublesome situation given incompatibilities with the recent Qt versions. Any improvements to the RPM bundles are the responsibility of their maintainers, they're not maintained by Plex.

Please report the PMS issue via our forum. It's a deeper issue that'll require other folks to get involved.

**Comment by dagunny** [comment]
I got the 2.55 from the Plex site I think and 2.58 from negativo17/multimedia/fc33 repo.  I also have FC33 beta 1 (5-8-12-300-fc33) Cinnamon running and PMP 4.29.2 loaded. It uses QT5-5.15.1-5 and works great.  If you do a dnf local install with the .rpm it will bring down all the dependencies.

**Comment by mseeley** [comment]
There's no official Linux download from Plex for Plex Media Player. Other developers/enthusiasts build+bundle for various Linux package managers. It's a little wild west ish.

We're working through dependency updates to address the core Qt compat issue. Actual behavior on various Linux platforms is still going to be a wildcard. Shipping official Linux packages would partially address this although we have no plans to share yet.

Thanks @dagunny for your feedback. I'll be closing this issue as it's caused the third party bundles, maybe accidentally or maybe intentionally due to platform requirements, omitting a dependency on compatible Qt.
