### ISSUE TITLE
Resizing Posters in Grid view not working

### ISSUE THREAD

**Issue by Sebbl22** [plexinc/plex-media-player#995]
### Test environment

**PMS Version:** 1.20.5.3562
**PMP Version:** 4.46.2 
**Platform (Windows/macOS/Embedded RPi/Embedded Intel):** Docker

### Steps to reproduce
1. Go to a movie or tvshow library
2. Go to "recommended" or "library"
2. Enter Grid view
3. Try to resize the poster images via the slider
![grafik](https://user-images.githubusercontent.com/10319545/99047997-4ac96700-2595-11eb-80da-8f9735ec6095.png)

### Current behavior
1. Nothing happens. The poster images stay the same

### Expected behavior
1. The poster images resize

### Remarks
- It works on other library types:
  - in picture librarys
  - in "other video" librarys
  - in a movie library in a collection view
  - in a tvshow library in a tvshow detail view
  - in a tvshow library in a season detail view

I am not quite sure, if it's an configuration error on my side.

Edit:
I have a widescreen monitor. It seems resizing stops working at a screen width of 2075 px (tested with Firefox). Anything smaller and the poster images change when using the slider. Maybe this is behaviour is intended?

**Comment by mseeley** [comment]
Hi @Sebbl22 you're right, that's an expected behavior. It's a shortcoming/bug in the version of the client that's bundled with PMP. The newer client code running on at https://app.plex.tv app should show improved behavior. Will you please confirm?

**Comment by Sebbl22** [comment]
Yes, I can confirm that this is not an issue / fixed on app.plex.tv

**Comment by mseeley** [comment]
Thanks for confirming @Sebbl22. We'll track this as a known issue but aren't planning to update the Desktop layout within Plex Media Player.
