### ISSUE TITLE
Green/purple/blue/etc. artifacts when hardware transcoding on AMD Radeon RX 5x00 series GPUs and Ryzen 4000 series APUs

### ISSUE THREAD

**Issue by hifihedgehog** [plexinc/plex-media-player#998]
### Test environment

**PMS Version:  1.21.0.3616**
**PMP Version: Plex Web Version 4.43.4 and Plex iOS 7.10.1**
**Platform: Windows 10 64-Bit for Server; Windows and iOS for clients**

### Steps to reproduce
1. Use an AMD Ryzen 4000 series APU with integrated graphics or a discrete AMD Radeon RX 5x00 series GPU. In this example, I am using the Ryzen 7 PRO 4750G. (Update: Based on forum comments, this seems to be common only to the Radeon RX 5x00 GPU and Ryzen 4000 series APUs, which share the same updated features in their Video Core Next (VCN) 2.0 codec block.)
2. On your Plex server, go to Settings -> Transcoder and ensure both "Use hardware acceleration when available" and "Use hardware-accelerated video encoding" are checked.
3. Attempt to play a video locally or on a separate device (platform independent for the client) at any at-playback transcoded bitrate, or attempt to sync a pre-transcoded optimized copy of the video. In my case, this behavior occurs both on my Plex server and on my iPhone 12 Pro Max.
### Current behavior
1. PMP green/purple/blue artifacts on the video content. See these examples below:

![image](https://user-images.githubusercontent.com/16614343/100487630-ac321f80-30d7-11eb-9796-2e18b4847e64.png)

![image](https://user-images.githubusercontent.com/16614343/100488027-c8cf5700-30d9-11eb-8b19-ad5d161c3955.png)

![image](https://user-images.githubusercontent.com/16614343/100488012-a89f9800-30d9-11eb-8d5a-d79bb236642b.png)

### Expected behavior
1. Clean video free of random color artifacts.

### Related forum thread where many other users have reproduced and report this issue:
https://forums.plex.tv/t/pmp-green-purple-artifacts-when-playing-x265-10bit-mkv/570323

**Comment by mseeley** [comment]
Logs and sample media clips that repro the problem are necessary please.

Tangential, what's keeping you using PMP on Windows instead of Plex for Windows? The latter has a newer mpv integrated.

**Comment by hifihedgehog** [comment]
> Logs and sample media clips that repro the problem are necessary please.
> 
> Tangential, what's keeping you using PMP on Windows instead of Plex for Windows? The latter has a newer mpv integrated.

The error occurs on any Plex PMP and is independent of the player.

**Comment by hifihedgehog** [comment]
> Logs and sample media clips that repro the problem are necessary please.

Will update this post with video segments with hardware encoding enabled and disabled

**Comment by hifihedgehog** [comment]
This example below is less severe since it has mostly static or stationary frames but it is plainly obvious where the bad encoding occurs. This does not occur with other encoding solutions I use, such as Handbrake, which feature VCE/VCN support. I included a log and database dump as requested.

**Comment by hifihedgehog** [comment]
### Related forum thread where many other users have reproduced and report this issue:
https://forums.plex.tv/t/pmp-green-purple-artifacts-when-playing-x265-10bit-mkv/570323

**Comment by hifihedgehog** [comment]
I can only guess, but the 4750G uses the same latest and greatest VCN core as the RX 5700. Both of these GPUs share this same common architectural piece which may be the common failure point. I would bet anything that Plex does not have a fully up-to-date VCN/VCE codebase with proper support for these GPU's codec block.

**Comment by hifihedgehog** [comment]
Pinging [AMD GitHub](https://github.com/amd) members @gregrodgers and @kiritigowda who hopefully can tap on the right folks if this requires driver-level rectification or advanced support.

**Comment by hifihedgehog** [comment]
Can also now confirm this issue does not occur on Jellyfin though Jellyfin is lacking in many critical features compared to Plex Pass.

**Comment by hifihedgehog** [comment]
For what it is worth, I just bought a lifetime Plex Pass this week, so I hope that raises awareness among Plex staff that paying customers like myself are looking for dependable support to patch this longstanding issue with Plex Server.

**Comment by hifihedgehog** [comment]
Decoding was broken with the release just prior to the recent update in the last few days. Here's Plex's new solution: disable hardware encoding for customers with AMD GPUs. Version 1.21.0.3711 now disables AMD GPU encoding entirely, probably given the sheer volume of the complaints. I noticed this today when I humored myself after updating and tried to turn on the GPU encoding. No weird color defects but now no hardware encoding at all. It does not engage at all now and the GPU remains un-utilized. The problem now is why in the world did I pay for Plex Pass when they are not properly supporting hardware encoding? Instead, they "fix" problems by disabling advertised features of their paid services. That's a big black mark on their reputation in my book.

**Comment by hifihedgehog** [comment]
New release (1.21.0.3711), no fix yet in sight. Tried again today. Same multicolored pixel errata.

**Comment by hifihedgehog** [comment]
It's still giving me what I reported to Plex here on GitHub. The issue is server-side and has to do with their custom broken implementation of FFMPEG and VCN 2.0. Other software out there like Handbrake that use FFMPEG have no issues with AMD's VCN hardware encoding. This example I provided them is with a non-live, pre-transcoded or optimized file. They have yet to fix their issue with hardware encoding:

> See example case below.
> 
> \> \> https://gofile.io/d/KbUSp0 < <
> 
> This example above is less severe since, as a CGI animated short, it has more static or stationary frames, but it is still plainly obvious where the improper encoding occurs. This does not occur with other hardware encoding implementations I use, such as Handbrake which features VCE/VCN support. I included a log and database dump as requested. Some very obvious problem points I quickly noted in the hardware encode are ~2:14, ~2:18, and ~3:11, but there are many more problem points before and after as you may have already noticed.

**Comment by rcombs** [comment]
Not a PMP issue.
